### ISSUE TITLE
Xcode 14 "xcodebuild failed with exit code 65"

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10034]
### Issue Description

Hi,

I have this issue during the IOS build, it seams that we need to add an output file for the PreLink and PostBuild ?

### Relevant log output (if applicable)

```shell
Command SwiftCompile failed with a nonzero exit code
note: Using codesigning identity override: 
note: Building targets in dependency order
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'MDFInternationalization' from project 'Pods')
note: Run script build phase 'NativeScript PreBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'XXX' from project 'XXX')
note: Run script build phase 'NativeScript PreLink' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'XXX' from project 'XXX')
note: Run script build phase 'NativeScript PostBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'XXX' from project 'XXX')
** BUILD FAILED **

Unable to apply changes on device: B6F715DF-C67C-4FC5-A233-7F8DE00. Error is: Command xcodebuild failed with exit code 65.
```

### Environment
```ts

<!-- COPY START -->
```yaml
OS: macOS 12.6
CPU: (10) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 16.16.0
npm: 8.17.0
nativescript: 8.3.3

# android
java: 18.0.1
ndk: Not Found
apis: 23, 30, 31, 32, 33
build_tools: 31.0.0, 33.0.0
system_images: 
  - android-33 | Google APIs ARM 64 v8a

# ios
xcode: 14.0/14A309
cocoapods: 1.11.3
python: 3.9.12
python3: 3.9.12
ruby: 2.6.8
platforms: 
  - DriverKit 21.4
  - iOS 16.0
  - macOS 12.3
  - tvOS 16.0
  - watchOS 9.0
```

### Dependencies

```json
"dependencies": {
  "@kefah/nativescript-uuid": "^1.0.1",
  "@nativescript-community/fonticon": "^3.0.0",
  "@nativescript-community/ui-canvas": "^4.4.4",
  "@nativescript-community/ui-collectionview": "^4.0.57",
  "@nativescript-community/ui-material-bottom-navigation": "^7.0.25",
  "@nativescript-community/ui-material-bottomnavigationbar": "^7.0.25",
  "@nativescript-community/universal-links": "^3.0.0",
  "@nativescript/appversion": "^2.0.0",
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/core": "^8.3.1",
  "@nativescript/datetimepicker": "^2.1.11",
  "@nativescript/firebase-auth": "^2.2.9",
  "@nativescript/firebase-core": "^2.2.9",
  "@nativescript/firebase-crashlytics": "^2.2.9",
  "@nativescript/firebase-messaging": "^2.2.9",
  "@nativescript/geolocation": "^8.0.2",
  "@nativescript/imagepicker": "^1.0.7",
  "@nativescript/iqkeyboardmanager": "^2.0.0",
  "@nativescript/local-notifications": "^6.0.0",
  "@nativescript/localize": "^5.0.4",
  "@nativescript/secure-storage": "^3.0.0",
  "@nativescript/theme": "^3.0.2",
  "@nstudio/nativescript-cardview": "^2.0.1",
  "@nstudio/nativescript-fancyalert": "^4.0.1",
  "@nstudio/nativescript-filterable-listpicker": "^3.0.1",
  "@nstudio/nativescript-loading-indicator": "^4.1.2",
  "@triniwiz/nativescript-stripe": "^8.0.3",
  "@triniwiz/nativescript-toasty": "^4.1.3",
  "@types/google-libphonenumber": "^7.4.23",
  "base-64": "^1.0.0",
  "build-url-ts": "^6.1.3",
  "crypto-js": "^4.1.1",
  "email-validator": "^2.0.4",
  "google-libphonenumber": "^3.2.29",
  "moment": "^2.29.4",
  "nativescript": "^8.2.3",
  "nativescript-feedback": "^2.0.0",
  "nativescript-intl": "^4.0.2",
  "nativescript-modal-datetimepicker": "^2.1.5",
  "nativescript-phone": "^3.0.3",
  "nativescript-ui-autocomplete": "^8.0.1",
  "nativescript-ui-listview": "^10.2.7",
  "nativescript-ui-sidedrawer": "^10.0.2",
  "rxjs": "^7.5.6",
  "url-parse": "^1.5.10",
  "utf8": "^3.0.0",
  "uuid": "^8.3.2"
},
"devDependencies": {
  "@nativescript/android": "8.3.1",
  "@nativescript/ios": "8.3.3",
  "@nativescript/types": "~8.3.1",
  "@nativescript/webpack": "~5.0.6",
  "typescript": "~4.5.5"
}
```

```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/nativescript-cli/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by kefahB** [comment]
@rigor789,

Thanks for replying, I have already done your solution before publishing this issue and the error persiste!

**Comment by rigor789** [comment]
@kefahB open the project in XCode (`platforms/ios/<projectname>.xcworkspace`) and try running from XCode, and see what errors you get. The above fix (updated comment with an alternative) should generally work, but you might be running into a different issue altogether.

**Comment by sudiptosen** [comment]
Worked for me locally on Emulator and on the device! Thanks

**Comment by NathanWalker** [comment]
Context: https://github.com/CocoaPods/CocoaPods/issues/11402

**Comment by abdallahkadour** [comment]
It's working for me on xcode: `14.0.1`, `"@nativescript/ios": "8.3.3"` and `"@nativescript": "8.3.3"`.

**Comment by vicmasa** [comment]
Hi.
I have the same problem, I already tried each of the alternatives and I can't solve it.

```yaml
OS: macOS 13.0.1
CPU: (8) arm64 Apple M1 Pro
Shell: /bin/zsh
node: 19.2.0
npm: 8.19.3
nativescript: 8.4.0

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.7.7
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@nativescript/background-http": "^6.0.0",
  "@nativescript/camera": "^5.0.15",
  "@nativescript/core": "~8.4.0",
  "@nativescript/geolocation": "^8.1.0",
  "@nativescript/google-maps": "^1.4.9",
  "@nativescript/social-share": "^2.3.0",
  "@nativescript/theme": "~3.0.2",
  "@nstudio/nativescript-exoplayer": "^6.0.1",
  "nativescript-sqlite": "^2.8.6",
  "nativescript-videoplayer": "^5.0.1"
},
"devDependencies": {
  "@nativescript/ios": "8.4.0",
  "@nativescript/webpack": "~5.0.12"
}
```


**CONSOLE:**
Searching for devices...
Preparing project...
NativeScript-SQLite Sync not detected, disabling support!
NativeScript-SQLite Commercial not detected, disabling support!
NativeScript-SQLite Encrypted not detected, disabling support!
NativeScript-SQLite NoSQL/Keystore not detected, disabling support!

webpack is watching the files...
asset vendor.js 6.49 MiB [compared for emit] (name: vendor) (id hint: defaultVendor)
asset bundle.js 344 KiB [compared for emit] (name: bundle)
asset runtime.js 86.2 KiB [compared for emit] (name: runtime)
asset tns_modules/inspector_modules.js 1.22 KiB [compared for emit] (name: tns_modules/inspector_modules)
Entrypoint bundle 6.91 MiB = runtime.js 86.2 KiB vendor.js 6.49 MiB bundle.js 344 KiB
Entrypoint tns_modules/inspector_modules 6.57 MiB = runtime.js 86.2 KiB vendor.js 6.49 MiB tns_modules/inspector_modules.js 1.22 KiB
runtime modules 24.8 KiB 11 modules
orphan modules 302 bytes [orphan] 5 modules
modules by path ./node_modules/@nativescript/ 1.53 MiB 191 modules
modules by path ./node_modules/css-tree/ 317 KiB 113 modules
modules by path ./app/ 123 KiB 7 modules
modules by path ./node_modules/source-map/lib/*.js 36.3 KiB 6 modules
modules by path ./node_modules/reduce-css-calc/dist/ 131 KiB 5 modules
modules by path ./node_modules/postcss-value-parser/lib/*.js 12.5 KiB
  ./node_modules/postcss-value-parser/lib/index.js 607 bytes [built] [code generated]
  + 4 modules
modules by path ./node_modules/mdn-data/css/*.json 242 KiB
  ./node_modules/mdn-data/css/at-rules.json 11.6 KiB [built] [code generated]
  + 2 modules
+ 4 modules
webpack 5.75.0 compiled successfully in 1339 ms
Webpack compilation complete. Watching for file changes.
File change detected. Starting incremental webpack compilation...
Updating runtime package.json with configuration values...
Project successfully prepared (ios)
Building project...
Xcode build...
assets by status 6.91 MiB [cached] 4 assets
Entrypoint bundle 6.91 MiB = runtime.js 86.2 KiB vendor.js 6.49 MiB bundle.js 344 KiB
Entrypoint tns_modules/inspector_modules 6.57 MiB = runtime.js 86.2 KiB vendor.js 6.49 MiB tns_modules/inspector_modules.js 1.22 KiB
cached modules 2.59 MiB (javascript) 24.8 KiB (runtime) [cached] 349 modules
./app/ sync .(xml%7Cjs%7Cs?css)$ 270 bytes [built]
webpack 5.75.0 compiled successfully in 69 ms
Webpack compilation complete. Watching for file changes.
./.build_env_vars.sh: line 506: declare: UID: readonly variable
NSLD: Swift bridging header '*-Swift.h' not found under '/Users/victor/Library/Developer/Xcode/DerivedData/plugins-foixvidvlbuimmazpqizborlzvep/Build/Intermediates.noindex/plugins.build/Debug-iphonesimulator/plugins.build/Objects-normal/arm64'
Generating metadata...~/invian/ns/plugins/platforms/ios/internal/metadata-generator-arm64/bin ~/invian/ns/plugins/platforms/ios
Python version: 3.9.6 (default, Sep 26 2022, 11:37:49) 
[Clang 14.0.0 (clang-1400.0.29.202)]
Generating metadata for arm64
Metadata Generator Arguments: 
./objc-metadata-generator -verbose -output-bin /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/metadata-arm64.bin -output-umbrella /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/umbrella-arm64.h -docset-path /Users/victor/Library/Developer/Shared/Documentation/DocSets/com.apple.adc.documentation.iOS.docset Xclang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk -std=gnu99 -target arm64-apple-ios16.1-simulator -I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/include -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios -I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling/ASBPlayerSubtitling.framework/Headers -I/Users/victor/invian/ns/plugins/platforms/ios/internal/Swift-Modules -I/Users/victor/invian/ns/plugins/platforms/ios/internal -I/Users/victor/invian/ns/plugins/platforms/ios/../../App_Resources/iOS/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/camera/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/geolocation/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nstudio/nativescript-exoplayer/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios/src -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/plugins/platforms/ios/internal/ -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling -F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios -DCOCOAPODS=1 -DDEBUG=1 
Clang Arguments: 
"-v", "-x", "objective-c", "-fno-objc-arc", "-fmodule-maps", "-ferror-limit=0", "-Wno-unknown-pragmas", "-Wno-ignored-attributes", "-Wno-nullability-completeness", "-Wno-expansion-to-defined", "-D__NATIVESCRIPT_METADATA_GENERATOR=1", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk", "-std=gnu99", "-target", "arm64-apple-ios16.1-simulator", "-I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/include", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios", "-I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling/ASBPlayerSubtitling.framework/Headers", "-I/Users/victor/invian/ns/plugins/platforms/ios/internal/Swift-Modules", "-I/Users/victor/invian/ns/plugins/platforms/ios/internal", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../App_Resources/iOS/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/camera/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/geolocation/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nstudio/nativescript-exoplayer/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios/src", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/plugins/platforms/ios/internal/", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling", "-F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Base/Frameworks", "-F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks", "-F/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios", "-DCOCOAPODS=1", "-DDEBUG=1", 
Merged 912 categories.
Result: 52716 declarations from 174 top level modules
Done! Running time: 3.47162 sec 
Saving metadata generation's stderr stream to: /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-arm64.txt
Generating metadata for x86_64
Metadata Generator Arguments: 
./objc-metadata-generator -verbose -output-bin /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/metadata-x86_64.bin -output-umbrella /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/umbrella-x86_64.h -docset-path /Users/victor/Library/Developer/Shared/Documentation/DocSets/com.apple.adc.documentation.iOS.docset Xclang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk -std=gnu99 -target x86_64-apple-ios16.1-simulator -I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/include -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios -I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling/ASBPlayerSubtitling.framework/Headers -I/Users/victor/invian/ns/plugins/platforms/ios/internal/Swift-Modules -I/Users/victor/invian/ns/plugins/platforms/ios/internal -I/Users/victor/invian/ns/plugins/platforms/ios/../../App_Resources/iOS/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/camera/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/geolocation/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nstudio/nativescript-exoplayer/platforms/ios/src -I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios/src -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/plugins/platforms/ios/internal/ -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator -F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling -F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Base/Frameworks -F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks -F/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios -DCOCOAPODS=1 -DDEBUG=1 
Clang Arguments: 
"-v", "-x", "objective-c", "-fno-objc-arc", "-fmodule-maps", "-ferror-limit=0", "-Wno-unknown-pragmas", "-Wno-ignored-attributes", "-Wno-nullability-completeness", "-Wno-expansion-to-defined", "-D__NATIVESCRIPT_METADATA_GENERATOR=1", "-isysroot", "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.1.sdk", "-std=gnu99", "-target", "x86_64-apple-ios16.1-simulator", "-I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/include", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios", "-I/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling/ASBPlayerSubtitling.framework/Headers", "-I/Users/victor/invian/ns/plugins/platforms/ios/internal/Swift-Modules", "-I/Users/victor/invian/ns/plugins/platforms/ios/internal", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../App_Resources/iOS/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/camera/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/geolocation/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/google-maps/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nstudio/nativescript-exoplayer/platforms/ios/src", "-I/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/nativescript-sqlite/platforms/ios/src", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/plugins/platforms/ios/internal/", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator", "-F/Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/ASBPlayerSubtitling", "-F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Base/Frameworks", "-F/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks", "-F/Users/victor/invian/ns/plugins/platforms/ios/../../node_modules/@nativescript/core/platforms/ios", "-DCOCOAPODS=1", "-DDEBUG=1", 
Merged 912 categories.
Result: 52772 declarations from 175 top level modules
Done! Running time: 3.45473 sec 
Saving metadata generation's stderr stream to: /Users/victor/invian/ns/plugins/platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt
~/invian/ns/plugins/platforms/ios
ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using codesigning identity override: 
note: Building targets in dependency order
note: Run script build phase 'NativeScript PreLink' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'plugins' from project 'plugins')
note: Run script build phase 'NativeScript PostBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'plugins' from project 'plugins')
note: Run script build phase 'NativeScript PreBuild' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'plugins' from project 'plugins')
** BUILD FAILED **

Unable to apply changes on device: EBE191C6-7225-4847-A1ED-D6079670D3E6. Error is: Command xcodebuild failed with exit code 65.

**Comment by vicmasa** [comment]
> @vicmasa seems to be related to the GoogleMaps pod based on your logs:
> 
> ```
> ld: building for iOS Simulator, but linking in object file built for iOS, file '/Users/victor/invian/ns/plugins/platforms/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/GoogleMaps' for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> It's missing arm64 simulator slice in the framework possibly.

I downgraded the Nativescript version ("@nativescript/ios": "8.3.3" and "@nativescript": "8.3.3"), but the problem persists.

**Comment by rigor789** [comment]
@vicmasa downgrading won't help most likely, it's a plugin issue, more specifically a GoogleMaps cocoapod issue - I can't look into the details for it right now, but it might just need an updated pod version (in the plugin). I suggest opening an issue in the plugins repo, or commenting on one if there's already one

**Comment by NathanWalker** [comment]
This is a well known google issue with google maps. Their pod actually does not support arm64 (M1) simulators. You can run on device only with it or manually include their xcframework.
https://github.com/googlemaps/google-maps-ios-utils/issues/355

**Comment by abdallahkadour** [comment]
@vicmasa may be you need to update IPHONEOS_DEPLOYMENT_TARGET as follow `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14'` in the podfile located in `App_Resources/ios/`. This was a reason why I get `Command xcodebuild failed with exit code 65` while building ios. Of course, @rigor and @NathanWalker have better insights.

**Comment by victorfaria** [comment]
I was facing the same problem. After a while I figured out that it was the firebase-core and firebase-firestore Pods the cause of problem. 
What worked for me:

Xcode14 and Macos Monterey

1. Ns clean
2. npm install (to install the dependencies and modules)
3. Access node_modules/@nativescript/firebase-core/platforms/ios/Podfile and change platform :ios,  to 13
4 .  Access node_modules/@nativescript/firebase-firestore/platforms/ios/Podfile and change the version of firestore-ios-sdk-frameworks.git to the latest.
5. ns run ios

After these steps It was able to download and install pods with no problem.
