### ISSUE TITLE
Cannot access 'profileFunctionFactory' before initialization

### ISSUE THREAD

**Issue by jgmedialtd** [NativeScript/NativeScript#10079]
### Issue Description

When I run 'ns run ios'

The build seems to go ok, then I get the error in the log output below on launch.

Running nativescript@8.3.3

### Reproduction

ns run ion - the app is seemingly installed and then immediately crashes

### Relevant log output (if applicable)

```shell
***** Fatal JavaScript exception - application has been terminated. *****
  NativeScript encountered a fatal error: Uncaught ReferenceError: Cannot access 'profileFunctionFactory' before initialization
  at
  profile(file: app/webpack:/smartcut/node_modules/@nativescript/core/profiling/index.js:210:0)
  at ./node_modules/@nativescript/core/ui/core/properties/index.js(file: app/webpack:/smartcut/node_modules/@nativescript/core/ui/core/properties/index.js:1074:37)
  at __webpack_require__(file: app/webpack:/smartcut/webpack/bootstrap:19:0)
  at ./node_modules/@nativescript/core/ui/core/view-base/index.js(file:///app/vendor.js:18208:69)
  at __webpack_require__(file: app/webpack:/smartcut/webpack/bootstrap:19:0)
  at ./node_modules/@nativescript/core/ui/core/view/view-common.js(file:///app/vendor.js:20008:68)
  at __webpack_require__(file: app/webpack:/smartcut/webpack/bootstrap:19:0)
  at ./node_modules/@nativescript/core/ui/core/view/index.ios.js(file:///app/vendor.js:19176:70)
  at __webpack_require__(file: app/webpack:/smartcut/webpack/bootstrap:19:0)
  at ./node_modules/@nativescript/core/ui/action-bar/action-bar-common.js(file:///app/vendor.js:12224:68)
  at __webpack_require__(file: app/webpack:/smartcut/webpack/bootstrap:19:0)
  at ./node_modules/@nativescript/core/ui/action-bar/index.ios.js(file:///app/ven<…>
```

### Environment

```yaml
OS: macOS 12.6
CPU: (10) arm64 Apple M1 Max
Shell: /bin/zsh
node: 19.0.1
npm: 8.19.3
nativescript: 8.3.3

# android
java: 11.0.17
ndk: Not Found
apis: Not Found
build_tools: Not Found
system_images: Not Found

# ios
xcode: 14.1/14B47b
cocoapods: 1.11.3
python: 2.7.18
python3: 3.9.6
ruby: 2.6.8
platforms: 
  - DriverKit 22.1
  - iOS 16.1
  - macOS 13.0
  - tvOS 16.1
  - watchOS 9.1
```

### Dependencies

```json
"dependencies": {
  "@finanzritter/nativescript-share-file": "^2.1.0",
  "@nativescript/core": "^8.3.5",
  "@nativescript/iqkeyboardmanager": "^2.1.0",
  "fraction.js": "^4.2.0",
  "nativescript-pdf-view": "^3.0.0-1",
  "nativescript-vue": "^2.9.3",
  "nativescript-webview-interface": "^1.4.4",
  "node-polyfill-webpack-plugin": "^2.0.1"
},
"devDependencies": {
  "@nativescript/android": "~8.3.1",
  "@nativescript/ios": "~8.3.3",
  "@nativescript/webpack": "~5.0.9",
  "nativescript-vue-template-compiler": "~2.9.3",
  "sass": "^1.56.0"
}
```

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by rigor789** [comment]
Your dependencies look ok, would you be able to share a sample that shows the issue, or at least try to reduce it in your app to a single page/view causing it?

**Comment by jgmedialtd** [comment]
Thanks @rigor789 - I have a public github at https://github.com/jgmedialtd/smartcut-app. I can't pinpoint where in the process the issue occurs as it crashes on launch - the error is referring to a core file @nativescript/core/profiling/index.js:210:0. I had a look at it, but I'm not sure I'm qualified to review the code!

**Comment by rigor789** [comment]
@jgmedialtd that works, I had a bit of trouble building because it has some absolute imports, but I commented them out and saw the crash on start. After a bit of trial & error, I traced that back to the NodePolyfillPlugin, as soon as I disable it in the webpack config, the app builds & runs! What exactly happens in `NodePolyfillPlugin` I'm not sure, but it definitely causes an issue with the webpack dependency graph.

If I edit the polyfills plugin in `node_modules` and comment out `console`, and `timers` the app seems to work - and in general these should not be enabled anyways, because both timers & console are implemented in {N} and don't need to be polyfilled to anything.

<details>
<summary>App running!</summary>

![image](https://user-images.githubusercontent.com/879060/200826756-2f3983ed-8630-48f8-a3e7-865a2096d398.png)

</details>

(a side note: you can remove `sass` from package.json, it's already included with `@nativescript/webpack` - just one less thing to worry about during updates)

**Comment by jgmedialtd** [comment]
@rigor789 - thank you so much, I'm so grateful. I was on the verge of giving up! 

I installed NodePolyfillPlugin due to all the webpack 5 errors I was getting before. I'm not sure if there is a better / approved way of dealing with the lack of polyfills with webpack 5?

I've seen a fair amount of questions about this in stackoverflow, so perhaps something we could add to the notes?

**Comment by rigor789** [comment]
It's tough, I was thinking about providing good defaults for polyfills, but it turns out it highly depends on the packages/plugins that need them, and there's no one size fits all solution.

As far as errors, commenting out the plugin didn't seem to cause polyfill issues in your repo, so perhaps you might not even need that plugin (but the above way should be fine).

**Comment by jgmedialtd** [comment]
Thanks again!
