### ISSUE TITLE
[IOS] FileSystem Documents are not writable in real app

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#10203]
### Issue Description

Hi,

The `Documents` from the `knownFolder` is not writable via `Folder.fromPath`. It work only on simulator but not on real app from AppStore.

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

**Comment by NathanWalker** [comment]
Documents is writeable and must be used for production Store apps. Provide full context of code in question to determine what else you’re working with.

**Comment by kefahB** [comment]
Excuse me, the currentApp folder that not writable, It seems that the sub folder should be created programmatically ? Because I have created the folders manually ‘currentApp/assets/images’ but the image wasn’t be saved

**Comment by NathanWalker** [comment]
This is expected behavior on iOS. Only the Documents folder should be written to or other permitted options as mentioned here:
https://en.proft.me/2019/11/23/reading-and-writing-files-ios-app/

In short you cannot and should not write files to currentApp because although may work in simulator, it won’t on a store production release.
