### ISSUE TITLE
Connectivity modules requires ACCESS_NETWORK_STATE permission on Android

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#1033]
The connectivity module requires the ACCESS_NETWORK_STATE permission on Android. It should be initially set within the AndroidManifest.xml when you create the application as this is a core module.

within the manifest it should contain:
```xml
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```

js:
```js
var connectivity = require("connectivity");
if (connectivity.getConnectionType() === connectivity.connectionType.none) {
    console.log("No connection");
}
```

**Comment by vakrilov** [comment]
@lscown Thanks for noting that. 
However, this is actually intended as noted in [the documentation](https://docs.nativescript.org/ApiReference/connectivity/README.html). The permission is not included by default because not all applications will need it. So if you are using this module you should add the permission manually

**Comment by atanasovg** [comment]
I think such modules are ideal candidates for separate plugins, where the module itself carries an `AndroidManifest.xml` file with the required permissions.
