### ISSUE TITLE
Feature request: Physics

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#1076]
I just found another framework named Fuse that looks really close to {N}. I wonder if it's based on it.

The interesting part i found is Physics support: https://www.fusetools.com/learn/fuse#-physics-
Great demo here: https://www.fusetools.com/community/examples/swipeplaces
And video here: https://www.youtube.com/watch?v=LJGOiNkkjCA

Are you planning something like this in your roadmap?

**Comment by manijak** [comment]
Keep in mind that Fuse is in a "open-beta" state. It might hint that in future they can charge for usage.

That beeing said, I am sorry to say this, but the competition is getting bigger & better. Fuse looks very very interesting, very similar to {N} when it comes to the UI definition. One thing I do not like here is that they mix the javascript and the UI in the same file. I perfer the way NativeScript does it.

But on the other hand Fuse has focused a lot on the UX/UI it seems. A lot of cool and great modules out of the box. Like the Physics, VideoPlayer, PageControl ect. 

It seems kinda odd that the competition that is out there, has somewhat the upper hand when it comes to the UI components. Compared to Telerik who is a UI company. :) But I guess that will change.

I just hope, for NativeScripts sake, that Telerik will re-think the idea of charging developers for simple, native features in UI-components (e.g. ListView pull-to-refresh, grouping, ect).

**Comment by valentinstoychev** [comment]
Hey guys - I think competition can really do only good things. Fuse are a good competitor by no means and it is really impressive how they show off their support for UX designers.

@manijak I'm really glad that you see Telerik as a UI - company. UI is really it the core of our company and we have tons of experience in this area. 

My only concern here is what you are mentioning at the end of your message - 
`I just hope, for NativeScripts sake, that Telerik will re-think the idea of charging developers for simple, native features in UI-components (e.g. ListView pull-to-refresh, grouping, ect).`

Can you please list ALL the things that in your opinion should be part of the free offering and lets see how we can fix this :).

**Comment by manijak** [comment]
Hi @valentinstoychev 
Knowing that a serious company such as Telerik/Progress is behind NativeScript, makes me as a developer more comfortable to use it. 

The idea that Telerik sells their own, feature-packed, components for NativeScript is perfectly understandable. Charts package is a good example of that, also the DataForm component that includes field-validation. But avoiding to implement all native features in a native component, just beacause that function is available in a paid-package, is in my opinion, a bad move. 

The comment you quoted above is just something I picked up from different users of NativeScript. Some of them come from similar open-source project and some directly from iOS/Android development. The first thing they notice or comment on is "Why do we have to pay for this, when it is available natively?".

The Nativescript UI package is limited for now, so there is not a lot to comment on. But I guess the main example is the ListView. In my opinion (and others) this should be available in the free offering:
- Pull-to-refresh (Refresh Control)
- View Styles (Plain, Indexed & Grouped)
- Swipe gestures (swipe-to-delete & swipe-to-action)

There are other components also, that I hope one day will be part of the {N} bundle (PagerControl, SplitView, Popover). But no point getting into them now, we know that time is your enemy.

Nativescript has come a long way, and it allready has a very good fundament for app development. I feel very comfortable developing apps for our cutomers and for myself, knowing it will only get better. Telerik has the sole power to attract even more users to {N} by doing what they do best: UI. 
By offering awsome UI out of the box would be an enourmous benefit for the framework as a whole and would make {N} even more popular. Not everything should be free, I agree, but giving the devs some features that they don't get elsewhere would be a huge plus.

**Comment by alexrainman** [comment]
Things that need to be free:

- RadListView with all the functionality that @manijak mentioned

Things that need to be done;

- PageControl/Carousel/PageSlider
- VideoPlayer
- Physics

Cheers!

**Comment by valentinstoychev** [comment]
Hey @manijak  and @alexrainman. Thanks a lot of the comments. Really helpful!

We are taking these comments into consideration. The things are really shaping as we speak and nothing is set in stone. **If there is a missing native functionality in the open source components it is not being made on purpose - it is just a matter of prioritization based on your and other customers' needs at the given moment.**

The reality is that having all and everything is just not possible to be done from the the core team. We are encouraging developers like you to contribute to the source code to fill those identified gaps. This way the NativeScript framework will have a much more sustainable development model. And one more note here - **if something is available in the paid tooling, doesn't automatically mean that it will not be available in the free tooling :)**. The reason that it is available first in the paid version is simple - in the UI for NativeScript package we are just re-using the already implemented functionality in our mature native components for [iOS](www.telerik.com/ios-ui), [Android](www.telerik.com/android-ui) and [Windows](www.telerik.com/wp7). The paid components step on the shoulders of those commercial component packages that we worked in the last 3 years. So it is normal that they are more feature-rich.

Our goal with NativeScript is to enable everyone to create a mobile app without the need of those paid tools. I believe that is a fundamental thing and a prerequisite for the success of NativeScript. **Our guiding principal is that if something is available by default in the iOS and Android OS it should be free and available in the core {N} components.** The paid tooling will give you the *support* options which can't be available for the free open source product and will also make some of our already existing paid entities (the native iOS/Android/Windows UI components and our mobile platform services) available for those who strive for the best experience and rapid development with NativeScript. As you can see this is not something that we invented, but a classic model for OSS monetization :).

I hope this gives you the context of why the things are what they are in the moment. Now more specifically on your suggestions:
 - **ListView** - I agree there is some missing native functionality in the core list view module and we should add it in the free version.
 - **PageControl** - definitely should be available in the core OSS modules. As this is not something too complex a community help is encouraged here and I already see that @alexrainman is already working on it!
 - **VideoPlayer** - definitely should be available in the core OSS modules. Again as the PageControl this is something easily achievable and can be done as a contribution to the core {N} components.

If you see any other gaps in the current core UI please do share them.

**Comment by manijak** [comment]
Thank you @valentinstoychev . Very happy to hear that things are going the the right direction. And that your vision and ambition around {N} is the same as for us developers. 

When it comes to contributing in the development of modules and controls, I bet there are a lot of us out there that would love to help out, including me. But we do not have the propper background from iOS or Android development to know where to start, what classes/functions/methods to use, how to wrap them. 

Would be great to get a step-by-step tutorial on how to. I know that these wrappers are almost never the same, but at least so that we can learn what to look for and learn some patterns. I would love to start on a VideoPlayer component.

**Comment by alexrainman** [comment]
@valentinstoychev i have been a Xamarin developer for a while and when i found {N} i said myself: this thing will be big, let me put as much time on it as i can ...

As @manijak said, with the right direction, the future will be awesome. I agree that if something is available in the native platform, it needs to be available in {N} core, like all the functionality of ListView mentioned before.

I will keep you guys posted about my progress with PageControl and SimpleTabView for Android.

**Comment by atanasovg** [comment]
@manijak I've prepared kind of a guide on [authoring user-interface related plugins](http://docs.nativescript.org/ui-plugin), it may be useful as a startup :) Additionally, there already exist quite [some plugins](https://www.npmjs.com/search?q=nativescript) that one may dig into and see how the author solves various problems.

**Comment by bradmartin** [comment]
@valentinstoychev - Glad to hear your response:
>  Our guiding principal is that if something is available by default in the iOS and Android OS it should be free and available in the core {N} components.

The more I kept reading about charging for some features/components started to have me worried. I completely understand monetizing on hard work and this project is not a light undertaking by the team so huge :+1: there. I know Telerik is investing quite a bit on this to have several core team members dedicated to it. I'm all for paying for a license to buy some nice components with killer features. I'll be one of the first to purchase a license for the components, if it's not too pricey :)

I come from a web background and more specifically I use Ionic Framework to build hybrid apps. With that said if NativeScript/Telerik were to move fast with the UI part and completing a core component set without charging devs. Telerik would be positioning itself to corner this market in the hybrid/native app space. Personally, I think you already have a better position than React Native due to it's syntax and the steep learning curve (my opinion). When you all decided to bring Angular 2 support on, you opened a huge door for devs going forward. I've said it before in the forums that the UI/UX is the only thing lacking with {N} (you might have been the one to reply then) and once that comes around I think you'll see developer adoption start to increase rapidly.

Just to cap this off, I'm a huge supporter of {N} and I can't contribute a lot of time to the code so I try to stay active on the forums to help out new devs learning some of the simpler things. So while that's not direct code contribution it does help this project in its own way by giving better faith to developers starting to learn the framework, so I encourage others to do that same also.

**Comment by hshristov** [comment]
@bradmartin - Could you please open an issue and specify what UI/UX feature are you missing most so that we can plan and prioritize them?

**Comment by bradmartin** [comment]
@hshristov - I believe there are already open issues for most of the items I had in mind.

- AV Player - https://github.com/NativeScript/NativeScript/issues/1066
- Border-radius bug (Android) - https://github.com/NativeScript/NativeScript/issues/830
- Pull-to-refresh (any view) - https://github.com/NativeScript/NativeScript/issues/724
- Radio Button control - https://github.com/NativeScript/NativeScript/issues/555
- Actionbar styling - https://github.com/NativeScript/NativeScript/issues/499
- ImageButton - https://github.com/NativeScript/NativeScript/issues/356
- TabView Styles - https://github.com/NativeScript/NativeScript/issues/260
- Built in Icons - https://github.com/NativeScript/NativeScript/issues/364
- Material Design - https://github.com/NativeScript/NativeScript/issues/399
- Paged Slider - https://github.com/NativeScript/NativeScript/issues/173
- Pseudo selectors in CSS - https://github.com/NativeScript/NativeScript/issues/50

I know some of these are in the master and will be released soon. One of the bigger issues for some devs, that I know, early on was inability to simply style the ActionBar/TabView bars with CSS. They didn't want to mess around with Android styles.xml files and learn the native approach because that was just slowing them down. So that will be an awesome addition when 1.5 hits. 

Another big one that has numerous comments/questions is the Material Design usage in Android apps pre-Lollipop. I know this can be achieved and I'm using the SwitchWidget with AppCompat but I think a good blog post from the team on how to create the Android Material Widgets would be really helpful for a lot of devs not sure how to work with gradle files. I've even struggled with it myself trying to get it set up correctly and working.

These are just some thoughts I had about the current state of {N} components. I am satisfied with everything so far and definitely not complaining. I only want {N} to succeed and dominate this market on native/hybrid apps and when more of these design elements are implemented it will only improve developer adoption and make people more impressed with the simplicity of {N} to create native apps.  :+1:

**Comment by alexrainman** [comment]
@hshristov here we go:

- ListView: pull-to-refresh, row actions, groups/sections, index, load-more
- TabView: simple TabView for Android not based on ViewPager (working not it asap)
- PageControl (working on it asap)
- Dialogs Module: Loading Wheel, Progress Dialog
- Http Module: bind progress to ui/progress or progress dialog
- Material design in Android
- ActionBar styling

Cheers!

**Comment by sitefinitysteve** [comment]
UI\UX shouldn't be just blown off (not that you are btw, but...)... there's lots of people of the mindset "What does a {N} app look like", or how easy is it to make it look good.  Right now if I was in eval mode for android the underlying framework is great, the end result with minimal\no code is pretty ugly.

While I also dislike the JS in the markup, what they can PUT in the markup is impressive...it's sometimes nice to not need to reference a view\object by ID in the script to just do a simple manipulation.  The design and motivation section makes it sound pretty slick https://www.fusetools.com/learn/fusejs

Wouldn't maybe be a bad idea to perhaps THINK about integrating some concepts...

**Comment by NathanWalker** [comment]
@hshristov This may be out in left field, but maybe there is opportunity to join efforts with Fuse? I don't see why knowledge sharing and collaboration could not benefit the community as a whole if NativeScript and Fuse joined forces to crack the ultimate holy grail of cross platform development via JavaScript.

Just my 2 cents. The collaboration would still bring inner competition of the 2 teams to come to the best solutions to solve various challenging problems.

**Comment by enchev** [comment]
Our own @vakrilov made very good plug-in recently: https://www.npmjs.com/package/nativescript-physics-js
