### ISSUE TITLE
Drawer widget

### ISSUE THREAD

**Issue by kikobr** [NativeScript/NativeScript#11]
Hi there, I'm having a hard time trying to find examples on implementing a drawer menu. I found a post "http://www.telerik.com/forums/drawers" where you could use a "custom NativeScript component", but I couldnt get it to work. In this page, Vlad's second reply said you'd need to use telerik's native components as libraries for the code to work. The problem is that this components is about $200, and I'm totally avoiding it. 

Is there a nativescript way to solve this? Is there missing documentation?

**Comment by ligaz** [comment]
Hey @kikobr,

The NativeScript way to solve this is to use native widgets and provide a common JavaScript API that exposes the component functionality. In your case there is a Drawer widget in the Android SDK and for iOS you will have to use a 3rd party component due to the lack of such widget in UIKit. Adding this 3rd party component will require that you use the `tns library add` command of the CLI. You can check how such components can be implemented in our cross-platform-modules repo (ex: [ListView](https://github.com/NativeScript/cross-platform-modules/tree/master/ui/list-view))

Regarding Telerik native components those are the components that we can provide support for and guarantee that they will work flawlessly in NativeScript.

**Comment by soone** [comment]
i think i can say nothing about nativescript....
