### ISSUE TITLE
Android Snackbar - pre lollipop text color conflict

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#1187]
![screenshot_2015-11-30-22-52-15](https://cloud.githubusercontent.com/assets/6006148/11492613/414a1a26-97b5-11e5-93b0-bacd46759826.png)

This is running on Android 4.4.2, on lollipop the text color is white and looks fine. Pre-lollipop there is a conflict somewhere. I read this post on SO (http://stackoverflow.com/questions/31061474/how-to-set-support-library-snackbar-text-color-to-something-other-than-androidt) and the suggested solution is to access the TextView of the snackbar but getView() is not a function available so this doesn't work. It's supposedly a styles/theme issue with 
    android:textColor
inheritance. Is there a workaround to color the text pre-lollipop for the snackbar? Or does anyone have a solution.

I guess I should also note I have not modified the styles.xml generated by the default nativescript build process.

**Comment by vakrilov** [comment]
Hey @bradmartin - I'm assuming that you are using your [snackbar plugin](https://www.npmjs.com/package/nativescript-snackbar). The problem seems to be that the Design library doesn't handle snackbar colors well, when the light theme is used - in out case `Theme.AppCompat.Light.NoActionBar`.
From the SO thread you posted - I think the best approach is to use `SpannableStringBuilder` to create a text with explicit foreground color. Here is what I tried (I just made the changes [here](https://github.com/bradmartin/nativescript-snackbar/blob/master/index.android.js#L49-L50)):
```
// Create red-colored text using SpannableStringBuilder
var sb = new android.text.SpannableStringBuilder();
var redColorForeground = new android.text.style.ForegroundColorSpan(0xFFFF0000);
sb.append(options.snackText);
sb.setSpan(redColorForeground, 0,  options.snackText.length, android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);

// construct the native snackbar
snackbar = android.support.design.widget.Snackbar.make(frame.topmost().currentPage.android, sb, options.hideDelay);
```
Maybe you can add `textColor` option in the API of the plugin so that users can set the color explicitly. What do you think about that?

**Comment by vakrilov** [comment]
I'm closing the issue for now.

**Comment by bradmartin** [comment]
Thanks. I'll give that a try, you were correct about the plugin :) I'll be
sure to add that and hopefully get it sent over to the marketplace soon.
