### ISSUE TITLE
Dynamically set actionbar background color with databinding

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#1188]
I've tried this in the loaded and navigatedTo events with no luck. Maybe I'm taking a bad approach to solve this. I want to style the actionbar with a random value from an array of hex values, similar to what Google does in the Messenger app.

If I try to databind a value to the background-color on the actionbar it never takes place but any hard coded value will be reflected.

    var materialColors = [
    { color: '#F44336' }, { color: '#E91E63' }, { color: '#9C27B0' }, { color: '#673AB7' }, { color: '#3F51B5'   },
    ];

      exports.loaded = function(args) {
    page = args.object;
    page.bindingContext = user;
    user.actionbarColor = materialColors[Math.floor(Math.random() * materialColors.length)].color;

And the XML: 

               action-bar title="Sign In" style="background-color: #{{ actionbarColor }}"

I've stepped through and the code works and the actionbarColor has a value so not sure what the issue is if it's a bug or designed this way.

**Comment by N3ll** [comment]
@bradmartin - what you can use instead of 
```
style="background-color: #{{ actionbarColor }}"
```
is
```
backgroundColor="{{actionbarColor}}"
```
Is there a specific reason why you want to use bindings in the inline CSS expression?

Another thing that I notice is that you are extending the **user** with the **actionbarColor** after you set the binding context. If the actionbarColor is not Observable, then the change won't be propagated to the view and the background color won't be set to the new value. If you don't want the actionbarColor to be Observable, you can just extend the user before you set the binding context.

**Comment by bradmartin** [comment]
@N3ll - no reason, I don't know why I was doing that ;) 

Thanks for pointing out the Observable/bindingContext set point. That fixed it.
