### ISSUE TITLE
Allow use of icon font codes in the TabView

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#1217]
_From @jlooper on December 3, 2015 15:49_

Currently, we can add an icon code to an element that has a 'text' property (like Label or Button). I'd like to use icons within a TabView and currently have to use an image because we have access only to the properties "iconSource" and "title". The Title should be the text, but maybe we can add a separate "iconCode" that would allow us to use an icon code.

Right now my tab bar looks like this on iOS:

![o6bcke0at30ugxta8jsiuamd3npw61uwekleq5as1ku](https://cloud.githubusercontent.com/assets/1450004/11565320/6d6413f8-99ab-11e5-9198-341878fb0432.png)

Using icon codes will allow me to avoid more image scaling battles. Thanks!

_Copied from original issue: NativeScript/nativescript-cli#1306_

**Comment by bradmartin** [comment]
+1

**Comment by enchev** [comment]
Hey folks,

I've implemented font-family support for the TabView however this will work only for the TabViewItem title property (font icon and text will be on the same line). Here is an example:
```XML
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <TabView style="font-family: FontAwesome;color: red;" selectedColor="green">
    <TabView.items>
      <TabViewItem ios:title="Tab 1 &#xf179;" android:title="Tab 1 &#xf17b;">
        <TabViewItem.view>
          <Label text="Tab 1" />
        </TabViewItem.view>
      </TabViewItem>
      <TabViewItem ios:title="Tab 2 &#xf179;" android:title="Tab 2 &#xf17b;">
        <TabViewItem.view>
          <Label text="Tab 2" />
        </TabViewItem.view>
      </TabViewItem>
    </TabView.items>
  </TabView>
</Page>
```
![screen shot 2015-12-11 at 2 30 02 pm](https://cloud.githubusercontent.com/assets/5804953/11743892/ca125d76-a013-11e5-8af5-494220f9a0f7.png)
![untitled](https://cloud.githubusercontent.com/assets/5804953/11743904/ecbbcbaa-a013-11e5-88fd-5e737da46a2d.png)

Unfortunately UITabBar/UITabBarItem cannot be customized to support multi-line titles nor font icons can be used instead of images.

**Comment by jlooper** [comment]
so, the behavior of the tab bar with stacked icon and title like on Twitter's mobile app and described below is dependent on using images? Oh well...

https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/BarIcons.html

**Comment by enchev** [comment]
@jlooper unfortunately. :/

**Comment by prantikv** [comment]
@enchev does this work for NativeScript with Angular 2

```
<TabView tabTextColor="#FF0000"  selectedColor="#FF0000" selectedTabTextColor="#FF0000">
    <StackLayout *tabItem="{title: '&#xf015; Profile &#xf1e0;" >
   <Label class="fa" text="&#xf015;"></Label>
<Button class="fa" id="button" text="&#xf1e0; Tap me!" ></Button>
    </StackLayout>
    <StackLayout *tabItem="{title: '&#xf015; Stats', iconsource:'~/icon/ic_account_circle_black_24dp.png'}">
        <Label text="Second tab item"></Label>
    </StackLayout>
 
    <StackLayout *tabItem="{title: 'Settings'}">
        <Label text="Third tab item"></Label>
    </StackLayout>
</TabView>
```

There is no ` <TabViewItem>` tag to work with and setting the `tabItem` JSON object does not work

**Comment by NickIliev** [comment]
Hey @prantikv 

At this very moment using icon fonts for your tab-view title is not supported.
The issue is logged [here](https://github.com/NativeScript/nativescript-angular/issues/364) and you can track the linked issues that are related to it.
Meanwhile, you can use **iconSource** and provide an image for your *tabItem.

e.g.
`<StackLayout *tabItem="{title: 'Title', iconSource:'res://icon'}">`
