### ISSUE TITLE
Vagrant Box

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#124]
Hi,

I think it would be very helpful to have a NativeScript base Vagrant box to get started.

**Comment by valentinstoychev** [comment]
Please [vote for this issue](https://nativescript.ideas.aha.io/ideas/NS-I-21) in our ideas portal.

**Comment by guillaume-roy** [comment]
Your link is good ?

**Comment by valentinstoychev** [comment]
Yep - it should be. The idea was private for a moment and initially it was not visible probably, but now should be ok :).

**Comment by guillaume-roy** [comment]
I have created a Vagrantfile that install : 
* VirtualBox Guest Additions
* Unity
* NodeJs
* NPM
* Git
* Requirements for NS until step 6 included (http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux)

http://pastebin.com/bBmtnNvb

After that, if I continue the installation process, i have some problems :
* I don't have the platform-tools dir in the SDK Tools Only archive
* I have some errors when i install nativescript with npm (using 'sudo' or not)
* If i install NS with 'sudo npm' then i must execute each next command with 'sudo'

**Comment by rosen-vladimirov** [comment]
Hi @guillaume-roy 
Thanks for sharing this additional information. You are correct - platform-tools dir is not part of the AndroidSDK dir by default, you should install it additionally (run "andorid" command on your terminal and inside Android SDK Manager select Android SDK Platform-tools and install them). Based on [this SO answer](http://stackoverflow.com/questions/17963508/how-to-install-android-sdk-build-tools-on-the-command-line) you should write something like:
`android update sdk -u -a -t 2` (on my machine 2 is the Android SDK Platform-tools, I believe this will be the case on yours as well).
As per the errors when you install nativescript with npm, could you share them, so we'll be able to investigate them. If you use sudo, we strongly recommend the following syntax:
`sudo npm i -g nativescript --unsafe-perm --production` where `--production` will prevent installation of dev-dependencies of nativescript cli and `--unsafe-perm` will really use root user (by default npm changes the user to nobody when sudo is used and this causes several issues).
If you install NativeScript CLI with sudo, you should be able to invoke it without sudo, but maybe you have faced some unexpected behavior due to the installation errors. 
Can you send us installation log and the output of `tns -h --log trace` after the installation is completed?
I'm looking forward to hearing from you.

**Comment by guillaume-roy** [comment]
Hello,

Please find attached my npm-debug.log : http://pastebin.com/JbJsnrNk 
Inside it, you'll find the last error i encoutered using a fresh "sudo npm i -g nativescript".

I also attached my Vagrant initialize file from where i just typed the sudo npm : http://pastebin.com/GT2Tsj0C

I can't execute "tns -h --log trace" because nativescript fail to install.

**Comment by guillaume-roy** [comment]
I succeed to install nativescript after installing nodejs-legacy, but : 
* During the NativeScript installation, i had a yellow message saying that i have a bad adb version installed
* This the result of my "tns -h --log trace" : http://pastebin.com/b3VJZYYC

**Comment by guillaume-roy** [comment]
I created a repo where you can find my Vagrant files to try to reproduce : https://github.com/guillaume-roy/NativeScript-Box

I can now install nativescript but when i try to create a new project, i have an error on ANT. I tried to add ANT to my PATH but it doesn't work.

Please can you detail your installation process in your Getting Started section ?

**Comment by teobugslayer** [comment]
Hello @guillaume-roy,

I am sorry for the late replay. I fought with Vagrant a bit but could not make it work for me.

That said, we keep our [documentation](http://docs.nativescript.org/setup/ns-cli-setup/ns-setup-linux) and [CLI readme](https://github.com/NativeScript/nativescript-cli#linux) up-to-date as much as possible and they usually are a good guide how to install the CLI manually.

We recommend installing node via the install scripts provided by node.js. Your vagrant script uses nvm AND nodejs-legacy packages at the same time, overwriting parts of node & npm in the process.  Also, you install nvm per user (and thus node per user) but npm globally (via a debian package).

I recommend following the official way of installing node as described on [their site](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions).

In your [log file](http://pastebin.com/b3VJZYYC) I can see that ant is not found - see line #80 - please rectify this.

Last, in your vagrant script, all paths contain ~vagrant. I could not test them, but I know that vagrant's user is "vagrant", and I wonder, shouldn't these paths be either |/home/vagrant"  or simply "~"? As I said, I could not test this so I am shooting in the dark here.

**Comment by Nathanaela** [comment]
I have a initialize script that can be used to build a vagrant box.   
https://github.com/Nathanaela/nativescript-vm

**Comment by guillaume-roy** [comment]
Nice ! I'll take a look when i go back at work (next week).
Le 26 mai 2015 05:49, "Nathanael Anderson" <notifications@github.com> a
écrit :
