### ISSUE TITLE
backstackVisible: false not working

### ISSUE THREAD

**Issue by firescript** [NativeScript/NativeScript#1262]
I'm just trying to navigate the user to the "dashboard" page with out the auto generated link to go back to sign in page. I am passing in an object to the navigate() that looks like this:

```
frameModule.topmost().navigate({
 moduleName: "views/dashboard/dashboard",
 backstackVisible: false,
 animated: false
});
```
When I get to the dashboard view there is still a link to the sign in page. Then If I hit log out, my app settings are cleared and i'm redirected to the sign in page with a back link to dashboard..

I'm running 
`nativescript@1.5.2`
`tns-core-modules@1.5.1`

**Comment by firescript** [comment]
I used clearHistory: false to get this working!

**Comment by atanasovg** [comment]
@firescript Your code will make the `Dashboard` page not present in the backstack, not the `Sign-in` one, which is still present in the backstack, hence the back button. You will need to navigate to the `sign-in` page using `backstackVisible: false`. If this is the main page of the application then you may use the [mainEntry](https://github.com/NativeScript/NativeScript/blob/master/application/application.d.ts#L101) property of the `application` module instead of the [mainModule](https://github.com/NativeScript/NativeScript/blob/master/application/application.d.ts#L96) one.
