### ISSUE TITLE
Android border-radius needs to be anti-aliased

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#1284]
Whenever I apply a border radius on Android, you can see visible jagged edges that need anti-aliasing applied to them. 

Here's examples:

![screenshot 2015-12-22 16 17 33](https://cloud.githubusercontent.com/assets/5018471/11947781/b0b1a6c8-a8d0-11e5-8c9f-af3a54dbb4cc.png)
![screenshot 2015-12-22 16 28 50](https://cloud.githubusercontent.com/assets/5018471/11947780/b0b0b25e-a8d0-11e5-93a8-ee86fcbf14e9.png)

**Comment by x4080** [comment]
Thats what i found looking weird in my nexus 7

**Comment by hshristov** [comment]
Check https://github.com/vinc3m1/RoundedImageView

**Comment by x4080** [comment]
I think thats only for image? And i remembered it crash when setting the border because not using image

**Comment by PanayotCankov** [comment]
I've found two places that cause problems.

[One is the android drawing of background that uses clip for corner radius-es](https://github.com/NativeScript/NativeScript/blob/a760328422c121156815419dcac9a3201c2231ae/ui/styling/background.android.ts#L94). It appears there is no way to make the clip anti-alias in android, so we should draw the border and the background here with proper geometry, aliasing paint and no clipping.

[The other is the ImageView's onDraw](https://github.com/NativeScript/android-widgets/blob/master/widgets/src/main/java/org/nativescript/widgets/ImageView.java#L163), that once again uses clip. To allow aliasing here we can:

 - Draw the super.onDraw(...) into Canvas of a new Bitmap and draw that Bitmap with drawRoundRect in the original canvas. This will be easy to implement, however it will maintain a new Bitmap in memory.

 - Another more lightweight solution may be to completely refactor the ImageView so that we have access to the underlying decoded Bitmap and draw it with anti-aliasing avoiding the additional intermediate BItmap (this is the [https://github.com/vinc3m1/RoundedImageView](https://github.com/vinc3m1/RoundedImageView) solution. That however will pull more code to support in our framework.

**Comment by PanayotCankov** [comment]
The issue should be resolved in 1.6 for elements that have border, background and corner radius set. It will still not anti-alias the corner radius of an ImageView. #1481

**Comment by x4080** [comment]
cool
