### ISSUE TITLE
Allow Livesync to watch the node_modules folder

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#1288]
I find it easiest to modify a plugin by tweaking the code installed into node_modules\module-name instead of in the plugin itself and constantly re-adding it to the solution.

Problem is, the livesync watch command doesn't seem to trip on these changes, so I have to keep re-running my code.

**Comment by NathanaelA** [comment]
I can tell you the reason why I don't do it in my LiveEdit plugin.  
1. It adds a much larger number of OS watches on both platforms (this contains 149 files in probably 120 folders.  That is a LOT of watches and a lot of OS resources on both the phone and the computer...
2. These files rarely ever change. 

My solution, In my case if I'm working on a plugin (say liveedit itself), I just copy the nativescript-liveedit.js file itself into my project app directory.  Then I modify that copy.  ;-)    The main app.js file is changed to instead of var liveEdit = require('nativescript-liveedit') becomes, var liveEdit = require('./nativescript-liveedit'); and then I add liveEdit.addRestartFile('nativescript-liveedit.js');   And I'm good to go.   When I am finally done with all my changes; I copy back to the plugin code to the main plugin repo.

**Comment by sitefinitysteve** [comment]
OKay fair enough, I can change the workflow :) :+1:

**Comment by hdeshev** [comment]
Since we're sharing hacks, I thought I'd show you mine. I use a `before-prepare` hook that copies the "library" code I'm working on to a test app's `app` folder. It's pretty easy to do, if you let `shelljs` do the cross-platform copying for you. Of course, I change imports from "blah" to "./blah" as well. Here's the `nativescript-angular/ng-sample` hook:

https://github.com/NativeScript/nativescript-angular/blob/master/ng-sample/hooks/before-prepare/10-copy-renderer.js

Note the weird hook name prefix. I use different numbers to make sure the copy hook runs before the TypeScript compile hook.

**Comment by saulshanabrook** [comment]
Would it be possible to add another flag to watch`node_modules`? It's a bit cumbersome to have to move it locally, especially when there are multiple dependencies to edit.
