### ISSUE TITLE
Determine if the app is running in local/debug/development mode

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#1293]
It would be good if we could call, e.g. `require("application").isDebug()` or similar to tell if the app is being run as a debug APK or is being run via Xcode debugger. Our use case is we only want to enable our external error reporting if the app is being run "in production".

Possible native implementations:

Android: http://stackoverflow.com/a/23844716/881691
iOS: http://stackoverflow.com/a/9063682/881691

**Comment by NathanaelA** [comment]
@maknz,

If you are interested I have an internal library that I am slowly turning into a plugin that I use on my projects that has a ton of helper functions like this.  I have process.isDebug() and isEmulator().

One of these days I need to finish making it an official plugin; isDebug just returns isEmulator on a iOS device since the DEBUG state doesn't appear to be propagated into the NativeScript environment.  However on Android it actually checks the signature of the application to detect if it is signed by a debug key.

**Comment by slavchev** [comment]
@maknz 

Regarding Android you can take a look at https://github.com/NativeScript/android-runtime/blob/698044c73cfb9c4ff6e075d3cb81f58667d4a045/src/src/com/tns/Util.java#L26
