### ISSUE TITLE
How to send data from view to backend i.e view-model

### ISSUE THREAD

**Issue by akkiittiwari** [NativeScript/NativeScript#1294]
I am trying to make a e-commerce app using nativescript but am unable to send data from frontend to backend on events such as add to cart, product selection from a list of products.

A quick and detailed help would be appreciated.

**Comment by NathanaelA** [comment]
Well there is a couple ways to do this.  
1. You can use the the native Fetch or HTTP library to send the data to the server. (see docs.nativescript.org for the docs on them)
2. You can use my NativeScript-WebSockets (https://github.com/NathanaelA/nativescript-websockets) plugin to have a realtime data stream to/from the server.

I do also have a book coming out Jan 6th, that actually shows you how to use both methods as the main project of the book is a real time communication application so it walks you through in chapter 4, how to use the internal HTTP code for communication, and then we replace that code in Chapter 5 with the websocket plugin so that it is now quicker and less resource intensive.
