### ISSUE TITLE
Question: Do I need to require the .jar file for access in code?

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/NativeScript#1328]
Hi,

Do I need to 
```
var jar = require("path_to_jarfile/my.jar");
```
to access the native java code or the following works:
```
var Variable = new com.blah.blah.myjar();
```
?
The reason for asking is that I am not able to program the dropbox sdk.

**Comment by N3ll** [comment]
@gaurav-chandra, you would usually use **require** for accessing **modules** and **.so files**. The best way to use **.jas files** is to create a [plugin](https://docs.nativescript.org/plugins/plugins.html). If you decide to follow this approach, it is best to try to find an **.aar file** instead of .jar.
Moreover, [this article](http://geekgarage.dad3zero.net/android-studio-gradle-dropbox-sdk/) could be helpful for working with the Dropbox SDK.
