### ISSUE TITLE
getting nativescript view from native view

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#1332]
Hi, if we want to get the native view from the nativescript view, we use _nativeView property, how to do the reverse ?

thanks

**Comment by hshristov** [comment]
There is no way to get {N} view from native widget. We don't keep such mapping is if you need this you can create a map between the two. I would highly discourage such map because we destroy and recreate the native widgets when navigation happens so this map could become outdated on navigation and will probably cause memory leak.

Why do you need such functionality?

**Comment by x4080** [comment]
I was thinking of using native touch listener which return the native view for example panning of views

**Comment by enchev** [comment]
By default there is no way to get this however you can easily add reference to the JavaScript wrapper using loaded event. For example:
```JavaScript
exports.loaded =  function(args){
   var jsObject = args.object;
   var nativeObject = args.object._nativeView;
   nativeObject["jsObject"] = jsObject;
}
```

**Comment by x4080** [comment]
OK then, related to this question, why is in android the view always gets destroyed and recreated when the app goes to background ?

**Comment by enchev** [comment]
Let's continue the conversation here: https://github.com/NativeScript/NativeScript/issues/1337
