### ISSUE TITLE
URL Scheme support

### ISSUE THREAD

**Issue by aaronjensen** [NativeScript/NativeScript#136]
It would be nice to have examples for setting up custom url schemes. I was able to do it in iOS by modifying the info.plist myself (is that safe? Docs say not to modify anything in the platforms folder...) and doing this:

```javascript
    NSNotificationCenter.defaultCenter()
      .addObserverForNameObjectQueueUsingBlock("com.telerik.TLKApplicationOpenURL", null, null, function(notification) {
          var topmost = frame.topmost();
          topmost.navigate("camera");
      });
```

But I wasn't able to figure it out on Android. An example or a native way to handle it would be awesome. Thanks!

**Comment by manijak** [comment]
+1 for a cross-platform module that would allow us to define custom url schemes.

**Comment by PanayotCankov** [comment]
Currently the CLI merges the Info.plist of the plugins into one and uses it in the applicaiton in platforms. I think there is a feature request to allow Info.plist to be set in the app/App_Resources and be merged similar to the way the plugins does. This will allow you to set these settings for iOS in the app folder instead of the platforms folder.

The state for android is similar. The scheme is defined in an intent filter of an activity. [You can check an example in this stackoverflow post](http://stackoverflow.com/questions/18102528/android-how-to-create-custom-url-scheme-with-the-given-format-myapp-http).

The intent data can be handled using the appication module's launch event, the intent is provided in the event data's `android` property:
https://github.com/NativeScript/NativeScript/blob/master/application/application.android.ts#L206

We should further investigate if the CLI hooks and the plugin and plugin variables will be sufficient to allow custom URI schemes to be defined and handled in a cross platform manner.

**Comment by NathanWalker** [comment]
Any update on this? Or pointer to how a custom URL scheme could be made for iOS at least?

**Comment by enchev** [comment]
Hey @NathanWalker,

This example may help you: https://github.com/NativeScript/NativeScript/issues/1513

**Comment by PanayotCankov** [comment]
As of 1.6.0 the `app/App_Resources/iOS/Info.plist` and `app/App_Resources/Android/AndroidManifest.xml` officially should contain full info plist and android manifest and stay in source control, where it is safe to keep the settings necessary for handling the schema.

**Comment by hypery2k** [comment]
you can use my plugin for this: https://github.com/hypery2k/nativescript-urlhandler
