### ISSUE TITLE
Livesync not syncing assets

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1364]
I am working on an Nativescript project on Android.

I noticed that when using **livesync** new assets in **App_Resources** (e.g. an image used by res://image) are not loaded.

In fact I don't see anything in particular in the terminal but most important I even need to

- uninstall the app (otherwise it just skips installation)
- delete 'build' folder (otherwise nothing new is actually uploaded)
- re-build / livesync

to make it recognize the new assets.

**Comment by NathanaelA** [comment]
Any actual assets the app has to be rebuilt.  You should not have to delete the build folder nor uninstall the app.  If I recall correctly, the built in LiveSync doesn't typically rebuild the app; so you can use.    **tns run android** or **tns deploy android** and then after it deploys switch back to livesync mode.   Their maybe a faster way than this (using stock tools); but since I don't actually use the limited built in LiveSync stuff, I can't really tell you.  

I do know in my free LiveEdit product; I also have the same limitation for compiled resources; the app _must_ be rebuilt for any actual app_resources; these can't be synced to the device since they are compiled into the actual application.   So in my case if I change a resource; I leave my LiveEdit watcher running, and then do a simple **tns run android --emulator** and let tns rebuild the app and redeploy it, and then just continue editing any of the source code and then my LiveEdit keeps everything else in sync on the device.

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#1390
