### ISSUE TITLE
Grid-Layout would deserve a .setCell(column,row,element) method

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/NativeScript#1374]
Populating a Grid-Layout is cumbersome today. It would deserve a .setCell(column,row,element) method.

**Comment by mike-ense** [comment]
(Not static of course.)

**Comment by NathanaelA** [comment]
What @mike-ense is proposing is a simple helper function added to the grid prototype chain so that you only have to call one function to add any item as a child of the grid table.   This would set the values on the element and add the element as a child to the grid.    I actually think this is a pretty good idea as is simplifies making grids programmatically since you eliminate multiple calls and only have a single call.   However, I think I would change it to be a bit more flexible and do something like:
MyGrid.addCell(element, options) where the options object can contain {column, row, colspan, rowspan, etc...}

**Comment by enchev** [comment]
Closing this due to low interest from the community. If you still think this will be useful please submit pull request.
