### ISSUE TITLE
How to change display name of the application in launcher?

### ISSUE THREAD

**Issue by jaysson** [NativeScript/NativeScript#1377]
I have an abbreviated name (based on app id?) showing up on launcher. How do I change it?

**Comment by PanayotCankov** [comment]
You must edit the Info.plist and AndroidManifest.xml.

For iOS with the next version of the CLI we will support a full Info.plist file located [in `app/App_Resources/iOS/Info.plist` in our nativescript marketplace demo](https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/App_Resources/iOS/Info.plist). However the one in this app is still copied in `platforms` in post prepare hook the value used is in the `CFBundleDisplayName` there. You should be able to edit the `platforms/ios/<proj-name>/<proj-name>-Info.plist` file and rebuild.

For android currently we do merge an [AndroidManifest.xml from `app/App_Resources/Android/AndroidManifest.xml` similar to the one here](https://github.com/NativeScript/nativescript-marketplace-demo/blob/production/app/App_Resources/Android/AndroidManifest.xml), there I think you can place `android:label="My App"` on the `application` element and avoid manually editing the files in `platforms/...`.

**Comment by irfanfadilah** [comment]
In Android you cannot simply change the value of `android:label` to any string because when I tried, it raise error "Manifest merger failed : Attribute application@label value=(Example App Name) from AndroidManifest.xml:25:3-33"..

I end up editing the file in `/platforms/android/src/main/res/values/strings.xml` and it's works..

**Comment by toddanglin** [comment]
The default Info.plist created for iOS projects include XCode build variables:
```
	<key>CFBundleDisplayName</key>
	<string>${PRODUCT_NAME}</string>
```
Since it's not obvious in NativeScript projects where these variables could be set, would it make sense to instead automatically use some value from the app's `package.json` at build time when this variable is present?

The `name` variable makes the most sense, but it doesn't allow spaces. Maybe dashes and underscores can be auto-converted to spaces? Or maybe the app name can be put in `nativescript > name` settings section?

Just a thought to improve the clarity of this process for iOS apps.

**Comment by jlooper** [comment]
While you're thinking about this, also note that name should be localizable, which may add a wrinkle

**Comment by Edujugon** [comment]
Hi guys!

I'm facing the same issue with the app name.
Once the app is installed, the app icon name shows the correct name as I set in android:label but when the app is being installed it show the package name instead of the app name..

Any idea around this?

**Comment by Devlain** [comment]
In my case I can't edit the application name even if I edit my **AndroidManifest** 
`<application android:name="DifferentName">`

what else could I try?

**Comment by Edujugon** [comment]
@Devlain 
Have a look [at this](https://docs.nativescript.org/publishing/publishing-android-apps#app-name).

Hope it's helpful :)

**Comment by Devlain** [comment]
Hi people!
I finally resolved this issue in the next manner.
First of all, I looked for String.xml in values folder, but there wasn't any **String.xml**, so **I simply created it just as @NickIliev said**.
From there I just needed to add that code to that file in that folder. **It wasn't required to do the same in values-21 folders to me to fix the issue**.
I hope this could help somebody else =)
Thanks all for your help!

**Comment by 3rror404** [comment]
Adding a string.xml file gave me a build error:

`Error: Duplicate resources`

Even after removing the files I still received the same error. I had to completely remove and re-add the Android platform.

Turns out when you do `tns platform add android` a `strings.xml` (notice the extra "s") file is created:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">AppName</string>
    <string name="title_activity_kimera">AppName</string>
</resources>
```

I also received build errors if I didn't include the `title_activity_kimera` value.

**Comment by NickIliev** [comment]
Hey @Devlain 

Nice to know you have resolved your issue!
Just a side note - the folder **values-v21** is used for API levels equal and greater than 21 so it will be used if you deploy on device with newer API.

**Comment by ivanblazevic** [comment]
I would also add in case app name is not changed even after strings.xml is added that you need to:
- uninstall app
- restart your phone
- tns run android

**Comment by marcosnc08** [comment]
Don't forget to re-add the android platform or to delete the platforms folder after changing the name.
