### ISSUE TITLE
LiveSync clears navigation history

### ISSUE THREAD

**Issue by Fatme** [NativeScript/NativeScript#1417]
_From @mikebranstein on November 28, 2015 2:22_

After LiveSync refreshes a page, the current navigation history is cleared. Attempts at navigating back  after a LyneSync refresh do nothing, i.e., `topmost.goBack();` does nothing. Additionally, the "< Back" navigation link is missing.

I feel LiveSync should maintain your navigation history to move about your app. 

I'm running NativeScript 1.5.0. 

_Copied from original issue: NativeScript/nativescript-cli#1273_

**Comment by Fatme** [comment]
_From @ligaz on December 7, 2015 21:22_

@hshristov can you elaborate on the current implementation and what we can improve in order to not clear the history?

**Comment by NathanaelA** [comment]
Status update; I've closed my pull request as it WON'T fix the issue.     What needs to happen is a feature to be able to replace the last item in history; that is something the framework currently doesn't allow.   

When you set the current loading page to not be in back history; it doesn't change that when you go back it still goes back to the prior page which is in history.  On a reload if you didn't clear the history, the prior page would be the same page (before the reload occurs).   So it ls weird to go back, and get the same page since it would be in history...

**Comment by atanasovg** [comment]
This issue is the same as this one: https://github.com/NativeScript/NativeScript/issues/4554. Closing this one.
