### ISSUE TITLE
Are there any plans to introduce a TCP socket module?

### ISSUE THREAD

**Issue by prawnsalad** [NativeScript/NativeScript#1438]
I'm currently developing an IRC client and knocked together a non-blocking TCP Socket .js module just to get going: https://gist.github.com/prawnsalad/586098d216cb09c660ac

Because it's only a js module on Android it does have its limitations such as running on the main thread occasionally locking it, hardly any connection error checking, etc. I don't know Java so not sure where to start on turning this into a proper compiled module nor to even attempt it for IOS.

What's my best option to get a usable TCP socket in nativescript?

**Comment by NathanaelA** [comment]
I'm sure at some point in the future a Native background socket layer will be available.  At this moment since threads are NOT available inside of NativeScript; you have two choices:
1. Create or use an android Socket library that already is threaded.  NS can use these; but you have to understand the events bringing data back into the NS will all be back on a single thread.
2. I just released NativeScript-WebWorkers; which allows additional JavaScript threads; however it is limited in that the additional thread is just a browser VM; not the full NativeScript VM.  So you unfortunately can't call into the Android/iOS runtime from it.  But the JS in these VM's do have access to anything a fairly modern browser has access to (like Ajax requests, etc).

**Comment by prawnsalad** [comment]
What's the status with this? Is there an official stance on how to use TCP connections?

A quick message instead of simply closing the issue would be great...

**Comment by enchev** [comment]
Hey @prawnsalad,

I'm closing this due to low activity from the community. If you think that this is needed you can submit pull request.
