### ISSUE TITLE
Enable Android 6 way for requesting permissions

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#1451]
Quoting from the [official Android guides](http://developer.android.com/training/permissions/requesting.html):
>Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app.

Once we integrate the new functionality from the Android Runtime (https://github.com/NativeScript/android-runtime/issues/283) we need to base our Activity on [AppCompatActivity](http://developer.android.com/reference/android/support/v7/app/AppCompatActivity.html) and provide an implementation of the [OnRequestPermissionsResultCallback](http://developer.android.com/reference/android/support/v4/app/ActivityCompat.OnRequestPermissionsResultCallback.html) interface. Then we need to design some JavaScript-friendly API to allow people to enable permissions more elegantly than calling native APIs.

**Comment by VicMota** [comment]
+1

**Comment by gopi-ar** [comment]
+1

**Comment by gopi-ar** [comment]
Essentially NativeScript doesn't fully support Android 6.0 then?

**Comment by aderbas** [comment]
+1

**Comment by bradmartin** [comment]
@gopi-ar - just wanted to point out that it does support 6.0, I'm sure this issue is to create a nice API for devs to use and not deal with the native code dealing with permissions, it can be a bit tricky without any Android knowledge.

**Comment by EddyVerbruggen** [comment]
Just wanted to add that @bradmartin is right and if you wonder what you can do now, then [here is an example](https://github.com/EddyVerbruggen/nativescript-mapbox/blob/master/mapbox.android.js#L23-L36). If you request permission before using the thing that requires the permission then all is fine.

Only in case you want to defer requesting permission until the thing that requires the permission is called and have it invoked immediately after the user has granted the permission - then you need the `OnRequestPermissionsResultCallback` API @atanasovg refers to.
Which I eagerly await by the way since I'm using this in 3 plugins now and want the developer to choose whether or not he wants to defer requesting permission or ask it upfront. Either way you want to check the user granted permission every time before triggering the code that may need the permission.

**Comment by bradmartin** [comment]
@eddyverbruggen does  that really work? I tried hacking that together in a hurry the other night for RECORD_AUDIO and I failed miserably but I was hurried to just check if it was possible :)

**Comment by EddyVerbruggen** [comment]
@bradmartin Yes I have that in 4 NS plugins and use the same approach for about 10 Cordova plugins as well as they started to support `OnRequestPermissionsResultCallback` only in a recent version of the fwk and I didn't want to force users to not use SDK 23.

Note that you need to [include the support v4 lib](https://github.com/EddyVerbruggen/nativescript-calendar/blob/master/platforms/android/include.gradle#L10).

**Comment by Daxito** [comment]
+1

**Comment by NathanaelA** [comment]
I have just added a pull request that will add the basic functionality to core to be able to handle Android 6+ permissions.  ;-)    Hopefully they will accept it.

**Comment by aderbas** [comment]
Any update about this? =/

**Comment by vjoao** [comment]
The PR is merged. 
You can go to nativescript.rocks and download a build from master if you are not willing to wait for the release.

**Comment by NathanaelA** [comment]
Please note I have a plugin that I will be releasing shortly that makes permissions a breeze for all of us plugin developers (and other uses are perfectly valid also :grinning: )

```
permissions.getPermissions(camera)
   .then( function() {  /* has support */  })
   .catch(function() { /* user denied giving you permissions */ });
```

The permission promise persists until the promise can be resolved via the requestPermissions system on Android 6 and automatically resolves on Android 5 and lower since we don't have to request permissions on those OS's.

**Comment by NathanaelA** [comment]
I've released the permissions plugin; however again this requires support that is in the masters; so it currently does NOT work on v1.7 unless you manually make the changes that I put into my two pull requests (Linked to earlier in this thread).   https://github.com/NathanaelA/nativescript-permissions
