### ISSUE TITLE
typings attribute in package.json violate typescript typings rules

### ISSUE THREAD

**Issue by mkosieradzki** [NativeScript/NativeScript#1458]
https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages
"Your typings file should...
•be a  .d.ts  file
•be an external module
•not have triple-slash references "

tns-core-modules.d.ts violates second and third rule: it is not an external module it has only triple-slash references.

**Comment by hdeshev** [comment]
Hi @mkosieradzki,

We are aware of those guidelines, and try to follow them as much as possible. The problem with the built-in NativeScript modules is that their compile-time file location is different than the runtime module location, and that poses some challenges. For example:

* A file like `ui/core/view.ts` defines the `ui/core/view` module.
* It is then bundled in the `tns-core-modules` package and client apps "see" it below `node_modules/tns-core-modules/ui/core/view`, and have it discoverable as `tns-core-modules/ui/core/view`
* At runtime it is available as `ui/core/view`.

That's why we publish a set of ambient modules that you need to reference in order for the compiler to "see" "tns-core-modules/ui/core/view" as "ui/core/view". tns-core-modules.d.ts is a helper file that lets you refer to all those ambient modules using a single reference.

To really fix this we would have to change the project structure and move all NativeScript modules below a folder like `nativescript` and refer to our modules as `nativescript/ui/core/view`. The problem with that is that it will break a lot of client code. There may be a way to do it without breaking existing code by shipping compatibility modules in place of the old modules and reexporting the new ones. That needs to be discussed in depth and hasn't been planned yet.

/cc @hshristov, @atanasovg, @PanayotCankov, @ligaz

**Comment by ligaz** [comment]
We might rely on this new module resolution strategy coming in TypeScript 2.0: https://github.com/Microsoft/TypeScript/issues/5039

**Comment by mkosieradzki** [comment]
Good thing about this situation is that there are mostly external modules and no internal modules (as for example in KendoUI), so at least this is possible at all.

I suppose one of solutions is to keep using tns-core-modules.d.ts for legacy code (for reverse compat) and allow discovery as: tns-core-modules/ui/core/view created as proper pure external module.

In runtime there should be some aliasing mechanism allowing to discover using both names:
ui/core/view => tns-core-modules/ui/core/view.

Regarding the new mechanism I haven't analyzed it yet but from the practical point of view nodejs resolution strategy is extremely handy as long as you use "npm everything".

**Comment by mkosieradzki** [comment]
This change maybe also somehow related to #1457 . Because for ES5 TS target you need to provide all the shims that are mostly internal modules (so you need to use some kind of tns-core-modules.d.ts with ambient typings). For ES6 target probably everything can be placed inside external modules.

**Comment by atanasovg** [comment]
It may be a dumb question but what would {N} modules benefit if we invest time in changing the current situation? Are there some known issues caused by the described guidelines inconsistency?

**Comment by hdeshev** [comment]
I have seen some tooling issues with our nonstandard directory structure. Webpack, for example, would look for the `ui/core/view` module inside `node_modules`. You could provide additional "modules" directories, but you can't (easily) make it map `ui/core/view` to `tns-core-modules/ui/core/view`. My guess is that other bundlers will have the same problem.

I have a pending task about investigating a way to map modules in a way similar to the above in webpack (We probably need to map `ui/core/view` to `tns/core-modules/ui/core/view/view.android.js`), and I'll report back when I know more.

**Comment by atanasovg** [comment]
Thanks @hdeshev. I read your comment on [this issue](https://github.com/NativeScript/nativescript-angular/issues/60#issuecomment-182536108) and the current issue makes perfect sense now.
