### ISSUE TITLE
Repeater: weird behaviour when data binding

### ISSUE THREAD

**Issue by Ivshti** [NativeScript/NativeScript#1485]
Hello,

This is the XML line in question:
```
<Repeater.itemTemplate>
   <Button class="{{ $parents['Repeater'].selectedType, $parents['Repeater'].selectedType == type ? 'menuButton selected' : 'menuButton' }}" text="{{ $value.name }}" tap="selectType" />
</Repeater.itemTemplate>
```

Notice how in the ``class`` attribute, I'm using ``type`` directly and it corresponds to the ``type`` property of the ObservableArray element within the ``Repeater``. Notice how on ``text`` attribute, I'm using ``$value.`` to access the same object.

Not using ``$value`` on ``text`` and using ``$value`` on ``type`` does not work.

The questions are:
1. Why does this inconsistency exist
2. Is it documented? Is it by design?
3. How to debug this myself through the source code? Would looking up the button component source code yield the answer?

**Comment by enchev** [comment]
Hey @Ivshti,

You are right about `$value` in expression (your `class` binding) and we will try to fix this ASAP. For the  text binding however you can use both `{{ $value.name }}` and `{{ name }}` directly.
We've made `$value` to [provide easy access to arrays with simple types like strings, numbers, etc.](http://docs.nativescript.org/core-concepts/bindings#binding-to-a-plain-object) and maybe to avoid further problems (since you have complex objects with properties) you should use directly property names without `$value` in front.

**Comment by Ivshti** [comment]
@enchev then I should not use ``$value`` for objects? Shouldn't the behaviour be consistent for objects and strings/numbers?

**Comment by enchev** [comment]
Yep, it should be consistent however to avoid problems in the meantime you can use $value only on simple types.

**Comment by nsndeck** [comment]
I've added the requested functionality with commit #1514.
