### ISSUE TITLE
var someModule = require("aModule") should give some error if "aModule" not found

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1518]
If a module does not exists, maybe because of a typo or a renaming, there should be some kind of error message when running the app, it would make it very easy to find the problem, today I spend some time trying to figure out why I could not navigate to a page and it turned out to be due to some renaming of a module that the destination page was using.
"var someModule = require("aModule") should give some error if "aModule" not found"

Not sure if this comment should go into the Nativescript-CLI
Thanks!

**Comment by Plamen5kov** [comment]
It should do exactly that. Are you sure the `require` statement is being called?

**Comment by enchev** [comment]
Hey @Daxito,

Is this under iOS or Android?

**Comment by Daxito** [comment]
This is under both, basically all I had was this JS file at ~/service/webapi.js, I had a "require" at the top of another screen, my home page, like:

var service = require("~/service/webapi")

Someone here renamed the webapi.js file to something else (webService.js), so when I was trying to navigate from my login page to this Home page, it just wouldn't navigate because of that.

Thanks

**Comment by enchev** [comment]
Hmm, as far as I know `~` is not yet supported. Hey @Plamen5kov, @jasssonpet can you confirm?

**Comment by NathanaelA** [comment]
@enchev I certainly hope it ( ~ ) is supported on iOS in the require statement; it is used on Android to point to the root of the app folder (and several other places in the NS library).

**Comment by fealebenpae** [comment]
@enchev Tilde paths are supported on both iOS and Android. Even if they weren't supported, I believe the issue here is that no error message is shown, regardless of the reason for failure.

**Comment by NathanaelA** [comment]
@Daxito  --  I've seen where a file is renamed; but the old (broken?) version still exists on the device/emulator.  Updates to the app does not remove old files.  So you do a require and get the old version, but it doesn't work properly because it is old/broken.   
@enchev - I have seen the same issue as @Daxito before, but I cannot duplicate it in a stand alone project; so I'm not sure what causes it.  Right now my stand alone test on Android fails with an error message as expected.   Maybe @Daxito can provide a sample that fails.

**Comment by Daxito** [comment]
@NathanaelA I will try to create a sample app and try to duplicate this issue.

**Comment by Daxito** [comment]
Weird, I am not able to duplicate this issue anymore, if I get it again I will reopen this ticket... closing...

**Comment by alejonext** [comment]
Reopen the issue... Well because this
```
$ tns build android
Executing before-prepare hook from /accel/hooks/before-prepare/nativescript-dev-jade.js
Executing before-prepare hook from /accel/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 1.7.5
/accel/app/models.ts(2,21): error TS2307: Cannot find module 'socket.io-client'.

Project successfully prepared

:config phase:  createDefaultIncludeFiles
```
I'm using version 1.5.1, and I have had this error. It is assumed that [socket.io](https://github.com/NativeScript/socket.io-client) was modified to be usable in [NativeScript](http://socket.io/blog/socket-io-1-4-1-1-4-2-and-1-4-3/#) ... The question is why did not find the module?

**Comment by enchev** [comment]
Can you post more info how you've imported this module? If you use TypeScript `import` instead JavaScript `var` you need to have TypeScript definitions for this module.

**Comment by alejonext** [comment]
Yes
````Typescript
import observable = require('data/observable');
import io = require('socket.io-client');
import meter = require('nativescript-accelerometer');
```
Compilate

````Javascript
var observable = require('data/observable');
var io = require('socket.io-client');
var meter = require('nativescript-accelerometer');
```
If I understand what you say, but it is not a failure of typing.

**Comment by enchev** [comment]
Do you have TypeScript definitions for `socket.io-client`?
