### ISSUE TITLE
bindingContext gets lost when clicking "back" button but it is not consistent

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1523]
I want some clarification on this, when I navigate from one page to another, what happens to the state of the previous page? like view models? 
I have this weird situation with a page and a list view, this list view gets populated when I click a "refresh" button, I click one item from the list view and it takes me to a detail screen, different screen, then I click go back and I can still see the list populated; if I click Back one more time it takes me to the Home Page, now, if I go back to the List View Page the list is now all gone.

Is this like a web page where if I click "Back" it takes me to a cached previous page? but if I click on a link it actually reloads the page or something like that?

Thanks

**Comment by hshristov** [comment]
Hi @Daxito,

When you call `navigate()` method we create new page and show it. The current page is put in a backstack so that you can later navigate back to it. It is kept alive until you go back to this page or you navigate forward with `clearHistory: true'` flag set in the `navigate` method.
Native views (on Android) are destroyed by default bur you can keep them alive by setting `frame.android.cachePagesOnNavigate = true`.
When you goBack out of the application your app is stopped so next time you start it either from Home or from recent apps it is started as a new process.

Let me know if you need more information.
