### ISSUE TITLE
Printing support should be added

### ISSUE THREAD

**Issue by Daxito** [NativeScript/NativeScript#1557]
Hi,
I have the need of printing out to a  Portable Thermal printer from my mobile app, is this already supported somehow in {N}? I was trying to find a plugin, any advice is welcome.

Thanks

**Comment by enchev** [comment]
Hey @Daxito,

We do not have cross-platform module yet however you can build one by using native classes related to printing:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPrintInteractionController_Class/index.html
http://developer.android.com/training/printing/custom-docs.html

**Comment by Daxito** [comment]
... ok, thank you!

**Comment by swatkins** [comment]
@Daxito Have you worked on this at all? I'm in need of the same functionality. If you already have something implemented, I'd hate to reinvent the wheel. Otherwise, I can start in on this.

**Comment by Daxito** [comment]
@swatkins my company ended up paying a contractor  to write a plugin for our specific printer, I have no idea how to program for android/ios and we didn't have time for researching, so paying someone to write it was quicker.

**Comment by davorpeic** [comment]
Hi @swatkins, do you have something that works with bluetooth thermal printers? I found this plugin from Eddy, https://github.com/EddyVerbruggen/nativescript-printer but still need to see if will work.

**Comment by NathanaelA** [comment]
@swatkins @davorpeic -
There are four printing plugins in the eco-system that I'm aware of.   Two of them are by me and two of them are by Eddy.

I have [NS-Zebra](http://nativescript.tools/product/9) and [NS-Epson](http://nativescript.tools/product/24) which are fully multitasking and share a common code base so that it can actually with the same programming print to either of those Bluetooth printer types.   In addition you can print to the printer using any font your application has access to, supports barcodes and exposes a large number of features.  I have also written my own background printer driver which eliminates the huge size of the Epson/Zebra drivers and allows the printer to print in the background thread and not tie up the main thread.   

Eddy has [NS-Star](https://github.com/EddyVerbruggen/nativescript-star-printer) - which exposes the basics and even offers the ability to open a cash drawer, and uses the standard Star SDK for its support. 
Eddy also has [NS-Printer](https://github.com/EddyVerbruggen/nativescript-printer), which basically sends a graphic to a printer.   

The best place to find plugins would be at [http://plugins.nativescript.rocks](http://plugins.nativescript.rocks); you can filter by category, or just start typing "print" and you will see all 4 plugins.

**Comment by davorpeic** [comment]
This is awesome @NathanaelA, thanks a lot!

**Comment by RosilBelli** [comment]
Hi @NathanaelA !
Does NS-Epson you said above works with Ethernet and USB Epson printers too? Or is it just for Bluetooth printers?

**Comment by NathanaelA** [comment]
@RosilBelli -
The NS-Print-Epson, and NS-Print-Zebra are currently Bluetooth only (as they currently only use my own custom bluetooth driver and eliminate using the sdks).   My NS-Print-Star supports USB, Network, and Bluetooth (using my driver and the star sdk).   

All three NS-Print-* use the same base NS code base so that you can fluently create reports that will work on any of the three printer types (Zebra, Epson, Star).   

Example report:
```
let document = printer.createDocument();

 document
        // Set all future output to be center aligned
        .alignment('center')

        // Path to an Image you want to use
	.image('~/Logo.png')

        // Uses normal printer built in font 
        .text("Master Technology", {font: docFont, size: 0, bold: true})

        // Use any TTF font in your app 
        // Print a Printer, Android, Apple, Mobile Phone to the printer
        .fontText("\uf02f \uf17b \uf179 \uf10b", "FontAwesome");     

        // Add a blank new line (can pass the number of newlines as a param)
	.newline()

         // Create a Barcode using UPCA
        .barcode("12345678901", document.BARCODE.UPCA, 30);
        /*** And many more commands ....  ***/

      Printer.print(document).then(...)
```

**Comment by aaminashafin** [comment]
If anyone has a proven code for label printer please contact me with printer model number.

**Comment by NathanaelA** [comment]
@aaminashafin - My NS-Print-Epson, -Star and -Zebra should work with all Network & Bluetooth printers; but I specifically test on a couple different models, some models are portable others are like receipt.     See the post up above for links to them.
