### ISSUE TITLE
The sample of nativescript-grid-view plugin unable to run with 1.6.0 - Building UI from XML.

### ISSUE THREAD

**Issue by vchimev** [NativeScript/NativeScript#1585]
Output:
```
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 1   0x128f20 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 2   0x7ee100 ffi_closure_inner
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 3   0x7eea52 ffi_closure_i386
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 4   0x176ddce -[UIViewController loadViewIfRequired]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 5   0x176e1ed -[UIViewController view]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 6   0x161bf94 -[UIWindow addRootViewControllerViewIfPossible]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 7   0x161c6b1 -[UIWindow _setHidden:forced:]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 8   0x161ca67 -[UIWindow _orderFrontWithoutMakingKey]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 9   0x1630118 -[UIWindow makeKeyAndVisible]
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: 10  0x7ee918 ffi_call_i386
Feb 18 19:51:02 vchimevmac GridViewSample[13916]: file:///app/tns_modules/ui/builder/builder.js:154:56: JS ERROR Error: Building UI from XML. @file:///app/main-page.xml:3:5
```

pointing to https://github.com/PeterStaev/NativeScript-Grid-View/blob/master/sample/GridViewSample/app/main-page.xml#L3

Repro app: https://github.com/PeterStaev/NativeScript-Grid-View/tree/master/sample/GridViewSample

**Comment by NathanaelA** [comment]
I'm pretty sure it is a bug in the Grid-View component; not NativeScript.   I'll be submitting a patch to Peter shortly.    I'm working through the actual issue right now as I use this component in one of my projects.

**Comment by NathanaelA** [comment]
There is some change in 1.6 that totally breaks bound values in the GridView.    It is the weirdest thing; I can trace down to where the item is being set from the data value.  But the bound labels don't show up.  And the bound buttons show up and don't work properly (i.e. you can click them but nothing happens MOST the time, occasionally the click handler will register even though the button doesn't show itself being clicked).   

Any ideas on how to proceed to debug this one; or would you rather I bundle up a sample app and you guys can take a look at it?

However, if the the specific data item actually decides to render; then _everything_ works.   I have tried limiting my dataset to 3 items, and it would either render 1 or 2 of them depending on going in to the detail and then back out. When I upped my dataset to 5 items, it always appeared to render the 2nd and the 5th item.  But again, depending on what I go into and back out of it might change which ones are rendered properly.

Things I've tried:
1. Limited DataSet, and stepping all the way down to the label getting an actual value from the dataset.
2. Verifing all three unique items are being created and indexed correctly.
3. Eliminating pretty much all XML except for the 
```
<Page><ActionBar><GridLayout><GridView><StackLayout><Label text="{{desc1}}"><Label></StackLayout></GridView></GridLayout</Page>
```
4. Eliminating all code on startup except for the Assigning the Array to the items.
5. Completely replaced almost all the GridView code with the newer ListView based code.
6. If I switch the GridView to a ListView everything WORKS.
7. Opening Android Device Monitor and getting a couple VH's (view hierarchies).
--- In the view hierarchies -- if the view was rendered properly the hierarchies showed all the elements properly.  If the view items was NOT rendered properly; the hierarchy was actually empty of all the elements (i.e it Showed a GridView with NO elements in it) even though you could see all the elements colored stackout, and the buttons fine (just couldn't click it).  If you put part of a good render and part of a bad render; you would see only the good elements in the VH.  (This part is really weird, because somehow the picture, the three static texts and the four buttons actually rendered, but they didn't show up in the view??/)

Do you have any ideas on how to narrow down what could be causing this.

**Comment by NathanaelA** [comment]
Ok, I managed to find several issues, by slowly making the test case as small as possible; I suspect they are all intertwined somehow.  
1. If you click on the bad button, actually nothing happens, but when you click anywhere else it registers the prior clicks on it.   So if you click on it three times, then wait a few seconds, then click anywhere else, it will console.log out that you clicked it three times.   WEIRD.
2. If you have isEnabled set on the button, it crashes during the initial rendering, with a weird error.
3. If you disable the Text alignment css on the "missing" labels, they actually show up.  But again that specific whole grid item is still messed up, the button still has the same issue and the whole item is tab-able, where on the other proper rendered items, only the button is tab-able.
4. If you change the Grid Item height; different items become the "bad" vs "good" rendered items.

Attached is a sample app; this is my "test" app, so it has several screens to try and duplicate bugs --  most of them aren't broken or relevent to this issue.   Once you run it only has one button, click it and it will bring up the GridView code/screen in the "GVIssue" folder.  The actual "GridView" code is in the "GridView" folder, since the main GridView plugin is broken, I included my version and then made the xml use my version, so all you have to do is install the Android runtimes, and the tns-core-modules and you should be set to go..

[sample.zip](https://github.com/NativeScript/NativeScript/files/139058/sample.zip)

**Comment by PeterStaev** [comment]
@vchimev the plugin and sample are now updated for 1.6. 

@NathanaelA  the problem with the button and labels is now resolved with the updated plugin. As for the  isEnabled binding the problem is in your expression. This property is boolean and your expression returns string. So it must be changed to:
```XML
<Button class="addButton" isEnabled="{{1 &gt; 0 ? true : false}}" text="{{text}}" row="1" tap="onTap"/>
```

**Comment by vchimev** [comment]
Thank you guys!

**Comment by NathanaelA** [comment]
@PeterStaev - I'll test the expression again; I actually tried it multiple way and it failed I just copied the last version I did.  :grinning:     Awesome on the update, I'll have to see what you did!
