### ISSUE TITLE
XHR.response is sometimes not parsed as JSON object

### ISSUE THREAD

**Issue by vakrilov** [NativeScript/NativeScript#1590]
When the `Content-Type` of the response is `application/json` the response property of the XMLHttpRequest should return a parsed object.

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by Erudition** [comment]
I was just about to open an issue regarding this behavior. I believe this is a nonstandard behavior for XMLHttpRequest, because it is causing problems in my code only when run in NativeScript - not anywhere else (web browser, Node with XMLHttpRequest package).

https://github.com/NativeScript/NativeScript/blob/c7d4b99056dcc42675de0410ade182f3b5c367f9/tns-core-modules/xhr/xhr.ts#L109
```js
      if (this.responseType === XMLHttpRequestResponseType.json) {
            this._response = JSON.parse(this.responseText);
        } else if (this.responseType === XMLHttpRequestResponseType.text) {
            this._response = this.responseText;
        }
```

By removing the `JSON.parse` bit in my copy of this module, my JS libraries that use XMLHttpRequest start working again! Before that, I was getting a strange error about failing to parse JSON ("unexpected token o"), which I [found out means the JSON is already parsed](https://stackoverflow.com/questions/15617164/parsing-json-giving-unexpected-token-o-error). No wonder! However, given that the library expects the response to always have a string to parse, and it works everywhere else, I'm inclined to think that there's nothing wrong on my end -- the end users are expected to do the `JSON.parse()` themselves.

If that's true, there was no bug before #1589 was merged -- let alone a "high severity" bug -- but there is now. If so, can we reopen this so that the changes can be reverted?

If this is actually against the spec for sure, then I'll shut up and go away -- I guess this is just a case of the spec not being followed everywhere else. But reading the spec right now, I'm not super sure.
