### ISSUE TITLE
Typescript transpiler printing many type errors which are in fact non existing

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1593]
Premise: I started working with Typescript only recently, so the following could be me non understanding what's wrong.

Here are some of the most recurring errors printed in console by Typescript transpiler during build (error followed by actual code):

- error TS2304: **Cannot find name 'ObservableEventData'**.
```

import ObservableEventData = require("data/observable");
exports.loaded = function(eventData: ObservableEventData) {
}
```

- error TS2339: **Property 'src' does not exist on type 'View'**

```
import {getViewById} from "ui/core/view";
let page;

exports.loaded = function(args) {
    page = args.object;
    getViewById(page, "some-id").src="~/images/some_image.png";  // some-id belogs to <Image in XML
};
```

The  error above is there also for other non-existing properties / methods when it comes using layout methods (programmatically) as  in:

```
let container = getViewById(page, "container1") // container1 id belongs to a StackLayout in XML
container.addColumn(...) // in fact 'src' property error here is 'addColumn' error (same error code as above)
```

I am not sure but I think these errors could be solved by, for example:

`let container = <View>getViewById`

or something like that but I wonder if this is really necessary since it would make the code extremely "longer".

Not only I don't understand why I get these errors, but they also "pollute" quite a lot the console, **sometimes being overlapped with console.log's output**.

**Comment by enchev** [comment]
Hey @dragGH102,

You get these errors since these properties and methods are not part of `View` type definition. The `src` property is part of `Image` definition and `addColumn` is part of `GridLayout` definition. If you want to access properties correctly you need to type cast (`<YourType>`).
This is actually the difference between TypeScript and JavaScript. If you cast to `<any>` you can use type anything like in pure JavaScript.
