### ISSUE TITLE
Javascript errors silently ignored (and blocking)

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1594]
I am developing on Android with latest {N}.

When there is Javascript error in the code, **the error is silently ignored and it's blocking** (and when it's not - for example in forEach - it breaks the following part of the forEach).

In general this is easily solvable but it can be quite frustrating not understanding why something doesn't happen with no JS error at all shown anywhere. 

One example of error is **assigning a non-existing variable**. e.g.

`let var1 = object1.property1; // object1 does exist, but it doesn't have property1 property`

Certain **JS errors actually break the app **printing it directly within the app, but they are **limited to setting properties on XML element which don't exist** and a few more.

In other very rare cases the error lead to a Java errors, which is sometimes printed to console as well.
I'm using livesync which is extremely handy and definitely much faster than re-building the app each time.

Actually I'm using Typescript but the big issue with typescript is that it prints so many (non-existing) type errors that it's very difficult to even detect "real errors". I opened another issue about that at https://github.com/NativeScript/NativeScript/issues/1593 .

**Comment by enchev** [comment]
Hey @dragGH102,

In my opinion this syntax is allowed, should not throw error and should result to `undefined`. If the `object1` is any this will allow TypeScript compilation as well.

Hey @fealebenpae, @slavchev, am I wrong?

**Comment by fealebenpae** [comment]
@enchev: indeed, `var1` should be set to `undefined`.

**Comment by NathanaelA** [comment]
@enchev & @dragGH102 - I just added to my test app on Android:
var obj1 = {};
var obj2 = obj1.missing;
console.log("!!!!", obj2, typeof obj2);
And it didn't crash the app and the console.log printed fine...

(BTW: "LET" is not a keyword in the current version of JavaScript so if you try to use it, it would crash on that. If all your code was TypeScript then that would work. )

**Comment by dragGH102** [comment]
@NathanaelA of course I use 'let' in Typescript, not Javascript.
@enchev the issue usually arises when performing a forEach after a HTTP call. In fact it doesn't block the code execution per-se but blocks the forEach as if we executed continue; just before the error. Difficult to reproduce without an ad-hoc api server like the one I'm using for my specific app locally

**Comment by NathanaelA** [comment]
@dragGH102 - on the "let" -- I was hoping so; but didn't want to assume that.  :-)     My understanding is that the iOS runtime actually lets you use "let" right now in it.

Are you 100% sure that "obj1" is defined properly in that loop.  Because if obj1 === undefined/null then obj1.missing WILL crash.    If obj1 is coming from JSON then maybe it isn't deserialized correctly.    I'm not trying to discount your issue; but I would expect a LOT more issues in the runtimes if obj1.missing caused issue.  That type of code is used a LOT in if statements.

**Comment by dragGH102** [comment]
@NathanaelA yes, that's the point. it happens (by mistake) that obj1 is not defined. the thing is that sometimes it's difficult to even see what went wrong, because no output is given (just the code doesn't give the right output as the following lines are ignored). In other cases for sure the app crashes. However my issue/advice was to implement a deep error reporting in nativescript-cli, eventually with an optional parameter --verbose as in many cli apps

**Comment by NathanaelA** [comment]
@dragGH102 -  The error _will_ be reported if it isn't wrapped in a promise or a try/catch.   If it is wrapped in a try/catch you will see the error in the catch.   If it is in a promise, again you will see it in the catch function.     If you have a case where it isn't in a try/catch or promise and it isn't reported than that is a bug, otherwise try/promise are designed to allow you to handle the error without reporting it.

**Comment by dragGH102** [comment]
@NathanaelA thanks. I will try when I have the chance in a practical situation and should it be an actual bug I'll re-open the issue
