### ISSUE TITLE
Expose Android and iOS type definitions

### ISSUE THREAD

**Issue by losttime** [NativeScript/NativeScript#1599]
I'm working on updating a plugin to work with 1.6.0. I've discovered that the Android and iOS type definitions, which are used in the plugin, are no longer included when I run `npm install tns-core-modules`. From what I can tell, the grunt file is specifically excluding them from the build that gets published.

Can those type definition files get published to the npm repo, or is there another preferred way to utilize them (preferably without copying them into my working directory)?

**Comment by losttime** [comment]
After further diffing I've realized that the Android and iOS weren't included with `tns-core-modules` before. That said, I still think it would be useful to have them exposed so plugin developers can extend them more easily.

**Comment by enchev** [comment]
Hey @losttime,

You are absolutely right! We have plans to add support for automatic generation of TypeScript definitions when you add for example platform using our CLI. In this case you will have the correct definitions for the current platform (for example iOS 9.2), otherwise we need to ship different definition for every Android API level and iOS version.

**Comment by Milewski** [comment]
by the way if i want to download those typing manually how could i do? where can i find them?

**Comment by fealebenpae** [comment]
@Milewski: on iOS you can generate them today: http://docs.nativescript.org/runtimes/ios/how-to/Use-Native-Libraries#troubleshooting. We're still working to make this seamless on Android, though.

**Comment by enchev** [comment]
Hey @ErjanGavalji can you help here?

**Comment by ErjanGavalji** [comment]
@Milewski, for the time being you can also download them from [the respective tags in the NativeScript repo in GitHub](https://github.com/NativeScript/NativeScript/blob/v1.6.0/android17.d.ts). There is some automation done for creating these as a package, but still figuring out how to deal with the dependencies.

**Comment by PeterStaev** [comment]
@enchev , from a plugin developer standpoint generating those from the CLI is not much of an option. I think the definitions of the latest stable version for each platform should be included either as a separate package or as part of the current tns-core-modules package.

**Comment by ErjanGavalji** [comment]
@PeterStaev: Well, the thing is, (at least on android) the definitions are different depending on the minimum version the plugin supports. That said, it might make a better sense of having these generated, addressing the minimum platform version the plugin or application developer intends supporting. (By the way, the core team are already working on implementing the generator @enchev mentioned earlier).

How do you feel about that? These can easily get published as an NPM package, but won't they be misleading?

This decision must be carefully made for once published it would be bad for the community to just unpublish or stop publishing them...

**Comment by PeterStaev** [comment]
@ErjanGavalji then how about publishing definitions for every platform version supported (so for example there would be android.17.d.ts, android.18.d.ts, ..., ios.7.dts, ios.8.d.ts, ios.9.d.ts). Then the plugin developer will reference whatever minimum version that plugin targets?

**Comment by ErjanGavalji** [comment]
@PeterStaev A valid suggestion indeed. Still, devs might choose to develop against android-17 and use a support library to get some of the later version functionalities.

In such a case they would need TypeScript definitions for the support library, hence, packages must exist, providing definitions for all the support library versions.

Wouldn't that make it too confusing for devs?

How about the NativeScript tooling, i.e. the CLI provide an automated way of having these? For example:

`tns plugin create [plugin-name]` would trigger a wizard, which will ask for the supported runtime version(s) and the language. Then, based on the answer, it would create the necessary definitions, which will be available for use...

@ligaz, @teobugslayer, @rosen-vladimirov, @PanayotCankov, what do you think about this, guys?

**Comment by PeterStaev** [comment]
@ErjanGavalji , I think having separate packages/files for the different support libs and including what is needed won't be confusing. The way I look at this is like adding a "reference" when you develop for android. So for example if you are developing some app and use support-v7 you have to add this to your build, it does not happen automatically. Same thing here: if you are developing/using support-v7 in your plugin/app then you need to add this to npm devDependencies. 

The problem I can see with a special CLI command is that from what I understand, in order for it to work properly, I would have to run it on Mac that has android SDK installed. Otherwise if I run it on a Windows machine where I have android SDK installed, will it be able to generate me the iOS definitions? And how is that going to work with the upcoming WP10 support?

**Comment by ligaz** [comment]
Having in mind that those declaration files will be more or less immutable I think it make more sense to publish them (or have them somewhere available for download). Having them available at a given URL is useful because we can refer to them online like for example when we answer issues on GitHub.

Ability to generate them locally is a nice addition as well that will be handy if you reference 3rd party libraries. This should be implemented in the `plugin init` command: https://github.com/NativeScript/nativescript-cli/issues/586

**Comment by NathanWalker** [comment]
Having them as separate installs would be great.
Ultimately, why not publish them via the `typings` registry:
https://github.com/typings/registry

And then the `tns` cli could auto setup `typings` as a local dependency and run `typings install` to setup whatever `typings` are needed. This way, it becomes very easy to manage `typings` for whatever you're doing.

https://github.com/typings/typings#quick-start

**Comment by ErjanGavalji** [comment]
:+1: 

I agree.
Will have the ones used for development published.
Both to the typings registry and npm.

Cheers for a great discussion, guys!
Erjan

**Comment by episodeyang** [comment]
@NathanWalker :+1:

**Comment by NathanWalker** [comment]
Any progress here? I could help?

**Comment by roblav96** [comment]
I can't seem to get this working https://github.com/NativeScript/android-dts-generator

**Comment by vossad01** [comment]
[This is coming up on StackOverflow as well](http://stackoverflow.com/q/37523071/1072626).  I have done only a little testing now, but @NickIliev has what--at least thus far--seems like [a workable solution](http://stackoverflow.com/a/37524018/1072626) now that 2.4.0 is released.  It would be nice if this were more available to users as it is not always easy to find that answer and it is not otherwise apparent that you need it.

**Comment by atanasovg** [comment]
The official solution is described in the `readme` of this package: https://www.npmjs.com/package/tns-platform-declarations

Closing the issue.
