### ISSUE TITLE
Switch component not rendering correctly on Android <= 4.4.4

### ISSUE THREAD

**Issue by dragGH102** [NativeScript/NativeScript#1606]
I'm used to develop on Android 5.0+.

On Android 5.0+ the switch is rendered properly (and it's nice to see).

I was making some tests with different screen sizes/devices/OS versions and I got into the following issue on **Android 4.4.4**.

When the switch has a limited space to render (e.g. when setting a width or putting it together with other components in stacklayout with **horizontal orientation**), the switch is **truncated**.

The issue can be easily seen at this sample project (in 3 switches in the first stacklayout): https://github.com/dragGH102/nativescript-sample-switch-button-binding

Beside the issue outlined above I can't understand how to make the **Switch component look alike (e.g. with styling)** Android 5's one in previous versions (the switch with ON-OFF label is quite awful I'd say :-) ). Any clue?

**Comment by PanayotCankov** [comment]
The NativeScript framework chases native look and feel. With that said we will prefer to display the switch as it is implemented in the native UI framework rather than implementing one from scratch. The switches in the Android versions you mention really is quite large in width. But it also looks like this when you go to the 'settings' for example.

If you want to use a fixed design switches I could recommend you use an Image view and bind its source to something like `src="{{ s1, s1 ? 'res://checked' : 'res://unchecked' }}"`, also handle tap and toggle the `s1` value.

**Comment by dragGH102** [comment]
@PanayotCankov thanks. that's a good idea too.
However it seems weird to me that on a native level it's not possible to customize. is it?
