### ISSUE TITLE
VSCode debugging w/ TypeScripts w/ Souremaps

### ISSUE THREAD

**Issue by lelong37** [NativeScript/NativeScript#1621]
Thank you very much for the VSCode integration https://marketplace.visualstudio.com/items?itemName=Telerik.nativescript..!

Could the team please provide the steps for debugging in TS (TypeScript) w/ Sourcemaps? We are already generating sourcemaps next to our TS files.

e.g. 

    ├── myapp
    │   ├── app.ts
    │   ├── app.js
    │   ├── app.js.map

Again, thanks!

**Comment by ivanbuhov** [comment]
Hi @lelong37 
Open your application folder in VSCode (not your `/app` folder but the folder created when `tns create` is executed) and follow the instructions [here](https://github.com/NativeScript/nativescript-vscode-extension/blob/master/README.md). Given the fact that you already have typescript compiler configured to generate source maps, the steps to debug typescript are the same as these for JS debugging.

**Comment by lelong37** [comment]
thanks @ivanbuhov here's is my folder structure, I know you mentioned not my /app folder, but I don't see any other app? I'm probably missing some here.

![image](https://cloud.githubusercontent.com/assets/4691404/13280581/7f8e9992-daa4-11e5-8289-53df6406545f.png)

**Comment by ivanbuhov** [comment]
@lelong37 you have opened the right folder. Are you able to debug the application?

**Comment by lelong37** [comment]
@ivanbuhov as instructed I did follow every step of https://github.com/NativeScript/nativescript-vscode-extension/blob/master/README.md and am able to debug .js fine, I don't see anything related to debugging *ts though.

**Comment by ivanbuhov** [comment]
What happens if you set a breakpoint in a `.ts` file. Does the debugger stop on the breakpoint?

**Comment by lelong37** [comment]
![image](https://cloud.githubusercontent.com/assets/4691404/13280778/85150184-daa5-11e5-81a6-4279db9ad132.png)

A gray hollow circle represents a breakpoint which could not be successfully registered with the debugger. For languages that are transpiled to JavaScript, this could mean that source maps are missing or invalid.

**Comment by lelong37** [comment]
I'm wondering if there is a setting we need to have in launch.json that NS plugin installed with, to flag to debug in TypeScript? Not sure, but when debugging Angular or Node.js I don't remember having to do anything other than provide the source-maps.

**Comment by lelong37** [comment]
@ivanbuhov I stand corrected in Chrome we have to set a flag to debug in TS, 

![image](https://cloud.githubusercontent.com/assets/4691404/13280890/32210332-daa6-11e5-9e57-db8e0bc7a5dd.png)

**Comment by lelong37** [comment]
Just wanted to double check but debugging Node.js works, I compared both my launch.json with NS's and they both have the sourcemap: true

Debuging Node w/ TypeScript

![image](https://cloud.githubusercontent.com/assets/4691404/13281088/5e4c335e-daa7-11e5-839c-d5f8ae8ce376.png)

Both have sourcemaps: true

![image](https://cloud.githubusercontent.com/assets/4691404/13281122/879d512a-daa7-11e5-855d-052fc38c93f2.png)

**Comment by ivanbuhov** [comment]
There is `sourceMaps` option for every configuration in `launch.json` but it is `true` by default. Can you send me the project or link to github repo?

**Comment by lelong37** [comment]
Done.

**Comment by lelong37** [comment]
@ivanbuhov where you able to clone/pull?

**Comment by ivanbuhov** [comment]
@lelong37  I cloned it successfully. I am investigating the issue.

**Comment by dennissheppard** [comment]
Did this get resolved? Having a similar problem.  Hitting .js breakpoints, but not .ts.

**Comment by ivanbuhov** [comment]
Hi @dennissheppard 
1. What is your nativevscript CLI version?
2. What VS Code debug configuration are you running (Debug/Sync/Attach)? Is it reproduced in both Android and iOS configurations?
3. Make sure that `sourceMaps` is set to `true` in your debug configuration settings in `launch.json`. Please post the content of the `lauch.json` file.
4. Make sure that the TS compiler generates `.js.map` files right next to your `.js` files.
5. What happens when you set a breakpoint in a `.ts` file? Is the color of the breakpoint changed to red or it stays in gray forever?

**Comment by dennissheppard** [comment]
Eh, that's why I said similar issue.  Mine isn't with VSCode, as I can debug with that. I'm trying to use the NativeScript inspector, because VSCode doesn't show network traffic (that I can see, anyway) from api calls. 

1. 2.3.0
2. n/a
3. SourceMaps in tsconfig are set to true
4. I can see the map files adjacent to the js files.
5. Breakpoints in ts files are just ignored.  Old ones that I can't seem to get rid of are either gray or lighter gray if I disable (but can't delete). New ones are blue.

**Comment by ivanbuhov** [comment]
@dennissheppard Can you reproduce the issue with the latest CLI (currently v2.4.2) on a newly created NS app?

**Comment by peter-raven** [comment]
I have same issue - debugging TypeScript in Visual Studio Code steps into .js files instead of .ts files. I can reproduce on freshly clone of the [NS samples](https://github.com/NativeScript/nativescript-sdk-examples-ng).

1. NS CLI: 2.4.2
2. Attach, iOS
3. sourceMaps in tsconfig are set to true, launch.json has sourceMaps = true as well.
4. .js.map files are present next to the .js files (next to the .ts files).
5. Setting a breakpoint it VS Code show a nice red breakpoint dot.

For example I can set a breakpoint in application-settings/values/values.component.ts, but when the breakpoint is hit, VS Code debugs values.component.js.

Let me know if I can do anyting further to narrow down the cause of this issue.

**Comment by peter-raven** [comment]
This thread appears to be dead. I ended up narrowing it down to an issue with spaces in the path:

* To reproduce: Put your source files in a path with spaces in it (eg. "c:/my great projects/source").
* To workaround: Avoid spaces in the path to your source, eg "c:/no_spaces_here/source").
