### ISSUE TITLE
require in npm modules/packages not checking node_module folder

### ISSUE THREAD

**Issue by emmanuelbuah** [NativeScript/NativeScript#167]
@valentinstoychev Per comments at https://github.com/NativeScript/NativeScript/issues/103, I started work on integrating meteor and nativescript via npm modules. I run into an issue where require(..) doesn't check the node_modules folder relative to the calling script (similar to node), but rather only checks tns_module.

It this a bug?

**Comment by ligaz** [comment]
Hey @emmanuelbuah we are already working on this. You can check our progress [here](https://github.com/NativeScript/nativescript-cli/issues/362)

**Comment by valentinstoychev** [comment]
@emmanuelbuah as @ligaz said - npm out of the box will be available soon - initial support in June. You can require the JS files manually. Please check this [blog post](http://developer.telerik.com/featured/building-your-own-nativescript-modules-for-npm/). Please let us know if you need help.

**Comment by emmanuelbuah** [comment]
@ligaz @valentinstoychev Thanks for the update. I have about 3 dependency level deep (x requires y, y which requires z,..). I will try to resolve the issue by modifying each to reference the js file. If it proves to be unproductive, I will wait for the initial support and go from there. Thanks for the update.

**Comment by emmanuelbuah** [comment]
@ligaz @valentinstoychev Failed to communicate this. Meteor integration requires websocket which JSCore (iOS) doesn't support. I don't know if there is current a socket nativescript implementation/polyfill. If not, would I be right to create a module than exposes https://github.com/socketio/socket.io-client-swift for iOS socket support, similar to native-script implementation here https://github.com/kirkness/react-native-swift-socketio

**Comment by kmkamruzzaman** [comment]
Hi dear!
Thank you to coperate me on given email.
So thank you

২০১৫-০৫-১৫ ৮:০০ GMT -০৭:০০, kwame <notifications@github.com>:

**Comment by RangerMauve** [comment]
@emmanuelbuah I've also been thinking of doing a Websocket polyfill for NativeScript, but I was going to do Android first. As well I've been waiting for the NPM integration to get finalized before getting too much into it.

**Comment by emmanuelbuah** [comment]
@RangerMauve if the websocket implementation is just a wrapper to the os (android) socket implementation, you should be able to create a tns modules (in the tns_module folder) to provide the nativescript js api. Same here, with the socket io client, i should be able to create a tns_module and have it work. 

In general, I think we should be able to expose ios/android websocket api via a tns websocket modules without having to wait till June. If you are interested, we can collaborate on a nativescript websocket module project with the follow struct in mind
tsn_modules/
   socket/
       socket.ios.js (implement ios specific wrapper for socket)
       socket.android.js (implement android specific wrapper for socket)
       socket.common.js (define nativescript socket api/protocals + helper func)
       package.json

**Comment by RangerMauve** [comment]
@emmanuelbuah I'd definately be interested. My only real caveat is that I was planning to rely on the [java-websocket](https://github.com/TooTallNate/Java-WebSocket) library for the websocket implementation, and I'm not 100% sure how I would be integrating the dependency with everything else.

**Comment by ligaz** [comment]
It will be great if we can collaborate on a WebSocket implementation for NativeScript. I have provided a guidance how this can be implemented for Android in [this](https://github.com/NativeScript/NativeScript/issues/72#issuecomment-95923621) issue. 

For iOS there is well known library that we can reuse as well [SocketRocket](https://github.com/square/SocketRocket). @fealebenpae what do you think?

**Comment by fealebenpae** [comment]
SocketRocket is a good choice, although I'd go with [PocketSocket](https://github.com/zwopple/PocketSocket) myself.

Ideally I'd like to see if some of the WebSocket code within WebKit can be reused in order to have a true W3C-conforming WebSocket implementation, but we have a long ways to go before we can comfortably reuse WebKit code in NativeScript. I suppose a custom WebSocket API is a good first step, though.

**Comment by RangerMauve** [comment]
Well, that's the main reason that I was interested in [java-websocket](https://github.com/TooTallNate/Java-WebSocket).. It's API is very similar to what exists in Browsers, so doing a NativeScript wrapper would be very simple.

**Comment by Nathanaela** [comment]
At least on WebSockets -- I have the Android side done; I'm currently working on the IOS side...   Hopefully released in a couple days.  :grinning:

**Comment by emmanuelbuah** [comment]
Cool. Do you need any help? More implementation details will be great.

**Comment by valentinstoychev** [comment]
@Nathanaela - this is great! Now we should try to run Firebase JS SDK on top of NativeScript. This was one of the showstoppers.

BTW: Make sure to work with @kiril-stanoev, he can help you get maximum visibility by including these on http://plugins.telerik.com. We will launch it soon for {N}.

**Comment by Nathanaela** [comment]
@emmanuelbuah it is actually pretty cool -- if I do say so myself.  :grinning:

Bascially it has two possible interfaces; it automatically when included in the app will create a global browser based WebSocket interface so everywhere in your code you can create and use the WebSocket interface like you would if you were in any recent browser.   It is as close to the browser that I would be surprised if any libraries that work on the browser won't work with mine.

The second interface is returned at the require; this one gives you a bit more control.  And the events are more like a standard Event system where the params are passed to your event, rather than a event object.   You can also re-open the socket on disconnects without having to recreate a new websocket.    I plan in the future to allow auto-reconnects with some sort of back-off system.   But at this point You can do that easily yourself in the onclose event call ws.open() and it will attempt to reopen the connection

Oh, and I also have the IOS side working properly.  Just now cleaning up all my code bases to be consistent, fixing issues in the two libraries and doing documentation...

**Comment by kshitizrimal** [comment]
Hi @Nathanaela I am just starting to use nativescript and I am from Meteor Background.. After reading the thread.. I feel very optimistic and I am anxiously waiting to use it on my project.. Thanx :)

**Comment by Nathanaela** [comment]
I've got it working almost perfectly on both IOS & Android.  However, I just found a weird issue with the IOS runtime; https://github.com/NativeScript/ios-runtime/issues/259 -- I'll be releasing it shortly; but I'm not 100% sure if I will have to make a work around for ios or make my installer automatically copy it into the app folder for use until we can determine a fix under iOS.

**Comment by Nathanaela** [comment]
Fully functional websockets for iOS and android are finally released.  http://fluentreports.com/blog/?p=95 for more details.
