### ISSUE TITLE
Nativescript does not work on Android 4.2, 4.3 and 4.4

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/NativeScript#1672]
I create an empty project and run it with `tns run android --emulator --avd <avd-name>`. When avd Android version is 5.0.1, it works. However, if version is 4.2, 4.3 or 4.4, the application returns an error.

- CLI: 1.6.1
- Cross-platform modules:1.6.2
- Runtime(s): 1.6.2
- Plugin(s): none

**Comment by rosen-vladimirov** [comment]
@erkanarslan 
The issue is caused by the new Android Support Library (now called ) and it's latest version - 23.2.0
You can find a workaround in [this thread](https://github.com/NativeScript/nativescript-cli/issues/1549)
Another way is to find where 23.2.0 version of appCompat is installed (it should be under `$ANDROID_HOME/extras/android/m2repository/com/android/support/appcompat-v7` and rename the directory 23.2.0 to something else, so nativescript-CLI will not use it.

**Comment by bradmartin** [comment]
@rosen-vladimirov - beat me to it. I thought this was the case on another issue about app crashing on Android. :smile:

**Comment by erkanarslan** [comment]
Not working.

````
FAILURE: Build failed with an exception.

* Where:
Script '/home/zarax/Documents/tns/test/app/App_Resources/Android/app.gradle' line: 10

* What went wrong:
A problem occurred evaluating script.
> No such property: generatedDensities for class: com.android.build.gradle.internal.dsl.ProductFlavor_Decorated
````

**Comment by erkanarslan** [comment]
Removed android sdk and reinstalled it. Now it works.
