### ISSUE TITLE
Feature Request: Pluggable WebView Engines

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#1697]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes.

### Tell us about the problem
The WebView module engines for Android and iOS are fixed (RandomWebView and UIWebView respectively).  Both perform inconsistently and/or poorly on remote sites across platform releases.

Down the line, I'd like to replace them with Crosswalk and WKWebView respectively, but the foundation to do this in a clean way isn't yet there, so I am submitting this feature request.

### Which platform(s) does your issue occur on?
Both.

**Comment by hshristov** [comment]
Hi @vbresults 
Changing the default webviews will probably require different delegate for iOS and listeners for Android. So a better approach is to create UI plugin use the custom webviews you want.
https://docs.nativescript.org/plugins/ui-plugin

If you don't require the full functionality exposed in cross platform manner you could use `Placeholder` component.
https://docs.nativescript.org/ui/placeholder

**Comment by vbresults** [comment]
@hshristov I respectfully disagree; Cordova figured out a way to do it as a plugin (e.g. cordova-plugin-wkwebview-engine, cordova-plugin-crosswalk-webview) and that approach works great;

Using the default Android webview on remote sites across different versions is.. perilous to say the least.  XW fixes all of that an runs quickly even on older Androids.

WKWebView has huge performance benefits, it's *almost* perfect, save CSS fixed position bug.  It is probably at Mobile Safari's performance level.  Hacking it in doesn't seem optimal here.

**Comment by NathanaelA** [comment]
@vbresults - @hshristov is correct, each of these webview components has different ways of doing things and each needs different delegates and different callbacks.  There is not really a good reason to make a separate custom plugin system for just webviews.  This would be a total waste of engineering talent.    NativeScript is a lot different than Cordova, NS doesn't need a webview engine to do any of its work. So Cordova needed a plugin system to be able to replace the webview engines seamlessly so they have certain interfaces around the webviews to do the work; then the replacement webview has to have a wrapper that exposes those interfaces.     

NativeScript already has a plugin system to allow you to include things that aren't built in. If you are a app dev and you want to use WKWebView then by including a wkwebview plugin you will be using it and you won't have a reason to use UIWebView.   So you don't actually need to have a common webview base to use it.

The different webviews will have the same basic things like url and loading events; but underlying the plugin would be built completely differently as where the callbacks/notifications occur are different.  Please note; I've actually done a  lot of work with the wkwebview in NativeScript and its delegates are completely different than the delegates in uiwebview.  However, in any case that I have written a replacement component, I always match the existing component functions so that it would be replacement compatibile other than switching the name in NS to my version.
