### ISSUE TITLE
Fetching PDF document fails

### ISSUE THREAD

**Issue by wubzz** [NativeScript/NativeScript#1754]
Hi,

So I needed a way to fetch a PDF document and in some way display the PDF in my app. I still have no clue how to display the data upon receiving it, but I got stuck on the first step of actually fetching the content.

Whenever I try to load a PDF document using the `fetch` module, I get the following error:

```javascript
JS: SyntaxError: Unexpected token %
JS:     at parse (native)
```

I've tried debugging the `fetch` and `xhr` modules but can't seem to find anything of relevance, so unfortunately I don't know where the origin issue is. I'm running this on android, but I'm assuming that doesn't matter in this case. Pressumably there's some mixup in content parsing as it should just be returning the raw response in this case.

Example code:

```javascript
fetch('http://stlab.adobe.com/wiki/images/d/d3/Test.pdf', {method: 'GET'})
.then((res) => {
})
.catch((error) => {
});
```

**Comment by enchev** [comment]
Hey @wubzz,

Is this for iOS or Android? I've just tried and it worked normally in Android however for iOS you need to allow HTTP protocol since such document cannot be accessed with HTTPS. 

Generally to open document for preview with iOS will be easier since I've added [openFile](https://github.com/NativeScript/NativeScript/pull/1479) function however in Android you will need to use external application which is not trivial.

**Comment by wubzz** [comment]
@enchev This was tested using Android, emulated via [Andy](http://www.andyroid.net/).

I wish I could provide more information but even modifying the core modules I can't get any relevant output information.

**Comment by enchev** [comment]
I've never used this emulator before. Can you try the standard Android emulators instead?

**Comment by wubzz** [comment]
@enchev I fail to see why the emulator would be the issue, isn't the point that they all run the same? ;) 

Anyway the issue was that my wrapper distinctly called `response.json()` which obviously won't work on a pdf document. Plain miss on my part, sorry.

Thanks!
