### ISSUE TITLE
Android SplashScreen hack needs update?

### ISSUE THREAD

**Issue by MiroValchev** [NativeScript/NativeScript#1774]
Comments under the post suggest that this solution is no longer working and needs update?

https://www.nativescript.org/blog/details/splash-screen-for-your-android-applications

**Comment by enchev** [comment]
Hey @atanasovg can you confirm this?

**Comment by NathanaelA** [comment]
The hack still worked as of 1.6.x; however the hack is very problematic in that when you hit the error screen you can't see much of anything because your "splashscreen" is the default theme.  (Remember this sets the overall app theme to this "splashscreen" theme and then switches to the normal theme once the page activity is loaded (but you have no control over the error activity).

**Comment by atanasovg** [comment]
IMO this is indeed a hack and we should not promote this as the suggested way for creating splash screens (in fact . If this becomes a highly requested feature then we should come with an official solution that lives within the framework's source and is updated and verified with every release.

As of now we may update the blog post with a disclaimer, just to ensure the proper expectations are set.

**Comment by atanasovg** [comment]
Closed unintentionally.

**Comment by PanayotCankov** [comment]
We use this in the nativescript-marketplace-demo.

**Comment by enchev** [comment]
Here is a link for the sample: https://github.com/NativeScript/nativescript-marketplace-demo

**Comment by PanayotCankov** [comment]
And with 2.2.0 it will be officially supported and added in the default template. You can read the upcoming docs here:
https://github.com/NativeScript/docs/blob/master/publishing/creating-launch-screens-android.md
