### ISSUE TITLE
NSDictionary usage

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/NativeScript#1814]
Trying to do something like this:
```
NSDictionary.alloc().initWithObjectsAndKeys(kAudioFormatMPEG4AAC, AVFormatIDKey, 44100.0, AVSampleRateKey, 2, AVNumberOfChannelsKey, null);    
```
Results in this error:
```
JS ERROR Error: Actual arguments count: "7". Expected: "1". 
```
Curious how to use NSDictionary/NSMutableDictionary in general. Haven't found any direct and clear examples. I tried passing it 1 argument as mentioned but still fails.

**Comment by NathanWalker** [comment]
Turns out this works:
```
new NSDictionary(['.mp3', 16, 44100.0, 2], ['AVFormatIDKey', 'AVEncoderBitRateKey', 'AVSampleRateKey','AVNumberOfChannelsKey']);
```

**Comment by jasssonpet** [comment]
Hey @NathanWalker,

You can also use this syntax:

```javascript
NSDictionary.dictionaryWithDictionary({
    AVFormatIDKey: '.mp3',
    AVEncoderBitRateKey: 16,
    AVSampleRateKey: 44100,
    AVNumberOfChannelsKey: 2
});
```

or pass the JSON literal directly to APIs that expect NSDictionary.

**Comment by roblav96** [comment]
@NathanWalker @jasssonpet 
This also works great:
```typescript
		let opts: NSDictionary = NSDictionary.dictionaryWithObjectForKey(0.0, kCIInputSaturationKey)
		global.tnsconsole.log('opts.description', opts.description)
		let cimg: CIImage = CIImage.new().initWithImage(img)
		let gray: CIImage = cimg.imageByApplyingFilterWithInputParameters(
			'CIColorControls',
			opts
		)
		Tesseract.tess.image = UIImage.imageWithCIImage(gray)
```

**Comment by noumaans** [comment]
@NathanWalker i know its a pretty old thread, but I've only seen this style that you mentioned work:
```
new (NSDictionary as any)(['.mp3', 16, 44100.0, 2], ['AVFormatIDKey', 'AVEncoderBitRateKey', 'AVSampleRateKey','AVNumberOfChannelsKey']);
```
NOTICE: The any keyword since NSDIctionary expects only one argument according to tns-platform-declarations 3.4.1.

The more readable versions, where one can pass directly a JS Object don't work.
NSDictionary.dictionaryWithDictionary(fooobj) fails to compile
NSDictionary.dictionaryWithObjectsAndKeys<string,any>([foo, bar]) or,
NSDictionary.dictionaryWithObjectsAndKeys<string,any>([foo, bar, null]) cause an app crash.

Is there a code-readable way to initialize an NSDictionary, or we are stuck with the single array initialization and using the any keyword to bypass TS checks... ?

**Comment by RobertGardner** [comment]
Can we (also) get the typings fixed so the "as any" cast is not necessary?

For example:
NSDictionary's constructor is currently:
```typescript
constructor(o: { objects: NSArray; forKeys: NSArray; });
```
but should probably be:
```typescript
constructor(objects: ObjectType[], forKeys: KeyType[]);
```

Similarly for NSArray:
```typescript
static arrayWithArray(array: NSArray): NSArray;
```
should probably be:
```typescript
static arrayWithArray(array: ObjectType[]): NSArray;
```
