### ISSUE TITLE
Css text properties not applying on DatePicker & TimePicker

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#1903]
When trying to set css **color** , **font-size** , **font-weight** and **font-style** on  **DatePicker** or **TimePicker**  styles are not applied. All other CSS properties are working.

_Example_

in app.css (or main-page.css)
```
TimePicker {
    background-color: brown;
    
    color:yellow; 
    font-style:italic;
    font-size: 50;
    font-weight: bold;
}
```

in main-page.xml
```
<!--Css text-properties won't apply for TimePicker-->
<Page xmlns="http://schemas.nativescript.org/tns.xsd">
  <StackLayout>
    <Label text="Test label" />
    <TimePicker hour="5" minute="20"></TimePicker>
  </StackLayout>
</Page>

```

**Comment by hamorphis** [comment]
Sample app: https://github.com/hamorphis/issue-1903

**Comment by hamorphis** [comment]
You cannot change the text attributes of the DatePicker and TimePicker programmatically without searching for their internals and then changing them with reflection: http://stackoverflow.com/questions/26015798/change-timepicker-text-color

We can't use such hacks in our source code, so if someone wants to do it, he will have to do it in his application, since this cannot become part of tns-core-modules.

The other options would be to use Date and Time picker from the http://www.telerik.com/nativescript-ui once they are developed.
