### ISSUE TITLE
FormattedString not working 

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/NativeScript#1914]
_From @dreambo8563 on April 8, 2016 6:9_

this is my template
```xml
<StackLayout orientation="vertical">

     <Label style="text-transform: uppercase; text-decoration: underline line-through;letter-spacing: 10;">
        <Label.formattedText>
          <FormattedString>
            <FormattedString.spans>
              <Span text="label" fontAttributes="Bold" foregroundColor="#0000ff"></Span>
              <Span text="Label" fontAttributes="Italic" foregroundColor="#00ff00"></Span>
            </FormattedString.spans>
          </FormattedString>
        </Label.formattedText>
      </Label>
      
      
            <Button text="buttonButton" style="text-transform: uppercase;foregroundColor:#00ff00;fontAttributes:Italic">
            </Button>
            
      
</StackLayout>
```
actually, just display the button, no label here.
my question is:
1. how to use FormattedString  with angular2. (xml & ts)
2. it seems the style  fontAttributes/foregroundColor not working for the button here
3. the definition of FormattedString   `public fontAttributes: number;` it's type of number. but I found all the material about it just accept sth like Italic/Bold. it's not a number

_Copied from original issue: NativeScript/nativescript-angular#161_

**Comment by dreambo8563** [comment]
_From @hdeshev on April 8, 2016 8:42_

It seems we need a directive that lets you define `formattedText` in markup. Until that is available, you'd have to define formatted text in JavaScript.

2 and 3 above may be problems with the underlying Label/FormattedText implementation. You should probably open issues for them on the [NativeScript/NativeScript](https://github.com/NativeScript/NativeScript) repo.

**Comment by nsndeck** [comment]
@dreambo8563 About your third point "the definition of FormattedString public fontAttributes: number; it's type of number. but I found all the material about it just accept sth like Italic/Bold. it's not a number" the reason here is that fontAttributes type actually is an flagged enum and enums represtation in TypeScript is number.

About the second point "it seems the style fontAttributes/foregroundColor not working for the button here" - it also should work just fine with the upcoming version (a.k.a 2.0) of NativeScript.

**Comment by dreambo8563** [comment]
@nsndeck you r right. I just remember the enum thing. I will check issue 2 with the latest version
