### ISSUE TITLE
Code share percentage compared to other similar frameworks/tools

### ISSUE THREAD

**Issue by svc76** [NativeScript/NativeScript#1921]
Hello friends!

i'm trying to prototype on different cross platform mobile frameworks. can someone point me to a comparative study of how much code can be shared when developing using nativescript as opposed to Xamarin, React native and others?

Personally, i like nativescript because of my affinity towards javascript/nodejs etc. But i need some supporting stats to have my team's trust to continue investing in nativescript.

Thanks

**Comment by NathanaelA** [comment]
I don't know of any studies off the top of my head but there was a contest a week or so ago; you might want to check out:
   https://www.nativescript.org/blog/anything-you-can-do---a-worldwide-nativescript-contest -- the thing is the contest was run over a weekend and produced several entries that easily rivaled and surpassed the original react version, in around two days.

I do know there is a white paper being worked on and I'm not sure what its status is maybe @sipacate or @burkeholland can answer the status on Xamarin vs NativeScript white paper and/or point you to other informational stats.

**Comment by svc76** [comment]
Thank you NathanelA for a quick and prompt response.

**Comment by sipacate** [comment]
I understand why you are asking the question. I hope in return, you can appreciate how difficult it is to give an accurate answer.

Because NativeScript has V8 and/or JavaScriptCore engines (platform depending) internal, this means you can reuse a ton of pre-built code. Pretty much anything that doesn't rely on the DOM (HTML style) you can use. 

If you are into Angular, with the upcoming release of Angular 2 and NativeScript, you'll be able to use almost all of your non-view code in your web and native mobile app. The code reuse quantities are immense. 

The views naturally have to be rewritten for mobile, because Angular on Web Platforms uses the DOM (HTML). However, likely you'd need to redo them anyways to account for the form factor disparity. Responsive web design can only take one so far before it's just a least common denominator solution.

I suppose the answer to "which has more code reuse" depends on which code you personally want to reuse. It's no secret JavaScript is the top and most popular language in the world, so we lean in that direction.

**Comment by enchev** [comment]
Hey folks,

In my opinion [StackOverlow](http://stackoverflow.com/questions/tagged/nativescript) is better place for such questions. Let's post only issues here!

Thanks
