### ISSUE TITLE
Add support for multiple itemTemplates on ListView

### ISSUE THREAD

**Issue by hshristov** [NativeScript/NativeScript#1932]
In order to get best performance in ListView component we need to support multiple itemTemplates.

**Comment by TheBrousse** [comment]
This feature is a must.

**Comment by rborn** [comment]
To give more context (based on the slack chat we had):
We need to be able to display sets of data with different "designs" in a ListView without the need of using collapsed views (like a huge template which will be impossible to maintain and cost CPU cycles) or logic inside the view-model for `ContentView` which would have performance penalties.

A good  scenario could be a news app, that needs to display the news with different designs based on the importance of the article: ![](http://razorianfly.com/wp-content/uploads/2015/01/Screen-Shot-2015-01-23-at-17.13.55.png)

Thank you 😄

**Comment by Core-13** [comment]
This is one of those "basic requirement" features that should be available already.

**Comment by NathanaelA** [comment]
@Core-13 - I'm not part of the NativeScript team, just a user who has been using NativeScript since v0.90 -- I even wrote a app that has multiple template views inside a listview.  Was it a harder than if it was natively supported; I suppose it was.  Did it stop me, no.    

The amount of cross platform features that NS supports out of the box for FREE is astounding.   The entire SOURCE code of the ENTIRE product is Open Source; so YOU can easily add those features you need or want without complaining about a FREE product...   And guess what is even better???  They actually DO take your pull requests; I've programmed several of my features/issues and submitted via a pull request and it ended up in the next major version.  ;-)   So, if this is a require feature for you; then ADD IT, make a pull request and then everyone wins!

**Comment by stephenfeather** [comment]
No need to come across as a jerk in a feature request.  Not everyone is as awesome as you are.

**Comment by Core-13** [comment]
I have been following your one man crusade to convince the world of your massive greatness @NathanaelA.  I do enjoy watching the self-opinionated puff up their chests in order to prove how great they are in-place of good manners.

Your buffonary may impress others, however it considered belittling to many and even harassment to others. I had been asked to give you time to grow up on each occasion you pull this - it appears that will not happen without an intervention.

But knowing a few things before you decide to share what should be commentary at best but in reality is diatribe is a must.  Firstly; when did you become the mouth price for all things NativeScript? How convinced are you that your language and tone are welcomed where community should be fostered?

It is clear you do not know who I am, or you would not have started - even your wish to seem big should be balanced with sensible doses of "there are some people you should think before leaping with".

First off I am old school.  This means I have been doing this for much longer than you think in much more community lead ways than your handful of years of experience allow for.  Secondaly consider how far I am inside the NativeScript world and just because you do not know who I am does not mean anything to anyone. 

I helped bring about a platform and was the community along with many other decent and polite people.  Not just a self declared member for the sake of my own ego but the top guy, not because I told people I was or needed others to think my work meant more than my manners but because the community said I AND many other great people were.

If your body of work as small as it appears to be in comparison with many of your peers is to be valued let it be on the merit of the work rather than the authors poor attitude of everybody else.

If you continue down this path of sheer rudeness then I will be waiting for you at each turn exposing your poor manners and bullying.

Now if you have anything actually constructive to say about my original statement - please do.  If you wish to continue your bullying ways think twice, I hate bullies, I will not let them stand.

The proper thing now is to say sorry or say nothing.  Anything else simply proves my point.

**Comment by NathanaelA** [comment]
@stephenfeather Hmm, interesting --  Complaining on a free product about **"basic requirement" features available already** came across to me as a **entitled** jerk; and I was trying not to call him and entitled jerk for posting, but rather to send him down a more helpful path.   I apologize if you felt I was coming off as a jerk!   I thought I was making it plain that the easiest way to add features was to add them yourself and make pull requests.   So you actually have my sincere apology for the miscommunication I had on my side.   I never was trying to point out how awesome I am, but that the team frequently takes pull requests unlike some of the other OS projects you may have used...

**Comment by NathanaelA** [comment]
@Core-13; Guess I need to change your opinion of me. :grinning:   First of all, I'm not great, I'm good at what I do; and I am not afraid of others being better and as such I personally have NO problems not only sharing my knowledge freely but also sharing my code freely.   So it isn't a crusade to prove any greatness; it is the opposite I actually want to help people become great.   My philosophy is to help people up the ladder and when they surpass me then awesome.  (Guess I'm a teacher at heart, so I help from the trenches.).   So when I discuss things I discuss things from my experience; because I find that the most helpful blog posts, comments, etc are from people who fight in the trenches over a issue vs those who just theorize them.  

However, I can see the point where you can take that the other way.  Interesting perspective; Thank you!   I'll have to ponder it, and figure out how to mitigate it -- and if any of you have a good suggestion how to not appear to be self serving I'd gladly take them, because that is NOT the impression I am trying to give, and that really can destroy my ability to just plain help people up...

Second, to be honest your right I have no idea who you are and your repos are empty so it is hard to even start to evaluate you.   However with that said, even if you were John Carmack, had he used that "entitlement crap"; I would have called him on it.  I do apologize if the message was lost; so here is the pure undiluted message in bold.  :grinning:

**Don't _demand_ a feature; either _request_ it nicely and/or produce it yourself and improve the community.**

It is awesome to find another old school developer, my avatar is a little misleading as it is me when I was younger, I love the costume, so it stays... --- I'm probably as old school as you are...  :grinning:

Now as to the bullying; for that I do sincerely apologize if you took my words to mean I was bulling; that is the farthermost thing from the truth.   My goal was as stated above; I really hate the entitlement crap probably as much as you dislike bullying.    I apparently missed the mark in my communication letting you know; you have no **entitlement** on a free project.  Putting a +1 on the top message was enough to signify you wanted this feature; demanding it was too far overboard for me.

Now, to sum this all up; I do apologize for the wrong communication; since both you and Stephen took it the wrong way, my message was obviously not clear enough and was way to easily misconstrued so I do apologize for that!   I also apologize for starting our relationship on such poor footing; and despite not having much of a clue to who you are I still prefer making friends...   As such, if you feel that I need to resolve anything else that I may not have covered; seriously feel free to email me.

**Comment by rborn** [comment]
@NathanaelA I tend to ignore this kind of discussions but this feature request is raised by me so I feel I have to reply, so:

- Should we be afraid that every time we raise a feature request you will come and trash everyone for how stupid they are and how good are you? It's the second interaction I have with you and in the first one you trashed @TheBrousse - I see a very similar pattern here, so this is why I ask
- Did you forgot who {N} is build for? It's for stupid people like me that don't have any idea of native code, they know some javascript and they finally could be able to build native mobile apps with their limited, low IQ, idiot knowledge.
- Did you at least consider that this feature request is opened by a Telerik guy not any other of the idiots here?
- Does "culture" or "character" ring any bell to you? Written text is emotionless, and even all of us write in english, the culture, the type of character each of us has means the way we write is not always transmitting what we wanna say. Except maybe when you follow an well know convention and you SHOUT - something that I don't see in ANY (eh? see what I did here 😉  ) @Core-13's comments.

Now, while I was writing this I saw you answered and apologised for your "misunderstood" message, so I won't go on. Maybe you had a bad day or maybe you are more of an "explosive" person. However this is not the first time you do this so I'm not really sure what to believe.

And about your PRs, your modules and **all** the work you put out there for free (or paid), believe it or not, people appreciate it. 
A lot. 
So maybe you should enjoy you altruism just the way it is instead of... (well do what you did 😃  )?

**Comment by NathanaelA** [comment]
@rborn - thanks for your insight, maybe your right -- maybe I need to layoff the github comments and just focus on the code.  :grinning:     

I actually have no issue with this feature request, and I even :+1:  it this morning before I even saw Core-13's statement.   In fact, I rarely have any issues with any of the requests, and those I do -- I just let the NS team be the deciders since they are the ones who decide what features are added.   I'll plus those I think are great ideas.  :grinning: 

The ONLY thing I was responding to which apparently I TOTALLY screwed up on was the **entitlement** of the feature.  Even my favorite feature request, I don't feel entitled to, even though it has been a serious thorn in my butt for well over a year, and has cost me much time.    Maybe I read more into Core-13's statement; but the way it came across to me was he was being ungrateful for what is their and that this feature needed to be done yesterday because it should have already existed.   I take serious exception to entitlement; but I _will_ just let the NS team deal with it in the future and hold my response for it is better to be considered a fool than to open my mouth and prove it.  :grinning:

@rborn This is meant to be TOTALLY in JEST:  Hmm, maybe your the common factor; I just can't be involved in threads that you are part of..  Two for Two threads....  Hmmm, Just saying...  :grinning: 

Again thank you for you comments; and I apologize for pulling this thread off track.

**Comment by Daxito** [comment]
+1

I opened a feature request about this and I close it since my workaround was to use the visibility property, so it would be really nice to have : )

**Comment by atanasovg** [comment]
Locking this conversation for now. I know everyone here on this thread wants {N} to succeed. That's why I'd like to ask everyone to respect other people's opinion and to try to find the reasoning behind each statement before making any conclusions.

**Comment by hamorphis** [comment]
Opened a new issue here: https://github.com/NativeScript/NativeScript/issues/2820
