### ISSUE TITLE
backstackVisible = false not working on Android with physical back button

### ISSUE THREAD

**Issue by guillaume-roy** [NativeScript/NativeScript#1953]
### Tell us about the problem

When i perform a navigation with `backstackVisible` to `false`, i can go back to the previous view with the physical back button on Android which wouldn't happen.

### Which platform(s) does your issue occur on?

Android 5.1

### Please tell us how to recreate the issue in as much detail as possible.

Create 2 views and navigate from one to anoher with `backstackVisible: false` and then press physical back button. You should go back to the first view.

### Please provide the following version numbers that your issue occurs with:
- CLI: 1.7.1
- Cross-platform modules:1.7.1
- Runtime(s): tns-android 1.7.1

**Comment by NickIliev** [comment]
Hi @guillaume-roy 

We have recreated your scenario under Android 5.1 and were unable to reproduce your problem.
Here is a sample app demostrating your situation [https://github.com/NickIliev/sample-navigation-backstackVisible](https://github.com/NickIliev/sample-navigation-backstackVisible)

Please let me know if that works for you and if you have some differences in your code that are causing the different behaviour.

**Comment by guillaume-roy** [comment]
Hi @NickIliev,

I can't compile and execute your project on my phone, so i created a new one : 
* [backstackVisible-issue.zip](https://github.com/NativeScript/NativeScript/files/217099/backstackVisible-issue.zip)

In `main-page.js`, you'll see the call to the navigation with `backstackVisible`.

I can set this property to `true` or `false`, when i'm in the `page-1` view, if i press physical back button, i always go back to the `main-page`.

I reproduced it in Genymotion with `Google Nexus 4 - 5.1.0 - API 22 - 768x1280` preset.

**Comment by NickIliev** [comment]
Hi again @galexandrov 

What **backstackVisible=false** do is to not add the history to the stack of visited pages.

_For example:_
We have **main-page, pageA and pageB**
You set **backstackvisible=false** on main-page navigation entry and go to pageA.
From pageA then you go to pageB.
Now when you press back with the hardware button on pageB 
you will go back directly to **main-page** because the stack do not have pageA 

If you however want to prevent users of going back at all you can use
```
clearHistory: true
```
This will clear the stack and users will not be able to return back.

Hope this will be useful for yourn project - let me know if you need further assistance.

**Comment by guillaume-roy** [comment]
OK i get it.

My mistake was that i though the `backstackVisible = false` applied to the target view and not the source view.

Now it's clear.

Thank you ! :+1:
