### ISSUE TITLE
Emit "maxValue" & "value" propertyChange when just change maxValue property

### ISSUE THREAD

**Issue by dreambo8563** [NativeScript/NativeScript#1976]
### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

For Progress component, when I change the maxValue property, I will get two propertychange event.
"maxValue" & "value", but value is not changed.

### Which platform(s) does your issue occur on?
iOS/Android/Both

android

### Please tell us how to recreate the issue in as much detail as possible.

```ts
import {Component, ViewChild, ElementRef} from "angular2/core";
import {Color}  from "color";
import {SearchBar} from "ui/search-bar";
import {TextField} from "ui/text-field";
import {Switch} from "ui/switch";
import {Slider} from "ui/slider";
import {Progress}from"ui/progress";
import {PropertyChangeData} from "data/observable";

@Component({
    selector: "my-app",
    template: `
<StackLayout orientation="vertical">

<Progress #sw style="color:red"  [value]="value" maxValue="300" ></Progress>
<Button text="add" (tap)="btn()"></Button>
</StackLayout>
`,
    styleUrls: ["app.css"]
})
export class AppComponent {


    @ViewChild('sw') ngSwitch: ElementRef;
    nsSwitch: Progress;

    value: Number = 280;

    constructor() {
    }

    ngAfterViewInit() {
        this.nsSwitch = this.ngSwitch.nativeElement;

        this.nsSwitch.on("propertyChange", (e: PropertyChangeData) => {
            console.log(e.propertyName);
            console.log(" Changing", this.value);
        })
    }

    btn() {
        console.log("before Change", this.value);
        this.nsSwitch.maxValue = 30;
        console.log("after Change", this.value);

    }
}
```

```log
JS: ANGULAR BOOTSTRAP DONE.
JS: before Change 280
JS: maxValue
JS:  Changing 280
JS: value
JS:  Changing 280
JS: after Change 280
```

**Comment by vakrilov** [comment]
Hey @dreambo8563 
What you see is actually expected. The `value` of the `Progress` is 280 but when you set the `maxValue` to 30 -  both the `value` and the `maxValue` are set to 30, because `value` should never be more than `maxValue`.

To recap when you set `maxValue` - both `value` and `maxValue` of the `Progress` are changed to 30 (thus 2 propertyChange event). If you are wondering why `this.value` of the component is not changed to 30 also - that's because you are using one-way binding. 

`Progress` is actually not an input component so there is no `ngModel`(two-way binding) support for it - but if you test the same code with `Slider` component and use `[(ngModel)]="value"` it will work as expected.

**Comment by dreambo8563** [comment]
yes, I have ever use ngModel for progress but get error. thanks for your explanation.
