### ISSUE TITLE
Navigate option "transitionAndroid" crashed on Android 4.4

### ISSUE THREAD

**Issue by Metalmate** [NativeScript/NativeScript#2060]
Greetings,

when i use the following code in my project, the app creashes once it is getting called:
```
topmostFrame.navigate({
    moduleName: url,
    context: context,
    clearHistory: true,
    transitioniOS: {
        name: "slideRight"
    },
    transitionAndroid: {
        name: "fade"
    }
});
```

It also crashes when you leave transitioniOS out of the options.

My current workaround is to not use a different animation for Android here, which is fine for me and my app, but it's still a bug.

Platform(s): Android 4.4
NativeScript CLI: 2.0.0

**Comment by NickIliev** [comment]
Hi @Metalmate 

This issue is related to this [#2060](https://github.com/NativeScript/NativeScript/issues/2060)
It now only appears in Android API 19 (v4.4.4) and I will re-open it as a bug to be fixed - tnank you for noticiing this behaviour. Removing **clearHistory **will stop your app from crashing but of course this is only a temporaly fix.

Closing as duplicate to [#2060](https://github.com/NativeScript/NativeScript/issues/2060)
