### ISSUE TITLE
Accelerometer

### ISSUE THREAD

**Issue by ligaz** [NativeScript/NativeScript#209]
_From @alejonext on February 26, 2015 6:40_

I really do not know where to place this issue... Well, the point is that I would like to access the accelerometer sensor. In the docs [android](https://github.com/NativeScript/docs/wiki/Getting-Started-with-NativeScript-for-Android#how-to-inherit-from-class) and [ios](https://github.com/NativeScript/docs/wiki/Getting-started-with-NativeScript-for-iOS#using-the-c-api).  As would be to implement? Do not know if an event ...

_Copied from original issue: NativeScript/nativescript-cli#246_

**Comment by ligaz** [comment]
_From @brianchirls on March 24, 2015 14:32_

Sensor access (accel, gyro, position, etc.) would definitely be useful.

I believe Android does it through event listeners, and that's probably the best way to do it. There are various settings that describe how often events get triggered, balancing needs of the application with energy consumption. It might make for an easier API to allow querying of sensor values on every frame, but I worry that it might encourage people to ignore those settings.

**Comment by ilyakam** [comment]
I just wanted to mention that thanks to [this response in Google Groups](https://groups.google.com/forum/#!topic/nativescript/UbOcKfvWAic), I was able to get the Android accelerometer to work correctly. The complete code is as follows:

```js
var application = require('application');

function onAccuracyChanged(sensor, accuracy) {
  console.log('onAccuracyChanged:', accuracy);
}

function onSensorChanged(event) {
  var azimuth = event.values[0],
      pitch = event.values[1],
      roll = event.values[2];
  
  console.log('azimuth', azimuth);
  console.log('pitch', pitch);
  console.log('roll', roll);
}

function onPageLoaded(args) {
  var sensorManager = application.android.foregroundActivity.getSystemService(
        android.content.Context.SENSOR_SERVICE
      ),
      accelerometer,
      sensorActivity;
  
  sensorActivity = new android.hardware.SensorEventListener({
    onAccuracyChanged: onAccuracyChanged,
    onSensorChanged: onSensorChanged
  });

  accelerometer = sensorManager.getDefaultSensor(
    android.hardware.Sensor.TYPE_ACCELEROMETER
  );

  sensorManager.registerListener(
    sensorActivity,
    accelerometer,
    android.hardware.SensorManager.SENSOR_DELAY_NORMAL
  );
}
```

Having said that, does anybody know how to read the accelerometer data from an iOS device?

**Comment by alejonext** [comment]
Well, i think to create a library for that

**Comment by valentinstoychev** [comment]
@alejonext please let us know if you need help with the library.

**Comment by alejonext** [comment]
OK!

**Comment by ilyakam** [comment]
After spending a few days messing with the iOS accelerometer, I am pleased to say that I've got it working on an iOS device! I've taken inspiration from @nikolay-diyanov's gists, specifically [this one](https://gist.github.com/nikolay-diyanov/fe8e58985c4fb065f699).

Here's the code to accomplish that:

```js
var motionManager = new CMMotionManager();

function onTapStart() {
  if (!motionManager.accelerometerAvailable) {
    return;
  }

  motionManager.accelerometerUpdateInterval = 0.1;

  motionManager.startAccelerometerUpdatesToQueueWithHandler(
    NSOperationQueue.currentQueue(),
    function(accelerometerData, error) {
      var acceleration = accelerometerData.acceleration;

      console.log('x', acceleration.x);
      console.log('y', acceleration.y);
      console.log('z', acceleration.z);
    }
  );
}

function onTapStop() {
  motionManager.stopAccelerometerUpdates();

  NSOperationQueue.currentQueue().cancelAllOperations();
}

exports.onTapStart = onTapStart;
exports.onTapStop = onTapStop;
```

The biggest issue was that the accelerometer would only work for a few seconds if it was being called directly from the `loaded`'s event listener. Therefore, we start logging only after `onTapStart` in this case.

---

Now that I've gotten both platforms to work, I tried writing a plugin, borrowing heavily from [nativescript-flashdrive](https://github.com/tjvantoll/nativescript-flashlight) and [the accompanying article](http://developer.telerik.com/featured/building-your-own-nativescript-modules-for-npm/). Since in both cases the accelerometer data is provided after some interval in a loop, I figured that an event-based architecture is most suitable.

The [documentation outlining the creation of custom events](https://docs.nativescript.org/events.html#creating-a-custom-event) isn't too helpful, and I haven't been able to find an example in JavaScript on how to use `.notify` and `.on` in a straightforward manner.

Can anyone on here please point me in the right direction…?

**Comment by enchev** [comment]
Hi @ilyakam,

I believe that you can use the approach from [our connectivity module](https://github.com/NativeScript/NativeScript/blob/master/connectivity/connectivity.d.ts) with a callback for the start method and additional stop method.

**Comment by bradmartin** [comment]
https://www.npmjs.com/package/native-script-accelerometer

@vakrilov - is the team wanting this in the core or is your plugin enough to close this out and announce it? I believe I've seen a couple other plugins that could close out some features.

**Comment by enchev** [comment]
Hey folks,

https://www.npmjs.com/package/native-script-accelerometer will be part of our verified plugins.

**Comment by dzcpy** [comment]
Any modules for accessing gyroscope?

**Comment by NathanaelA** [comment]
@dzcpy - You can find all known plugins on https://plugins.nativescript.rocks
