### ISSUE TITLE
File.exists return true even the file is actually not exist

### ISSUE THREAD

**Issue by Alphmega** [NativeScript/NativeScript#2160]
I wanna apply the css if it exists.
And I convert `.css` to `.tns.css` with following codes
```typescript:
  public static STYLE_URL(paths: string[]): string[] {
    if (CoreConfigService.IS_MOBILE_NATIVE()) {
      let fs = require('file-system');
      var documents = fs.knownFolders.documents();
      return paths.map((path) => {
        let paths = path.split('.');
        paths.splice(-1);
        let newPath = `${paths.join('.')}.tns.css`;
        var fullPath = documents.getFile(fs.path.join(CLIENT_PATH, newPath).replace(/\.[/\\]/g, '')).path;
        console.log(fullPath);
        if (fs.File.exists(fullPath)) {
          console.log('Exists!!!');
          return newPath;
        } else {
          console.log('No Exists!!!');
          return path;
        }
      });
    } else {
      return paths;
    }
  }
```
But i found it always return true when i use `fs.File.exists`, And I only has navbar.component.tns.css in my project
And directory structure of the nativescript likes following

- app
    - app
      - components
         - about
         - app
            - app.component.e2e.js
            - app.component.e2e.js.map
            - app.component.e2e.ts
            - app.component.html
            - app.component.js
            - app.component.js.map
            - app.component.spec.js
            - app.component.spec.js.map
            - app.component.spec.ts
            - app.component.tns.html
            - app.component.ts
            - navbar.component.css
            - navbar.component.html
            - navbar.component.js
            - navbar.component.js.map
            - **navbar.component.tns.css**
            - navbar.component.tns.html
            - navbar.component.ts
            - toolbar.component.css
            - toolbar.component.html
            - toolbar.component.js
            - toolbar.component.js.map
            - toolbar.component.tns.html
            - toolbar.component.ts

Console:

```
Found peer TypeScript 1.8.10
JS: /data/data/com.yourdomain.appname/files/app/app/components/app/navbar.component.tns.css
JS: Exists!!!
JS: /data/data/com.yourdomain.appname/files/app/app/components/app/toolbar.component.tns.css
JS: Exists!!!
JS: /data/data/com.yourdomain.appname/files/app/app/components/home/home.component.tns.css
JS: Exists!!!
JS: /data/data/com.yourdomain.appname/files/app/app/components/about/about.component.tns.css
JS: Exists!!!
JS: Page loaded
JS: BOOTSTRAPPING...
JS: Setting DOM
JS: NSAppCmp ----
```

**Comment by NickIliev** [comment]
Hi @Alphmega 

The command documents.getFile() **_will create a new file or overwrite an existing file._** as described in the  [documentation article about file-system](https://docs.nativescript.org/cookbook/file-system) so the reason fs.File.exists(fullPath) is returing true is because of the newly created files.

However I must point out the depending on the IDE you are using the file-structure may not be updated - for examle VSCode will not update immediately the app structure and will not show you the newly created files. What you can do is to manually refresh or re-open the app in VSCode - Can you verify if that is your case!?

p.p. Meanwhile insted of documents.getFile() which is creating a new file 
you can use something like this to create only a valid path
`var path = fs.path.join(documents.path, "myFiles", "test.txt");`
