### ISSUE TITLE
IOS: cannot access NSLocalizedString

### ISSUE THREAD

**Issue by rborn** [NativeScript/NativeScript#2163]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0

### Please tell us how to recreate the issue in as much detail as possible.
I simply cannot access the `NSLocalizedString` that exists in the Foundation framework.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

app.js
~~~
console.error(NSString); // <- displays function NSString() { [native code] }

console.error(NSLocalizedString); // <- displays Can't find variable: NSLocalizedString and crashes
~~~

It might be me, not knowing how to access it but in this case maybe a manual page should be dedicated on how to expose missing methods, etc from the xcode frameworks and not only 3rd parties.

Thank you 😄

**Comment by TheBrousse** [comment]
According to Apple's documentation on [NSLocalizedString](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Miscellaneous/Foundation_Functions/index.html#//apple_ref/c/macro/NSLocalizedString). It appears that it is actually a macro that returns the result from the [localizedStringForKey](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/index.html#//apple_ref/occ/instm/NSBundle/localizedStringForKey:value:table:) method (Which is present in the [ios.d.ts](https://raw.githubusercontent.com/NativeScript/NativeScript/master/ios.d.ts) file).

Swift *technically* has the same problem since it doesn't have macros per se. So it added its own version of the macro using a function.
```swift
func NSLocalizedString(
    key: String,
    tableName: String? = default,
    bundle: NSBundle = default,
    value: String = default,
    #comment: String) -> String
```
 Maybe this could be a way to address the issue where some macros a "wrapped" in the `ios` namespace when generating the files?

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#568
