### ISSUE TITLE
Android build failing on OSX at step ':processF0F1F2F3DebugResources'

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/NativeScript#2213]
### Tell us about the problem
I have an android project which builds fine on windows, but on my mac, it fails at the `:processF0F1F2F3DebugResources` step of the build.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0 (android)

### Please tell us how to recreate the issue in as much detail as possible.
`$ tns doctor` throws no issues, I have XCode 7.3 installed and the latest version of Nativescript. I am running node v4.4.3. I am running OSX El Capitan (v10.11.5). 

However, if I clone the sample-groceries app, run `npm i` and then `tns run android`, I get the error. [Here](https://gist.github.com/georgeedwards/cab35078beac901bbf2ee33a0fbd5e4e) is the full stack trace build log.

**Comment by PeterStaev** [comment]
This seems to be the same problem as described in https://github.com/NativeScript/nativescript-cli/issues/1740 solution is instead of using `npm install` to use `tns install` or just run `tns run android`. 

Note that once you used `npm i` you must remove and re-add the android platform in order to clear the bad state of the `platforms/android` directory.

**Comment by NickIliev** [comment]
Hello @georgeedwards 

I was not able to reproduce this problem but I believe your issue is directly related to this [https://github.com/NativeScript/nativescript-cli/issues/1740](https://github.com/NativeScript/nativescript-cli/issues/1740)

As a solution try the following:

- Instead of  _npm install_ use **_tns install_** (or don't call npm install att all and directly run tns run android)

- Check your build-tools version and update if needed.

**Comment by georgeedwards** [comment]
Awesome - that's done it - thanks!
