### ISSUE TITLE
Could not find module 'globals' deployment failures on ios

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/NativeScript#2230]
### Tell us about the problem
I have an ios project which builds fine for android, but on the same machine, it fails when it's run on an ios device.

> JavaScript error:
file:///app/tns_modules/nativescript-angular/application.js:2:8: JS ERROR Error: Could not find module 'globals'. Computed path '/var/containers/Bundle/Application/D3EB2D6A-2A3A-4A80-8B56-38387A795D6C/PersonalApp.app/app/tns_modules/globals'.

If I remove the ios platform and re- `tns run ios`, the problem goes away, but I keep getting it if I build with the same platform twice, not sure why my platform keeps becoming corrupted?

I get a similar behaviour with the debug command, throwing error:

>Command failed: The debug process exited unexpectedly code:null

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0 (ios)

### Please tell us how to recreate the issue in as much detail as possible.
`$ tns doctor` throws no issues, I have XCode 7.3 installed and the latest version of Nativescript. I am running node v4.4.3. I am running OSX El Capitan (v10.11.5). My full build log is [here](https://gist.github.com/georgeedwards/9e8914fdc2ec64abf24a05bf6bdc6870) and for the debug command [here](https://gist.github.com/georgeedwards/9e8d98b9972c4d3b898dfeff0ff4dfdf)

**Comment by NathanaelA** [comment]
Can you double check your node_modules folder and see if you have a folder called **tns-core-modules** if not then do a **npm install tns-core-modules@latest --save** and then try rebuilding your app.

**Comment by georgeedwards** [comment]
@NathanaelA I do have that, but if I remove it and run your command + remove the ios platform, I still get debug failing with error `Command failed: The debug process exited unexpectedly code:null`

**Comment by NathanaelA** [comment]
Well, the first error that you are getting; looks like you are totally missing the tns-core-modules.  Your build log also doesn't show it being included.  

 So either your tns-core-modules isn't present, or it is a empty folder or perhaps it has been tagged as a dev-dependancy in your package.json rather than a normal dependancy.

**Comment by georgeedwards** [comment]
The folder is full and my package.json (I believe) is correct, see below:

[![enter image description here][1]][1]


  [1]: http://i.stack.imgur.com/61fkP.png

**Comment by georgeedwards** [comment]
even when deleting both platforms and the node_modules folder, then running `tns install` I still get this: 

>$ tns debug ios
Neither --debug-brk nor --start option was specified. Defaulting to --debug-brk.
Copying template files...
Timeout waiting for response from NativeScript runtime.

**Comment by NathanaelA** [comment]
What do you have in your dev-dependancies?

**Comment by georgeedwards** [comment]
```
{
	"description": "NativeScript Application",
	"license": "SEE LICENSE IN <your-license-filename>",
	"readme": "NativeScript Application",
	"repository": "<fill-your-repository-here>",
	"nativescript": {
		"id": "org.nativescript.AzureTest",
		"tns-android": {
			"version": "2.0.0"
		}
	},
	"dependencies": {
		"@angular/common": "2.0.0-rc.1",
		"@angular/compiler": "2.0.0-rc.1",
		"@angular/core": "2.0.0-rc.1",
		"@angular/http": "2.0.0-rc.1",
		"@angular/platform-browser": "2.0.0-rc.1",
		"@angular/platform-browser-dynamic": "2.0.0-rc.1",
		"@angular/platform-server": "2.0.0-rc.1",
		"@angular/router-deprecated": "2.0.0-rc.1",
		"nativescript-angular": "0.1.1",
		"nativescript-azure-mobile-apps": "^0.5.1",
		"nativescript-bluetooth": "^1.1.2",
		"nativescript-floatingactionbutton": "^2.2.2",
		"tns-core-modules": "^2.0.1"
	},
	"devDependencies": {
		"babel-traverse": "6.9.0",
		"babel-types": "6.9.0",
		"babylon": "6.8.0",
		"filewalker": "0.1.2",
		"lazy": "1.0.11",
		"nativescript-dev-typescript": "^0.3.2",
		"nativescript-dev-webpack": "0.0.15",
		"typescript": "^1.8.10"
	}
}
```

**Comment by AdamDenoon** [comment]
I had the same issue, which was caused by not having `"tns-core-modules": "^2.0.1"` in my package.json file under dependencies. I added that line, relaunched on ios, and it worked.

**Comment by pap5508** [comment]
Getting this error while running the application on IOS


`CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in main/main-menu.component.html:40:0 caused by: null is not an object (evaluating 'tabBar.items.count')
CONSOLE LOG file:///app/shared/login.service.ts:182:18: access_token: login_check: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSIsImtpZCI6ImEzck1VZ01Gdjl0UGNsTGE2eUYzekFrZnF1RSJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMDMuMTIwL0lkU3J2IiwiYXVkIjoiaHR0cDovLzE5Mi4xNjguMTAzLjEyMC9JZFNydi9yZXNvdXJjZXMiLCJleHAiOjE0ODYzNzYwMzIsIm5iZiI6MTQ4NjM3MjQzMiwiY2xpZW50X2lkIjoicm8uY2xpZW50Iiwic2NvcGUiOlsib2ZmbGluZV9hY2Nlc3MiLCJvcGVuaWQiLCJyZWFkIl0sInN1YiI6ImMyY2Y4ZjhjLWI4MzEtNDcwOS05NWRjLTA5ZGMzYmFhZTNkYiIsImF1dGhfdGltZSI6MTQ4NjM3MjQzMiwiaWRwIjoiaWRzcnYiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0YXJlayIsIm5hbWUiOiJ0YXJlayIsImNsaWVudCI6IjAiLCJjdXN0b21lciI6IjAiLCJwcmluY2lwYWwiOiIwIiwiYW1yIjpbInBhc3N3b3JkIl19.GlfmwNMCtWwKq2wQuxa8dtjlmpXuUi_0rBcmPFwbMOy0mECtB18JoYzrFITmzKFDWr9JJv4rjFiaFtwso_yJtZj5mfSCqa9MES03Lb-8HmY_vRwL0pb9CouMxbiHc-WqEFZLrgqEv54UIUSRf7MZ8mDR6NI37CMQ4gBOkgfh6OUZydUG86GRG1wshosDwJJNOd9Kl-e3ZNVbAdBRB_tH_SONnbrVL9DYOR8VcByRKEsnW6-THOjMXPVjot3m9LVpdmdkcRBkuGgj1gClLvE3GMiWN78s0971YK-h772oCJJQgVaOF4nkOYB_rYBGlcqNi2vpaa2ppkX3wQAuJlW0Aw
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:2837:32: EXCEPTION: Uncaught (in promise): Error: Error in main/main-menu.component.html:40:0 caused by: null is not an object (evaluating 'tabBar.items.count')
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:2842:36: ORIGINAL STACKTRACE:
CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:2843:36: resolvePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:416:40
resolvePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:401:31
file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:31
invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:42
onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5966:51
invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:54
runTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:57
drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:42
promiseReactionJob@[native code]
UIApplicationMain@[native code]
start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:67:26
bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:55:26
anonymous@file:///app/main.js:5:57
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:342:26: Unhandled Promise rejection: Error in main/main-menu.component.html:40:0 caused by: null is not an object (evaluating 'tabBar.items.count') ; Zone: angular ; Task: Promise.then ; Value: Error: Error in main/main-menu.component.html:40:0 caused by: null is not an object (evaluating 'tabBar.items.count') getNativeFontValue@file:///app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js:427:25
applyProperty@file:///app/tns_modules/tns-core-modules/ui/styling/style.js:1352:86
_applyStyleProperty@file:///app/tns_modules/tns-core-modules/ui/styling/style.js:1117:38
file:///app/tns_modules/tns-core-modules/ui/styling/style.js:1032:103
forEach@[native code]
_endUpdate@file:///app/tns_modules/tns-core-modules/ui/styling/style.js:1032:40
_applyInlineStyle@file:///app/tns_modules/tns-core-modules/ui/core/view-common.js:1114:38
_applyXmlAttribute@file:///app/tns_modules/tns-core-modules/ui/core/view-common.js:1246:35
setPropertyInternal@file:///app/tns_modules/nativescript-angular/view-util.js:209:36
setProperty@file:///app/tns_modules/nativescript-angular/view-util.js:198:37
setElementProperty@file:///app/tns_modules/nativescript-angular/renderer.js:154:34
setElementAttribute@file:///app/tns_modules/nativescript-angular/renderer.js:159:39
createRenderElement@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4973:41
createInternal
create@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9396:52
createInternal
createHostView@file:///app/tns_modules/@angular/core/bundles/core.umd.js:9407:60
createComponent@file:///app/tns_modules/@angular/core/bundles/core.umd.js:7129:55
loadWithFactory@file:///app/tns_modules/nativescript-angular/common/detached-loader.js:38:49
activateOnGoForward@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:161:75
activate@file:///app/tns_modules/nativescript-angular/router/page-router-outlet.js:135:37
placeComponentIntoOutlet@file:///app/tns_modules/@angular/router/bundles/router.umd.js:3178:28
activateRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:3152:50
file:///app/tns_modules/@angular/router/bundles/router.umd.js:3107:76
forEach@[native code]
activateChildRoutes@file:///app/tns_modules/@angular/router/bundles/router.umd.js:3107:40
activate@file:///app/tns_modules/@angular/router/bundles/router.umd.js:3093:37
file:///app/tns_modules/@angular/router/bundles/router.umd.js:2818:68
file:///app/tns_modules/rxjs/Observable.js:108:25
__tryOrSetError@file:///app/tns_modules/rxjs/Subscriber.js:232:20
next@file:///app/tns_modules/rxjs/Subscriber.js:174:42
_next@file:///app/tns_modules/rxjs/Subscriber.js:125:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:133:34
_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_complete@file:///app/tns_modules/rxjs/operator/reduce.js:105:34
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:125:38
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32
subscribe@file:///app/tns_modules/rxjs/Observable.js:56:37
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:120:55
_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:117:23
_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:100:26
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:133:34
_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
notifyComplete@file:///app/tns_modules/rxjs/operator/every.js:47:30
_complete@file:///app/tns_modules/rxjs/operator/every.js:64:28
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_complete@file:///app/tns_modules/rxjs/operator/mergeMap.js:125:38
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_subscribe@file:///app/tns_modules/rxjs/observable/ArrayObservable.js:116:32
subscribe@file:///app/tns_modules/rxjs/Observable.js:56:37
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:120:55
_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:117:23
_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:100:26
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
notifyNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:133:34
_next@file:///app/tns_modules/rxjs/InnerSubscriber.js:23:31
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_subscribe@file:///app/tns_modules/rxjs/observable/ScalarObservable.js:49:28
subscribe@file:///app/tns_modules/rxjs/Observable.js:56:37
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
_innerSub@file:///app/tns_modules/rxjs/operator/mergeMap.js:120:55
_tryNext@file:///app/tns_modules/rxjs/operator/mergeMap.js:117:23
_next@file:///app/tns_modules/rxjs/operator/mergeMap.js:100:26
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/Subscriber.js:125:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_next@file:///app/tns_modules/rxjs/operator/map.js:83:30
next@file:///app/tns_modules/rxjs/Subscriber.js:89:23
_complete@file:///app/tns_modules/rxjs/operator/last.js:109:29
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_complete@file:///app/tns_modules/rxjs/operator/mergeAll.js:94:38
complete@file:///app/tns_modules/rxjs/Subscriber.js:114:27
_subscribe@file:///app/tns_modules/rxjs/observable/ScalarObservable.js:51:36
subscribe@file:///app/tns_modules/rxjs/Observable.js:56:37
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
subscribe@file:///app/tns_modules/rxjs/Observable.js:53:26
file:///app/tns_modules/rxjs/Observable.js:87:47
ZoneAwarePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:37
forEach@file:///app/tns_modules/rxjs/Observable.js:86:31
file:///app/tns_modules/@angular/router/bundles/router.umd.js:2800:29
ZoneAwarePromise@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:465:37
runNavigate@file:///app/tns_modules/@angular/router/bundles/router.umd.js:2739:31
invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:190:33
onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5975:47
invoke@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:189:42
run@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:83:49
file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:449:60
invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:223:42
onInvokeTask@file:///app/tns_modules/@angular/core/bundles/core.umd.js:5966:51
invokeTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:222:54
runTask@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:123:57
drainMicroTaskQueue@file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:355:42
promiseReactionJob@[native code]
UIApplicationMain@[native code]
start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:67:26
bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:55:26
anonymous@file:///app/main.js:5:57
evaluate@[native code]
moduleEvaluation@[native code]
[native code]
promiseReactionJob@[native code]
CONSOLE ERROR file:///app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js:344:22: Error: Uncaught (in promise): Error: Error in main/main-menu.component.html:40:0 caused by: null is not an object (evaluating 'tabBar.items.count')`
