### ISSUE TITLE
How to place an image on top of two elements as shown in the image.

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#2277]
![cosmo](https://cloud.githubusercontent.com/assets/10844041/15926547/38d4dc14-2e5a-11e6-9d14-3c7f00cd8b12.PNG)

**Comment by NickIliev** [comment]
@dhanalakshmitawwa 

In order to set element position against another element the best solution is to use an absolute-layout.
For example : 
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
  <AbsoluteLayout>
      <GridLayout backgroundColor="green" width="200" height="200" top="0"  right="0" />
      <GridLayout backgroundColor="red" width="200" height="200" top="200"  right="0" />
      <Image src="res://icon" stretch="none" top="180"  right="0"/> 
  </AbsoluteLayout>
</Page>
```

More about absolute-layout functionality you can find at our documentation article : [https://docs.nativescript.org/ui/layout-containers#absolutelayout](https://docs.nativescript.org/ui/layout-containers#absolutelayout)

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
