### ISSUE TITLE
tns-platform-declarations slows down the building process

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#2285]
### Tell us about the problem
When it's installed the building process much slower. 

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 1.7.1
- Runtime(s): tns-ios: 2.0.0
- Plugin(s): tns-platform-declarations

### Please tell us how to recreate the issue in as much detail as possible.
Build any NativeScript app without the plugin installed. Notice the speed. Now install the plugin and repeat the build. Same count for livesync.

**Comment by NickIliev** [comment]
@terreb I think this is expected behavour as what essentially tns-platform-declartions do is to provide you
with two really big text files (approx. 15MB) in order to help you with the development under TypeScript.
Notice that you need this files only if you are going to use TypeScript + native APIs during the development process.

After adding a plugin the first build is slower.. Run second build fater your plugin instalationb and performance should be improved significantly.
 (on my PC with the template app it was 15 seconds vs 4 seconds)

**Comment by terreb** [comment]
Hmm, does it depend on the project size? For me it takes approx. 1 min with the plugin and 20 secs without. My machine is pretty performant (mac book pro late 2013). This longer not only during the first build. Same for livesync : when the plugin is installed it takes forever to reflect changes in the simulator. But once I remove the plugin all is super fast.

**Comment by NickIliev** [comment]
@terreb For a mid-size app (approx 5-10 plugins) on MAC and building for Android the timing are pretty much the same like yours (approx. 48 sec. vs 16 sec for the second build) However livesync option should reflect changes within few seconds, 
You can try running 
``
`tns build android --log trace
```
to observe more detailed information
