### ISSUE TITLE
Typescript definition files for 17+ APIs

### ISSUE THREAD

**Issue by georgeedwards** [NativeScript/NativeScript#2295]
### Tell us about the problem
I need to use some APIs after 17, 21 is particularly interesting. I have manually added the features I specifically need, but it would be really helpful to have full and complete definitions for each subsequent API release. I am hoping that the C.250K line file wasn't written manually, in which case, adding an `android18.d.ts`, `android19.d.ts`, `android20.d.ts` etc. file shouldn't be a huge job. I am more thank happy to prepare a PR, just let me know how this was done originally.

### Which platform(s) does your issue occur on?
Android

**Comment by tsonevn** [comment]
Hi @georgeedwards, 
Thank you for your suggestion.
Such a feature will be really useful. This will be scheduled the issue for feature request for some of the next NativeScript versions.

As a temporary solution you could change `"noEmitOnError"` property to `false` and this will allow you to build your project.

I hope this helps.

**Comment by PanayotCankov** [comment]
The typescript definitions were generated by a tool, but the operation couldn't be completed unattended as there were some corner cases we couldn't cover well. We are working on the tool and hope we will be able to expose it for public use in the future. We would not add the android.d.ts nor ios.d.ts files in the `tns-core-modules` since they are really big and adding different versions would increase the download size even further. We may consider putting them in `@typgins` or a similar mechanism, but the best we can do is let the .d.ts-es be generated of the native projects. Then we will be able to provide .d.ts-es even for client code and third party libraries installed through Cocoapods etc.

**Comment by georgeedwards** [comment]
@PanayotCankov OK, sounds good, I really don't think the delivery mechanism matter, typings would be good. It would just be good to have the API up to 23 documented.

**Comment by georgeedwards** [comment]
@tsonevn could we tag this for `2.0.1`?

**Comment by tsonevn** [comment]
related to
[#104](https://github.com/NativeScript/android-runtime/issues/104)
 [#181](https://github.com/NativeScript/ios-runtime/issues/181)
