### ISSUE TITLE
performance issues when navigate to another page 

### ISSUE THREAD

**Issue by yclau** [NativeScript/NativeScript#2377]
I trying navigate xml to another xml, in android that is have performance issues , it like take a few second then start navigate to another xml. And I try in IOS, it work fine. 

### Tell us about the problem
When I click a button navigate to another xml(heavy xml include binding), it will take a few second to take response, no smooth and I try in example apps of nativescript, it same. 

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): 2.0.0
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
Examples NativeScript apps - main page navigate any page

**Comment by NickIliev** [comment]
Hi @yclau 

On which NativeScript example app you experiencing this navigation performance issue?
In order to reproduce this behaviour please provide more information or even better a sample code
that is causing this delay in your environment.
Also please provide information about the Android API Level and SDK version you are using.

**Comment by yclau** [comment]
I sent email to you and the Android API Level and SDK version is 17. thx

**Comment by NickIliev** [comment]
Hey @yclau have you send your project!? (if yes - on which email, if not perhaps you can share a GitHub link)

**Comment by yclau** [comment]
yeah ~~ update version solved the issues , thank very much
