### ISSUE TITLE
Idea: development Docker file

### ISSUE THREAD

**Issue by joeblew99** [NativeScript/NativeScript#2415]
keeping up with the dependencies for NativeScript and other frontend project takes time.

Using Docker solves all of this but for Mobile the USB pass through needs to be setup correctly so that:

- debug off an emulator

- debug off real devices.

**Comment by NathanaelA** [comment]
I'm a huge desktop VM guy.   However, How many people use Docker on the desktop?    

Are you also aware that I have a vagrant script; that will build the entire image?   I believe It is slightly out of date; and no one has bothered to ask for any updates to it; So it seems like virtualization like this (docker, vmware, virtualbox, docker) is not used by many people in this community...

**Comment by joeblew99** [comment]
@NathanaelA  Thanks for answering.

The vagrant scripts would be useful to look at only because of the USB aspects. The reason onyl this is because i use Docker for the servers and for the Desktop.On Desktop i use Docker for Mac (so no virtual box needed). Its out of beta and really fantastic i find. Much easier than when i had to work with vagrant, virtualbox etc.

Inside DOcker you can also run all the GUI too. You just export the GUI using x11. SO it a bit like running VNC etc. There are many examples and it works well.

The only thing to work on is the USB driver aspects, so that people can run on live hardware. This is because the USB drivers must be installed in the Host, not the docker.

I have been doing this for all development now. It means my Team can just grab the docker image and start working on a full setup environment

**Comment by NathanaelA** [comment]
Yeah, I understand -- Before I started doing contract/consulting -- the company I worked for I built virtual images for the other developers for the same reason; it was so much simpler for them to grab a preset image and go.   I still use a ton of VM's during the week, (windows, mac & linux)... :grinning:

Fortunately; a vagrant script doesn't need any special usb support, because both VMWare and VirtualBox support per device USB pass-through.     But if you want to check it out; it is at https://github.com/NathanaelA/nativescript-vm   

Your biggest issue with Docker is that you can't really set it up for xcode or iOS development -- so you also have to worry about keeping all those tools up to date.   Getting a docker image for  Android to work on mac and linux (windows requires a bit more work) to talk to the usb should be fairly trivial and I know I could probably build it in a couple hours.    However, to be honest, I think because the android Geny emulator has to also be outside the container; that Vagrant (maybe with a mostly pre-built image, rather than a scripted build image) might be a superior solution as both would be running on the same virtual engine VirtualBox; which would mean the machine isn't having to deal with two different virtualized environments and the additional memory that that would entail.

However, the very best way to do this would be for all development would be a single virtualized mac osx environment with everything except the android emulator installed -- The biggest issue with this is this couldn't be distributed outside of a company, and you would have to own as many OS licenses as you have VM's deployed, as the OS itself is copyrighted by Apple.  (So no license to distribute it to other people).    If you had that fully built, then you could just deploy that image and the geny emulator on the box; and go.  :grinning:   (This type of image is currently about 80gb of disk space)
