### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bogdan1995** [NativeScript/NativeScript#2417]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching [Stack Overflow]
No

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.0
- Cross-platform modules: 2.1.0
- Runtime(s): "version": "2.1.0"
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
I installed Mac OS X 10.11.5. Then I install nativescript following recommendations on nativescript site. Then I followed this article https://www.thepolyglotdeveloper.com/2016/05/build-simple-mobile-app-nativescript-angular-2/?utm_campaign=NG-Newsletter&utm_medium=email&utm_source=NG-Newsletter_149 and try to emulate application (use command "tns run --emulator") and get error "Cannot read property 'id' of undefined".

Command "tns doctor" shows: "WARNING: CocoaPods is not installed or is not configured properly.
You will not be able to build your projects for iOS if they contain plugin with CocoaPod file.
To be able to build such projects, verify that you have installed CocoaPods.
There seem to be issues with your configuration."

I tried to reinstall ruby, gems, nativescript, but this warning didn't missing.

**Comment by NickIliev** [comment]
Hello @bogdan1995 

To verify that you have installed CocoaPods you can run the following command:
```
pod --version
```
If you don't have installed CocoaPods you can install it manually with
```
sudo gem install cocoapods
```
The same command will update your CocoaPods if ones are installed but outdated.
Here is our documentation article about CocoaPods : [https://docs.nativescript.org/plugins/cocoapods#using-cocoapods](https://docs.nativescript.org/plugins/cocoapods#using-cocoapods)

As for the error, you are receiving _"Cannot read property 'id' of undefined"_ we will need more information (the actual code you are running, a detailed error log and if possible the sample project itself) in order to be able to reproduce this behavior. and give you further instructions.
More detailed error log you can have with 
```
tns run ios --log trace
```

I should also point out that the command is ` tns run ios --emulator` and not just `tns run --emulator`

As you are interested in NativeScript + Angular2 I can also recommend our own tutorial which is pretty similar to the one you are following but a bit more extended and with a detailed step by step instructions.
You can find out N+A tutorial at the following link [https://docs.nativescript.org/angular/tutorial/ng-chapter-1.html](https://docs.nativescript.org/angular/tutorial/ng-chapter-1.html)

**Comment by bogdan1995** [comment]
@NickIliev Thanks for answer. I run command `pod --version` and have `version: 1.0.1`. I tried to run `tns run ios --emulator` but nothing is changed. Also I run `tns run ios --log trace` and log of this command you can check here http://pastebin.com/7HaCX7Z4

**Comment by bogdan1995** [comment]
@NickIliev I follow this [tutorial](https://docs.nativescript.org/angular/tutorial/ng-chapter-1.html), that you recommend and iOS emulator successfully ran. Thanks.
