### ISSUE TITLE
Are there plans to expand to other base libraries?

### ISSUE THREAD

**Issue by morningrat** [NativeScript/NativeScript#2437]
Vue.js and Riot.js would be good, because they don't have any native support yet.

**Comment by UranusCEO** [comment]
Vue.js +1

**Comment by babakness** [comment]
Riot-js +1

**Comment by pi-ron** [comment]
+1 riotjs

**Comment by rtpm** [comment]
+1for vue2

**Comment by AkaOne** [comment]
Vue.js +1

**Comment by Rastishka** [comment]
Vue.js +1

**Comment by valentinstoychev** [comment]
Most definitely! As a core team in order to remain focused, we need to polish the Angular 2 story first. There are still some things that we can enable before we say that we are DONE with the task. I think related to this discussion is the full integration with the Chrome DevTools. Once we have the Angular story, it will be much easier to use other frameworks like Vue.js or React.

I want to encourage someone who has a good knowledge of the internals of Vue.js to get in touch with us and we can help him with guidance and development to enable Vue.js in NativeScript. It will be a great experience for us to work together.

**Comment by constantyn** [comment]
Vue 2 would be fantastic!

**Comment by quangv** [comment]
+1 vue.js

**Comment by vjoao** [comment]
Vue would be a game changer. I love Vue more than I love Angular.

**Comment by vjoao** [comment]
Vue + Vuex for data streams is just awesome.

**Comment by CrashyBang** [comment]
Vote here: https://nativescript.ideas.aha.io/ideas/NS-I-94

**Comment by elygre** [comment]
+1 for Vue.js

**Comment by babakness** [comment]
+1 VueJS. 

Just look at the popularity among the Github demographic. AngularJS 2: 20k+ stars, VueJS: 40k+ stars.

**Comment by samayo** [comment]
+1 VueJS

**Comment by siruguri** [comment]
+1 VueJS

**Comment by NZX-DeSiGN** [comment]
+1  VueJS

**Comment by wilsilva** [comment]
+1 VueJS

**Comment by welintonti** [comment]
+1 VueJS

**Comment by a-komarev** [comment]
+1 VueJS

**Comment by sorcerershell** [comment]
+1 VueJS

**Comment by Symfomany** [comment]
+100 VueJS

**Comment by thulioph** [comment]
+ 1 Vuejs

**Comment by jartaud** [comment]
+∞ Vue.js

**Comment by smolinari** [comment]
VueJS for the win! 

Scott

**Comment by ivanpadavan** [comment]
VueJS is so tinier, I think that after all the angular experience it would be soo easy to make vuejs integration. Nativescript is the best way to make native apps on JavaScript but, unfortunately, people just don't know about it. Let them know by focusing on this, and nativescript will shine like never before.

**Comment by NathanaelA** [comment]
If there are any VueJS users/developers who want to work on this; I'd be willing to lend them my expertise in how the low levels work (I've written over 40 plugins for NS).    Please note I am a contractor, and I don't work for Telerik so I am not willing to do all the work myself since I really can't afford that much free work, but I can help a person/group of you who wants to the majority of the work on this.  ;-)

That is interesting that VueJS does have 48k stars and Angular2/4 only has 22k stars...    That is pretty nifty that the VueJS framework has taken that much developer mind share in that quick amount of time...

**Comment by babakness** [comment]
I completely agree! Angular is a target audience; yet most projects will lend themselves to something simpler. VueJS has a lot of momentum. NativeScript would bloom in popularity with VueJS support!

**Comment by smolinari** [comment]
> That is pretty nifty that the VueJS framework has taken that much developer mind share in that quick amount of time...

There is a simple reason as to why and please don't laugh when I say it. But, VueJS has a "PHP mentality". What I mean by that is, it is purposely built to be attractive to less advanced programmers, yet there is a lot of power under the hood, for more advanced programmers. Note, I could have just as easily said  "JavaScript mentality" too, but I like the controversy. 😄 LOL! At any rate, VueJS' clear direction of being simple and pragmatic opens up its market of developers considerably and anything that supports it will automatically build up a synergy too, especially if they follow that same direction. 

Hint, hint, NativeScript. 😉 

Scott

**Comment by NathanaelA** [comment]
@smolinari - LOL to be honest; simple is actually way way better (imho) when dealing with mobile.   NAN (NativeScript Angular)  offers a lot; but it costs a lot on mobile too because of its massive code base really effects the app startup/size.     

I think that if a couple of the people with lower decent lower level experience with VueJS couple probably get a NS wrapper working pretty quickly -- however based on a quick look at VueJS this might not even be needed; you guys might feel right at home in NS already, without doing anything.   NS already uses `{{variable}}` in the screen markup for any variables already, and you just assign you variables to a observable and you are gold.    But I must confess I don't have ANY experience with VueJS; so I can't say what is missing beyond just briefly looking at the website and thinking the markup looked standard handlebar format..  

NAN support has its own view engine which tends to break certain types of plugins.   If you were able to use the standard PAN (Plain Awesome NativeScript) view engine without many modifications; VueJS would have a leg up on NAN apps because you would instantly inherit all the standard interface plugins.

**Comment by alexsandro-xpt** [comment]
Vue.js +1

**Comment by vinicius73** [comment]
ping @yyx990803

Can you give us your vision about this and the possibility of helping to create an integration?

**Comment by vinicius73** [comment]
@NathanaelA vue works with v-dom and SSR. Your template is compiled in js code (render function)
Vue have a [weex](https://weex.apache.org/) [integration](https://github.com/vuejs/vue/tree/dev/src/platforms/weex) he is more similar with react-native
Vue also supports [css-modules](http://vue-loader.vuejs.org/en/features/css-modules.html)

I believe that an integration will not be difficult, after all the pieces already exist.
I would love to help, but I have no technical knowledge of these specific parts of the vue.

I'm sure an integration with Vue will show the full potential of using the NS has.

**Comment by yyx990803** [comment]
Making a proper integration requires decent understanding of both Vue and NS's architecture - unfortunately, I haven't really had time to look into how NS works under the hood and what a proper integration would require. I don't think there would be any roadblocks technically, it just takes time :/

**Comment by kid-wumeng** [comment]
+1

**Comment by diaskooo** [comment]
+1

**Comment by decates** [comment]
+1

**Comment by vjoao** [comment]
@yyx990803 Doesn't Vue have a strict dependency to the DOM? How would this work?

**Comment by rigor789** [comment]
@vjoao Vue has a template compiler that can generate AST's https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler

I'm still familiarizing myself with NS but as far as I can tell, building upon an AST would be the ideal approach. Let me know if my theory is flawed!

**Comment by rezaxdi** [comment]
Vue.js +1

**Comment by IvanFon** [comment]
Is there a reason people are commenting +1? I suggest you add a thumbs-up to the top comment.

**Comment by smolinari** [comment]
It's probably because the OP is asking for two different libraries, and most of the people are making it known they particularly want Vue support with their comment. 

Scott

**Comment by a-komarev** [comment]
@IvanFon To receive notifications about activity in this issue. When you are receiving hundreds notifications daily it will be easier to see this issue in **Participating** list and you will be emailed about comments.

**Comment by nartzco** [comment]
RiotJS +1

**Comment by pi-ron** [comment]
For anyone wanting to help integrating Vue with NativeScript... https://nativescript.ideas.aha.io/ideas/NS-I-94

> Jen Looper commented April 19, 2017 17:04
> We have started on a community-led initiative to port NativeScript for Vue.js! Take a look at our Community Slack in the #vue channel. The very initial steps are being taken by Igor here: **https://github.com/rigor789/nativescript-vue** and we need PRs and lots of help! Please join us!

**Comment by pi-ron** [comment]
NativeScript Vue on Github: https://github.com/rigor789/nativescript-vue

Contribution guide:
https://github.com/rigor789/nativescript-vue/blob/master/CONTRIBUTING.md

**Comment by michelebroggi** [comment]
+1 for Vue!

**Comment by Modcat** [comment]
Vue2!!

**Comment by fengfudev** [comment]
Vue.js +1

**Comment by inssitu** [comment]
vue +1

**Comment by amritk** [comment]
vue +1

**Comment by sleewoo** [comment]
+1 for Vue2

**Comment by tebanep** [comment]
vue +1

**Comment by BennyAlex** [comment]
vue 2 +1

**Comment by atanasovg** [comment]
There is a community project on Vue.js support in NativeScript:
https://github.com/NativeScript/NativeScript/issues/2437#issuecomment-299340229

For questions/suggestions on this integration please use the respective GitHub repository:
https://github.com/rigor789/nativescript-vue/issues

Closing this issue

**Comment by kliron** [comment]
Vue.js +1

**Comment by ksolberg** [comment]
Vue2 +1

**Comment by kid-wumeng** [comment]
Vue2+1

**Comment by geodeveloper** [comment]
Vue2 +1

**Comment by babakness** [comment]
NativeScript's own Angular repository

https://github.com/NativeScript/nativescript-angular

despite all fanfare and homepage marketing, etc. has less stars on GitHub than the community grown Vue integration, which has been out for less time.

https://github.com/rigor789/nativescript-vue

**Comment by tvld** [comment]
Vue2 +1

**Comment by SkyGrass** [comment]
vue.js +1 i hope NativeScript can support .vue file.

**Comment by NickIliev** [comment]
@SkyGrass @tvld the Vue integration can now be experimentally tested in the [NativeScript playground](https://play.nativescript.org/?template=play-vue)

**Comment by tvld** [comment]
Thanks @NickIliev, I just had a go at it.

I don't understand the concept of _two_ applications: _Playground_ and _Preview_. I would have thought to see just a Playground with selectable preview projects, but apparently I am off the whole Nativescript concept... 

Further, Preview only shows the last dropped component and does not show any of the earlier inserted, which cant be right.

I seriously want to like the concept, but I still need to work on that ;))

**Comment by tvld** [comment]
@NickIliev That works; the blog was helpful. The complete reloading of the preview app slows things down after each change, but the results are promising... diving further ))

**Comment by xlcrr** [comment]
Another +1 for Vue
