### ISSUE TITLE
NativeScript on Lenovo A880 phone using Android 4.2.2 keep crashing

### ISSUE THREAD

**Issue by fatguppy** [NativeScript/NativeScript#2445]
NativeScript on my Lenovo A880 phone using Android 4.2.2 keep crashing.

There are no crash log option in the Android Companion app.

NativeScript crashes on startup on my Lenovo A880 phone using Android 4.2.2 and I cannot disable this status notification on my start screen.

Can fix?

![screenshot_2016-07-07-08-31-56](https://cloud.githubusercontent.com/assets/3380241/16791923/ea7f2464-48f5-11e6-8e6a-0798fb7f299d.png)
![screenshot_2016-07-07-08-32-14](https://cloud.githubusercontent.com/assets/3380241/16791924/ea836114-48f5-11e6-8e2c-0c8793e0deb7.png)
![screenshot_2016-07-07-08-32-22](https://cloud.githubusercontent.com/assets/3380241/16791925/ea86d542-48f5-11e6-9be5-714c43d85b50.png)
![screenshot_2016-06-24-21-46-29](https://cloud.githubusercontent.com/assets/3380241/16791926/ea87d136-48f5-11e6-8294-d6408ecf635a.png)
![screenshot_2016-06-25-10-36-21](https://cloud.githubusercontent.com/assets/3380241/16791927/ea8ae15a-48f5-11e6-979f-3338926f0644.png)

**Comment by tsonevn** [comment]
Hi @fatguppy,

In my opinion this issue is not related with NativeScript, you could use Telerik Platform, where you could sent a ticket describing your problem. For your help you could review this article [here ](http://docs.telerik.com/platform/appbuilder/troubleshooting/support/support-tickets) , where you could learn, how to submit support ticket to AppBuilder team.

I hope this helps,
Regards,
@tsonevn
