### ISSUE TITLE
How Can i extend  TabViewItem with view class for titleView instead of title?

### ISSUE THREAD

**Issue by katturajam** [NativeScript/NativeScript#2450]
I want like this tab bar with dynamic text instead of static. Like facbook notification badge.  

![6d6413f8-99ab-11e5-9198-341878fb0432](https://cloud.githubusercontent.com/assets/14198567/16805526/44e22180-492e-11e6-8421-66279b978152.png)

So can i extend TabViewItem with view class for titleView instead of title?

```
<TabViewItem>
                 <TabViewItem.titleVew>
                       <StackLayout>
                                   <Label text="Hello"></Label>
                                    <Label text="World"></Label>
                        </StackLayout>
                </TabViewItem.titleView>
                <TabViewItem.view>
                           <T1:tab1/>
                </TabViewItem.view>
</TabViewItem>
```

**Comment by NickIliev** [comment]
Hello @katturajam 

There are some limitations for customizing the native iOS UITabBar/**UITabBarItem** as mentioned at [https://github.com/NativeScript/NativeScript/issues/1217](https://github.com/NativeScript/NativeScript/issues/1217#issuecomment-163927443) (more specifically you can not apply multi lines for the tab-view-item title in iOS). This is the reason why you can not extend your tab-view-item title.

However in the same issue, there is a solution from @enchev that allows you to use [Icon Fonts ](https://docs.nativescript.org/ui/icon-fonts) in your title. Again this solution is suitable only for single-line titles.

In order to use it import your Icon Font and use it as shown in the example code.
