### ISSUE TITLE
Page not destroyed on back

### ISSUE THREAD

**Issue by jaysson** [NativeScript/NativeScript#2518]
### Which platform(s) does your issue occur on?
Android - not tested on iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.0.1
- Cross-platform modules: 2.0.1
- Runtime(s): tns-android - 2.0.0

### Please tell us how to recreate the issue in as much detail as possible.
I have a list page and a form page. When I tap "save" button on form page, a new entry is created and added to listing page. I do `topmost().goBack()` after that. However, if I again tap "Add Entry" and go to the form, it has old values prefilled.

How do I destroy the page once I do goBack? Doesn't nativescript destroy it once I go back?

**Comment by NickIliev** [comment]
Hey @jaysson 

 Is it possible to illustrate your scenario with a sample project or an example code snippets in order to reproduce your issue?

The default behaviour in Android should be as mentioned [here](https://github.com/NativeScript/NativeScript/issues/1337#issuecomment-172510016)

Meanwhile, if you need to control the stack of pages that are held in your navigation history stack you can refer to [this section ](https://docs.nativescript.org/core-concepts/navigation#navigate-without-history)of our navigation article where **_backstackVisible_** and **_clearHistory_** options are described. Basically, with **_backstackVisible_** set to false you prevent your navigation entry becoming part of your navigation stack and with **_clearHistory_** is used to completely clear the entire navigation history.
