### ISSUE TITLE
Restart app after error

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#2560]
Hi,

How I restart my app in onUncaughtError? Documentaton say "The method is intended to be used for crash reports and/or application restart.". So I did:
```
application.on(application.uncaughtErrorEvent, function (args) {
    frameModule.topmost().navigate({moduleName: "views/local/local"});
}
```
But this not work.

**Comment by tsonevn** [comment]
Hi @mobilemindtec, 
Thank you for contacting us.
However `uncaughtError` Event will be fire when the app crash or for example when the  have been  unexpected restart. In my opinion this issue is related to [#1204](https://github.com/NativeScript/NativeScript/issues/1204) , where possible solution for your scenario heve been given. In regard to that I will appreciate if you could give me more info about your case and if you could send me a link from the documentation where you have seen the part for `application restart`.

I hope this is applicable for you.

Regards, 
@tsonevn
