### ISSUE TITLE
Npm Error when running `tns prepare ios` with github package dependency

### ISSUE THREAD

**Issue by speigg** [NativeScript/NativeScript#2563]
### Tell us about the problem

After (successfully) installing a dependency directly from github via npm, `tns prepare ios` emits errors like this: 

```
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1' ]
nativescript-screen-orientation@1.0.1 node_modules/nativescript-screen-orientation
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1', '1.0.1' ]
nativescript-screen-orientation@1.0.1 node_modules/nativescript-screen-orientation
npm ERR! install trying to install 1.0.1 to /Users/gspeiginer/Code/<nativescript-app>/node_modules/nativescript-screen-orientation
npm ERR! install but already installed versions [ '1.0.1', '1.0.1', '1.0.1', '1.0.1' ]
```

### Which platform(s) does your issue occur on?
iOS , but probably not relevant

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.1.1
- Cross-platform modules: 1.7.1
- Runtime(s): 2.1.1

### Please tell us how to recreate the issue in as much detail as possible.

You can try installing the same dependency I am using:
`npm install bionictk/nativescript-screen-orientation --save`

**Comment by tsonevn** [comment]
Hi @speigg,

I reviewed the given scenario with latest modules and it seems to work as expected. In my opinion this issue is related to the old modules. You could try to upgrade you nativescritp using the described instruction [here ](http://docs.nativescript.org/releases/upgrade-instructions) and try to remove the plugin and add it again in your project. In regard to that you could also use `tns plugin remove <plugin_name>` and `tns plugin add <plugin_name>` to uninstall and install plugin in your project.

Let me know whether this helps.

**Comment by speigg** [comment]
I just tried updating tns_core_modules as you suggested, but it's definately a CLI issue. Updating tns_core_modules didn't help. My guess is that the problem has to something to do with my npm / node version (I have npm v3 and node v6 installed).

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#1990
