### ISSUE TITLE
The :highlighted pseudo-class requires movement during taps on iOS

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#2627]
### Tell us about the problem

On iOS, the new `:highlighted` pseudo-class usually does not apply when I tap buttons. After some investigating, I’ve found that the `:highlighted` pseudo-class only works if I move my finger (or mouse if on the simulator) a bit while tapping the button. The problem is, most of the time fingers aren’t moving when they tap buttons. I believe the `:highlighted` pseudo-class should always briefly apply to a button whenever it is tapped, and that is not currently occurring on iOS.

### Which platform(s) does your issue occur on?

iOS

### Please provide the following version numbers that your issue occurs with:

- CLI: 2.2.2
- Cross-platform modules: 2.2.1
- Runtime(s): 2.2.x
- Plugin(s): None

### Please tell us how to recreate the issue in as much detail as possible.

Clone and run the NativeScript theme app at https://github.com/nativescript/theme. Go to the buttons view and tap the buttons. All of the buttons should change colors when you tap on them, but none of them do.

Now, move your finger a bit as you tap (or your mouse if in the iOS simulator), and notice that the pseudo-class is applied as expected.

**Comment by nsndeck** [comment]
Hi @tjvantoll,

There is no need to move finger or mouse, just have to wait a little and `highlighted` state will appear. The problem with a slight delay on going to `highlighted` state is caused by iOS framework since all buttons are placed in a ScrollView control which sets such delay to control touches (more info (here)[http://stackoverflow.com/questions/7541159/is-it-possible-to-remove-the-delay-of-uibuttons-highlighted-state-inside-a-uisc]. So for the theme example there are two solutions (remove ScrollViewer or set its `delaysContentTouches` property to false.). Therefore I'll remove `bug` label, since it is working just fine (outside ScrollViewer).

**Comment by tjvantoll** [comment]
Thanks for the thorough response @nsndeck; I had no idea this was a thing on iOS. We’ll have to do some thinking about how we want to handle this in the theme (if at all), but since there doesn’t seem to be a problem in the framework itself I’ll close this for now.

**Comment by jimmirbn** [comment]
Hi Guys.
Is it possible to set delaysContentTouches = false in nativescript?

Regards.
Jimmi
