### ISSUE TITLE
Android Custom Activities and TNS incompatibility

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#2658]
_From @NathanaelA on August 24, 2016 21:40_

If you create a custom activity in your NativeScript application; TNS can no longer launch the app because it assumes the name of the launch activity is `com.tns.NativeScriptActivity` and well, it has a new name when you build a custom activity...

_Copied from original issue: NativeScript/nativescript-cli#2012_

**Comment by enchev** [comment]
Hey @slavchev @hshristov can you comment on this?

**Comment by Plamen5kov** [comment]
Hi @NathanaelA,
If you want to start up a custom activity you need to update the `app/App_Resources/Android/AndroidManifest.xml` of your application with the custom activity you want to use. It's true that by default we use `com.tns.NativeScriptActivity`, but this is easily configurable.

**Comment by NathanaelA** [comment]
@Plamen5kov -- LOL I think you misunderstand what I was reporting..  I know exactly how to implement it.  ;-)    I have an app that I have to do a custom activity on.

The issue is that when a developer does implement it, TNS can't launch the app; because it is hard coded to use `com.tns.NativeScriptActivity`.   This had me confused for a few minutes why it wasn't launching, then I noticed my `LiveEdit` plugin was doing the same thing.  Then it hit me that I changed the activity and we both were hard coding it to a specific Activitiy Name.    My LiveEdit plugin has already been updated to fix this issue (it now reads the AndroidManifest) ; but I figured I should report it to you guys so that you can fix it in the `tns` command so that others in the future aren't hit by this...

**Comment by NathanaelA** [comment]
@enchev I just realized you dropped this in the NativeScript repo; this is NOT a CORE modules issue; this is a TNS command line issue (which is why I put it in that repo.  :grinning:).   

 TNS command line assumes the name of the Android startup activity is `com.tns.NativeScriptActivity` which 99% of the time is a valid assumption.  However in Android if you need to change things in the default Activity you currently have to create your OWN activity (and so it has it's own name) and then that activity is what is built into the app and it is the main activity that needs to be launched with TNS is attempting to launch the app on android.   TNS unfortunately is still attempting to launch the `com.tns.NativeScriptActivitiy` activity which does not do anything...

**Comment by enchev** [comment]
This issue was moved to NativeScript/nativescript-cli#2028
