### ISSUE TITLE
How to run .java files?

### ISSUE THREAD

**Issue by terhoraj** [NativeScript/NativeScript#2761]
I need to include .java files according to this link: [https://www.azavea.com/blog/2013/01/14/wms-on-android/](https://www.azavea.com/blog/2013/01/14/wms-on-android) but where?

Then I need to call those files somehow? to use them with one nativescript plugin.

So where should I put my .java files and how I call them?

This is very important!

**Comment by NickIliev** [comment]
Hi @terhoraj ,

Based on the link you provided perhaps you can create a plugin for your application.
Follow [this link in our documentation](https://docs.nativescript.org/plugins/plugins#directory-structure) for additional information.
[
The directory structure](https://docs.nativescript.org/plugins/plugins#directory-structure) for creating plugn for NativeScript will allow you to use *.jar and  *.aar files in platforms/android

**Comment by terhoraj** [comment]
Actually this is the nativescript plugin where I would like  to make this feature but I'm not skilled enough.
https://github.com/dapriett/nativescript-google-maps-sdk

**Comment by NickIliev** [comment]
@terhoraj 

As far as I understood the WMS On Android article, it shows some concepts for using WMS tiles in Google Maps for Android.  Now the plugin you have linked in your last comment is ready to use with NativeScript  to create a fully working google maps for your app. However, if you want to create an extended logic for google-maps with WMS tiles probably the best approach is to adopt the google APIs needed and create your own plugin from scratch. That said you should notice that you will need to get familiar with the marshaling techniques used in NativeScript in order to adopt the Android Java code to NativeScript JavaScript.

You can also extend the logic of the existing plugin you have linked. The plugin itself can be used as a reference how to marshal Java to javaScript. For example take a look [at this code line ](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/map-view.android.ts#L44)in the plugin

e.g.
```
var cpBuilder = new com.google.android.gms.maps.model.CameraPosition.Builder();
```

[Here is the starting point](https://docs.nativescript.org/runtimes/android/marshalling/java-to-js) to get familiar with how to do marshalling for Java-to-JavaScript

**Comment by terhoraj** [comment]
Okay, thanks for replying. I try something.

**Comment by priyangamani** [comment]
I wrote a java file app.android.context is not working passing context to other class
