### ISSUE TITLE
Keyboard hides when moving to next textfield using "next" key

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#2809]
_From @dotlens on September 28, 2016 10:32_

The soft keyboard hides when the user tries to move from one textfield to next one with "next" button on the keyboard.

I reproduced this problem on android with and without using angular.

Found in {N} 2.3

To reproduce:
- build and run the sample groceries app using tns 2.3 (https://github.com/NativeScript/sample-Groceries/tree/angular-end)
- select username on the login page (keyboad opens)
- press "next" on the keyboard (password is selected but keyboard is hidden)

Possible workaround (not tested):
- use the (returnPress) event of the TextField to focus the next textfield.

_Copied from original issue: NativeScript/nativescript-cli#2085_

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/sample-Groceries#161

**Comment by dotlens** [comment]
This is a general issue which I discovered in my own app. Therefore it makes noo sense to fix it only in the samle-groceries app using a workaround...

It appears with every app that has multiple textfields and one wants to go to the next textfield using the "next" button on the standard soft keyboard.

**Comment by NathanaelA** [comment]
@hdeshev - This issue is still present in normal NativeScript on iOS, can we re-open this issue?

**Comment by mcrvaz** [comment]
Still present on Android too

**Comment by NathanaelA** [comment]
@hdeshev - Sorry buddy; I though you were still capable of changing the status; send me an email!  @hshristov - Can you re-open this one; this is NOT fixed for normal NativeScript.

**Comment by toddanglin** [comment]
Is this still an open issue for iOS?

@tjvantoll Did it get fixed in the Groceries app?

**Comment by tjvantoll** [comment]
I’m a little bit confused by this issue because the Groceries app—the app this issue was originally created for—has never shown a Next button in that branch. So.... I don’t know. Maybe @NickIliev or @NathanaelA have good memories and can fill in some details.

For anyone that stumbles upon this issue though, I’ll just spit out what I know about handling this keyboard management situation. I might turn this into a blog post.

---

With the {N} of today, if you want your textfield to have appropriate “Next” behavior you must set two attributes—`returnKeyType="next"` to change the return button text, and `returnPress="myHandlerThatMovesFocus"` to actually move the focus from one text field to the next. For example, here’s a complete implementation of a very basic form that has this behavior.

``` XML
<Page navigatedTo="onNavigatedTo">
  <StackLayout class="form">
    <StackLayout class="input-field">
      <TextField hint="Name" class="input" returnKeyType="next" returnPress="focusAddress"></TextField>
      <StackLayout class="hr-light"></StackLayout>
    </StackLayout>

    <StackLayout class="input-field">
      <TextField hint="Address" id="address" class="input"></TextField>
      <StackLayout class="hr-light"></StackLayout>
    </StackLayout>
  </StackLayout>
</Page>
```

``` JavaScript
var page;

exports.onNavigatedTo = function(args) {
  page = args.object;
};

exports.focusAddress = function() {
  page.getViewById("address").focus();
};
```

For iOS even after these changes there are a few additional things you might need to be aware of, like the soft keyboard potentially overlapping textfields and preventing your users from typing.

The [IQKeyboardManager plugin](https://github.com/tjvantoll/nativescript-IQKeyboardManager) solves the overlapping keyboard issue, as well as provides some sane default that make interacting with the keyboard so much nicer on iOS. @EddyVerbruggen recently added some advanced options to that plugin so you can do some [even more custom stuff](https://github.com/tjvantoll/nativescript-IQKeyboardManager#advanced-usage) as of the last few weeks.

For anyone struggling to get their keyboard behavior working correctly I’d advise you to try out the IQKeyboardManager plugin, because chances are it does what you’re looking for.

**Comment by toddanglin** [comment]
SUPER info. Thanks, TJ.

**Comment by nikoTM** [comment]
Hey, @NickIliev. Any updates on this?

**Comment by TheOnlyMatt** [comment]
Hi, I just solved this !
It might be some kind of hacky fix, but I followed the commit referenced at the end of this [issue](https://github.com/NativeScript/NativeScript/issues/5033).
Open the file located under node_modules/tns-core-modules/ui/editable-text-base/editable-text-base.android.js and go to the line 81.

There is an "if" statement, where you have to add the second condition and remove the return true.
It must look like this after these changes : 


```
if (actionId === android.view.inputmethod.EditorInfo.IME_ACTION_NEXT   || actionId === android.view.inputmethod.EditorInfo.IME_ACTION_PREVIOUS) {
      owner._onReturnPress();
}
return false;
```


I don't know if this is the most clean way to solve this but it works pretty well under {N} 3.3.0

**Comment by NickIliev** [comment]
Closing as with NativeScript 4.0.0 I am not experiencing this issue (however the returnType next is causing [this one](https://github.com/NativeScript/NativeScript/issues/4461))

**Comment by edusperoni** [comment]
This still happens in iOS, but works fine in Android, so this should probably be reopened.

**Comment by edusperoni** [comment]
@NickIliev ?

**Comment by NickIliev** [comment]
@edusperoni use the [nativescript-iqkeyboardmanager](https://www.google.bg/search?q=nativescript-iqkeyboard&rlz=1C1CHBF_enBG781BG781&oq=nativescript-iq&aqs=chrome.1.69i57j35i39j0l2.3606j0j7&sourceid=chrome&ie=UTF-8) plugin to handle the keyboard on iOS

**Comment by edusperoni** [comment]
@NickIliev I already do, but it only adds the arrows, the next button still needs to be handled by a function telling it to focus the next input

**Comment by EddyVerbruggen** [comment]
@edusperoni Have you wrapped the input fields as shown [here](https://github.com/tjvantoll/nativescript-IQKeyboardManager#grouping-related-textfields-previous--next-buttons)? That _should_ make focusing work. If not, please share a repo reproducing the issue.

**Comment by edusperoni** [comment]
I have, as soon as I get to a computer I'll post my current code

**Comment by EddyVerbruggen** [comment]
OK, but please push it to a repo or NativeScript Playground. A snippet won't help much.
