### ISSUE TITLE
How to format the input of a TextField to currency etc, while typing?

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#2839]
**Platform:** iOS
**TNS:** 2.3.0

I want to set up a formatter into the TextField view. If a user types in a price, it should be formatted to a specific currency and other stuff such as spacing, dots and commas.

I am unable to do this by hooking an observable event to the TextField's initial text property, which is an observable. If I do so and change the TextField's value, it doesn't actually change in the UI. `console.log` works fine though.

Sample below:

**XML**
```xml
<Page navigatingTo="navigatingTo">
  <TextField text="{{ price, price }}" id="priceValue" />
</Page>
```

**JS**
```js
var Observable = require("data/observable").Observable;
var numeral = require("numeral"); // JS plugin to format numbers

var page, pageData = new Observable({
  price: ""
});

var eventFlag = false; // To prevent propertyChange event from firing endlessly

exports.navigatingTo = function(args) {
  page = args.object;
  page.bindingContext = pageData;
  
  pageData.on("propertyChange", function(e) {
    if(e.propertyName === "price" && !eventFlag) {
      eventFlag = true;
      
      var value = numeral(e.value).format("$0,0.00");
      e.value = value;
      console.log(e.value);
      
      eventFlag = false;
    }
  });
};
```

The console logs `$1,234.00` if I type `1234`. But the TextField itself is still `1234`.

**Comment by tsonevn** [comment]
Hi @NordlingArt, 

You could use [nativescript-maskedinput](https://www.npmjs.com/package/nativescript-maskedinput) plugin, which provides such a functionality ad allows you to restrict  the input. For further help you could review the plugin's [demo](https://github.com/bthurlow/nativescript-maskedinput/tree/master/demo).

I hope this helps.

**Comment by NordlingArt** [comment]
@tsonevn - I tried it, but it crashes. I'll ask the plugin author, but I figured it might have something to do with `ui/builder`:

`
file:///app/tns_modules/ui/builder/builder.js:162:56: JS ERROR Error: Building UI from XML. @file:///app/views/test/test.xml:5:5
	 ↳UIColor.blackColor is not a function. (In 'UIColor.blackColor()', 'UIColor.blackColor' is an instance of UIColor)
`

**Comment by tsonevn** [comment]
Hi @NordlingArt,
The given error has been caused due to the fact that  with Xcode 8 some of the methods now are properties. While the author fix this in the plugin you could replace the following line in `node_modules/nativescript-maskedinput/maskedinput.ios.js` file the following line:

`this.ios.textColor = this.ios.textColor ? this.ios.textColor.colorWithAlphaComponent(0.22) : UIColor.blackColor().colorWithAlphaComponent(0.22);`
 with 
`this.ios.textColor = this.ios.textColor ? this.ios.textColor.colorWithAlphaComponent(0.22) : UIColor.blackColor.colorWithAlphaComponent(0.22);`

Further you should keep in mind that in case you delete `node_modules`  folder you should replace the this code again.


I hope this helps

**Comment by NordlingArt** [comment]
Thanks @tsonevn, will fix!
