### ISSUE TITLE
Question: nested view load sequence

### ISSUE THREAD

**Issue by ryc16** [NativeScript/NativeScript#2856]
I have a bit complex view and I use nested xml as following. Why file3.xml pageLoaded() is loaded before file3.xml pageLoaded() this causes viewmodel not yet created.

```
file1.xml
<Page loaded="pageLoaded">
   <ns:file2 />
</Page>

file2.xml
<GridLayout loaded="pageLoaded">
   <ns:file3 />
</GridLayout>

file3.xml
<GridLayout loaded="pageLoaded">
</GridLayout>

file2.ts
export var viewModel;
export function pageLoaded(args) {
  // viewmodel created here and assign to variable viewModel
}

file3.ts
export function pageLoaded(args) {
   // want to use viewModel from file2
}
```

 Is there any way to reference the viewModel from file2 on the nested file3?

**Comment by NickIliev** [comment]
Hello @ryc16 

I guess your question has a type because in **_"Why file3.xml pageLoaded() is loaded before file3.xml"_** you have double **file3**.

Now, as a suggestion to what might be your issue I can suggest the following:
In nested component the bottom nested one will load first , then the middle one and finally the page.
However, in your example, you are using the same loading function for all your components! Perhaps, it would serve you better to attach different load function with its specific logic for your nested components to avoid duplicated execution of a code and side effects from that matter.

file1.xml
<Page loaded="pageLoaded">
   <ns:file2 />
</Page>

file2.xml
<GridLayout loaded="middleGridLoaded">
   <ns:file3 />
</GridLayout>

file3.xml
<GridLayout loaded="bottomGridLoaded">
</GridLayout>

**Comment by ryc16** [comment]
@NickIliev, Sorry for the typo. Thanks for the important information where nested one will load first. My question is why not load parent first. The main issue is about to share the parent viewmodel. Because of nested one load first, we can't get the parent viewmodel on loaded events. But I think there are different way to approach. For me, I think I will create new viewmodel for nested one.
