### ISSUE TITLE
Provide DOM-like methods for interacting with the visual tree

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#287]
Personally I find interacting with the visual tree in NativeScript to be very difficult. There are [a handful of methods](https://docs.nativescript.org/ApiReference/ui/core/view/README.html) defined on the view, but that's about it.

I would like to suggest that several methods be added to the [`Page` class](https://docs.nativescript.org/ApiReference/ui/page/Page.html) as almost every app is going to use a `loaded` event which gives them easy access to that object. Here are a few examples of the type of things I'd like to do given this XML:

```xml
<Page loaded="loaded">
	<Button cssClass="foo" />
	<Label cssClass="bar" />
</Page>
```

* `getElementsByTagName()`

```js
exports.loaded = function(args) {
	var page = args.object;
	page.getElementsByTagName("button"); // returns [Button]
}
```

* `getElementsByClassName()`

```js
exports.loaded = function(args) {
	var page = args.object;
	page.getElementsByClassName("foo"); // returns [Button]
}
```

* `querySelector()` and `querySelectorAll()` (at least match on tag name, class name, and id)

```js
exports.loaded = function(args) {
	var page = args.object;
	page.querySelectorAll(".bar"); // returns [Label]
}
```

``` js
exports.loaded = function(args) {
	var page = args.object;
	page.querySelector("label"); // returns Label
}
```

* `remove()`

``` js
exports.loaded = function(args) {
	var page = args.object;
	page.querySelector("label").remove();
}
```

* `classList`

``` js
exports.loaded = function(args) {
	var page = args.object;
	var label = page.querySelector("label");
	label.classList.add("someOtherCssClassName");
	label.classList.remove("someOtherCssClassName");
	label.classList.toggle("someOtherCssClassName");
	label.classList.contains("someOtherCssClassName"); // true
}
```

These are all DOM methods that will feel very familiar to web developers, and will make managing the visual tree substantially easier than it is today. For example at the moment I'm trying to remove all elements with a certain class name. What I want to do is this:

```js
exports.loaded = function(args) {
	var page = args.object;
	page.querySelectorAll(".icon").forEach(function(icon) {
		icon.remove();
	})
}
```

I actually can't figure out how to to get at all elements with a certain class name using the APIs that are available in NativeScript today. Anyways, this is just a suggestion and I'm sure it could be tricky to implement, but I thought I'd toss the feature request out there.

Thanks.

**Comment by RangerMauve** [comment]
On one hand, the view models that NativeScript provides should in theory be powerful enough to make these apis not necessary. But I agree that it would be very useful to have.

**Comment by hshristov** [comment]
@tjvantoll What are you planning to do with these method?
I'm asking because as @RangerMauve said we are targeting MVVM pattern where you have all your logic placed in viewmodels and don't mess with the visual tree.
If you could point to some use cases it will help us evaluate this request.

**Comment by dbbk** [comment]
@hshristov I've had to do it a lot in cases where there are no CSS abstractions. For instance,

`logo.ios.font = UIFont.fontWithNameSize("HelveticaNeue-UltraLight", "30");`

**Comment by tjvantoll** [comment]
My primary use case is making visual changes, usually showing and hiding, but also for other visual things. To give a specific case, suppose I click a button and I want to show two different things on the screen—maybe I click an “Edit” button and I want to show delete icons and a `<Label>` with some text.

I could use MVVM to implement that with code that looks something like this:

```xml
<Button text="Edit" tap="{{ functionThatTogglesTheDeletingFlag }}" />

<Label text="Deleting elements will remove them permanently, and..."
  visibility="{{ deleting ? 'visible' : 'collapsed' }}" />
<Button text="Delete"
  visibility="{{ deleting ? 'visible' : 'collapsed' }}" />
```

This works, but it feels very verbose. (I'd rather have a `visible` attribute that accepted a boolean, but that's for a separate feature request.)

More generically, as a web developer it feels strange for me to put presentation code in my markup. If I were implementing this sort of thing on the web I'd add a CSS class to each element I wanted to show/hide under these conditions, and run something like this:

```js
$(".deleting").toggle();
```

Or more likely [I'd apply a class name to the parent, and use that to drive my display logic](http://tjvantoll.com/2014/05/01/using-semantic-html-to-drive-display-logic/). Regardless these class-name-based approaches are a lot more flexible. I think no matter how many abstractions we provide people are always going to need the ability to go off the rails—@dbbk's use case being one example. I think animations are another good one. In order to animate elements you'll almost certainly need the ability to reference them to kick the animation off. If I want to select all my delete icons to animate them in it'd be great to use `querySelectorAll()` to do that.

**Comment by valentinstoychev** [comment]
Thanks @tjvantoll! I want to go one step further and ask you what would be the ideal API that you want to see in {N} regarding this scenario. Can you please list the methods/properties you would like to see available? Then we can decide if we can make them available by default or available as part of a *shim* module for web developers. Thanks!

**Comment by tjvantoll** [comment]
Hey @valentinstoychev. I just expanded my original comment to include all the useful-in-a-NativeScript-context APIs that came to my head. If I think of any more I'll add them to the list.

**Comment by atanasovg** [comment]
We need to be extra careful when bringing DOM APIs to the cross-platform layer to avoid any potential confusion that the {N} visual tree resembles a full-blown Web DOM.

**Comment by akorchev** [comment]
I second all suggestions that @tjvantoll made. Making the {N} API the same as the JavaScript DOM will bring a lot of value IMHO. The JavaScript web developers know and understand the DOM API and will feel very comfortable if {N} provides the same. This will be the ultimate skill reuse.

More suggestions:
- getAttribute/setAttribute
- className
- addEventListener, removeEventListener
- getElementById

I think all of those have 1:1 mapping with the {N} visual tree and already have corresponding methods - we just need to change the names (deprecate the current ones).

The argument about using MVVM vs modifying the visual tree is valid. However we can go only as far as to recommend it as best practice. There are people who don't believe in data-binding and will want to avoid it.

**Comment by tenorok** [comment]
In my opinion it is very good idea! :+1: 
Especially `classList`, because today we should manipulate with `className` string, that is so ugly.

**Comment by tenorok** [comment]
I wrote little module which can help for work with classes list in {N}: https://github.com/tenorok/cnclasslist

For convenience we can create interface:

```js
import * as view from 'ui/core/view';
import { CNClassList } from 'cnclasslist';

export interface CLView extends view.View {
    classList?: CNClassList;
}
```

And now we can use usual API of classList:
```js
import { CNClassList } from 'cnclasslist';
import { CLView } from '../../views/CLViewInterface';

var picker: CLView = page.getViewById('picker');
picker.classList = new CNClassList(picker);
picker.classList.add('picker_visible');
picker.classList.remove('picker_visible');
picker.classList.contains('picker_visible');
```

**Comment by NathanaelA** [comment]
@tjvantoll -- I haven't published my internal development JS plugin yet; but I support almost that entire list (& a several other things like Performance.now()) totally seamlessly (i.e when the library loads it auto-attaches to all the prototypes of the relevant items).   

I currently support the majority of your list;   global & element based getElementsByTagName, getElementById, getElementsByClassName, and the entire element.classList.* -- I haven't bothered to to implement querySelector/QSAll since the use case isn't currently their for as simple of screens that are designed for the mobile.  Now maybe I'll need those when I get more complex screens, but QS/QSA actually is a lot of work to properly support...

If you want a copy; let me know, and I'll try and get it into a repo..  No docs; but it is just a simple require to make everything go... :grinning:

**Comment by tjvantoll** [comment]
@NathanaelA 🎉

Yeah, let me know when it’s in a repo. I’d love to try it out 😀

**Comment by toddanglin** [comment]
@NathanaelA +1

I was just talking internally about how helpful it would be to have a "jQuery-like" framework grow on top of NativeScript to provide things like helper methods for animation effects. Something like:

`$(element).slideUp("slow");`

Not sure how closely it would need to follow/emulate the jQuery syntax, especially since there is no need to handle multiple underlying browser JavaScript implementations. Just need something that can provide convenient access to helper methods. Maybe it can even be:

`[element].[libraryName/Alias].[namespace].method`
SO...
`myButton.$.effects.slideUp("slow")`

Either way, sounds like you may have a great start. Would love to see your work on GitHub and try to support the idea of growing/popularizing your library. OR maybe this is a new library just focused on effects/animation helpers. :)

**Comment by NathanaelA** [comment]
Oops, forgot to respond in this thread, I dropped my master-technology helper file up in my repos last week.   https://github.com/nathanaela/nativescript-master-technology -- but if we want to start creating a library like "nativescript-dom" or some other name; I have no issue helping get it started.   

I just figured that some of the smaller routines that I have abstracted out of the programs that I have been working on and used many times but aren't big enough to turn into a plugin people might be able to use also... :grinning:

**Comment by NathanaelA** [comment]
After some discussion with @tjvantoll I released this as an actual full plugin called 
**[nativescript-dom](http://github.com/nathanaela/nativescript-dom)** - I pulled out everything that was dom related out of my nativescript-master-technology helper file and put in into the dom plugin.

**Comment by ludwiktrammer** [comment]
May I ask why this ticket was finally closed? I can't find any reasoning posted here. I still feel that methods like 'getVieByClassName` and `querySelector`would still be extremely helpful...

**Comment by NathanaelA** [comment]
@ludwiktrammer - Probably was closed because my plugin `nativescript-dom` has getViewBy* -- in most cases if there is a plugin that handles it then the bug report is closed.  The core is designed to be smaller and plugins are used to fill in any additional functionality.  ;-)  

See http://plugins.nativescript.org for the thriving plugin eco-system.

**Comment by ludwiktrammer** [comment]
@NathanaelA 
I've been seriously thinking about installing your plugin for a couple of months now, but every time I open the website and read "You do NOT need to keep a reference to it; and you only need to load it once. It will automatically attach its methods to all the proper classes in the NativeScript library making it act as if they are built in." this seems so icky to me that I decide against it.

The other thing: I'm totally for delegating functionality to plugins... but those methods really seem like a core functionality to me. Everybody needs to be able to interact with DOM and classes on elements. I think the fact that those methods are a core part of JavaScript in browsers partially proves this...

Also, the fact that you've felt a need to do the thing that felt "icky" to me, i.e. monkey patch those methods into core classes, also strongly suggests that that is where they actually belong.

**Comment by NathanaelA** [comment]
@ludwiktrammer - Well, some plugins I would agree should be built in.     However, since I've been around since the beginning; I can tell you,  that typically if the community has done something that works well; the NativeScript team WILL NOT spend any time duplicating or consuming the  functionality.   Hence the closed feature request.   ;-)     In fact; they just recently took some code out of core and turned it into a plugin.   Plugins are the official way to add features to the code base.   (http://plugins.nativescript.org)

`nativescript-dom` is one of the few plugins I do use in I think all of my apps that are more than a simple test.      So I wouldn't mind if it was built in, but I doubt that will happen as they want to leave the core code smaller and the less code they have the less they have to maintain.  ;-)

Lets makes sure we have our definitions correct; my understanding of the definition of monkey patching is to typically you take a reference to an `existing` function and then `replace` that existing function via assigning my own function to that function.  

So if you use the definition of monkey patching as I understand it;  I don't monkey patch anything for ns-dom!     I also try and define my plugins to be forward compatible and even have checks to see if the getElementBy* exists already and if so, I won't install my version.  ;-)     With as many plugins as I have, the less things that break during each runtime upgrade the better it is for me.  

To be globalized; I just add the functions to the global namespace.  ;-)     I do also add the getElementBy* to the `view.prototype` (again not really monkey patching). Out of all my plugins (around 40) I only have a couple that I have to monkey patch to make work.    Monkey patching is brittle, and I prefer not to do so if I don't have to.  ;-)

One final note; I can't say for sure that ns-dom won't ever be added to the core; as I've already had a couple of my plugins get added to core.  But I tend to think since it hasn't been added for almost 2 years, it probably never will be...    
 
Please note you can do everything I do inside my ns-dom plugin manually; it is just `getElementById("someName").classList.toggle("hidden", shouldIadd);` is way way easier than the 20 odd lines of code you would have to do it manually.    ;-)

(ns-dom adds not only the getElement*, but also the .classList. ability and a couple others).

**Comment by toddanglin** [comment]
@NathanaelA @ludwiktrammer Never say never. :)

As Nathan said, this issue was closed as a solution to the original request became available. But if there are good reasons and strong interest in seeing this re-evaluated as a "core" API, that can certainly be done.

For a start, I'd suggest submitting this as "Feature Request" so we can aggregate community interest/votes in the feature to help with backlog planning: https://nativescript.ideas.aha.io

It will also help if we can identify the reasons this makes a good addition to Core. There is no doubt these APIs are more convenient for web developers, so I agree that is a great reason out of the gate. Just need to make sure they are "essential" to Core.

**Comment by ludwiktrammer** [comment]
@toddanglin Awesome! I created the idea here: https://nativescript.ideas.aha.io/ideas/NS-I-165
