### ISSUE TITLE
Does nativescript support normal xml markup like <date> and another issue

### ISSUE THREAD

**Issue by Shtayo** [NativeScript/NativeScript#2904]
Does Nativescript support regular xml markup like `<date>2004/05/17</date>`?

If it does please tell me as soon as possible.

If it doesn't then I have another issue (If it does you can still answer this one), I am trying to create a dropdown menu that opens a small list. Here is the following code: 

main-page.xml:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" onNavigatingTo="onNavigatingTo">
  <StackLayout orientation="vertical" class="dropdown">
      <Label>Click on the button to open the dropdown menu.</Label>
      <button onclick="myFunction()" class="dropbtn">Dropdown</button>
        <StackLayout id="myDropdown" class="dropdown-content">
            <Label text="Sup" />
            <Label text="Man" />
        </StackLayout>
  </StackLayout>
</Page>
```

main-page.js:
`var observable = require("data/observable");
var frameModule = require("ui/frame");
 

function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

exports.onNavigatingTo = onNavigatingTo;`

main-view-model.js:
`var Observable = require("data/observable").Observable;

function createViewModel() {
    var viewModel = new Observable();
    viewModel.counter = 42;
    viewModel.message = getMessage(viewModel.counter);

    viewModel.onTap = function() {
        this.counter--;
        this.set("message", getMessage(this.counter));
    }

    return viewModel;
}

exports.createViewModel = createViewModel;`

However when I run the app, it tells me this:
```
Oct 15 20:13:32 Frankys-MacBook-Air backboardd[908]: SecTaskCopyDebugDescription: Test[1104]
Oct 15 20:13:32 Frankys-MacBook-Air backboardd[908]: SecTaskCopyDebugDescription: Test[1104]
Oct 15 20:13:32 Frankys-MacBook-Air backboardd[908]: SecTaskCopyDebugDescription: Test[1104]
Oct 15 20:13:32 Frankys-MacBook-Air backboardd[908]: SecTaskCopyDebugDescription: Test[1104]
Oct 15 20:13:32 Frankys-MacBook-Air backboardd[908]: SecTaskCopyDebugDescription: Test[1104]
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: assertion failed: 15G1004 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 1   0x10403e379 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 2   0x1046ab51e ffi_closure_unix64_inner
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 3   0x1046abed2 ffi_closure_unix64
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 4   0x105295cd3 -[UIViewController view]
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 5   0x10516bfb4 -[UIWindow addRootViewControllerViewIfPossible]
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 6   0x10516c69d -[UIWindow _setHidden:forced:]
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 7   0x10517e180 -[UIWindow makeKeyAndVisible]
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 8   0x1046abd2d ffi_call_unix64
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: 9   0x117f80950
Oct 15 20:13:32 Frankys-MacBook-Air Test[1104]: file:///app/main-page.js:11:40: JS ERROR ReferenceError: Can't find variable: onNavigatingTo
Oct 15 20:13:32 Frankys-MacBook-Air com.apple.CoreSimulator.SimDevice.5055F1B8-FBED-4AFB-B075-C08858003549.launchd_sim[891] (UIKitApplication:org.nativescript.Test[0xce09][1104]): Service exited due to signal: Segmentation fault: 11
```

Please solve this issue as soon as possible.

Thank You! :)

**Comment by tsonevn** [comment]
Hi @Shtayo,
Thank you for your interest in NativeScript.

I reviewed your case, however `<date>` markup has been not supported in NativeScript.  
Regarding to your second issue I found that the problem has been caused due to mistake of event name.  You should use `navigatingTo="onNavigatingTo"` instead of `onNavigatingTo="onNavigatingTo"`. 
Further more in NativeScript to handle click event for the button you should use `tap` event handler instead of `onclick` You could also review the NativeScript [documentation](https://docs.nativescript.org/cookbook/ui/button) , where has been described, how to use `Button` component. For further help you can also review the [Getting Started Guide](http://docs.nativescript.org/tutorial/chapter-0) . In case you would like to use drop-down menu in your app, you could use `nativescript-drop-down` plugin. Here you will find [example](https://github.com/PeterStaev/NativeScript-Drop-Down/tree/master/sample) .

I hope this will help.
