### ISSUE TITLE
Missing ui/styling/style.d.ts in tns-core-modules

### ISSUE THREAD

**Issue by williamltb** [NativeScript/NativeScript#2906]
Hi,

I found out that the ui/styling/style.d.ts is missing from the node_modules/tns-core-modules in Nativescript 2.3.0

I have to manually add the style.d.ts from the repository to use the Styler

**Comment by tsonevn** [comment]
Hi @williamltb,
I reviewed your case and create new project with `tns create <sample_project> --template typescript` and found that the `style.d.ts` file exist in ` node_modules/tns-core-modules/ui/styling`. The problem could be related to some network issues, while downloading the `modules`. Could you try to create new project using `tns create <sample_project> --template typescript` , to run `tns run <platform_name>` and verify if the file exist.

**Comment by williamltb** [comment]
Hi @tsonevn,

Can you look at this pull request I submitted https://github.com/PeterStaev/NativeScript-Drop-Down/pull/42 . travis-ci reports the same issue as well.

**Comment by tsonevn** [comment]
Hi @williamltb,
 I am still unable to reproduce such an error, this could be caused due to some error in the `references.d.ts` file. check , whether you have set the correct path to `style.d.ts` file in your pull request. Another option is to try to download in external folder `tns-core-modules` and to reference them to the `travis` build, to verify whether this has not been caused due to old modules version.

Regards, 
@tsonevn

**Comment by williamltb** [comment]
Hi @tsonevn,

I think there is another questions facing similar issues as well.
https://github.com/NativeScript/NativeScript/issues/2806

Thanks
@williamltb

**Comment by PanayotCankov** [comment]
That's because it is private.
In theory we are not ready to support the current state of the API for the general public.

To use it either clone the .d.ts in your plugin and reference it from references.d.ts, or clone the NativeScript repo, `npm link` in the tns-core-modules in the NativeScript repo, `tsc` in the root of the `NativeScript` repo and then go to your plugin/app directory, do a `npm link tns-core-modules`. This will add the tns-core-modules from source with access to the private APIs. You should be able to add the style.d.ts of the modules in reference.d.ts.

At some point we will polish its API and promote it to public.
