### ISSUE TITLE
Support border-color, border-width, and border-radius

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/NativeScript#291]
I'm using several `<Border>` elements in my app, and I'm finding that I duplicate the `borderWidth` and `borderColor` attributes all over the place. I would like to be able to use CSS properties `border-width` and `border-color` (and `border-radius`) to visually change `<Border>` UI elements instead of the corresponding attributes. This would allow me to do `<Border cssClass="mySuperAwesomeBorder">` to keep my code DRY.

Also it's a bit unfortunate that we need to have a separate UI element for borders rather than a CSS-only implementation, but I'm guessing the native implementations require them to be in the visual tree. Is that correct?

Thanks.

**Comment by zephraph** [comment]
Couldn't it hypothetically be injected into the visual tree if that's the case though?

**Comment by enchev** [comment]
Hey folks,

Actually in both [iOS](https://github.com/NativeScript/NativeScript/blob/border-backgroundImage/ui/border/border.ios.ts) and [Android](https://github.com/NativeScript/NativeScript/blob/border-backgroundImage/ui/border/border.android.ts#L33) is technically possible to define border (color, width, corner radius, etc.) on any element, this however is not possible in Windows (Universal, WinRT, etc.) and that is why we've decided to provide Border element. 

Exactly because of this reason border properties are not exposed as CSS where we want to keep only properties available for all UI components. 

Let me know what you think!

Thanks

**Comment by bundyo** [comment]
In my opinion border styles should be **supported on any element** as it should be in CSS. **Additionally** provided Border element can cover Windows and could be easily deprecated when/if Windows supports such borders on any element.

Currently the Border element is one of the major PITAs in NativeScript and was the sole reason I had to implement a custom Button element for one of the templates. The reason for this is that the Border element is a **container** and if you want to **hide** it in a specific platform, you need to change the XML markup to achieve it...

**Comment by tjvantoll** [comment]
@bundyo++

I'll just add that coming from a web development perspective it feels *very* weird to put this presentation code in my markup. The XML component also makes my app far less configurable. For instance in my app I only want the borders to be in place on iOS, and with XML only I'm going to need some really messy code to make that happen, whereas with CSS it would be trivial. The same is true if you want to use a different border color, border radius, border width, etc, which I would think would be incredibly common.

I can understand wanting to fully support Windows, but currently we're letting a Windows limitation provide a degraded experience for iOS and Android. I'm strongly in favor of supporting border styles in CSS.

**Comment by zephraph** [comment]
I agree with both of the comments above. Any styling aspect should be left to the style sheet, regardless of compatibility. If there's an incompatibility, I would log a warning from the cli tool when building that particular platform saying that style x is not supported on platform y. Otherwise I would just ignore it.

**Comment by ligaz** [comment]
Actually on Windows [those properties](https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.control.aspx#properties) are present on the `Control` class. I'm also voting for moving them to our `View` class which is our base representation of a UI component.

**Comment by valentinstoychev** [comment]
For the next milestone 1.2 we will perform a research to see if there is a performance friendly way to introduce this in a cross-platform way.

**Comment by hshristov** [comment]
Related to #191
