### ISSUE TITLE
I recommend a Gitter room (like angular 2 guys)

### ISSUE THREAD

**Issue by born2net** [NativeScript/NativeScript#2930]
The success of any project, especially large scale as NativeScript requires good users support.
I recommend we open an official Gitter chat room and would also recommend someone from the NativeScript should always be assigned to support users (just like the ng2 do)

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by Pip3r4o** [comment]
@born2net couldn't help but notice the follow up issue, I'd like to pitch in - the suggestion's not bad at all, but we already have a dedicated slack channel where people from the nativescript community help one another, NativeScript devs, like myself, also stop by from time to time to lend a hand. We do support with actual issues here, in github, because they are recorded in github, and others facing similar issues can easily refer to them, tracking progress on issue resolution also happens here.

Slack -> https://nativescriptcommunity.slack.com

**Comment by born2net** [comment]
perfect tx!!!
joining and closing!!!
regards
