### ISSUE TITLE
Android: ActivityIndicator Ignores Width and Height Properties

### ISSUE THREAD

**Issue by vbresults** [NativeScript/NativeScript#2960]
### Tell us about the problem
ActivityIndicator on Android ignores the width and height observable properties and they have no effect, it is locked into some fixed size.

### Which platform(s) does your issue occur on?
Android (5.1)

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.3.0
- Cross-platform modules: 2.3.0
- Runtime(s): tns-android

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```xml
<activity-indicator width="32" height="32" color="{{ layout.color.value }}" busy="{{ loading ? 'true' : 'false' }}" visibility="{{ loading ? 'visible' : 'collapsed' }}" />
```

**Comment by NickIliev** [comment]
Hey @vbresults 

I have tested the described situation on my side and it works as expected.
Here is [the sample application](https://github.com/NickIliev/NativeScript-issues/tree/master/NativeScript/issue_2960_js) I have created in order to test the **ActivityIndicator**.
I am able to successfully change the width and height for Android app.
e.g.
```
<ActivityIndicator width="122" height="32" id="ai" busy="true" />
```

Perhaps, some other styles are overriding your desired dimensions!?

As a side note you can try to chenge the width and height with native code.(behind ActivityIndicator in Android it is [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar.html))
e.g.

```
var activityindicator = page.getViewById("ai");
var params = new android.widget.LinearLayout.LayoutParams(300, 10);
activityindicator.android.setLayoutParams(params);
```

**Comment by vbresults** [comment]
@NickIliev It was a child of a stacklayout which itself was a child of a gridlayout, and the stacklayout didn't have it's own width/height fixed so the activity indicator stretched as it should.  Not a bug, thank you (:
