### ISSUE TITLE
Error on adding feathersjs module

### ISSUE THREAD

**Issue by kaurag007ph** [NativeScript/NativeScript#3005]
I having this issue when I tried adding feathersjs module to my newly created nativescript project during build. I haven't add any code yet. Why I encountered the issue below even I haven't any code on my project?

![image](https://cloud.githubusercontent.com/assets/5998974/19925061/53bf0b70-a129-11e6-81bf-04785f865cba.png)

**Comment by hdeshev** [comment]
Hi @kaurag007ph 

I tried this on a project using an `npm install feathers --save` command before trying to run the project and the app ran fine.

Could you post your full `tns create` and `npm install` commands? It'd be great if you put your project somewhere on github too.

**Comment by kaurag007ph** [comment]
Hi @hdeshev 

Installing `feathers` alone is also working to me, but when I added their other module, thats the time I encountered the issue. My current project now is based on ngnative and firebase, I'm just exploring feathers if its working on nativescript so that I could create my own backend server and replace firebase. Below is my step reproducing the issue.

`tns create feathersclient --ng`
`tns platform add android`
`tns install feathers feathers-hook feathers-socketio feathers-authentication`
`tns build android`

**Comment by hdeshev** [comment]
I reproduced the problem:
- Android's AAPT tool tries to compress all files using the following scheme: myfile.js -> myfile.js.gz
- That breaks if you already have a compressed file sitting next to your original file. AAPT aborts the build to avoid overwriting the file.

In your `featherjs` case, it's caused by a depencency, `bcryptjs`. It ships with the `node_modules/bcryptjs/dist/bcrypt.min.js.gz` file. Delete it, remove and add the platform, and the problem will go away.

Ideally you should `npm install` your server-side packages in a separate directory or list them as dev dependencies, so that nativescript-cli doesn't try to copy them to the mobile device.

Related to NativeScript/nativescript-cli#1802
