### ISSUE TITLE
Event Propagation

### ISSUE THREAD

**Issue by tobydeh** [NativeScript/NativeScript#3006]
I have a container view that listens for a Touch event and inside the container is a label with a Tap event listener.

The parent containers Touch event is triggered when a user taps the Label. Also, the parent containers Touch event is triggered before the child labels Tap event.

There doesn't seem to be a way for the Labels Tap event listener to stop the event propagating to the parent containers TouchAction handler. Also, it wouldn't be much use if their was because they're fired in the wrong order.

**Comment by NickIliev** [comment]
Hey @tobydeh 

Can you provide the actual code behind the container and label you are using (and also some details on what platform you are experiencing this case)?

The thing is that it really depends on what container you are using and how you are placing your label as this is crucial on how the label's dimensions will be rendered.(and from there what event will be triggered.)
Take this example where everything works as expected - tapping the Label is triggering only the label tap and touching the container is triggering only the touch event.
```
  <!-- toucing container triggeres onTouch; tapping the Label triggers onTap->
  <GridLayout width="300" height="400" backgroundColor="red" touch="onTouch">
    <Label height="100" text="Tap the label" tap="onTap" backgroundColor="green" />
  </GridLayout>
```

However the same example but without predefined size of the label will have totally different result because the Label will be stretched on the whole container

```
  <GridLayout width="300" height="400" backgroundColor="red" touch="onTouch">
    <!-- only onTap is triggered -->
    <Label text="Tap the label" tap="onTap" backgroundColor="green" />
  </GridLayout>
```


The code behind is just logging the events
**_page.ts_**
```
export function onTouch(args: EventData) {
  console.log("onTouch");
}

export function onTap(args: EventData) {
  console.log("onTap");
}
```

**Comment by tobydeh** [comment]
It's a lot of code so ill just include the relevant parts.

The main view is a custom component which extends GridLayout, after is has finished drawing itself it registers an event handler on a child called container which is another grid layout:

```
this.container = new gridLayout.GridLayout()
this.container.className = "nav-container"
this.addChild(this.container)
this.container.on(gestures.GestureTypes.touch, function (args) {
if(args.action == gestures.TouchAction.down) {
    console.log('down')
}
else if(args.action == gestures.TouchAction.move) {
    console.log('move')
}
else if(args.action == gestures.TouchAction.up) {
    console.log('up')
}
```

Later on, the component adds a child view to the container using builder.load:

```
var v = builder.load({
    path: 'some/path',
    name: 'childView'
})
this.container.addChild(v)
```

The child view xml:

```
<ScrollView style.backgroundColor='#ffcc00'>
<Label text="Test" tap="onTap" />
</ScrollView>
```

The child view js:

```
function onTap(args) {
    console.log("label tap")
}

exports.onTap = onTap
```

Some background: The component is a TabBar which displays tabs at the bottom of the screen, the container listening for the touch event is a place holder to load in the views when the user selects a tab. The reason I'm listening for the touch event is to detect when the user slides the screen laterally which displays the previous view underneath, and if they slide far enough navigates back to the previous screen. The behaviour copies the iOS Navigation behaviour.

When a user taps a button or interacts with other elements inside the child views I don't want the touch event listener on the container to fire.

**Comment by NickIliev** [comment]
@tobydeh indeed this behaviour is by design. Still, you can use native solution to resolve this issue.

```
class MyGestureRecognizerImpl extends NSObject {
    public func: () => void;

    public recognize(recognizer: UIGestureRecognizer): void {
        if (this.func) {
            this.func();
        }
    }
    public static ObjCExposedMethods = {
        "recognize": { returns: interop.types.void, params: [UIGestureRecognizer] }
    };
}

var target = new MyGestureRecognizerImpl();
target.func = () => { console.log("HELLO"); }

var target2 = new MyGestureRecognizerImpl();
target2.func = () => { console.log("HELLO FROM THE OTHER SIDE"); }

export function navigatingTo(args: EventData) {
  let page = <Page>args.object;
  st = page.getViewById("st");
  let gesture = UITapGestureRecognizer.alloc().initWithTargetAction(target, "recognize");
  st.ios.addGestureRecognizer(gesture);

  let lbl = page.getViewById("lbl");
  let gesture2 = UITapGestureRecognizer.alloc().initWithTargetAction(target2, "recognize");
  gesture2.cancelsTouchesInView = true;
  lbl.ios.addGestureRecognizer(gesture2);
}
```

**Comment by tobydeh** [comment]
@NickIliev Thank you. Could you please example the code example to me? I'm sure the magic lies in cancelsTouchesInView on the labels GestureRecognizer - why does it require me to make my own MyGestureRecognizerImpl?

Can I leave the touch code on my container view as it is, and just create a tap handler for all labels and buttons that cancelsTouchesInView?

Also, how would this be implemented on android?

Thanks again for your help this far.

**Comment by tobydeh** [comment]
@NickIliev ignore my previous comments, this behaviour is correct. When I place a Button with a tap event inside a GridLayout with a touch event the tap event fires correctly and the touch event fires after a slightly longer press which is fine.

However, when I add the touch event to my container dynamically using container.on() and the child button is loaded through builder.load the behaviour seems broken. The button disables itself aster a long press, What is the correct way for me to add the listeners dynamically?

**Comment by NickIliev** [comment]
Hey @tobydeh the code sample above is needed only for IOS as this behaviour we need to change only in iOS (where the event propagation is different from the one in Android). You should not experience this scenario in Android.

**Comment by ycherniavskyi** [comment]
For NativeScript newcomers (as me) I want to explain iOS by design behavior of gestures recognizer and why @NickIliev [solution](https://github.com/NativeScript/NativeScript/issues/3006#issuecomment-258077802) to overcome this problem works.

Currently NativeScript add [UIGestureRecognizerDelegate](https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate) delegate to all created recognizer, which allowed to recognize gestures simultaneously by always returning `true` form [gestureRecognizer(_:shouldRecognizeSimultaneouslyWith:)](https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate/1624208-gesturerecognizer) method (see [`UIGestureRecognizerDelegate` implementation](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/gestures/gestures.ios.ts#L18) in `gestures.ios.ts` file).

And as you can see @NickIliev [solution](https://github.com/NativeScript/NativeScript/issues/3006#issuecomment-258077802) does not add any delegate that is why those manually created gestures recognizer does not recognize simultaneously.

That is it (but it took me some hours to understand it 🥺).

**Comment by ludcila** [comment]
Hi @NickIliev,

I have recently upgraded a project and have noticed that the behavior you describe for your first Android example in https://github.com/NativeScript/NativeScript/issues/3006#issuecomment-257856937 has changed. Tapping the label now also triggers the touch event on the parent container.

Here is the code: https://play.nativescript.org/?template=play-tsc&id=On2f1X

In my app, one of the situations is similar to this one: https://play.nativescript.org/?template=play-ng&id=u2mhmf&v=3. Tapping on a child element also triggers the tap on the parent element, except for the case where the child is a Button. This used to behave differently in previous versions of Nativescript, where it would trigger the event only on the child element. Is this new behavior the correct one or is it a bug? Why is the behavior different for a Button?

**Comment by NickIliev** [comment]
@ludcila thanks for bringing that one into my attention. It seems that indeed there is a change in the event propagation on Android. I've also noticed that the issue is discussed here and [a workaround](https://github.com/NativeScript/NativeScript/issues/6606#issuecomment-450008324) is provided

Here is[ your Playground with the workaround applied](https://play.nativescript.org/?template=play-ng&id=u2mhmf&v=4) - meanwhile I will investigate further and post as soon as I have more insights.

**Comment by Lelelo1** [comment]
I am having the same problem with an `Image` inside a `AbosluteLayout`. The same event goes to both Image and AbsoluteLayout. And it its happening on both iOS and Android.
