### ISSUE TITLE
CSS not applied when view is loaded with builder and added to native view

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#3054]
I am loading a view with builder, getting the native representation and adding it to a native view programmatically (Android ViewPager and iOS UIPageViewController), but CSS is not being applied.

TemplateSelector OnSelectTemplate:

```
var page = frame.topmost().currentPage;

var view = builder.load({
    path: "~/Views/Slides",
    name: "slider-view",
    page: page
});

view.bindingContext = bindingContext;

return view.
```

Android ViewPager Adapter:

```
instantiateItem (container: android.view.ViewGroup, position: number)
{
    var item = this._owner.itemsSource.getItem(position);
    var view = this._owner.templateSelector.OnSelectTemplate(position, item);
    var obj = <any>view;
    obj._onAttached(application.android.currentContext);
    container.addView(obj.android);
    obj.onLoaded();
    return obj.android;
}
```

iOS UIPageViewController DataSource:

```
public createViewController(position: number) : UIViewController 
{
    var item = this.itemsSource.getItem(position);
    var view = this.templateSelector.OnSelectTemplate(position, item);
    var obj = <any>view;
    var viewController = new ViewContainer();
    viewController.view = obj._view;
    obj.onLoaded();
    return viewController;
}
```

Any ideas?

**Comment by alexrainman** [comment]
@NickIliev this one is critical. Can you help?

**Comment by NathanaelA** [comment]
@alexrainman - is this TNS 2.3.0 or the new 2.4.0 @next version?

**Comment by alexrainman** [comment]
@NathanaelA 2.3.0

**Comment by NathanaelA** [comment]
@alexrainman I think this must be an issue in your code...    These are created using the builder and several other techniques and css works great; in fact at this point all the color boxes are totally css generated.    This example was done in 2.3.0.    

![nativescript-dl2](https://cloud.githubusercontent.com/assets/850871/20313875/e99811f2-ab1d-11e6-8376-1b0652106d86.gif)

![nativescript-dl3](https://cloud.githubusercontent.com/assets/850871/20313852/d485efbe-ab1d-11e6-9c3a-ab37f6e9d9f2.gif)

**Comment by alexrainman** [comment]
What i can be doing wrong? Loading the view with builder and specifying page parameter as required. When i add a css file with the same name as the xml file, i get exception asking to provide page parameter in builder. I add page parameter using this:

```
var page = frame.topmost().currentPage;
```

Then i add the view native representation to the native widget (Android ViewPager and UiViewController in iOS) without luck. CSS is not applied.

You can take a look at the whole thing in the repo of the plugin https://github.com/alexrainman/nativescript-carousel-view

**Comment by NathanaelA** [comment]
The issue is simply a mis-understanding of what the builder does.  The builder does NOT load any CSS.   It only takes the XML file and builds a view layout from it.    So that is why your CSS is not working, you aren't actually loading it.  :grinning:

**Comment by alexrainman** [comment]
Thats why the question. How i supose to load css?

**Comment by alexrainman** [comment]
And thats not what i read about loading components with builder. It says you have to provide page option for css to be applied, dont?

**Comment by NathanaelA** [comment]
Then at least I totally misunderstood you -- the title says "CSS not applied when view is loaded with builder and added to native view" and your comment was "but CSS is not being applied" -- The issue isn't that css isn't being applied; any existing CSS already loaded will be applied.     (And to re-iterate no matter what you read anywhere else -- the builder does NOT deal with CSS at all; the styling system deals with the CSS and styles  :grinning: )

Your issue is you don't know how to apply new CSS.   Take a look at my nativescript-theme plugin.  I apply css dynamically when they enable or switch themes.  That should be able to get you going...

**Comment by alexrainman** [comment]
I know the builder does NOT deal with CSS, i know the styling system deals with the CSS and styles :) but, if i create a css file with same name as the xml file i am loading with builder, {N} is telling me this:

```
Error: CSS file found but no page specified. Please specify page in the options! (/Users/alexrainman/Desktop/NativeScript/CarouselView/node_modules/tns-core-modules/trace/trace.js:160:25)
```

Then after providing page parameter, no console message but css is not applied.

**Comment by NathanaelA** [comment]
@alexrainman - Interesting, I never saw that code in the builder before.  Had to search for your error message.   ;-)   Learned something new...       I'll have to play with it...  :-)      Unfortunately this is something I can't really help you with since I didn't know it even existed.  :grinning:     Looking at the code it appears for a glance that it should work as long as you are giving it the root page (which depending on how & when you are getting it, might not be the correct page value)

1. Are you sure your css isn't malformed or anything?
2. Are you sure a different rule isn't more specific and overriding the rules you think aren't working?

**Comment by alexrainman** [comment]
CSS seems to be ok as i copied .message class from default template. Doing a simple thing just for testing so im not overriding any rule.

Also, i have only one page where the carousel is being rendered.

I have this issue and another with constrains in iOS that i need to solve to make the plugin perfect ;)

**Comment by alexrainman** [comment]
@NathanaelA @NickIliev any help on this?

**Comment by alexrainman** [comment]
:(

**Comment by NathanaelA** [comment]
@alexrainman - I'm sorry, I can't provide any more help on this issue; I am totally swamped with contract work so I don't have the spare time to dig into why it isn't working.  If they don't get you going in a couple weeks; ping me and I might have some spare time to take a look at it by then.

@NickIliev is paid by Telerik to do support, and so I know he is busy dealing with all the repos, making test cases and answering StackOverflow; I'm sure he will be along soon to try and help.  :grinning:

**Comment by NickIliev** [comment]
Hey @alexrainman 

I am sorry for the delay in my answer - I 've missed your ping somehow!
I was able to take a look at your code along with @PanayotCankov  and what is happening is that you are using **_onAttached** instead of **_addView** and this way you ar not receiving your expected context.

In order to have access to your child context remove [this line](https://github.com/alexrainman/nativescript-carousel-view/blob/d94fcf3b1a89fc0c6298061a10f15e92cfeb8379/carousel-view.android.ts#L214)
and add the following instead:
```
this._owner._addView(obj);
```

Now the context will be received and the CSS will be applied as expected. You can take a look at the layout implementation to notice how **_addView** and **_removeView** is used in our source.

**Comment by alexrainman** [comment]
@NickIliev this works nice in both platforms. Thanks. Now i need help with the latest roadblock i have. I already implemented a class to add page indicators in Android but i have an issue in iOS. The piece of code i am providing works in Xamarin and native but doesn't works in {N} https://github.com/NativeScript/NativeScript/issues/3052

**Comment by alexrainman** [comment]
@NickIliev this creates another problem, as i suspected. _addview seems to add the view to the {N} view itself or something i don't understand. Take a look at the screenshot. If i add margin between pages, you can see a view behind the scenes.

<img width="311" alt="screen shot 2016-12-01 at 9 16 51 am" src="https://cloud.githubusercontent.com/assets/3793554/20798979/6156758c-b7a6-11e6-8cd5-b946d63fa604.png">

Weird.

**Comment by alexrainman** [comment]
As a temp fix i added this

```
this._viewPager.setBackgroundColor(android.graphics.Color.parseColor("#FFFFFFFF"));
```
