### ISSUE TITLE
Does "ui/builder" can inflate html(Nativescript-Angular2)?

### ISSUE THREAD

**Issue by filldike** [NativeScript/NativeScript#3084]
I tried to make custom view, in Nativescript-angular2 Project.
(Tested on "tns-core-modules": "2.3.0")
like below.

```
//in main.ts
export class MyLayout extends StackLayout {
public myvar: string = "myvar";
    constructor() {
        var source = `
                    <StackLayout>
                        <WrapLayout>
                            //some other stuff
                            <Label [text] = 'myvar' ></Label>
                            <Button text="ON" (tap)="onTap()"></Button>
                            //some other stuff
                        </WrapLayout>
                        //some other stuff
                    </StackLayout>
                    `
        this.view = builder.parse(source, this);
        this.addView(this.view);
        //do oher stuff
    }
    public onTap(args) {
        console.log("onTap button, changetext");
        myvar = "name chaged";
    }
}

```
but label shown nothing & tap event does not working.

but as i tried
`<Label text = "{{myvar}}"></Label>`
and it is working. (of course was data was binded)

So I assumed "ui/builder" is not for Nativescript-angular2 layouts.
If I`m right can i get one for Nativescript-angular2?

**Comment by NickIliev** [comment]
Hey @filldike 

The builder module is intended for use in NativeScript core applications and is obsolete for N+Angular2 application. Instead of using the "ui/builder" you can create your custom component logic with Angular-2 logic.

You can use as reference [this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/lazy-load-routes/app/ui-category/ng-directives/create-custom-directive) which shows how to implement your own custom directive in N+Angular2 application and this directive is used to create custom component. Of course, this is only one possible approach - you can take a look at some other sceanrios with angular directive s [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/lazy-load-routes/app/ui-category/ng-directives).

Closing as duplicate to [https://github.com/NativeScript/nativescript-angular/issues/442](https://github.com/NativeScript/nativescript-angular/issues/442)

**Comment by alexrainman** [comment]
@NickIliev tried to take a look at the example but the link is dead. Can you re-upload?

**Comment by NickIliev** [comment]
@alexanderfilipov I have updated the links as they were refering to non-existen branch.

One additional note for your question - keep in mind that all of your angular components can be reused with their selector.

More details on that [here](http://learnangular2.com/components/) but basically you do the following:
```
import { Component } from '@angular/core';

@Component({
  selector: 'my-component',
  template: '<Button (tap)="sayMyName()"></Button >'
})
export class MyComponent {
  constructor() {
    this.name = 'Max'
  }
  sayMyName() {
    console.log('My name is', this.name)
  }
}
```
and then when you need to use this component `<my-component></my-component>`
In order. that to work properly make sure that you do not have components with identical selector name.
