### ISSUE TITLE
application-settings setNumber/getNumber return wrong values

### ISSUE THREAD

**Issue by 3rror404** [NativeScript/NativeScript#3109]
ApplicationSettings seems to behave strangely when dealing with numbers over a certain size in Android. I haven't yet tested in iOS.

As you can see in the example below, the value I am saving to Application Settings with `.setNumber()` is different from the value returned by `.getNumber()`

```
var dNow = Date.now();

console.log(dNow); // => 1479390381732
Settings.setNumber('dNow', dNow);
console.log(Settings.getNumber('dNow')); // => 1479390396416
```

Setting a smaller number such as 14793903 works as expected. 

I can work around this by storing the value as a string but it would be better if we could store large numbers with confidence.

```
┌──────────────────┬───────────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version       │ Latest version │ Information      │
│ nativescript     │ 2.3.0                 │ 2.4.0          │ Update available │
│ tns-core-modules │ 2.5.0-2016-11-17-4794 │ 2.4.0          │ Up to date       │
│ tns-android      │ 2.3.0                 │ 2.4.0          │ Update available │
│ tns-ios          │ 2.3.0                 │ 2.4.0          │ Update available │
└──────────────────┴───────────────────────┴────────────────┴──────────────────┘
```

**Comment by NickIliev** [comment]
Hey @3rror404 

Indeed, the case you are pointing out is reproducible - however, it is by design.
The reason for this is that application-settings module is using [shared preferences for Android](https://developer.android.com/reference/android/content/SharedPreferences.html).
Now there are three options to save number in shared preferences
- putFloat
- putInt
- putLong
As you can see the only option that allows the user to save the number with floating point is putFloat. The minus of that method is that as you can see it can not handle big numbers. If we use putLong instead we will break all the people that wants to handle numbers with floating point. So we chose to use putFloat.

If you need to save larger numbers I recommend that you use [setString](https://docs.nativescript.org/cookbook/application-settings#set-and-get-string-value) instead and pass your large number as a string.

**Comment by 3rror404** [comment]
Yeah I'm using setString now. 

I can't see any mention of this in the documentation. Perhaps a note should be added?

Would it be possible in a future release to give us the ability to set specific types? Something like `setFloat()`, `setInt()` and `setLong()`?

**Comment by NickIliev** [comment]
Hey @3rror404 

I have updated the documentation section for setNumber with [this PR](https://github.com/NativeScript/NativeScript/pull/3131).

As for your suggestion about the additional methods, you can create your own PR and become a part of the contributors. All you need is to sign the CLA and create your PR.

For example, how the android part of setNumber is implemented you can see [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application-settings/application-settings.android.ts#L63-L69) and at [this link](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application-settings/application-settings.ios.ts#L52-L57) you will find the iOS implementation. based on that logic you can add the additional methods and if your PR pass the tests and is approved it will become part of the next official release.

**Comment by 3rror404** [comment]
Thank @NickIliev. I'll take a look at implementing this when I get some time 👍
