### ISSUE TITLE
Internal Error after an Invalid Bundle

### ISSUE THREAD

**Issue by shinzao** [NativeScript/NativeScript#3152]
Hi,

I received an mail from Apple saying : 
Invalid Bundle - A nested bundle contains simulator platform listed in CFBundleSupportedPlatforms Info.plist key

I've tried to follow this : https://github.com/telerik/nativescript-ui-samples/issues/123 but since this moment, I get an Internal Error when I want to publish again.

So, this is my 2 files that I modified : 
![capture d ecran 2016-11-22 a 22 47 14](https://cloud.githubusercontent.com/assets/12793476/20543536/8233eff6-b106-11e6-8c71-feec9914af86.png)
![capture d ecran 2016-11-22 a 22 46 58](https://cloud.githubusercontent.com/assets/12793476/20543537/82364cb0-b106-11e6-860d-08c7735177dd.png)

And this is the Internal error : 
<img width="715" alt="capture d ecran 2016-11-22 a 22 46 28" src="https://cloud.githubusercontent.com/assets/12793476/20543569/9c2f0012-b106-11e6-828a-b23738ab5ddb.png">

I've tried to restore like before my files but I get the same error.
I follow this way : 
1) Modify my files
2) `tns build ios`
3) `tns publish ios MyItunesAccount MyPassword`
4) I get the error

It's my  first time I deploy an app on the store. I've tried to modify the version of my build (because I already have an incorrect version on my Itunes Connect but I don't think I have to change that for the moment ? : 
<img width="1145" alt="capture d ecran 2016-11-22 a 22 47 57" src="https://cloud.githubusercontent.com/assets/12793476/20543779/6e34bdea-b107-11e6-9df3-8bcdbf968ed9.png">
)

This is my differents versions : 
node.js version : v5.9.0
xCode version: v8.1
OS : OS X El Capitan v10.11.6
NativeScript CLI version : 2.4.0
TNS version : 2.4.0

Thanks in advance

**Comment by shinzao** [comment]
For anyone who get the same error, just replace this : 
`<key>CFBundleSupportedPlatforms</key>
<array>
<string>iPhoneSimulator</string>
</array>`

with this

`<key>CFBundleSupportedPlatforms</key>
<array>
<string>iPhoneOS</string>
</array>`

in all Info.plist of your framework !

**Comment by NickIliev** [comment]
Hey @shinzao 

With the nex **xCode** some changes were introduced by Apple in the publishing process.
I;ve researched your error and I think it is closely related [to the one logged here](https://github.com/telerik/nativescript-ui-samples/issues/123) and also discussed in the Apple developers forums [here](https://forums.developer.apple.com/thread/62261).

Basically in some of your inflo.plist files you have the following key (which is no longer accepted by Apple for release)
```
<key>CFBundleSupportedPlatforms</key>
<array>
<string>iPhoneSimulator</string>
</array>
```

Change the value to `<string>iPhoneOS</string>` and you should be able to resubmit your app succsessfully.As mentined in the logged thread where the issue is discussed the possible files you should be looking for are:

- ./lib/iOS/TelerikAppFeedback.framework/Info.plist
- ./lib/iOS/TelerikUI.framework/Info.plist
- ./lib/iOS/TNSWidgets.framework/Info.plist

**Comment by Daxito** [comment]
@NickIliev I have the same issue and I was using the workaround you mentioned, modify the ./lib/iOS files but since NS 2.5 that folder is gone or not auto-generated and I can't find those files any more, any advice?

**Comment by Daxito** [comment]
Just for the record, the issue was the nativescript-telerik-ui-pro, it was version 1.4.*, I had to be 1.6.1 for NS 2.5.1
