### ISSUE TITLE
How to write the code for this page

### ISSUE THREAD

**Issue by dhanalakshmitawwa** [NativeScript/NativeScript#3183]
![registration](https://cloud.githubusercontent.com/assets/10844041/20656300/1704689c-b551-11e6-8c7f-454660d65624.PNG)
![registered](https://cloud.githubusercontent.com/assets/10844041/20656304/1d9957b2-b551-11e6-88eb-8ab40bad9b1b.PNG)

Please let me know the code for the upper image.
I tried this code
			<GridLayout rows="50" columns="*,*" class="textFieldborders m-10">
				<Label row="0" col="0" text="Mobile Number" class="bg-primary testing"></Label>
				<StackLayout class="input-field form " row="0" col="1">
					<TextField class="input" text="9618717947" style="font-size:15;"></TextField>
				</StackLayout>

			</GridLayout>
			<GridLayout rows="35" columns="*,*" class="textFieldborders m-10">
				<Label row="0" col="0" text="Mobile Number" class="bg-primary testing"></Label>
				<StackLayout class="input-field form " row="0" col="1">
					<TextField class="input" text="9618717947"  style="font-size:15;"></TextField>
				</StackLayout>

			</GridLayout>

**Comment by NickIliev** [comment]
Hey @dhanalakshmitawwa 

This repository is for logging and resolving issues - the better place for common UI and UX techniques would be [stackoverflow](http://stackoverflow.com/questions/tagged/nativescript) .

In order to create a form looking like the first one you should apply some[ CSS styling](https://docs.nativescript.org/ui/styling) to your Label and TextField.
I've noticed that you have applied two CSS classes for you label (**bg-primary** and **testing**) so you can either modify them or add third class.
What you should do is to apply **padding** to your label text in order to have proportional alignment for your label content.
e.g.:
```
<Label text="Mobile Number" padding="20" frontSize="20"></Label>
```

You can also apply border-width and border-radius to create rounder corners.
.rounded {
```
   border=width: 1;
   border-color: black;
   border-radius: 10
}

```

**Comment by dhanalakshmitawwa** [comment]
Thank you for reply
