### ISSUE TITLE
App settings

### ISSUE THREAD

**Issue by rumkin** [NativeScript/NativeScript#3212]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

iOS

- CLI: 2.4.0
- Cross-platform modules: "version": "2.4.0"
- Runtime(s): "tns-ios": {
      "version": "2.4.0"
    }
- Plugin(s): 
"dependencies": {
    "nativescript-theme-core": "^0.2.1",
    "tns-core-modules": "2.4.0",
    "uuid": "^3.0.1"
  },

How does application-settings should works in ios emulator? When I close application (from app menu double cmd+shift+H) and run it again app settings are empty.

Code example:
```javascript
viewModel.switched = appSettings.hasKey('switched')
      ? appSettings.getBoolean('switched')
      : false; // Always false
```

**Comment by NickIliev** [comment]
Hello @rumkin 

The **application settings** module. is using NSUserDefaults for iOS and is working just as in the native environment. There are also no differences in the expected behavior under simulator or real device.This means that if you save a value (e.g with `setBoolean("switched", true)`) it will be preserved until the application is re-installed or re-deployed in this simulator. Just like in real device those settings will be saved unless you uninstall the application.


However, notice that each time you run `tns run ios` your application will be re-build and this will reset your previous saved settings.

**Comment by rumkin** [comment]
Ok. I will test it again using `run` instead of `livesync` command.

**Comment by NickIliev** [comment]
Hey @rumkin I meant that using `run' or any other CLI command will always reset your data if the application needs to be redeployed.

**Comment by rumkin** [comment]
@NickIliev I understand. But now I found that my switch doesn't trigger change event which should set the app settings key.

Is it proper to set `propertyChange`:
```xml
<Switch checked="{{ switched }}" propertyChange="switchPropertyChange"/>
```

```javascript
viewModel.switchPropertyChange = function(change) {
        if (change.propertyName === 'checked') {
            this.set('switched', ! this.switched);
            appSettings.setBoolean('switched', this.switched);
        }
    };
```

**Comment by rumkin** [comment]
Problem solved. It was unclear to me that onPropertyChange should be exported from app.js. Not from bindingContext. App settings works properly.

@NickIliev thanks for response.
