### ISSUE TITLE
Using Pure NPM Modules In NativeScript

### ISSUE THREAD

**Issue by putraxor** [NativeScript/NativeScript#3287]
I'm using NPM modules in Nativescript but it seems not compatible, otherwise my node-js is running well without problem. 
The error has vary things, modules not found and many more.
How to make pure npm module compatible to nativescript?

**Comment by NickIliev** [comment]
Hello @putraxor 

Which NPM packages you are trying to use in your NativeScript?
It really depends on the modules you a trying to use. As most of the NPM modules are web-related by design they also bring with them web-related dependencies that require for example DOM handling. This simply won't work directly in NativeScript where there is no such thing as DOM. So one approach is [to create your own plugin](http://docs.nativescript.org/plugins/plugins). 

There is already a great selection of [plugins for NativeScript in npm](https://www.npmjs.com/search?q=nativescript) from which you can choose.

**Comment by putraxor** [comment]
@NickIliev I'm using instagram-private-api from https://github.com/huttarichard/instagram-private-api

**Comment by NickIliev** [comment]
@putraxor it relies on dependencies like **_socks5-https-client_** which won't work in NativeScript. Overall this is a wrapper meant to be used in browser.

**Comment by putraxor** [comment]
@NickIliev What about **util** module from NodeJS, is it supported by NativeScript by now?
My code doesn't work using it even when I add manually from npm

**Comment by NickIliev** [comment]
Well I tried it and it works on my side
`npm install util --save`

TypeScript
```
import * as util from "util";

var myString = "ala bala";
console.log(util.isString(myString));
```
