### ISSUE TITLE
WebRTC Support

### ISSUE THREAD

**Issue by mrcmrc** [NativeScript/NativeScript#330]
Nativescript supports webrtc? I want implement webrtc in my nativescript app, but i dont know that's nativescript supports webrtc

**Comment by RangerMauve** [comment]
NativeScript doesn't come with it out of the box, but it should be possible to use something like [openWebRTC](https://github.com/EricssonResearch/openwebrtc) with it.

**Comment by mrcmrc** [comment]
I do not know if this is the right place for this question , some bad hesitate implementation OpenWebRTC and NativeScript ?

**Comment by RangerMauve** [comment]
I've been investigating integrating WebRTC with NativeScript since I first saw it. The WebRTC implementation used in Google Chrome can be found [here](http://www.webrtc.org/native-code) as an alternative to OpenWebRTC. The issue is that it's all c code and isn't very easy to convert to TypeScript with NativeScript's tools. OpenWebRTC has libraries in Java and Objective-C so that should be easier to convert into something that NativeScript can easily understand.

**Comment by mrcmrc** [comment]
OK, thanks

**Comment by devna13** [comment]
Did you have any luck with the conversion ?

**Comment by RangerMauve** [comment]
I personally haven't had time to look into it, and have since seen people implement it in alternatives to NativeScript like [React-Native](https://github.com/oney/react-native-webrtc)

**Comment by dotnetdreamer** [comment]
Hi there, any luck on this ? anyone ?

**Comment by triniwiz** [comment]
For future ref you can check out this [plugin](https://github.com/triniwiz/nativescript-webrtc)
