### ISSUE TITLE
how can i use third jar in android ? and this jar have a view

### ISSUE THREAD

**Issue by minjunlan** [NativeScript/NativeScript#3412]
how can i use third jar in android ? and this jar have a view, i want to use map sdk (not google) ,how can i use it ?

**Comment by tsonevn** [comment]
Hi @minjunlan,
Thank you for your interest in NativeScirpt.

To be able to use JAR file in NativeScript project, you should expose the needed  features. Regarding to that you could create your own UI Plugin. For further help you could read the NativeScript docs on [how to do data marshaling and using the android runtime](http://docs.nativescript.org/runtimes/android/overview.html). Then you could read more on what is [Android Plugins Infrastructure](https://docs.nativescript.org/runtimes/android/plugins/plugins) and how to create UI Plugin in the below-attached articles.

[UI Plugin](http://docs.nativescript.org/plugins/ui-plugin)

[Creating a plugin using third party code](http://fluentreports.com/blog/?p=167).

Regarding to the topic, you could also use [nativescript-mapbox](https://github.com/EddyVerbruggen/nativescript-mapbox) instead of [nativescript-google-maps-sdk](https://www.npmjs.com/package/nativescript-google-maps-sdk) and [nativescript-googlemaps](https://www.npmjs.com/package/nativescript-googlemaps).

Hope this helps

**Comment by minjunlan** [comment]
@tsonevn thank you very much , i make my ui plugin . nativescript is very nice , i can use html technology quickly Design UI .
