### ISSUE TITLE
Adding an item to a pre-scrolled ListView will make the ListView blank

### ISSUE THREAD

**Issue by nikolay-diyanov** [NativeScript/NativeScript#344]
Using the sample-PhotoAlbum project with sample local (rather than Backend) data.

Load a ListView a few image items, using the following template:

ListView items="{{ photoItems }}" row="0" >
			ListView.itemTemplate>                
              GridLayout>
                  Image imageSource="{{ itemImage }}" row="0"/>
              /GridLayout>               
			/ListView.itemTemplate>
/ListView>

The images will be loaded as they should. Now scroll down the ListView a little and on a button tap, add few more items. The ListView will go blank (white) until you scroll it just a little which will make it show its image content again.

**Comment by nsndeck** [comment]
Rendering problem is more noticeable when `estimatedRowHeight` value differs significantly from the actual (measured) `rowHeight`. Due to some issues in iOS 7 actual row measure is not taken into account. It seems that issue is fixed with iOS 8. So for the time being priority of this issue is set to minimum.
