### ISSUE TITLE
Why come up with a different http request api?

### ISSUE THREAD

**Issue by vjeux** [NativeScript/NativeScript#35]
I wonder why you implemented a new API to do http request instead of picking one that already exist? Also, require('http') conflicts with node require('http') and doesn't have the same interface.

- NativeScript http: http://docs.nativescript.org/ApiReference/http/HOW-TO.html
- Node http: https://nodejs.org/api/http.html
- XMLHttpRequest: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest
- Fetch: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

**Comment by vjeux** [comment]
Same question for local-settings instead of localStorage?

- NativeScript local-settings: http://docs.nativescript.org/application-management.html#persist-and-restore-application-settings
- LocalStorage: https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

**Comment by ligaz** [comment]
Hey @vjeux, very good questions :smile: 

### Http
The core of the NativeScript HTTP API is the [request](https://github.com/NativeScript/cross-platform-modules/blob/master/http/http-request.d.ts#L5) function which has similar signature to the one found in Node.js but returns a Promise rather than taking a callback as argument. We took an early architectural decision to use Promises in all our async APIs so strictly following the Node's API was no go for us. Also the Node's http module has a lot of server side baggage with it like `createServer` and friends.

Regarding the XMLHttpRequest we have provided a [shim](https://github.com/NativeScript/cross-platform-modules/blob/master/http/http.ts#L35) for it so all libraries using it will feel at home.

About the fetch API - it was not emerging as standard when we designed our API but we can consider adopting it. Currently a [pollyfill](https://github.com/github/fetch) can be used.

### LocalStorage
Our current local settings API doesn't feel very JavaScript-_ish_ and we should definitely simplify it by mimicking the LocalStorage API. We already [got](https://twitter.com/ligaz/status/573969081377882113) that feedback :smile_cat: 

### Requiring Node.js built-in modules
We definitely want to enable to _somehow_ require Node's built-in modules. What we currently have in mind is a [RequireJS plugin](http://requirejs.org/docs/plugins.html) style of requiring: `require("node!http")` but be aware that this is just loud thinking for now.

**Comment by pitaj** [comment]
@ligaz 

> `require("node!http")`

Sounds good to me.

**Comment by enchev** [comment]
We've decided to rename our current module "local-settings" to "application-settings", to avoid any confusion in the future, and we will add additional "local-storage" module with the same API as [WebStorage](http://dev.w3.org/html5/webstorage/#storage-0).

**Comment by ligaz** [comment]
@enchev Are we going to expose a `localStorage` instance on the `global` object the way we do it for `console`, `XMLHttpRequest`, etc.?

**Comment by enchev** [comment]
@ligaz Yep, we can expose it!

**Comment by ligaz** [comment]
Hey @vjeux,

Last week we released version 1.2 of NativeScript which introduces the `fetch` API. It currently supports text, JSON and FormData contents. ArrayBuffer and Stream are about to follow as well.

**Comment by valentinstoychev** [comment]
It is here - http://docs.nativescript.org/ApiReference/fetch/HOW-TO.html

**Comment by vjeux** [comment]
Sweet :)

**Comment by enchev** [comment]
I've created new issue for [binary data support in both fetch and xhr](https://github.com/NativeScript/NativeScript/issues/570) and I'm closing this.
