### ISSUE TITLE
ImageButton widget

### ISSUE THREAD

**Issue by cime** [NativeScript/NativeScript#356]
Please add ImageButton control

Android: http://developer.android.com/reference/android/widget/ImageButton.html
iOS: https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIButton_Class/#//apple_ref/occ/instm/UIButton/setBackgroundImage:forState:

If possible it would be nice to have image+text button, where you can place text + image on the left/right/bottom/top.

**Comment by manijak** [comment]
This is highly missed.

**Comment by enchev** [comment]
Hey folks,

Since {N} 1.2 release we have full support for background-image, background-repeat, background-attachment and background-position CSS properties and in my opinion you can create now very easily buttons with text + image. Furthermore when we add support for CSS pseudo-classes you will be able to use different images for different button states. 

Do we really need special image button component? Do you see anything missing in the CSS support?

Let me know what you think!

Thanks

**Comment by cime** [comment]
I'm fine with background-image support.
But it would be nice if button widget supported custom content instead of just text.
Something like:

    <Button>
       <StackLayout>
           <Image ... />
           <Label ... />
           <SomeThing.... />
       </StackLayout>
    </Button>

**Comment by enchev** [comment]
Please use [Button.formattedText](https://github.com/NativeScript/NativeScript/issues/1813#issuecomment-201218952) and/or some of the [supported CSS properties](http://docs.nativescript.org/ui/styling#supported-properties) like (background-image, background-repeat, background-position and background-size) to achieve this.

**Comment by jr76** [comment]
Anyone know how to get the border to show up when a background image is used? As soon as I add a background image to a button, the border disappears. It's as though the image covers the border.

**Comment by matiasvilches** [comment]
`
<StackLayout class="..." @tap="..." orientation="vertical">
          <Image src="..." />
          <Label text="test" verticalAlignment="center" />
</StackLayout>
`

Referencia: https://stackoverflow.com/a/44475428
