### ISSUE TITLE
IOS set actionBar height

### ISSUE THREAD

**Issue by michaelchan1992** [NativeScript/NativeScript#3583]
I am trying to set height for the actionBar in IOS through css property but it doesn't seem to work. For android it's working well. I'm new to IOS development, is there anyway to accomplish this?

css:
```
.acBar{
 height: 100;
}
```
javascript:
```
page.getViewById("acBar").ios.setBackgroundImageForBarMetrics(img, UIBarMetricsDefault)
var rect = page.getViewById("acBar").ios.frame;
page.getViewById("acBar").ios.sizeThatFits(CGSizeMake(60, 375))

//OR		
rect.size.height = 60;
page.getViewById("acBar").ios.frame = rect;
```
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
http://stackoverflow.com/questions/20439167/is-there-a-way-to-change-the-height-of-a-uinavigationbar-in-storyboard-without-u
http://stackoverflow.com/questions/32006330/programmatically-change-height-of-navigation-bar-in-swift

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.4.4
- Runtime(s): tns-android 2.4.1, tns-ios 2.4.0
- Plugin(s): "tns-core-modules": "^2.4.4"

**Comment by NickIliev** [comment]
Hey @michaelchan1992 the styling of ActionBar has some limitations as mentioned [here](https://docs.nativescript.org/ui/action-bar#styling). The reason is that we would want the Actionbar to be as native as possible and changing the height would break the concept of what Apple has in mind for this element under iOS. 

Currently, only background-color and color are supported CSS properties for the Actionbar.
