### ISSUE TITLE
IOS: application launch event on ios not passing remote notification intent

### ISSUE THREAD

**Issue by sud80** [NativeScript/NativeScript#3656]
## Please, provide the details below:
The launch event on ios passes only the local notification information and not the remote notification information.
The current code go generate the launch event in (/tns-core-modules/application/application.ios.ts) is as follows:
```
 const args: LaunchEventData = {
            eventName: launchEvent,
            object: this,
            ios: notification.userInfo && notification.userInfo.objectForKey("UIApplicationLaunchOptionsLocalNotificationKey") || null
        };
```
ios variable is populated only in case of local notification. Any specific reason why only local notification is passed and not remote notification. As per document it says launch options, so  would it be better to pass the userInfo object itself? 

In my application I want to handle the remote notification intent to handle certain cases. 

### Which platform(s) does your issue occur on?
iOS

**Comment by PanayotCankov** [comment]
Create and register a custom AppDelegate similar to this:
https://github.com/FireSt-dead/thesis/blob/master/GitCraft/app/main.ts#L26
Instead of the applicationHandleOpenURL there, handle `applicationDidReceiveRemoteNotificationFetchCompletionHandler(app, userInfo, completionHandler)`. You may need to edit the Xcode project to enable push notifications and background handling from the capabilities panel. I am not sure this will be useful, but the nativescript-plugin-firebase handles it here: https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/firebase.ios.js#L44
