### ISSUE TITLE
events inside web workers

### ISSUE THREAD

**Issue by m3l7** [NativeScript/NativeScript#3695]
I'm trying to listen to an event inside a web worker, specifically I'm trying to set error handling for bluebird (http://bluebirdjs.com/docs/api/error-management-configuration.html).

It seems that addEventListener is not available, nor as a global variable nor in self object.

Is it possible to listen to events inside web workers?

**Comment by ivanbuhov** [comment]
Hi @m3l7 

NativeScript doesn't support `addEventListener` API but everything you can achieve with `addEventListener` can be achieved by using `onmessage` API. Here is an example:

```
onmessage = function(msg) {
    console.log("Message received from main thread: " + msg.data);
    postMessage(" - Hello main! I am worker!");
}
```

More detailed explanation on NativeScript workers you can find in [Using Workers in NativeScript Guide](https://www.nativescript.org/blog/using-workers-in-nativescript-to-execute-javascript-on-background-threads).

**Comment by m3l7** [comment]
Hello,
Bluebird actually fires an event ("unhandledRejection"), which is not caught by onmessage.

The problem is that promises unfortunately "swallow" errors and don't throw them. The only way I can handle errors is to catch that event and throw the error

**Comment by ivanbuhov** [comment]
@m3l7 In the time of writing my first answer I couldn't understand the issue, so I was answering to the wrong question. 
Regarding your question - the `addEventListener` method of the global object (the `window` object) in the context of the browser is not part of the JS engine. It is actually added by the browser. Since NativeScript is not a `WebView` it lacks the `addEventListener` method. This is also the case with nodeJS, where the Bluebird guys use the `process` object to trigger their special events, because (like in NativeScript) there is no event triggering mechanism on the global object. Since NativeScript is not browser nor nodeJS, there is no `global.addEventLister` nor `process.addEventListener` methods which means that Bluebird is not 100% supported in NativeScript environment. However, making Bluebird works in 100% in NativeScript environment is not in our hands.

P.S.: As a last resort, you can try listening for events like this:
```
global.onunhandledrejection = function(reason, promise) {
};
global.onrejectionhandled =  function(promise) {
}
```
 I can't guarantee that this will work, but depending on how the event subscribing logic is implemented in Bluebird, it may work properly in NS environment. The best check is to try it out.

**Comment by m3l7** [comment]
thanks for the support.
I've just tried settings the functions in globals: no luck.

I will ask to bluebird devs
