### ISSUE TITLE
Android: return key listener executes code twice

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#3776]
When listening to a return key press on android, it executes the code twice. Naturally, only one instance of listener is set:
```
appPage.getViewById("login-password").on(textFieldModule.TextField.returnPressEvent, function(eventData: any){
    console.log("event happened");
});
```
Result: 
```
event happened
event happened
```

**Comment by NickIliev** [comment]
Hey @dxshindeo 
I've tried to reproduce your behavior but to no avail. (the event fires only once)
[Here you can find the basic project](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_3776) I've used for test. Can you please test it at your side and let me know if you still reproduce this issue?

Also, if the issue is reproducible with more specific situation or API level can you please share with us all the needed information (code snippet and infop about the testing API level)
