### ISSUE TITLE
SearchBar onClear firing even when it was not clicked.

### ISSUE THREAD

**Issue by dzfweb** [NativeScript/NativeScript#3813]
I've a Searchbar, and the "onClear" function is firing even when it was not clicked, at the load of the page.

`<SearchBar #sba hint="Pesquisar..." [text]="searchFilter" (clear)="onClear()"></Searchbar>`

what am i doing wrong?

**Comment by NickIliev** [comment]
@dzfweb I guess you are experiencing this on Android.
The **clear** event is fired when loading because you have a value attached for **text** (via binding).
Even if the value is empty string the clear event is still fired to ensure that any other previously set values are reset. If you want to remove this specific behavior, you can simply declare your SearchBar without the text property and bind to it later via your code behind (for example using the NativeScript loaded event for SearchBar).
e.g.
```
<SearchBar row="0" #sb  (loaded)="onSearchLoaded($event)" (clear)="onClear()"  (submit)="onSubmit(sb.text)"></SearchBar>
```
and in your code behind you can directly set and get teh value of your SearchBar text the following way:
```
    public onSearchLoaded(args: EventData) {
        var search = <SearchBar>args.object;
        search.text = this.searchPhrase;
    }

    public onSubmit(value) {
        this.myItems = new ObservableArray<DataItem>();
        let searchValue = value.toLowerCase();
        if (value !== "") {
            for (let i = 0; i < this.arrayItems.length; i++) {
                if (this.arrayItems[i].name.toLowerCase().indexOf(searchValue) !== -1) {
                    this.myItems.push(this.arrayItems[i]);
                }
            }
        }
    }

    public onClear() {
        console.log("onClear");

        this.searchPhrase = "";
        this.myItems = new ObservableArray<DataItem>();

        this.arrayItems.forEach(item => {
            this.myItems.push(item);
        });
    }
```

**Comment by dzfweb** [comment]
Thank you @NickIliev 
i followed your instructions and it worked.
