### ISSUE TITLE
FlexboxLayout doesn't measure and layout properly long labels

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#3834]
The following case fails on iPhone 6 and Nexus 5 emulator:
```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" navigatingTo="navigatingTo">
    <FlexboxLayout flexDirection="row" alignItems="flex-start" verticalAlignment="top" backgroundColor="yellow">
        <Label text="txt" backgroundColor="#ffe4c4" class="date" width="80" flexShrink="0"></Label>
        <FlexboxLayout flexDirection="column" flexShrink="1" backgroundColor="#7fffd4">
            <Label text="There are many variations of passages of sssssss Lorem Ipsum available, but the majority have suffered alteration in some form!" textWrap="true" flexGrow="3"></Label>
            <Label text="Subtitle..." textWrap="true" fontSize="10"></Label>
        </FlexboxLayout>
    </FlexboxLayout>
</Page>
```
The ' some form!' string is absent or clipped.

> N.B. It looks like the first FB measures the second with some width, and then arranges the second with another smaller width, making the text in its Label wrap into an additional line, unforeseen during measure, wreaking havoc vertically in the the second FB layout.

**Comment by erkanarslan** [comment]
I also have the same problem but couldn't find the reason until now. It seems that flexbox layout process has some problems. Here is the same element with flexbox layout and grid layout, respectively.

![img_1585](https://user-images.githubusercontent.com/11949947/39060976-8d05756c-44cb-11e8-8365-dd60033a02d3.PNG)

![img_216a0e748953-1](https://user-images.githubusercontent.com/11949947/39060985-91067616-44cb-11e8-9de0-8d75a70ab9de.jpeg)

Some part of the labels are missing in the flexbox case. This issue is open for more than 1 year. This needs to be fixed.

**Comment by manoldonev** [comment]
Probably related to https://github.com/NativeScript/NativeScript/issues/4834
