### ISSUE TITLE
Image Button not working 

### ISSUE THREAD

**Issue by BryanYomar** [NativeScript/NativeScript#3874]
I'm trying to make an image act like a button. I've already added an image as a background to the button, but when pressed it doesn't give the normal feedback (ripple effects) that buttons do. I don't know if Nativescript supports this, but any kind of help would be greatly appreciated!

**Comment by erjdriver** [comment]
Did you add class="btn btn-active" style to the button?

Can you post your Button definition?

**Comment by BryanYomar** [comment]
I tried your suggestion by making a button using that class and adding an image to its background, but it still doesn't show up the effect. Thanks for it though, it was a good one!

Right now I have it defined as an icon. And the tap action occurs on icons not buttons. Here's how it's currently written:

`<FlexboxLayout style="margin: 25;" alignItems="center" justifyContent="space-between">`
             `<Label class="fa text-center btn-active" [text]="'fa-calendar-o' | fonticon" width="50%" height="100%" (tap)="showDatePicker()"></Label> `
        `<Label class="fa" [text]="'fa-clock-o' | fonticon" width="50%" height="100%" (tap)="showTimePicker()"></Label>`
    `</FlexboxLayout>  `

**Comment by NickIliev** [comment]
The **tap** functionality is not coming with out-of-the-box ripple effect but you can add your own logic providing the effect. Currently only the button has built-in ripple effect which is why for your **Label** you should provide custom logic.
One possible workaround would be to use a plugin called [nativescript-ripple](https://www.npmjs.com/package/nativescript-ripple) and apply the ripple when needed.
Another possible solution is as @erjdriver suggested to created the effect using some CSS styles or provide the ripple effect by changing the styles in your code behind.

**Comment by BryanYomar** [comment]
Thanks, I'll try those options!
