### ISSUE TITLE
Q: Can I view console.log from a webpage in a webview somewhere?

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#3880]
Just a quick question:

I have created an app with a webview and the webpage displayed has some console.log outputs.

I have changed it to write this to a DIV on the page, but is there some way I can view them, the same way as I view the console.log in the nativescript code? :) 

tns --version -> 2.5.3

Thanks in advance :)

**Comment by NickIliev** [comment]
Hello @AndersGerner 

No out-of-the-box functionality but  there is a very nice blog post about bi-directional communication with WebView in NativeScript [here](http://shripalsoni.com/blog/nativescript-webview-native-bi-directional-communication/). The solution is using [nativescript-webview-interface](https://www.npmjs.com/package/nativescript-webview-interface) plugin,.

**Comment by minskmaz** [comment]
By my guess you lose about 50% of your potential user base on this right here.

**Comment by lukesUbuntu** [comment]
https://www.npmjs.com/package/nativescript-webview-interface provides a great example, i have used this in a project that would emit the console.log back to my nativescript app.

**Comment by minskmaz** [comment]
This works without issue - but I do think it's a pain point for the project that could be simplified or at least better documented. For instance it's not clear what WebView's network stack is capable of - I had hoped a IndexedDB would be there as I can't find one for NativeScript - still not certain.

**Comment by NathanaelA** [comment]
@minskmaz - Well the reason it isn't really documented; is the webview is whatever webview the phone supports.   So if you are using Android 4.2/4.4; the webview is really really limited and is rather pathetic.    If you are using Android 9; the webview is virtually equivalent to a very recent version of Chrome which means it performs really well.  WebView is whatever the OS is using.

WebView is really only for displaying web pages.   The actual NativeScript application doesn't run in a webview; so webview's are pretty pointless for that vast majority of most users.  (In fact in the 30 or so non-demo NativeScript apps I've worked on, I can only think of a couple that used WebViews...).    

As for storage; you can use NS-Sqlite (do a search on https://plugins.nativescript.rocks for Database) and you should see a ton of possibilities.  :grinning:

**Comment by minskmaz** [comment]
@NathanaelA thanks for the the useful and illuminating info. That should definitely find its way to the WebView docs! I started with the preview app a months back and really appreciate the npm friendly environment ans how well integrated the toolset is (tns, sidekick & debugger). I wanted to point out that the opaqueness of WebView (which you clarified) might be a place where users shy away from the project. Demo apps aside, WebView matters. When I'm done with this project I'll push an example using Framework7's "swiper"module which has a really rich gesture api, among other things. Thank you again for the insight!

**Comment by NathanaelA** [comment]
@minskmaz - I don't want to trivialize the webview; I do realize their are several app types that need good integration with online hosted websites and using WebView is really the only solid way to do it.  In fact one of the last apps I helped work on; used a webview for a large chunk of the app's viewable content.  The interface, searching, and many features were all NativeScript controls, so the app was very fluid -- but loading content for display purposes was using a authenticated webview session.     It was integrated really well... 

But since I have been a contractor/developer in NativeScript for several years; out of the very large number of apps I have helped develop that use NativeScript -- very very few have actually needed WebViews.       So I think that is probably why this component isn't as well rounded as some of the others; it isn't as high of a priority because it isn't really used as much as many of the other controls by the vast majority of the user base.   

I look forward to see your future contributions...  We love contributors; and feel free to ask questions on StackOverflow or Slack.   ;-)
