### ISSUE TITLE
Navigation Bar is changing 

### ISSUE THREAD

**Issue by adappter** [NativeScript/NativeScript#3907]
Hello,

in my iOS Project the navigation bar is changing when I'm routing through a tabview.

Look at this video: https://www.dropbox.com/s/4h3ht4u29k0k0ok/Bildschirmaufnahme_2.mov?dl=0

Watch the navigation bar changing from navigtion item to navigation controller

**Comment by NickIliev** [comment]
Hey @adappter 
One again thank for reporting this issue as well!
Can you please provide a code snippet or a sample project where the issue is reproduced so we can investigate the reasons and provide a fix/workaround.

**Comment by adappter** [comment]
Here you go @NickIliev 

[TestApp.zip](https://github.com/NativeScript/NativeScript/files/881549/TestApp.zip)

**Comment by NickIliev** [comment]
@adappter thank you for the test project - it helped a lot!
The reason for this issue is because the UITabBar controller (the native iOS control behind TabView) is creating its own navigation bar when using "**more**" items (meaning when there is not enough space for all tab items). So what is happening is that this controller is replaced with the action bar controller with a delay. To overcome this one there is a easy solution -create your own ActionBar for the pages which will load in the **more** section.
e.g. for the specific case given in the video
components/settings/settings.html
```
<ActionBar>
      <NavigationButton text="Back" (tap)="onNavBtnTap()">       
      </NavigationButton>
</ActionBar>

<GridLayout columns="*,*" rows="*,*">
  <!-- more content follows here -->
</GridLayout>
```

**Comment by tsonevn** [comment]
The issue is no longer reproducesable with  latest `tns-core-modules` -> `4.1.1` and `nativescript-angular`-> `6.0.6`
