### ISSUE TITLE
JS: Error: Failed to apply property [color] ... Invalid color: inherit

### ISSUE THREAD

**Issue by BenGermany** [NativeScript/NativeScript#3941]
After upgrading ns 2.5.x to 3rc and just testing tns create MyApp --template tns-template-hello-world@rc i had the following error log:

![image](https://cloud.githubusercontent.com/assets/26675531/24675298/e1c538a4-197e-11e7-982c-165967552e4d.png)

not a big problem but something went wrong ;-)

**Comment by NickIliev** [comment]
@BenGermany we are working on this one. Currently this one will only warn you and will not stop your work.

**Comment by NickIliev** [comment]
This is now fixed with next official version of nativescript-theme-core plugin via [this PR](https://github.com/NativeScript/theme/pull/130).

**Comment by IRCraziestTaxi** [comment]
I just saw this error today. "Failed to apply property [color] with value [inherit] to Button(...). Error: Invalid color: inherit" Using tns version 3.2.1.

Possibly related? I also saw "Failed to apply property [color] with value [#f0506e !important] to Label(...). Error: Invalid color: #f0506e !important"

I assume I'll need to open a new issue, but I thought at least the first error was relevant since it's the same error as referenced in this issue.
