### ISSUE TITLE
I cannot add Authorization Headers to http.getFile

### ISSUE THREAD

**Issue by asultonov** [NativeScript/NativeScript#3942]
NativeScript Http module has a simple and good method to download files from remote server and save them on device. But today I need to set the headers for authorization and I don't know how do it...

[NativeScript Http module documentation](https://docs.nativescript.org/cookbook/http)

**Comment by NickIliev** [comment]
Hey @asultonov 

I would recommend posting similar question ins the community channels like SO or forum.nativescript.org in order to keep the repository strictly for reporting issues and bugs, Also this way you will receive faster answer and the information will be visible for the whoile community.

Regarding your question - you can use [http.request](https://docs.nativescript.org/cookbook/http#post-json) to add headers
```
http.request({
    url: "https://httpbin.org/post",
    method: "POST",
    headers: { "Content-Type": "application/json" },
    content: JSON.stringify({ MyVariableOne: "ValueOne", MyVariableTwo: "ValueTwo" })
}).then(function (response) {
    // result = response.content.toJSON();
    // console.log(result);
}, function (e) {
    // console.log("Error occurred " + e);
});
```

**Comment by asultonov** [comment]
@NickIliev, thank you for your quick response.

But, I can't download .zip file with http.request. response.content has toJSON, toString and toImage methods, and for .zip files response.content is empty.

Downloading .zip well with http.getFile. Only problem with the ability to add a header for authorization.

P.S. On SO I also asked about this issue.

**Comment by NickIliev** [comment]
@asultonov glad to hear you have found the solution! Another point for the NativeScript community! :)
