### ISSUE TITLE
ListView life cycle behaving strangely

### ISSUE THREAD

**Issue by Cayan** [NativeScript/NativeScript#3978]
### Did you verify this is a real problem by searching [Stack Overflow]
The closest that I've found is: https://github.com/NativeScript/nativescript-angular/issues/612

### Tell us about the problem
I have created a repository from scratch to confirm this behavior that I have seen in my project. It is linked in the end.

It basically describes a strange behavior on a project with **Angular** using ListView with a ChildComponent and the `@Input` parameter to send data to it, the methods `ngOnInit`, `ngOnChanges` and `ngAfterViewInit` were used to improve the detection of this behavior.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.4
- Cross-platform modules: 2.5.2
- Runtime(s): 2.5.0
- Plugin(s): default ones that come with tns create --ng

### Please tell us how to recreate the issue in as much detail as possible.
With just one item in the ListView (the number in front of the events represent the ChildComponent index):
https://gist.github.com/Cayan/3618e8fca3342bf6f8694d215d02bce1

With two items:
https://gist.github.com/Cayan/57f606ab46a2384149f870f0cc4e79bd

With two items, but 500ms delay before adding the second element:
https://gist.github.com/Cayan/2b1480bcaf308eb68b57c90ec08e7258

There are three commits in the repository linked below, each one of them reproduces the above reports.

As you can see there is a really weird behavior going on there with two elements and this grows up with more items (5: https://gist.github.com/Cayan/d6231f2108ac465ab5af8e21fa46598b)

The behavior is the same without the index input.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
https://github.com/Cayan/nativescript-listview-ng-lifecycle

**Comment by tsonevn** [comment]
Hi @Cayan,
Thank you for contacting us.

If I understand you correctly, you are haveing an issue with multiple firing the `ngOnInit`, `ngOnChanges` and `ngAfterViewInit` Events for `ItemPreviewComponent`, while using it in the `ListView` template.
I tested the sample project on my side with `tns-core-modules` 2.5.2 and was able to reproduce this behavior on both iOS and Android.

In my further research, I tested the project with our [release candidate ](https://www.nativescript.org/blog/nativescript-3.0-release-candidate-available-today) and this issue seems to be fixed for iOS, however, still exists for Android.
For further info, you could keep track on the issue.

**Comment by Cayan** [comment]
Thank you @tsonevn, as a temporarily fix, I moved the ChildComponent into the parent.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-angular#756
