### ISSUE TITLE
[TNS 3.0 RC] TextView inside ListView template not autosizing as they did in TNS 2.5

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#3981]
**Platform:** iOS
**TNS:** 3.0 RC

I am creating a chat plugin using ListView, where a TextView is within an itemTemplate. Before upgrading from 2.5.x to 3.0 RC, the TextViews respectively auto-sized themselves according to their content size. However, in 3.0 RC, the TextView will only auto-size to the correct dimensions if it's the first item that is pushed to the ListView. The other ones will be the size of its previous item neighbour. More or less. It's buggy in random ways, because if I scroll they all resize to random dimensions.

![nachat_bug](https://cloud.githubusercontent.com/assets/2098838/24951058/6c3a5aec-1f73-11e7-8ed1-e6a51e3ad170.gif)

The difference between 2.5.x and 3.0 RC can be checked here:

**2.5.x:** https://github.com/NordlingArt/nativescript-na-chat
**3.0 RC:** https://github.com/NordlingArt/nativescript-na-chat/tree/TNS3

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Thank you for the attached sample projects.
I managed to build the sample app with `tns-core-modules` version 2.5.0, however, was unable to build the second one with NS 3.0, which prevents me from reproducing the issue with TextFiled auto-sizing.

Perhaps the issue could be related to the fact that in the plugin `package.json` file the `tns-core-modules` refers to 2.5.0, instead of `@rc`. Could you verify, whether you will have the same problem with building the [https://github.com/NordlingArt/nativescript-na-chat/tree/TNS3](https://github.com/NordlingArt/nativescript-na-chat/tree/TNS3) with @rc CLI (`npm install nativescript@rc -g`) and if it is possible to give us a sample, which could be debugged locally.

**Comment by NordlingArt** [comment]
@tsonevn - Actually it seems like my commit to the TNS3.0 branch was never fully pushed. I have now pushed the latest work. Can you please retry evaluate the TNS3.0 branch?

**Comment by tsonevn** [comment]
Hi @NordlingArt,
After the latest push in the branch, I was able to build the project with `@rc` modules. 
I will research, what is causing this issue and will provide additional info about it.

**Comment by NordlingArt** [comment]
@tsonevn - Thanks for investigating!
