### ISSUE TITLE
Animation: translate to device width wrong calculation

### ISSUE THREAD

**Issue by vjoao** [NativeScript/NativeScript#3997]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes. Couldnt find any clue.

### Tell us about the problem
I'm trying to animate a view from one side of the screen to another. Imagine there is a listView with 200dp width lying on the right side of the screen within a flexboxLayout with `justifyContent="flex-end"`. I want to animate the list so it appears to have `justifyContent="flex-start"` (assuming the flexLayout takes the whole screen). To do that, I try to animate the translateX property with the value `-(screen width -  list width)` but the list goes past the border of the screen. To make it work I need to translate `40dp` less than the list width by doing so: `"transform": "translateX(" + (screen.mainScreen.widthDIPs - (200 + 40)) + ")"`.
200 here is the list width, 40 is coming from nowhere.

### Which platform(s) does your issue occur on?
Tested on Android.

### Please provide the following version numbers that your issue occurs with:

tns@2.5.4
tns-angular latest.

### Please tell us how to recreate the issue in as much detail as possible.

Translate one element the whole screen width, element will leave the screen. Translate (screenW - elementW), element passes over the screen border.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

[Project on github](https://github.com/vjoao/ns-animation-example)

**Comment by vjoao** [comment]
I actually tried on 2 physical phones and the animation to `screenW - listW` is working. On Genymotion though I have to add 40dp to the calculation.

**Comment by tsonevn** [comment]
Hi @vjoao,
If I understand you correctly, this issue is reproducible on `Genymotion` emulator. I tested the sample project on my side while using default Android emulator  API level 23 and real device with API level 19 and this type of animations seems to work as expected.
Could you verify, whether you will have the same issue while using the [AVD emulator](https://docs.nativescript.org/tooling/android-virtual-devices)?
If you still have the same problem could you provide some more info about the device or emulator?
