### ISSUE TITLE
Cross-platform in-app notifications

### ISSUE THREAD

**Issue by valentinstoychev** [NativeScript/NativeScript#401]
Implement a cross-platform API for displaying in-app notifications. 

Here are the native counterparts:
[local notifications in Android](http://docs.appcelerator.com/platform/latest/#!/guide/Android_Notifications),
[SnackBars, toasts in Android](http://www.google.com/design/spec/components/snackbars-toasts.html),
[iOS notifications](https://developer.apple.com/library/prerelease/ios/documentation/UserExperience/Conceptual/MobileHIG/NotificationCenter.html#//apple_ref/doc/uid/TP40006556-CH39-SW1).

I asked our UX designer to prepare a proposal for the cross-platform implementation of the notifications.

**Comment by TheBrousse** [comment]
While a cross-platform approach to notifications will be a welcome addition. It is also important to allow developers to leverage the true native *extra* features that are made available for each platform. 
##iOS Notifications
iOS notifications have an interactive component that allow users to take diferent actions depending on the type of notification they receive.
###Notification Actions
Actions can either have a simplistic presentation up until two.

![Simple Actions](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Art/notif_ctr_banner_actions_2x.png)

But must rely on an options dialog once this number gets higher.

![Options](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/Art/notif_ctr_alert_actions_2x.png)

Maning that there must be a way to add actions and (most importantly) handle those actions.
### Reply directly from notification
Other notifications allow user to type in content directly into the notifiction itself. This is very common for chat or social applications.
![iOS reply from notification](http://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2014/09/quick_reply_ios_8_how_to_anywhere.jpg?itok=QrXzBq2Q)
###Lock Screen Integration
Actions are also available directly from the iOS lock screen.
![iOS Lock Screen](http://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2014/09/quick_reply_ios_8_how_to_lock_screen.jpg?itok=8DcCorHG)


##Android Notifications
Android has a more complete set of notification and interactions *(has been present since Android 5, so we wannot withold those features from today's users)*. They are defined in the
[Android Design documentation
](http://developer.android.com/design/patterns/notifications.html).

### Expand / Collapse
From the Notification Center, some notification can only show a small abstract of the notification content. But can be expanded when the user taps on it; thus showing additional content related to the notification.
![Custom actions](http://developer.android.com/images/android-5.0/notifications/ExpandedImage.png)
### Summaries
When there are multiple notifications from a single application, they can be *grouped* together and have a *summarised* presentation. Thus giving a clearer presentation to the user.
![Summaries](http://developer.android.com/images/android-5.0/notifications/Summarise_Do.png)

**Comment by valentinstoychev** [comment]
There are two major type of notifications - in-app notifications, where the UI of the notification can be customized by the developer, and system notifications for an app.

With the introduction of #71 we will cover teh second scenario - the system notifications. We will just use the native API to show the notifications and set the content. The notification will be then displayed by the OS and will follow the system UX. So the scenarios you are mentioining are all supported.

The in-app notifications are part of the app UI and app visual tree and we need to make sure we have the needed cross-platform components to display them.

**Comment by N3ll** [comment]
You can vote on our ideas-voting site here: https://nativescript.ideas.aha.io/ideas/NS-I-68.

**Comment by mdgiles** [comment]
I think there is still some confusion between in-app and system notifications.  I need to be able to create a system notification, but not triggered by a push. It will be triggered by an internal system event, such as venturing outside a certain location radius, or a certain date+time event. This scenario does not seem to have been covered.

**Comment by EddyVerbruggen** [comment]
I'm thinking about adding something similar as the Cordova Local Notifications plugin for iOS and Android.

**Comment by jlooper** [comment]
+1, very useful thing to have!

**Comment by amjd** [comment]
+1. Must have!

**Comment by valentinstoychev** [comment]
This is now done! https://github.com/NativeScript/NativeScript/issues/1397

**Comment by Milewski** [comment]
not compiling on {N} 1.7.1
