### ISSUE TITLE
Animating a view is broken, and freezes the animated properties

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4046]
**Platform:** iOS
**TNS:** 3.0 RC
**Git for example project:** https://github.com/NordlingArt/tns-animate

`button1` ("Move me"), works as expected without animation. I can set `translateX` and `translateY` over and over again. But animating `button2` ("Animate me") is broken:

1. The animation jumps and translates the view towards an unexpected position.
2. After the animation is complete, I can no longer set the properties `translateX`, `translateY`, nor `opacity` because they were animated.

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Thank you for reporting this and for the sample project.
I reviewed this case on my side and was able to reproduce the issue with setting up `translateX` and `translateY` after the animation complete.
This problem is reproduced on both iOS and Android. We will research the issue and will provide the appropriate fix.

**Comment by NordlingArt** [comment]
@tsonevn - Thank you for looking into it :)

**Comment by PanayotCankov** [comment]
1. Is still reproducible.
2. Has been fixed in the master.

**Comment by tsonevn** [comment]
HI @NordlingArt, @PanayotCankov 
I just tested the sample project with modules from the master branch and everything seems to work as expected now.

**Comment by NordlingArt** [comment]
@tsonevn, @PanayotCankov - Happy to hear it! Thank you!

**Comment by PanayotCankov** [comment]
There is a certain kind of behaviour that was frequently requested:
 - have initally a view with animatable property set at value A
 - set this animatable property to value B
 - animate this animatable property to value C using .animate with target and duration
In the first incarnation of the .animate for iOS was to animate the view from A to C (ignoring the fact the value was set to B prior calling the animation)
Later in the v2 series, CATransaction.begin/commit calls were added when setting animatable properties so the B value can be applied prior the .animate calls so the view animate from B to C, this was done for background and opacity.
In v3 we added such calls for each animatable properties, but obviously this plays wrong with the translateX/translateY pair. The commit transaction will sometime apply the translateX, render incorrectly, then apply the translateY and render in the expected position.

We've been discussing several resolutions internally:
 1. Revert the begin/commit transaction for properties that affect the render transform
 2. Add a uniform way to set all properties (like .transform property that is set to a matrix, rather than setting translateX, translateY etc.)
 3. We have internal _batchUpdate(callback), where the callback accumulates multiple changes and releases a single commit transaction, used in the CSS implementation.
 4. Delete the begin/commit transaction logic and make the .animate check if the properties were previously set directly (by non-animation) and if they were, use the value for "from" value. (at the moment this seems most reasonable)

**Comment by PanayotCankov** [comment]
There are updates. Internally we now have a mechanism to suspend and resume native updates, batching multiple changes on the same property to be released just once to the native view. Now setting transform will use such batching when setting translateX, translateY so instead of setting these smaller properties, consider setting transform:
```
view.transform = "translate(0, 0)"
```
Then we found a second issue that shorthand properties (such as transform) won't update the composite properties (such as translateX, translateY) in some cases, that's been fixed in https://github.com/NativeScript/NativeScript/pull/4607

Now both scenarios should work, but you will have to set transform instead of translateX/translateY.

**Comment by NordlingArt** [comment]
@PanayotCankov - Great! Setting translate with `transform` property seems like a more natural way of doing it anyways, so I'm cool with it :)

Is this `transform` property available in the `style` object as well?

**Comment by PanayotCankov** [comment]
@NordlingArt yes it is. I've updated my snippet to use the transform on the style.
