### ISSUE TITLE
sed: invalid replacement string because of applicationId

### ISSUE THREAD

**Issue by khcr** [NativeScript/NativeScript#4081]
Hi,
I'm trying to build my application for android by I'm facing a problem with applicationId/packageName. The build works fine when I set the applicationId according to the guidelines, in a three parts string like "org.company.appName". But my problem is that I created the first version of my application (not with Nativescript) with a two parts string like "id.randomString". And now when I try the set this applicationId, I get the error `sed: invalid replacement string` when it builds. It is quite annoying given that I want to publish an update to my app and not create a new one on the Play Store !
Thanks !

- CLI: 2.5.4
- Cross-platform modules: 2.5.2
- Runtime(s): 2.5.0

**Comment by NickIliev** [comment]
Hey @khcr 

As far as I understood you simply want to have a package name of your Android app in the following form:
e.g.
```
nativescript.myApp
```

instead of the default three-part string
```
org.nativescript.myApp
```

This should not cause any problems (In fact I 've just tested this case to confirm that it is hassle free - [test application here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4081)). To achieve the change of your package id once in your [package.json](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4081/package.json#L7) and also in your [app/App_Resources/Android/app.gradle](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4081/package.json#L7) file

Then remove platforms folder and rebuild your application. Let me know if this is applicable to your case and if not please provide as much as possible details on how to reproduce your issue based on your project local settings.

**Comment by khcr** [comment]
I downloaded your sample project and try to build, but I got the exact same error ! Did you run it with NS 2.5.4 ?

**Comment by khcr** [comment]
I tested with NS 3.0.0 and it works.

**Comment by NickIliev** [comment]
@khcr indeed I have tested this one with the latest versions of NativeScript (3.0.0) - closing this one as it is working in 3.0.0

**Comment by NickIliev** [comment]
@khcr indeed it appears this was not working in 2.5.x but is currently fixed in NativeScript 3.x.x
