### ISSUE TITLE
[Request] Ability to set header and footer template in a ListView

### ISSUE THREAD

**Issue by NordlingArt** [NativeScript/NativeScript#4116]
RadListView sort of has this feature, although it is extremely limited when it comes to styling them. Also, RadListView is sometimes an overkill when I just want to add a search bar on top of a simple vertical list.

**Comment by tsonevn** [comment]
Hi @NordlingArt,
Thank you for the feature request.
Indeed this s common functionality, however in my opinion this functionality should be included for RadCalendar component instead of adding it in the pure NativeScirpt ListView.

I also found that similar issue is logged [here ](https://github.com/telerik/nativescript-ui-feedback/issues/144) in the `nativescript-ui-feedback` repository. You could keep track on it for some further info and also write your suggestion about this feature.
