### ISSUE TITLE
Shell script invocation error, Run custom shell script ‘Nativescript PostBuild’

### ISSUE THREAD

**Issue by SandipFichadiya** [NativeScript/NativeScript#4128]
### Tell us about the problem
I had tried to run my native-script app from xcode 8.2.1. But it is throwing following error:

```
Run custom shell script ‘Nativescript PostBuild’

PhaseScriptExecution NativeScript\ PostBuild /Users/myUser/Library/Developer/Xcode/DerivedData/demoProject-fbnjhlljfjrtmscikekuxmygrfcw/Build/Intermediates/demoProject.build/Debug-iphonesimulator/demoProject.build/Script-CD3EAD351B05FF060042DBFC.sh
    cd "/Users/myUser/Desktop/demoProject/platforms/ios"
    /bin/sh -c /Users/myUser/Library/Developer/Xcode/DerivedData/demoProject-fbnjhlljfjrtmscikekuxmygrfcw/Build/Intermediates/demoProject.build/Debug-iphonesimulator/demoProject.build/Script-CD3EAD351B05FF060042DBFC.sh

~/Desktop/demoProject/platforms/ios/internal ~/Desktop/demoProject/platforms/ios
Stripping frameworks
fatal error: lipo: -remove's specified would result in an empty fat file
```

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 2.5.0
- Cross-platform modules: 2.5.2
- Runtime(s): 2.5.0

**Comment by dtopuzov** [comment]
This issue was moved to NativeScript/nativescript-cli#2785

**Comment by tbsf** [comment]
I had this same issue. The problem was the build/emulator folder in

/Users//Library/Developer/Xcode/DerivedData/-bitimkehdpflqafsyvbzfhgkwnsg/Build/Products/Debug-iphoneos/.app/Frameworks/build/emulator

I just closed xcode, removed /Users//Library/Developer/Xcode/DerivedData/-bitimkehdpflqafsyvbzfhgkwnsg, re-started xcode and re-added the product. I was finally able to build. My guess is that this emulator folder got created somehow and started messing up the builds.
