### ISSUE TITLE
[TNS 3.0] iOS:ActionBar will be hidden after closeCallback of modal page

### ISSUE THREAD

**Issue by kssfilo** [NativeScript/NativeScript#4141]
### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.0
- Cross-platform modules: 3.0.0
- Runtime(s): 3.0.0
- Plugin(s): -

### Please tell us how to recreate the issue in as much detail as possible.

1. create default project with iOS platform(tns create..)
2. make a modal page and open it by tap event on 1st page
3. close the modal page by closeCallback

-> ActionBar on 1st page will be hidden and not be shown after closing the modal.

I found a workaround like below. 

1. before showModal(), set actionBarHidden property of 1st page to true
2. in closeCallback, set actionBarHidden property to false

**Comment by tsonevn** [comment]
Hi @kssfilo,
Thank you for pointing this issue.
I reviewed the case on my side and indeed this is a real issue, which could be reproduced only for iOS.
I am attaching sample project, where the problem could be reproduced and could be used for debugging.
For further info about this behavior and about possible fix keep track the issue here.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/985622/Archive.zip)
