### ISSUE TITLE
iOS: 2.5.4, undefined is not an object (evaluating 'b.prototype')

### ISSUE THREAD

**Issue by dxshindeo** [NativeScript/NativeScript#4149]
iOS
NS 2.5.4
Real device

I had a project successfully built and released ~3-4 weeks ago, I haven't touched it since, and now I need to do some changes.
So, I simply run `tns run ios` and for my surprise - it fails at startup screen:
```
Found peer TypeScript 2.1.6
2:08:04 PM - Compilation complete. Watching for file changes.

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0xb40cdb -[TNSRuntime executeModule:referredBy:]
2   0xc85d9
3   0x1b4ae4eb <redacted>
JavaScript stack trace:
1   @undefined:7:68
JavaScript error:
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')
```
The same error happens if I build my project as AOT version.
In my `package.json` I had tns ios `"version": "2.5.0"`, and now, if I run `tns run ios`, it will overwrite it to `"version": "3.0.0"`. Could that be the cause?

`package.json`:

```
{
  "description": "Test Mobile Application",
  "license": "",
  "readme": "",
  "repository": "",
  "nativescript": {
    "id": "com.app.test",
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/router": "4.0.3",
    "PhoenixClient": "file:resources/PhoenixClient",
    "base-64": "^0.1.0",
    "nativescript-angular": "1.5.2",
    "nativescript-angular-snapshot": "1.5.2-5.5.372.32",
    "nativescript-camera": "3.0.0",
    "nativescript-geolocation": "3.0.0",
    "nativescript-gif": "1.0.9",
    "nativescript-google-maps-sdk": "1.4.3",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-phone": "1.3.0",
    "nativescript-vibrate": "1.1.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.3.1",
    "tns-core-modules": "2.5.2",
    "tns-platform-declarations": "2.5.2",
    "zone.js": "0.8.9"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.1.0",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "copy-webpack-plugin": "4.0.1",
    "extract-text-webpack-plugin": "2.1.0",
    "htmlparser2": "3.9.2",
    "lazy": "1.0.11",
    "nativescript-css-loader": "0.26.1",
    "nativescript-dev-android-snapshot": "0.*.*",
    "nativescript-dev-typescript": "0.4.2",
    "nativescript-dev-webpack": "0.4.1",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "2.0.2",
    "typescript": "2.1.6",
    "webpack": "2.4.1",
    "webpack-sources": "0.2.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

`tsconfig.json`
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "lib": [
            "es2016",
            "es2015.iterable"
        ],
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

`references.d.ts`:
```
/// <reference path="./node_modules/tns-core-modules/tns-core-modules.es2016.d.ts" />

declare type Comment = any;
declare type CloseEvent = any;
declare type Document = any;
declare type DocumentFragment = any;
declare type Element = any;
declare type History = any;
declare type HTMLAnchorElement = any;
declare type HTMLCollection = any;
declare type HTMLDocument = any;
declare type HTMLElement = any;
declare type HTMLInputElement = any;
declare type HTMLScriptElement = any;
declare type HTMLStyleElement = any;
declare type KeyboardEvent = any;
declare type Location = any;
declare type MessageEvent = any;
declare type MouseEvent = any;
declare type Node = any;
declare type NodeList = any;
declare type Text = any;
declare type WebSocket = any;
declare type HTMLMetaElement = any;

```

**Comment by dxshindeo** [comment]
Found the perpetrator - error is caused by `var imagepickerModule = require("nativescript-imagepicker");`.
Gona update once I find a workaround.

**Comment by dxshindeo** [comment]
Updated to `nativescript-imagepicker: "3.0.0"`, now at least there is more to the error:
```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0xacccdb -[TNSRuntime executeModule:referredBy:]
2   0x8f5d9
3   0x1b4ae4eb <redacted>
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-imagepicker/images.js:8:25
JavaScript error:
file:///app/tns_modules/nativescript-imagepicker/images.js:8:25: JS ERROR Error: Could not find module 'nativescript-telerik-ui/listview'. Computed path '/var/mobile/Containers/Data/Application/A141C337-B95E-4FC1-96A6-7EE4E75C01AD/Library/Application Support/LiveSync/app/tns_modules/nativescript-telerik-ui/listview'.
```

**Comment by NickIliev** [comment]
@dxshindeo as you yourself discovered when you execute `tns run ios` it will update your runtime and modules to 3.0.0. This is known bug which is logged [here](https://github.com/NativeScript/nativescript-cli/issues/2782).

To avoid the force update of your runtime and modules you can follow [these steps](https://github.com/NativeScript/nativescript-cli/issues/2782#issuecomment-299395789). (note that the second step adds the specific version 2.5.0). 

The image picker plugin version 3.0.0 is compatible with nativeScript 3.x.x. so if your projects depend on modules 2.5.x you would want to have nativescript-imagepicker 2.5.1
```

**Comment by dxshindeo** [comment]
Thank you for info. Your mentioned workaround did install 2.5.0 tns-ios platform, but I still get the error from `"nativescript-imagepicker": "^2.5.1",`.

**Comment by NickIliev** [comment]
@dxshindeo it appears that the issue is related to an internal dependency of nativescript-imagepicker plugin.
After `tns plugin add nativescript-imagepicker@2.5.1` the plugin version is successfully installed however the plugin itself depends on nativescript-telerik-ui and the versioning in the internal package.json is using * which means install the latest version. The latest version of nativescript-telerik-ui is not compatible with NativeScript 2.5.x so it might be the reason for your issue. We are currently on releasing a patch version of nativescript-imagepicker but meanwhile, you can try the following: 

- ni your project run `npm install`
- go to **_node_modules/nativescript-imagepicker_** and open **package.json** file
- from the root project directory rerun `npm install`

Now if you go to **_node_modules/nativescript-imagepicker/node_modules_** the dependency to nativescript-telerik-ui should be installed and with proper versioning

Please if you can test this do let me know if this works out for you.

**Comment by NickIliev** [comment]
@dxshindeo 
The patch version is now published with versions 2.5.2
You can try it in your applicaiton
```
tns plugin remove nativescript-imagepicker
tns plugin add nativescript-imagepicker@2.5.2
```

**Comment by NickIliev** [comment]
@dxshindeo have you managed to try the solution for the image picker plugin? Let me know if that worked and if you need further assistance for that issue.

**Comment by dxshindeo** [comment]
I will try it this weekend, gona post my results afterwards.

**Comment by dxshindeo** [comment]
Thank you, it works as you described!

**Comment by nmandyam** [comment]
I have NS 3.1.3, Core Modules 3.1.1, tns-ios 3.1.0 - so, all the current versions. And I DON'T have imagepicker. But I still get exactly this same error when running on the simulator - "undefined:7:68: JS ERROR TypeError: undefined is not an object ((evaluating 'b.prototype')". And the app crashes with Seg Fault 11. Any thoughts on what else may be the problem?

**Comment by sserdyuk** [comment]
@nmandyam Did you find what was the problem? Why was your process? I have the same problem. It's likely something related to webpack-ing, but I can't figure out what exactly.

**Comment by NathanWalker** [comment]
@NickIliev I have just run into this very ominous error as well. First time I've encountered it. The exact error is incredibly vague and soul crushing :)

```
JavaScript stack trace:
1   @undefined:7:68
JavaScript error:
undefined:7:68: JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')
```

Are there any other ways to debug these JS errors with NativeScript? Here is a screenshot of the *entire* log output from XCode right when the app launches to show how incredibly difficult of a spot this leaves developers...

<img width="1007" alt="screen shot 2017-10-19 at 12 44 12 am" src="https://user-images.githubusercontent.com/457187/31759581-ad1e4220-b466-11e7-8d62-00159002d89d.png">

I've spent pretty much all day trying different things to find a solution to this issue and nothing has worked. Everything from:
* compiling libs different ways with different tsconfig settings
* restructuring `vendor.ts` with all sorts of different configurations
* manually changing `vendor.js` (the built file - inside the built app) with various console.log's to try and see what's going on
* stepping through debuggers

Nothing can find what is causing this error. Any tools the NativeScript team has which could help me get to the bottom of what in the world this error is and where it is coming from?

The only clue I've been able to tell is it somehow relates to the `__extends` function since that appears to be the only place `b.prototype` is called in all webpack files.

I am using `nativescript-imagepicker` but latest version `3.0.7`. I don't think it is related to that plugin as I've tried removing that plugin altogether and the issue remains.

@vakrilov @sis0k0 @rosen-vladimirov @PeterStaev

**Comment by PeterStaev** [comment]
@NathanWalker , seems like it is related to the TS extend function and more precisely the base class ends up `undefined`. I have not encountered this error, but you should check your code for usage of the TS `extends` operator  and check if you have all your base classes defined and that webpack includes them in the bundle. For example if you have added somewhere `declare class Base {}` just to suppress TS compile error and then you extend that `Base` I guess it could cause this kind of problem.

**Comment by NathanWalker** [comment]
Thank you @PeterStaev I will check into that. Any pointers are helpful at this point. It would be great if the runtime allowed you to follow the stack down to exactly where that error is coming from to help pinpoint the cause.

**Comment by vakrilov** [comment]
## About the "meaningful" error
I agree - the stack trace is frustrating and gives almost no clue what the problem might be. There is much room for improvement here. It's best to open an issue in the [ios-runtime](https://github.com/NativeScript/ios-runtime) with a code sample that produces this stack trace. We will se what can be done to make the stack-trace meaningful and point to the right place in the code.

## About the actual issue
Speaking from experience - it is most probably `__extends`. I've seen it when you try to extend class that is still not loaded, usually because of a circular dependency in the required modules. 

We are using a neat npm package to detect circular require dependencies - `mange`. [Here](https://github.com/NativeScript/NativeScript/blob/master/package.json#L68-L69) is the npm script that runs the tool for the `tns-core-moudles`. Ypu can do the same for your project - it might give you an insight of where to look.

**Comment by NathanWalker** [comment]
Thank you @vakrilov - we will look into using that tool to dig more. 

The difficult thing with errors like this is it most likely will occur on large scale projects so very hard to create a small sample project to reproduce as it involves many levels of architecture to run into this but we will see if we can create a sample after we have solved it (to even understand how it can be reproduced).

**Comment by sserdyuk** [comment]
@NathanWalker I had the same error, but only if I webpacked the app. While it might be caused by various issues, mine was triggered by my attempt to vendorize Telerik UI on iOS. I ended up moving it out of the bundle. Here's a open ticket: https://github.com/NativeScript/nativescript-dev-webpack/issues/260
@PeterStaev

**Comment by alg** [comment]
For me it's livesync that's causing it. As soon as I commented it out in `main.m` -- `TNSInitializeLiveSync();` -- it's working again.

**Comment by NathanWalker** [comment]
@sserdyuk thanks we were using the latest nativescript-pro-ui and didn't have any issues there.
But we did find out what it was @vakrilov @sis0k0 @PeterStaev @NickIliev 
```
import 'nativescript-angular/animations';
```
Causes problems for a projects webpack build. Removing that 1 single import from `vendor.ts` solved everything. We weren't using anything from it so in our case that worked out.

For what it's worth this was the `vendor.ts` file we had (with animations) which caused the `b.prototype` issue:
```
/* tslint:disable ordered-imports no-import-side-effect*/

// std core
import './vendor-platform';

import 'reflect-metadata';

// ng
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/http';
import '@angular/platform-browser';
import '@angular/router';

// ng libs
import '@ngrx/core';
import '@ngrx/effects';
import '@ngrx/store';
import '@ngx-translate/core';

// ns-ng
import 'nativescript-angular/animations';   
import 'nativescript-angular/platform-static';
import 'nativescript-angular/common';
import 'nativescript-angular/router';
import 'nativescript-angular/forms';
import 'nativescript-angular/http';

// libs for @pnp-client/core
import 'date-fns';

// @pnp-client/core (shared library code)
import '@pnp-client/core';

// plugins
import 'nativescript-audio';
import 'nativescript-camera-plus';
import 'nativescript-cardview';
import 'nativescript-checkbox';
import 'nativescript-coachmarks';
import 'nativescript-drop-down';
import 'nativescript-exoplayer';
import 'nativescript-fresco';
import 'nativescript-imagecropper';
import 'nativescript-imagepicker';
import 'nativescript-loading-indicator';
import 'nativescript-ngx-fonticon';
import 'nativescript-payments';
import 'nativescript-permissions';
import 'nativescript-social-share';
import 'nativescript-pro-ui/listview';
import 'nativescript-pro-ui/listview/angular';
import 'nativescript-timedatepicker';
import 'nativescript-toasts';
import 'nativescript-zendesk-sdk';

// must go last
import 'nativescript-plugin-firebase';
import 'nativescript-youtubeplayer';

// app
import './helpers';
import './modules/shared';
```

*Changing above to below solved everything for us (note only animations is removed):*

```
/* tslint:disable ordered-imports no-import-side-effect*/

// std core
import './vendor-platform';

import 'reflect-metadata';

// ng
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/http';
import '@angular/platform-browser';
import '@angular/router';

// ng libs
import '@ngrx/core';
import '@ngrx/effects';
import '@ngrx/store';
import '@ngx-translate/core';

// ns-ng
import 'nativescript-angular/platform-static';
import 'nativescript-angular/common';
import 'nativescript-angular/router';
import 'nativescript-angular/forms';
import 'nativescript-angular/http';

// libs for @pnp-client/core
import 'date-fns';

// @pnp-client/core (shared library code)
import '@pnp-client/core';

// plugins
import 'nativescript-audio';
import 'nativescript-camera-plus';
import 'nativescript-cardview';
import 'nativescript-checkbox';
import 'nativescript-coachmarks';
import 'nativescript-drop-down';
import 'nativescript-exoplayer';
import 'nativescript-fresco';
import 'nativescript-imagecropper';
import 'nativescript-imagepicker';
import 'nativescript-loading-indicator';
import 'nativescript-ngx-fonticon';
import 'nativescript-payments';
import 'nativescript-permissions';
import 'nativescript-social-share';
import 'nativescript-pro-ui/listview';
import 'nativescript-pro-ui/listview/angular';
import 'nativescript-timedatepicker';
import 'nativescript-toasts';
import 'nativescript-zendesk-sdk';

// must go last
import 'nativescript-plugin-firebase';
import 'nativescript-youtubeplayer';

// app
import './helpers';
import './modules/shared';
```

**Comment by lukeramsden** [comment]
I've got the same problem but without Angular, Webpack or NativeScript Image Picker. What can I even do to debug this? I don't know where to start.

**Comment by sserdyuk** [comment]
@lukeramsden I'd suggest to look for circular references in your module imports. Also, iIf you had a working version before, you could use `git bisect` to find the change in the log that broke it.

**Comment by lukeramsden** [comment]
@sserdyuk I'll admit my searching isn't perfect, but I couldn't find any. The weird part is that it works on Android, but not iOS.

**Comment by lukeramsden** [comment]
https://github.com/NativeScript/ios-runtime/issues/807 I guess I'll wait for this.

**Comment by NathanaelA** [comment]
@lukeramsden - You can download my custom 3.2 runtime from http://nativescript.rocks/master/ tns-ios-3.2.0-mt.tgz - This runtime basically adds the code I mention in #807
This runtime really should only be used to debug this issue; as the added try/catch inside the `__extends` will cause ios startup to have a very minor performance hit.   

To use; you:
1. download it.  
2. tns platform remove ios
3. tns platform add ios --frameworkPath=/path/to/where/tns-ios-3.2.0-mt.tgz

Then run and watch the logs, to see the full call stack.

**Comment by lukeramsden** [comment]
@NathanaelA Wow thanks, will try.

**Comment by lukeramsden** [comment]
`undefined is not a constructor (evaluating 'new view_base_1.Property({ name: "automationText" })')`

```js
// error
exports.automationTextProperty = new view_base_1.Property({ name: "automationText" });
```

That's what the stack trace gave me. Any ideas? VSC seems to give Property a type of `any`, so maybe that's the problem? It doesn't exist? I don't understand enough about the NS core to understand what this code is doing, and it being transpiled JS instead of source TS doesn't help.

**Comment by NathanaelA** [comment]
@lukeramsden - I would open a new error for your issue -- your error above is "unrelated" to the extends.   This was about he _extends hiding the root error, now you have the root error you need to get help with it.  :grinning:

**Comment by lukeramsden** [comment]
Will do.

**Comment by nmandyam** [comment]
Believe it or not, the offending element in my code is this: 
`var activityIndicatorModule = require("ui/activity-indicator");`
I am running nativescript 3.3.1, tns-core-modules 3.3.0 on iOS.
I don't really need that line, so I just deleted it and all is OK. But I wonder: why is that code a problem anyway?

**Comment by sagar1911** [comment]
@lukeramsden Can you please link your raised issue here? (As suggested by Nathanael)

**Comment by kamlekar** [comment]
@lukeramsden Can you please link your raised issue here? (As suggested by Nathanael)

**Comment by lukeramsden** [comment]
@kamlekar I don't think I raised the issue, because I wanted to try get a reproducible version of it and I got pulled away to some other stuff.

**Comment by aleksander351** [comment]
I added `import { topmost } from 'ui/frame';` to my project to style the color of the iOS statusbar and got this error.
