### ISSUE TITLE
[NS 3.0] Plugin migration issue

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#4249]
I've recently migrated my Carousel plugin to tns v3.0. The plugin is written in plain JS, TS port will come in the near future. But I expect the plugin to work in plain JS (don't see why it should not). 

The issues I'm having after porting are as follows:
Plugin has a property called `selectedPage` that sets the index of the page to be selected. It can be used as a initial value or to change pages via code. 

**Android**
When setting the property to, for example, `selectedPage="1"` via XML, the change is only applied on iOS, while on Android it is not. The `setNative` property is called and the value is set on the `nativeView` (ViewPager), but nothing happens in the UI. 

**iOS & Android**
When calling the  `selectedPage` property via code, lets say from a tap-event in a view. It works on both platforms. BUT! I can call it only once for some reason. Calling it the first time, the property is hit and the value is set, UI responds in the correct manner. Calling it again, does absolutely nothing, the property is not even being hit. 

My repo is located here: https://github.com/manijak/nativescript-carousel
It also includes a demo app that can reproduce the above issues. 

tns 3.0.1
tns-ios 3.0.1
tns-android 3.0.0
core-modules: 3.0.0 (also tried with `next`)

Thanks in advance

**Comment by NickIliev** [comment]
Hey @manijak I have tested with your demo app and a test app of mine and as an observation can say the following:

- the first issue (Android not respecting the XML value for **selectedPage** property) is reproducible only when you are using the "list-view" syntax. For example setting selectedPage [here](https://github.com/manijak/nativescript-carousel/blob/master/demo/app/carousel1.xml#L11)will work but won't work [here](https://github.com/manijak/nativescript-carousel/blob/master/demo/app/carousel2.xml#L16). This said I've noticed that your template will be **refreshed** when a value is changed. In the implementation in the refresh, you are always defaulting to selection with index 0. So basically change [this line](https://github.com/manijak/nativescript-carousel/blob/master/index.android.js#L112) to
```
this._pageIndicatorView.setSelection(this.selectedPage);
```
And now setting the selectedPage via XML should work as expected with the "list" type template.

- Regarding the second issue for selectedPage not firing from code behind
After implementing the change in [this line](https://github.com/manijak/nativescript-carousel/blob/master/index.android.js#L112) this issue was also solved for my test app.

**Comment by manijak** [comment]
Thank you so much @NickIliev , yes you are right that the problem was in the `refresh()` function. I should have tested this better. Sorry about wasting your time! The example you added only changed the selected-indicator, I had to add the `this.nativeView.setCurrentItem()` as well, in order to set the ViewPagers index. 

Regarding the second issue, I got it to work when I applied the demo2 changes you added above. But what is bothering me is why it didn't work with my original example. When the tap event only called `myCarousel.selectedPage = 2;`. 
If I open the carousel-2 demo view, and tap the "Select page 3" button, it selects "Page3". 
Then I manually slide the Carousel to some other page, and tap the button again. Nothing happens, the property is not even called. Any idea why?

**Comment by NickIliev** [comment]
@manijak from the initial observation the problem is not in your tap function but in the fact that the **selectedPage** property is not updated when the users are **swiping manually** throught the different pages.
e.g.
create a debug breakpoint or log in setNative for selectedPageProperty
```
    Carousel.prototype[carouselCommon.selectedPageProperty.setNative] = function (value) {
        console.log("selectedPageProperty.setNative");
        this._selectedPage = value;
        this.nativeView.setCurrentItem(value);
        //console.log("selectedPageProperty.value: ", value);
        //console.log("selectedPageProperty.get: ", this.nativeView.getCurrentItem());
    };
```
and then use this in your tap
```
exports.selectPageEvent = function (args) {
	if (!myCarousel) {
		return;
	} else if (myCarousel.selectedPage == 2) {
		myCarousel.selectedPage = 1;
	}
	else {
		myCarousel.selectedPage = 2;
	}
}

```
Notice that setting **selectedPage** will be executed on each tap. However, if you start **swiping manually** selectedPage property won't be set at all!. So I guess that you will need to debug the logic behind the pageChanged event which should also update the selectedProperty.

**_Side note_**: during my tests, I've noticed that [this code](https://github.com/manijak/nativescript-carousel/commit/65feb2c98b77533fb5881caeb0bf6ec8678b95e0#diff-cd1f14f508a6bba08c447a7aeed686b4) pushed yesterday would break your carousel1.xml demo as there is no default value set for indicatorOffset. As far as I understood the logic [this lines](https://github.com/manijak/nativescript-carousel/blob/master/index-common.js#L99-L102) should become 

```
exports.indicatorOffsetProperty = new viewModule.Property({
    name: "indicatorOffset",
    defaultValue: "0,0"
});
```

**Comment by manijak** [comment]
Thanks a lot @NickIliev think I know where to look now ;) 

Yeah I noticed the error as well, fixed it. Thanks again!

**Comment by manijak** [comment]
Sorry to bother you again @NickIliev , but I am totally confused regarding the new property system. 
I did not see this until just now, this is how I defined my properties:
```
Carousel.prototype[carouselCommon.selectedPageProperty.getNative] = function () {
        return this.nativeView.getCurrentItem();
};
Carousel.prototype[carouselCommon.selectedPageProperty.setNative] = function (value) {
        this._selectedPage = value;
        this.nativeView.setCurrentItem(value);
};
```
Now I see that there is no `getNative`, only `getDefault` which sets the default value on start. 

So how do we write the `get` function that should return the current native value? Before the migration I had this. and it worked:
```
Object.defineProperty(Carousel.prototype, "selectedPage", {
get: function () {
     return this.nativeView.getCurrentItem();
},
set: function (value) {
   if(!this.nativeView) return;
   this._selectedPage = value;
   this.nativeView.setCurrentItem(value);
   this._pageIndicatorView.setSelection(value);
 },
enumerable: true,
configurable: true
});
```
Adding only the get-part next to the existing `setNative` property causes exceptions ("property has only a getter"). Does this mean that the new property-system does not have a custom getter? 

Printing `mycarousel.selectedPage` in the carousel2.js demo, gives me the value that was set the last time `setNative` was called. How do we define what is returned here? 

Sorry about this, just trying to get my head around it all... 😄 

PS. I've checked and when manually changing the pages, all native properties are being set with the correct index of the page. Only the local `_selectedPage` was not.

**Comment by manijak** [comment]
@NickIliev never mind, got it working. 😉 

Basically just changed all local `this._selectedPage` to `this.selectedPage`. Now the property is being set correctly and the correct value is returned when getting. 

Thanks again!
