### ISSUE TITLE
SearchBar dissmiss issues

### ISSUE THREAD

**Issue by tigrenok00** [NativeScript/NativeScript#4260]
Hi, 
I'm using SearchBar with Angular, and I'm having some issues with dismissing the keyboard in certain scenarios. 

The issues are:
1. When no text entered in the search, it does not dismiss the keyboard on sumbit
2. When clicking X while having text in the search bar, the text is getting cleared, but the keyboard is not dismissed. Only on second X click it closes.

I attach all the events I'm currently handling. Thanks!

```
<SearchBar #sb id="searchbar" (submit)="onSubmit()" (loaded)="searchBarLoaded()" (textChange)="searchBarTextChanged()"
(clear)="onClear()"></SearchBar>
```

```
 public searchBarLoaded() {
        this.searchPhrase = "";
        this.dismissInput();
    }

    dismissInput() {
        let sbComponent = view.getViewById(this.page, "searchbar");
        if (sbComponent) {
            sbComponent.dismissSoftInput();
            if (isAndroid) {
                if (sbComponent.android)
                    sbComponent.android.clearFocus();
            }
        }
    }

    public onSubmit() {
        this.dismissInput();
        if (this.searchbarComponent.text != "")
            this.beginSearch();
    }

    public beginSearch() {
        // filter items list here
    }

    public onClear() {
        this.dismissInput();
        // filter items list here
    }

    public searchBarTextChanged() {
        if (this.searchbarComponent.text != "") {
            this.searchPhrase = this.searchbarComponent.text;
            this.beginSearch();
        }
        else {
            this.searchPhrase = "";
            this.dismissInput();
            // filter items list here
        }
    }
```

**Comment by NickIliev** [comment]
Hi, @tigrenok00 

To resolve this issue you can use directly the [dismissSoftInput ](http://docs.nativescript.org/api-reference/classes/_ui_search_bar_.searchbar.html#dismisssoftinput)method provided by NativeScript which is pretty similar to your logic.
To hide the soft keyboard on **submit** event I've used the following 
```
    public onSubmit(args) {
        let searchbar = <SearchBar>args.object;

        console.log("onSubmit");
        searchbar.dismissSoftInput();
    }

```

To hide the keyboard on **clear** event in Angular is a bit trickier. The thing is that when textChanged is fired the focus is set again on your Search bar. Due to timings issue, both events might happen simultaneously causing the keyboard not be closed on the **clear** event. So just as your logic goes I am again explicitly closing the keyboard in both clear and textChange but using a small delay in textChange event (e.g. 300 miliseconds)
```
    public searchBarTextChanged(args) {
        let searchbar = <SearchBar>args.object;

        console.log("searchBarTextChanged: " + searchbar.text);

        if (searchbar.text != "") {
            this.searchPhrase = searchbar.text;
            this.beginSearch();
        } else {
            setTimeout(function() {
                searchbar.dismissSoftInput();
            }, 300);
        }
    }

    public beginSearch() {
        // filter items list here
    }

    public onClear(args) {
        let searchbar = <SearchBar>args.object;

        console.log("onClear");
        searchbar.dismissSoftInput();
    }
```

For your convenience, I have created a [test applicaiton here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4260) demonstrating how to hide the keyboard on both **submit** and **clear** events.

Note: If you need to hide the soft keyboard on the initial page load you can also use [this](https://github.com/NickIliev/NativeScript-NG-Marvel/blob/master/app/comics/comics.component.ts#L31). Keep in mind that on pages where the UI is refreshed (for example with list-view changing its items) the search bar may again regain its focus so you might need to explicitly take the focus from it - like in this scenario [here](https://github.com/NickIliev/NativeScript-NG-Marvel/blob/master/app/comics/comics.component.ts#L31)

**Comment by tigrenok00** [comment]
Thanks a lot, these solved all the issues we had. Thank you for the detailed answer!
