### ISSUE TITLE
[Feature request] Ability to to open multiple modal pages.

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#4264]
Ability to open ModalPage from another ModalPage. 
At the moment the possible workaround is to close the first page and then to open the second one.
I am attaching sample project with the workaround:
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1028965/Archive.zip)

**Comment by NathanWalker** [comment]
I just wanted to add additionally to the vote above, this is a highly desirable thing - run into this many times working on apps.

**Comment by alexziskind1** [comment]
I just wanted to add that this was working under 2.5.1 in iOS as it does in [this project](https://github.com/alexziskind1/courses-rps-project-tracker/tree/master/FinalProject/rpspt). Would be great if it started working again.

**Comment by erkanarslan** [comment]
This would be nice to have.

In my application, users can create content from different areas of the application. After creating or updating them, they should stay on the page where they opened edit/create page and see the new content in the list. Because of that, I need modal page. In that modal page, I need to open another modal page to select some items.

Currently, I do this by opening the form in a new page and keeping the state of the previous page. A little bit dirty.

**Comment by alexziskind1** [comment]
One thing I've been doing lately is simulating a modal by sliding up a separate panel that's part of the same page.

**Comment by jdnichollsc** [comment]
Ohhh exist any example to do that? @alexziskind1 
Thanks in advance

**Comment by alexziskind1** [comment]
@jdnichollsc Yes, check out this demo project here: https://github.com/alexziskind1/ndd/tree/master/twitter-replies

**Comment by isaacfi** [comment]
Finally the feature is ready and works like a charm: [Features nativescript 4.0](https://www.nativescript.org/blog/nativescript-4.0-is-out)

I've tested it on android and ios with nativescript+angular
