### ISSUE TITLE
White screen on navigate with clear history parameter

### ISSUE THREAD

**Issue by mayureshjadhav** [NativeScript/NativeScript#4269]
I am using NativeSctipt 2.5 and nativescript-angular 1.2.0 in my app. 

Scenario is I am navigating from page 1 to page 2 while navigating I am clearing the history but I can see a white screen while moving from page 1 to page 2 . 

What is the issue?

**Comment by NickIliev** [comment]
@mayureshjadhav there might be multiple reasons for your issue so please post more detailed information on how to reproduce your case. As the latest version is 3.x.x we will need both the content of your **package.json** file and the code used to create your application - the best case would be to create a sample application that demonstrates the issue and what you have achieved so far.

**Comment by mayureshjadhav** [comment]
Actually, I created project from hello word template and added two more pages and when I try to navigate from one page to another by using following code 

```
this.routerExtensions.navigate(["about"], {
                            clearHistory: true
                        });

```
I can see a white screen and then it moves to about (another) page.

Actually, you will not see the difference in a small application but when your app becomes complicated you will observe this issue.

**Comment by NickIliev** [comment]
@mayureshjadhav I was able to fully reproduce this issue using **Angular** application and **ClearHistory** set to **true** with some **PageTransition** (the default one as well). The issue is not reproducible with core NativeScript project. Marking this one as a bug - keep track of this issue for further updates.

Sample application to reproduce the issue can be found [here](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4269_ng).

Steps to reproduce:
- load the app
- navigate with `clearHistory` set to `true`+ page transition  (use some of the provided options in the app)

**Actual result**: the current page is replaced with a white screen and then the navigation proceeds.

Expected result : the current page to stay during the navigation transition as in [this NativeScript core application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4269)

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#829

**Comment by mayureshjadhav** [comment]
@NickIliev Is that issue solved? When and How I can see?

**Comment by NickIliev** [comment]
@mayureshjadhav the issue was moved to the nativescript-angular repository (see the link in my previous oost) and is planned for fixing in 3.2 release - still for the best updates on that matter please track the linked issue
