### ISSUE TITLE
error TS2339: Property 'animate' does not exist on type 'ViewBase'

### ISSUE THREAD

**Issue by shyandsy** [NativeScript/NativeScript#4276]
any change about the animate property of view in NativeScript 3?

error TS2339: Property 'animate' does not exist on type 'ViewBase'

**Comment by NickIliev** [comment]
@shyandsy I was not able to reproduce your error log with both imperative (Code behind) and declarative (CSS) animations and using [this test application.](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4276).

In order to investigate further please provide more details on how to reproduce this error - best case providing a test applicaiton or code snippets along with the content of your package.json file.. Specifying on which platform this occurs is also good practice.

As a possible solution check your TypeScript related dependencies (like [typescript](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4276/package.json#L23) and [nativescript-dev-typescript](https://github.com/NickIliev/NativeScript-Issues-2017/blob/master/NativeScript/issue_4276/package.json#L22)) and make sure taht they are compatible with the version of NativeScript you are uising in your project

**Comment by bradmartin** [comment]
@shyandsy try asserting the type of the UI component you're animating. Like this: `const myBtn = topmost().getViewById('whateverId') as Button` or you could assert it to the `View` class. The compiler will then be aware of the `animate` property on the instance you are animating. I assume this is how you're getting an instance of the UI view with `getViewById()`, if so it returns the type `ViewBase`, which again, is mentioned in the error not having the `animate` property. Hope that helps.

**Comment by NickIliev** [comment]
@shyandsy we haven't heard from you for a while - have you managed to resolve your issue?
