### ISSUE TITLE
Styling problems - cascading & inheritance

### ISSUE THREAD

**Issue by bfattori** [NativeScript/NativeScript#430]
I am having an issue with styling. I know this is intended to function like CSS, but it's not, and that's causing a headache. I'm trying to determine where to assign the `cssClass` attribute for the following XML (this is only _part_ of it)
```
    <Label row="0" col="1" cssClass="headerActionButton" tap="onHeaderAction">
        <Label.formattedText>
            <FormattedString>
                <FormattedString.spans>
                    <Span fontFamily="sans-serif-condensed" fontSize="18" text="{{ actionBtnText }}"/>
                </FormattedString.spans>
            </FormattedString>
        </Label.formattedText>
    </Label>
```
The style for the CSS is simple:
```
.headerActionButton {
   horizontal-align: right
}
```
The issue is when I have a `Span` inside the formatted text of a label, it doesn't get any styles from the cssClass `headerActionButton`. However, if I change that to read:
```
    <Label row="0" col="1" style="horizontal-align: right" tap="onHeaderAction">
```
It gets the style just fine. Also, I am wondering why I have to re-declare styles:
```
.alignRight {
    horizontal-align: right;
}

.up {
    color: #00c853;
    horizontal-align: right;
    font-size: 18;
}

.down {
    color: #c41411;
    horizontal-align: right;
    font-size: 18;
}

.same {
    color: black;
    horizontal-align: right;
    font-size: 18;
}
```
I have to re-declare `horizontal-align` for each of the classes `up`, `down`, and `same`, even though the label is assigned the two styles I have declared:
```
<Label cssClass="alignRight up" text="33.3"/>
```
Why is this? Is `cssClass` intended to only have one class name assigned?

**Comment by vakrilov** [comment]
@bfattori 
I tried the code you've posted and it seems to be styled correctly - the label is aligned to the right and the font-size of the span is 18. Note, that we have only added support for fontFamily recently (#361) and it is still not in the official bits, so that probably won't work on you side.

About the multiple CSS classes on one element - that is also supported. I've tried to remove the `horizontal-align: right;` form the `.up` selector and the label is aligned correctly to the right as it picks the alignment from the `.alignRight ` selector. 

If you are still having problems with the styling (or your head still aches) after this clarification - send us the whole page(xml + css) so we can look it trough and be more helpful.
