### ISSUE TITLE
Camera requestPermissions Suggestion

### ISSUE THREAD

**Issue by AGutan** [NativeScript/NativeScript#4308]
Hi!

I'm trying to use the camera following these instructions: https://docs.nativescript.org/hardware/camera#requesting-permissions

As a suggestion:
Could you make requestPermissions return a promise? 
So that I can use it like this:
```
    camera.requestPermissions()
      .then(function() {
         console.log("Woo Hoo, I have the power!");
         camera.takePicture ...
      })
```

**Comment by NathanaelA** [comment]
@AGutan - My NativeScript-Permissions plugin is promise based; you can use it to get permissions for the camera just like you are asking for...

**Comment by AGutan** [comment]
@NathanaelA the following code returns ERROR TypeError: Cannot read property 'then' of undefined

```
    requestPermissions()
        .then(() => {

          takePicture({ width: 200, height: 200, keepAspectRatio: false, saveToGallery: this.saveToGallery })

        })
        .then((imageAsset) => {

           console.log('Success!');

        }, (error) => {
          console.log("Error: " + error)
        });
```

**Comment by NathanaelA** [comment]
@aguten - I haven't really used the built in permissions for the camera plugin as it (the camera plugin code used to be part of core) and so it is fairly new.     What I was suggesting, since you want to use promises is use my promise based nativescript-permissions https://github.com/NathanaelA/nativescript-permissions as you can use it to get permissions

**Comment by AGutan** [comment]
@NathanaelA Ok Thanks!
