### ISSUE TITLE
"import-ed" css rules don't override existing rules with same specificity

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#4323]
This is a deviation from how CSS works in web. Normally, rules from `@import` statements override previously defined rules. In NS, you have to use a rule with higher specificity, or nothing happens. The glaring case of it is right in the tns-template-hello-world-ts app template, where the theme is imported at the bottom and css above is effective. The expected result would be that importing the theme at the bottom of the file nulls the `.btn` styling because the same selector is styled in the theme. The expected behavior would require importing the theme at the top of the `app.css` file and overriding the details after that.

The real life implication of that is that any attempt to increase css maintainability by breaking your `app.css` into smaller files, runs into the requirement to always use more specific selectors into included files, where there's no other real reason to do so. 

Since NS boasts itself as mobile development platform with web developers' skills reuse, such a departure from standard behavior is a bug.

`$ tns create CssImportBug --tsc
`

Red color sticks to the button even though the theme applies blue. 

```
.btn {
    font-size: 18;
    background-color: red;
}

@import 'nativescript-theme-core/css/core.light.css';
```

**Comment by NickIliev** [comment]
@sserdyuk Thank you for reporting this issue - confirming that this behavior is not the expected one so I am marking this as a bug.

**_Side note_**: the class **_btn_** in the theme is not setting any background or other colors (only dimensions and spacing.) so to test this case we should overwrite the style applied by **btn-primary** class as in the XML file the button is styled with several classes 
```
<Button text="TAP" tap="{{ onTap }}" class="btn btn-primary btn-active"/>
```

As a rule of thumbs, you can always [import your external CSS files at the very beginning](https://docs.nativescript.org/ui/styling#import-external-css) so they can precede all other styles that come later. By specification, the CSS that is loaded last will "win" so that will ensure that you are controlling the CSS in the proper way.

**Comment by NickIliev** [comment]
@sserdyuk after some additional research it appears that the imported CSS styles should **always precede** any other custom styles and this is the expected behavior [by specification ](https://developer.mozilla.org/en/docs/Web/CSS/@import). 

For example, when you have two different imports that are overwriting the background-color of your button, the last one will be the one that applies the style (as expected). All other custom styles should come after the imports. 

In our templates we have made a structural mistake for which I apologize - the templates will be updated accordingly to these rules. Once again thank you for pointing that out!

**Comment by NickIliev** [comment]
Resolved via [https://github.com/NativeScript/template-hello-world/pull/64](https://github.com/NativeScript/template-hello-world/pull/64) and [https://github.com/NativeScript/template-hello-world-ts/pull/32](https://github.com/NativeScript/template-hello-world-ts/pull/32)

**Comment by MIYankov** [comment]
@NickIliev What about platform specific styles? Following this guideline means that platform specific rules should precede global app rules and can be overridden by them. This can potentially cause problems for users. This can be avoided if the platform specific css is the main one and it has the global app.css imported into it.

**Comment by NickIliev** [comment]
@MIYankov even with a Web application, you would expect that all style coming **after** the imports will overwrite any identical styles declared in the import files (based on [specs](https://developer.mozilla.org/en/docs/Web/CSS/@import)).
e.g.
```
@import 'style-aaa.css';  /*let's assume something like  .note { background-color: red }*/

.note { background-color: blue } /* this should win */
```

I would expect that the class **note** would apply blue color at the final result.

Now in the context of Web, we don't have platform-specific files - this is something strictly related to a cross-platform framework like NativeScript. So the thing is that we would want either to follow specification or break them to support platform-specific CSS imports on a random principle.

In my opinion, instead of breaking specifications, we could simply take care of the overwriting identical CSS with import order.
e.g
app.scss
```
@import 'style-aaa.css';  // Global main styles
@import 'style-ios.css';  // platform specific overwriting of global styles
@import 'style-android.css';  // platform specific overwriting of global styles
@import 'style-bbb.css'; // overwrite all that is preceeding this line

/* all styles that follow will overwrite all the identical styles rules in the imports */
.note {
    background-color: green;
}
```

@vakrilov , @PanayotCankov - opinions on that ^^^

**Comment by NickIliev** [comment]
Closing this issue as the order of the imports is respected.
To make sure that your custom CSS classes are respected make sure that the imports are loaded priorly
