### ISSUE TITLE
Webview not scaling a 'non-responsive' website

### ISSUE THREAD

**Issue by tonyhogben** [NativeScript/NativeScript#4441]
## Please, provide the details below:

When I load a non-responsive url into a WebView (i.e. [http://www.parentpayshop.com/schools/wsm/index.htm](http://www.parentpayshop.com/schools/wsm/index.htm)), there is no ability to scale it to display the whole view on the screen (as it would do in a native web browser).

### Did you verify this is a real problem by searching [Stack Overflow]
I have scoured the web and attempted to use native code to achieve this. In Android I was able to use:

```
var pageWidth: number = 800,
      screenWidth: number = screen.mainScreen.widthPixels;

var scale: number = (screenWidth / pageWidth) * 100;

webView.android.setInitialScale(scale);
```

In iOS, nothing works including:

`webView.ios.scalesPageToFit = true;`

### Which platform(s) does your issue occur on?
I am looking for an iOS solution as I have something working in Android, however it only works as I know what screen width the website was designed for. The Android solution, in my opinion is not good enough and it feels like this really should be the default behaviour of the WebView component.

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.0.3
- Cross-platform modules: 3.0.1
- Runtime(s): 3.0.1

### Please tell us how to recreate the issue in as much detail as possible.

In it's simplest form, add a WebView and a point it at a non-responsive webpage...

`<WebView id="paymentPage" src="http://www.parentpayshop.com/schools/wsm/index.htm" />`

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

xml:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded">
    <WebView id="paymentPage" />
</Page>
```

ts:

```
import { Page } from "ui/page";
import { EventData, } from "data/observable";
import { WebView, LoadEventData } from "ui/web-view";
import { isIOS, isAndroid, screen } from "tns-core-modules/platform";

export function pageLoaded(args: EventData) {
    let page: Page = <Page>args.object;
    let webView: WebView = <WebView>page.getViewById('paymentPage');

    if ( isAndroid ) {
        let pageWidth: number = 800,
            screenWidth: number = screen.mainScreen.widthPixels;

        let scale: number = (screenWidth / pageWidth) * 100;

        webView.android.setInitialScale(scale);
    }

    webView.on('loadFinished', (args: LoadEventData) => {
        if (!args.error) {
            if ( isIOS ) {
                // Does not work
                webView.ios.contentMode = UIViewContentMode.ScaleAspectFit;
                webView.ios.scalesPageToFit = true;
            }
        }
    });
    webView.src = "http://www.parentpayshop.com/schools/wsm/index.htm";
}
```

**Comment by NickIliev** [comment]
@tonyhogben both solutions are using native APIs and NativeScript is not changing the native implementation in any way so any inconsistency is related to the original code implementation by Android and iOS. I suspect that the site you are trying to open is written in a way that does not allow proper resizing  (after some research on the topic it seems that the are a number of sites that are not scaled properly when using **scalesPageToFit** ). You can take a look at the numerous examples when the method was not able to scale a page in a native iOS application using [this query](https://www.google.bg/search?q=scalespagetofit+not+working&rlz=1C1CHBF_enBG741BG742&oq=scalesPageToFit+&aqs=chrome.2.69i57j0l5.2207j0j7&sourceid=chrome&ie=UTF-8)

This said it would be a nice feature for default WebView but as we do not have a stable native solution (neither for iOS nor Android) then its implementation is not recommended due to the side effects.

**Comment by tonyhogben** [comment]
@NickIliev thanks for taking a look. I too suspect the site we are trying to open does not have the correct meta tags to allow proper resizing. However, when you visit the website in Safari or Chrome on iOS and Android respectively, the site is shown correctly. Surely we should be able to mirror this behaviour?

My code attempt does indeed delve into the native APIs as NativeScript's WebView seemed to be lacking any options or support in this area (or did I miss something?).

With regard to iOS, it appears to be quite a mess as the link you posted supports. Of course, that is based on me using the correct approach/code (something I am not 100% certain on) so it would be good to get a second opinion.

As for Android, my code is flawed as it contains a fixed width value. I had wanted to measure the width of the WebView once it was loaded, but all attempts to do so failed. My code would benefit an approach to solve this so the scale can be correctly calculated - any ideas?

**Comment by NickIliev** [comment]
@tonyhogben  you can get the measured width and height of your WebView with loadFinished event

e.g.
```
wv = <WebView>page.getViewById("wv");

wv.on("loadFinished", (args) => {
    console.log(wv.getActualSize().height);
    console.log(wv.getActualSize().width);
    console.log(wv.getMeasuredHeight());
    console.log(wv.getMeasuredWidth());
})
```

**Comment by tonyhogben** [comment]
@NickIliev I did try those (and just did again using your code) and each line returns a big fat 0!?

**Comment by NickIliev** [comment]
@tonyhogben I have used [this application](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4441) to test the above code - in the test application also another example is given (with **loaded** event and **setTimeout**). Keep in mind that depending on your internet connection the time needed for the site to fully load mighty differ - try wrapping your code in a small setTimeou to observe if you are hitting timing issues due to slower internet connection.
