### ISSUE TITLE
Webpack build

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/NativeScript#4459]
The current build for web pack is implemented as npm script that does the following:

 1. Calls `tns prepare <platform>`
 2. Calls `tns clean-app <platform`
 3. Cleans snapshot artefacts (rm -rf src/main/assets/snapshots, rm -rf configurations/snapshot/include.gradle)
 4. Cleans build artefacts if there is a difference from the previous build, at some point may do a `gradle clean`
 5. Runs `webpack`
 6. Regenerate snapshot artefacts
 7. Perform `tns run` or `tns build`

The process is fragile with that:
 - The `tns prepare` is called several times, at some points products of `tns prepare` are cleaned so they can be replaced by webpack, and subsequent `tns build` calls will assume the app have not changed and rely on that the cli will skip prepare.
 - The ownership of some intermediate artefacts is not handled well and some of the directories are created by the CLI and cleaned by the Gradle or the vice-versa.
 - The webpack npm scripts does not integrate well in the CLI, it may be better to be a CLI extension instead.
 - The gradle includes each .aar and each .jar, that fails if different versions of the same plugin is installed (e.g. tns-core-modules-widgets), the CLI flattens the dependencies but the gradle is not aware of it.

We would like to spend some time to:
 - [x] Figure out ownership of the intermediate files.
   - The gradle should clean only files that gradle build produced.
   - The CLI should clean only files that the CLI produced.
 - [x] Gradle builds in platforms should roundtrip through `gradle build` `gradle clean`, as well as perform incremental builds when called with sequences of `gradle build`, `gradle build`.
 - [x] Provide abstraction over the JavaScript assets build, so the prepare step can be switched to use the web pack to produce `platforms/android/src/main/assets/app/` and `platforms/ios/<app>/app` and suppress the builtin CLI scripts build.
 - [x] Builds with web pack should not involve cleaning of artefacts produced during the same build.

We would like to also:
 - Try to minimise the amount of file copies created by the CLI and gradle. 
  This should let some plugins to be consumed with `npm link` and the gradle may be able to perform incremental builds on plugin changes.
  This should remove some code generation performed in the build.gradle and should make the build.gradle somewhat more maintainable, include.gradle files will be consumed directly from node_modules and won't be copied anymore. This will sacrifice the existing plugins variable interpolation mechanism and we should be careful not to brake existing plugins.
    - The CLI can provide list with dependencies to the android build, instead of copy plugin files.
    - The gradle can use imperative code to include all dependencies from the native plugins list without writing code in generated include.gradle files.

**Comment by PanayotCankov** [comment]
Here is the PoC branch in the android runtime: https://github.com/NativeScript/android-runtime/tree/gradle-configs

**Comment by ivanbuhov** [comment]
[This fix](https://github.com/NativeScript/nativescript-cli/pull/2930/files) introduces the following implications: 
 * When using snapshots as native libraries instead of blob files, the libraries are installed in `platforms/android` folder just before `tns build android` is executed. Next, the build command performs `gradle clean` and snapshot libraries are removed from `platforms/android`. Since using libs instead of blobs has no so much benefits, we are fine to stop supporting it (maybe temporarily).
 * The blobs scenario is also affected, because an `include.gradle` file is placed in `platforms/android/configurations` folder that gets removed later by `tns build android` command. The only goal of the copied `include.gradle` file is to exclude the snapshotted script from the final APK. Since the snapshotted script is loaded from blobs it is not needed in the APK as source file. Leaving the file in the APK bundle will has no any effect on the app performance/startup time but still it unnecessarily increases the APK size.
We should take these issues into account when implementing more general solution of the problem.
