### ISSUE TITLE
Webpack/ng project fails with NS3.1.1

### ISSUE THREAD

**Issue by berchik** [NativeScript/NativeScript#4478]
Updated to NativeScript 3.1.1 and my webpack project stopped working. windows 10, node v6.11.0 npm 5.0.4, android platform

I’m trying to test from scratch:

`new ng project`
`npm install --save-dev nativescript-dev-webpack`
`npm install`

`npm run build-android-bundle`

Running webpack for android...
'webpack' is not recognized as an internal or external command,
operable program or batch file.
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jo\AppData\Roaming\npm-cache\_logs\2017-06-29T18_34_34_379Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-android-bundle: `npm run ns-bundle --android --build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by NickIliev** [comment]
@berchik the issue is most likely caused by the version of NPM you have on your machine (related to [this](https://github.com/NativeScript/nativescript-cli/pull/2926)). From the error log, it appears that your webpack plugin is not included or is installed incorrectly.

I have tested bundling with WebPack on a brand new Angular project (with NPM 3.10.10), and it works flawlessly so you might want to downgrade the version of NPM until all issues rea officially resolved (keep track on the linked issue)

**Comment by berchik** [comment]
@NickIliev - Yes, I can confirm that downgrading npm to 3.10.10 is working. Creating a new project and adding the webpack plugin works with no problems. 

It was a bit more complicated to manage the existing project, still needed some adjustments to the dependencies. The last trap - after deleting node_modules and clearing the cache, I continuously got errors when attempting to ‘npm i’ which after quite some time was solved by adding an exclusion of the working folder to windows defender..

Now all is well, thanks.
