### ISSUE TITLE
create plugin by static static libraries error

### ISSUE THREAD

**Issue by xiaochong44** [NativeScript/NativeScript#4501]
I create new plugin by static libraries;
he have  three file. jcore-ios-1.1.5.a jpush-ios-3.0.6.a and JPUSHService.h.
tns run ios show error 
Processing node_modules failed. Exception: The static library at /Users/feng/AnBangCrmApp/node_modules/nativescript-jpush/platforms/ios/jcore-ios-1.1.5.a is not built for one or more of the following required arch
itectures: armv7, arm64, i386. The static library must be built for all required architectures.

lipo -info show
Architectures in the fat file: /Users/feng/AnBangCrmApp/node_modules/nativescript-jpush/platforms/ios/jcore-ios-1.1.5.a are: armv7 armv7s x86_64 arm64

**Comment by NickIliev** [comment]
@xiaochong44 the static library you are using is not build for all required architectures and you are trying to build for architecture that is missing (e.g. you are building on real device that requires armv7 but the static library is build only for i386).
What you need is to create a **fat** static library - see [this thread](https://stackoverflow.com/questions/3520977/build-fat-static-library-device-simulator-using-xcode-and-sdk-4) for more information on the topic.

**Comment by xiaochong44** [comment]
@NickIliev 
Thanks for you message.
This static library is provided by other companies
He is a push service, I386 is before IPhone5 ,The simulator is already x86_64, is there a setting that can not check i386?

**Comment by NickIliev** [comment]
@xiaochong44 for real devices your static library needs to be built for armv7, arm64,

**Comment by xiaochong44** [comment]
@NickIliev 
lipo -info 
Architectures in the fat file: /Users/feng/AnBangCrmApp/node_modules/nativescript-jpush/platforms/ios/jcore-ios-1.1.5.a are: armv7 armv7s x86_64 arm64
It should have armv7 arm64？

**Comment by ivanbuhov** [comment]
@xiaochong44 The CLI [checks each library against a list of required architectures](https://github.com/NativeScript/nativescript-cli/blob/60cf564b19c439f0b21b83222f19aec21704878d/lib/services/ios-project-service.ts#L965-L972) and fails if the binary doesn't contain even one of them. Currently, the list contains `armv7`, `arm64` and `i386` archs. However, it is a perfectly valid scenario to include a library containing only device architectures (`armv7`, `arm64`) so IMO the current behaviour is buggy. Ideally, we should check for existence only those archs we are building for. This way, building for release won't fail because of missing simulator architecture. I am reopening the issue and tagging it as bug.

To workaround the problem you can merge your existing `jcore-ios-1.1.5.a` binary with an empty `i386` library. Open Xcode and create an empty static library target and run a build for `i386` arch. The produced binary can be merged with the existing library:

```
lipo -create jcore-ios-1.1.5.a my_dummy_i386_lib.a -output  jcore-ios-1.1.5-fat.a
```
This way, the library still won't work on simulators because the `i386` slice doesn't contain any symbols but it is enough to make the CLI check pass.

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-cli#2967
