### ISSUE TITLE
Modal not showing

### ISSUE THREAD

**Issue by terreb** [NativeScript/NativeScript#4576]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes I did

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

Nativescript throws an error when trying to show a modal
"JS ERROR TypeError: page._showNativeModalView is not a function. (In 'page._showNativeModalView(this, context, closeCallback, fullscreen)', 'page._showNativeModalView' is undefined)"

### Which platform(s) does your issue occur on?
iOS, not sure about Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project)
- Plugin(s): (look for the version number in the `package.json` file of your
project)

tns: 3.1.2
tns-core-modules: 3.1.0
tns-ios: 3.1.0

### Please tell us how to recreate the issue in as much detail as possible.

1. in typescript hello-world template create any modal page modal.xml
2. on page loaded event try to show it:  args.object.showModal('modal') 

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

Please see above, that's pretty much it.

**Comment by tsonevn** [comment]
Hi @terreb,
 I tested this case with the [sample ](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/master/app/modal-page) from [nativescript-sdk-examples-ng](https://github.com/NativeScript/nativescript-sdk-examples-ng/), however, was unable to reproduce an issue with the modal page. Could you provide more info about the case? It would help if you could provide sample project, which could be debugged locally.

**Comment by terreb** [comment]
@tsonevn, ok added: https://github.com/terreb/ns-modal. Please let me know if anything else. 
Also, just in case I'm testing on simulator iOS 10.3 iPhone 6.

**Comment by terreb** [comment]
Hi @tsonevn, have you managed to reproduce the bug using the test app I provided?

**Comment by tsonevn** [comment]
Hi @terreb,
Excuse us for the delay in the reply.
I reviewed your project and found that the issue is related to several mistakes in the project.

The first problem was that you are calling showModal method, before the page to be fully loaded. On second hand the method expects four arguments as is described [here](http://docs.nativescript.org/core-concepts/navigation#example-14--receive-data-from-the-modal-page), the first one is the name of the page, where we will navigate, the second one is the context, which is used to send data to the modal page, the third is the callback method, which is executed, when we close the modal page and the last one is a boolean  argument, which describes if the page should be a fullscreen or not.

The last problem in the demo app was the missed declaration in the modal page for the onShowMosally event.
For your convenience, I am attaching a sample project with all needed fixes. also for further help, you could review the documentation [here](http://docs.nativescript.org/core-concepts/navigation#modal-pages) and the [sample app ](https://github.com/NativeScript/NativeScript/tree/master/apps/app/ui-tests-app/modal-view) provided in it.

**Comment by terreb** [comment]
@tsonevn, ok, thank you works perfectly! The last quick question here. If I want to show a dialog after closing the modal I get "Attempt to present <UIAlertController: 0x7ffcb37efb20> on <UIViewControllerImpl: 0x7ffcb341daf0> whose view is not in the window hierarchy" on iOS:

```typescript
    page.showModal( modal, context, ( recipe: object ) => {
        page.closeModal()

        dialogModule.action({
            title: '',
            message: 'Do you want to add the recipe to a new dish or active one?',
            cancelButtonText: 'Cancel'),
            actions: ['new', 'active']
        })

    }, true ) 
```  

On Android it works though...

**Comment by tsonevn** [comment]
HI @terreb,
This is an iOS behavior, which is related to the fact that you are trying to show the dialog too early, to resolve that you could set a timeout of 700 milliseconds, which will allow you showing the dialog for the both platforms, without facing any further issues.
```
export function onTap(args){
    console.log('gotcha');
    var button:Button = args.object;
    const modal = './modal'
    button.page.showModal(modal, null, (args)=>{
        console.log("closed");
        setTimeout(function() {
            alert("test")
        }, 700);
        
    }, true)
}
```

**Comment by terreb** [comment]
@tsonevn, thank you!

**Comment by yassern** [comment]
And still needs of a setTimeout to make it works

**Comment by tsonevn** [comment]
Hi @yassern,
Can you send us sample project, which could be used for debugging?

**Comment by yassern** [comment]
@tsonevn The bug is the same of that issue ~> https://github.com/NativeScript/nativescript-angular/issues/1325

**Comment by griffithstek** [comment]
I just got done implementing modals in our application It's working so nicely with iOS, but I've essentially had to fork the navigation for Android and iOS in order to maintain animations on Android. This is an ugly solution though. Let's get this bumped up the priority list please.
