### ISSUE TITLE
question: overview of components todo

### ISSUE THREAD

**Issue by michahell** [NativeScript/NativeScript#4640]
I believe there used to be an overview of components that were finished and yet to-do, where did this go? I can't find it anymore...

**Comment by tsonevn** [comment]
Hi @michahell,
First of all, thank you for your interest in NativeScript. 
Regarding the topic, of the issue, you could find list of all supported component in the Cookbook section of the documentation. there you will also find an example for every one of them. 

About the upcoming features, those issues have been marked with the Label `Feature` and you could use the search to filter the issues by their label and to list them.

However, if the idea for this issue is different, please provide some more details about your request.

**Comment by michahell** [comment]
thanks @tsonevn , the Cookbook will definitely help me find what's there. I was looking for a simple text list that looked like this:

NativeScript todo:

button               done
list                     done
link                    in progress
loader               in progress
table                 planned
scrollbar           planned

etc.

**Comment by tsonevn** [comment]
Hi @michahell, 
Thank you for the attached example.
However, it would help if you could provide an info, what would be the benefits and expectations of the similar table versus the existing Cookbook section, where we also have an example for every UI component?

**Comment by michahell** [comment]
Well, I can see which components are `in progress`, `planned`. right now, I have no idea of a roadmap or something similar. maybe there is a roadmap in which I can find information on planned components etc. ?

**Comment by tsonevn** [comment]
Hi @michahell,
Indeed similar [section ](https://www.nativescript.org/roadmap#v3.2) exists on the web site, where are described all tasks that have been planned for the upcoming releases. There you will also find an info if there are plans for some new feature or components that will be introduced with the newer versions of the product.

**Comment by tsonevn** [comment]
Hi @michahell,
I am assuming that the given solution in my previous comment is applicable to you and In my opinion, we could close this issue.
Let me know if you have something further to add on this topic.

**Comment by michahell** [comment]
sure, close it! thanks!
