### ISSUE TITLE
Execution Failed for Task 'asbg:generateBindings

### ISSUE THREAD

**Issue by jeneiro** [NativeScript/NativeScript#4644]
![issue](https://user-images.githubusercontent.com/28535480/28870838-adc61632-7779-11e7-979e-ab5fd71fa003.jpg)

Encountered this problem trying to build. Really appreciate if i am pointed in the right direction. thank you

**Comment by tsonevn** [comment]
Hi @jeneiro,

thank you for contacting us,

Regarding the problem It would help if you could provide some more info about your problem and your environment(NativeScript CLI, tns-core-modules, node versions ). Also, it would help if you could provide a sample project, which could be debugged locally.

In the meantime, you could try to remove `node_modules`, `platforms` and `hooks` folders and to rebuild the project.

**Comment by tsonevn** [comment]
Hi @jeneiro,
Were you able to resolve your case? If the problem still exists please provide some more info.

**Comment by jeneiro** [comment]
![wooo](https://user-images.githubusercontent.com/28535480/29031280-a02d7082-7b85-11e7-8107-b6cc139973bd.jpg)
i did a fresh build after deleting node_modules, platforms and hooks folders. and i got a different error.

**Comment by tsonevn** [comment]
Hi @jeneiro 

the problem seems to be related to the gradle and the fact that some o;d file has been cached. To resolve this you could follow the steps described in [this StackOverflow thread](https://stackoverflow.com/questions/43010547/errorunexpected-lock-protocol-found-in-lock-file-expected-3-found-0). 

However, if the problem still exists please provide a sample project or at lease your project package.json file. Also provide an info about your environment(NativeScript CLI, tns-core-modules, node versions ).

**Comment by jeneiro** [comment]
thank you. it worked like a charm.
