### ISSUE TITLE
Using huge third-party JavaScript lib increases loading time

### ISSUE THREAD

**Issue by budilovskiy** [NativeScript/NativeScript#4701]
### Tell us about the problem
In my android app i need to use third-party JavaScript lib (about 3 MB) generated with ScalaJS. This causes an increase in the of the application loading time (over 1 minute on real Android device) in two cases:
- when the application starts
- when the application returns from the background mode to active state

In first case loading time depends on the used Typescript version. With version 2.3.4 or lower application starts normally within 10 seconds. But since version 2.4.0 loading time is about 1 minute.

In both cases loading speed depends on js-file size: I used two files:
- normal javascript-file (~3 MB)
- same javascript-file, but uglified/optimized (~550 KB)

A larger file increases the download time more.

I have tested my app at Meizu M3s device and made a table with dependency of the loading and resume from background state on the Typescript version and size of the js-file:

| Typescript version | JS file size | app loading time | app resume from background time |
|--------------------|--------------|------------------|---------------------------------|
| 2.3.4              | -            | 6 s              | 4 s                             |
|                    | 2,9 MB       | 9 s              | 80 s                            |
|                    | 550 KB       | 7 s              | 25 s                            |
| 2.4.2              | -            | 9 s              | 5 s                             |
|                    | 2,9 MB       | 58 s             | 77 s                            |
|                    | 550 KB       | 7 s              | 25 s                            |

I noticed that the most part of the application loading time is the call of the **com.tns.runtime.dispathCallJsMethodNative** method:
![image](https://user-images.githubusercontent.com/11961551/29327006-54bd1888-81f6-11e7-80d1-c812e3784e50.png)

Is this a Nativescript/Android/Google's V8 problem or maybe this is a problem with my js-lib?

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.1.1
- Cross-platform modules: 3.1.1
- Runtime(s): 3.1.1
- Plugin(s): 3.1.1

### Please tell us how to recreate the issue in as much detail as possible.
I created a [repository](https://github.com/budilovskiy/tns-scalajs-sample) with a simple example of use huge third-party JavaScript library.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
import {Component} from "@angular/core";
import {SocketIO} from "nativescript-socketio";

let jsApp = require('./js/scalajs-fastopt.js'); // 2.9 MB

@Component({
    selector: "my-app",
    template: `
        <ActionBar title="My App" class="action-bar"></ActionBar>
    `
})
export class AppComponent {

    constructor() {
        let transportService = new jsApp.TransportService(new SocketIO("http://localhost:3000", {}));
    }
}
```

**Comment by NickIliev** [comment]
@budilovskiy this is kinda expected as what is actually happening is that this huge JS library is directly injected as application javascript (although 99% of the functionality is never used). The better approach would be to convert the library to NativeScript plugin and expose and use only the wanted functionality 
```
import { wantedClass, wantedMethod, wantedProperty } from "my-plugin"
```

You can profile the application with the timeline-view tool ](https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements)

When bundling the application with Webpack you can also take a look at the generated **report.html** (located in the report folder at the root level in your project) - with your default configuration you will see that the bundle.js chunk is enormously big as the huge JS is part of your application. [You can add modules and plugins that are used in your application in the `vendor.ts`](https://docs.nativescript.org/best-practices/bundling-with-webpack#how-nativescript-dev-webpack-works) file so that they can be bundled separately
