### ISSUE TITLE
No connection between IOS app and WatchOS app

### ISSUE THREAD

**Issue by AndersGerner** [NativeScript/NativeScript#471]
Hi Telerik / NativeScript team, 

I have been reading your information on the watchkit samle app [link](https://github.com/NativeScript/sample-iOS-WatchKit) - and i got it to work with my own app. Took a bit of time with all the on/off checking of the controllers.

Well - My issue is, that i need the watch app to require HTTP and make requests - I think the "best practice" way is to implement all the logik in the IOS app and then serve it to the watchOS app. (Correct me if am wrong).

But honestly I'm a bit confused on how my /platforms/ios/watchappname extension/app/bootstrap.js is suppose to communicate with my IOS app. 

What would your approach be on doing this? 

Note: If you are having a similar issue, know that i also posted this on [Stack Overflow] (http://stackoverflow.com/questions/31569129/how-to-make-a-connection-between-ios-app-and-watchos-app-nativescript)

**Comment by fealebenpae** [comment]
Hi @AndersGerner,

In order to receive messages from the WatchKit app in your host app, you will need to implement the [`application:handleWatchKitExtensionRequest:reply:`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/#//apple_ref/occ/intfm/UIApplicationDelegate/application:handleWatchKitExtensionRequest:reply:) method in your host app's application delegate. With the upcoming NativeScript 1.3 release, this can be done in the following way:
```
var application = require("application");

application.ios.delegate = UIResponder.extend({
    applicationHandleWatchKitExtensionRequestReply(application, request, reply) {
        if (request.objectForKey("command") == "doFoo") {
            reply({ foo: true });
        }
    }
}, {
    protocols: [UIApplicationDelegate]
});

application.start();
```

Then, in your WatchKit app you need to send a message that the above method will handle using [`+[WKInterfaceController openParentApplication:reply:]`](https://developer.apple.com/library/prerelease/ios/documentation/WatchKit/Reference/WKInterfaceController_class/#//apple_ref/occ/clm/WKInterfaceController/openParentApplication:reply:)
```
WKInterfaceController.openParentApplicationReply({ command: "doFoo" }, function (response, error) {
    if (error) {
        // an error occurred
    } else {
        if (response.objectForKey("foo")) {
            // foo is done
        }
    }
});
```
