### ISSUE TITLE
slider ui component 

### ISSUE THREAD

**Issue by rehamalisalehhosni** [NativeScript/NativeScript#4716]
nativescript slider ui 
Is support multiple ranges ?

**Comment by NickIliev** [comment]
@rehamalisalehhosni the slider in NativeScript behave like the native [UISlider](https://developer.apple.com/documentation/uikit/uislider) (iOS) and [SeekBar](https://developer.android.com/reference/android/widget/SeekBar.html) (Android) and both controls do not support multiple ranges by design. 

The solution would be to create your own native multi range slider by either creating a plugin or directly using the native code in your application. There are many examples on how to approach this feature (e.g. - [here](https://stackoverflow.com/questions/26836534/how-to-make-double-seekbar-in-android) for Android and [here](https://stackoverflow.com/a/30589205/4936697) for iOS)
