### ISSUE TITLE
ListViewAdapter implementation reports it has stable IDs, but its IDs are actually position-based

### ISSUE THREAD

**Issue by madakk** [NativeScript/NativeScript#4724]
The ListViewAdapter implementation returns true from hasStableIds:

https://github.com/NativeScript/NativeScript/blob/6e06eba2189172eb04ca46b4ea9cf1e1b141582f/tns-core-modules/ui/list-view/list-view.android.ts#L229-L231

But in fact, the item IDs are just reflecting the item positions:

https://github.com/NativeScript/NativeScript/blob/6e06eba2189172eb04ca46b4ea9cf1e1b141582f/tns-core-modules/ui/list-view/list-view.android.ts#L225-L227

So if the items are rearranged, or removed, the IDs are no longer stable.

**Comment by hshristov** [comment]
Hi @madakk,

Do you have a project where this is failing?

**Comment by madakk** [comment]
No, but it's incorrect and has undefined implications in terms of the Android runtime.

**Comment by hshristov** [comment]
I've done some tests in order research the implication of `hasStableIds`. It seems that android could give you `android.view.View` that is already prepared so we could skip all the work of changing `bindingContext` which in terms will update the item. But in order to do it the user should provide unique id for every item. Or we could attach symbol on every item and then use that symbol as unique id. 

In any case the current implementation works correctly because we update all visible views every time `notifyDataSetChanged` is called.

I've logged new issue to expose function on the ListView that will return the `id` of an item: https://github.com/NativeScript/NativeScript/issues/4729

Thanks for bringing this up. I'm closing this issue. Please use the other item to track the progress.
