### ISSUE TITLE
NativeScriptActivity should be exported so it can be subclassed

### ISSUE THREAD

**Issue by madakk** [NativeScript/NativeScript#4790]
Currently, if an app wants to extend the activity, it needs to basically clone the implementation of NativeScriptActivity (per [this document](https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity#extending-activity)), in order to support the built-in callbacks. If the built-in class was exported, the activity could instead be extended, reusing the existing implementation.

**Comment by Pip3r4o** [comment]
Hey @madakk,

Extending a generated Java class whose implementation is in JavaScript (TypeScript) is not possible, so extending the `NativeScriptActivity` implementation in the frame module would not work.

It is for that very reason that the frame module has exported `AndroidActivityCallbacks` and `setActivityCallbacks` so that you could plug your own implementation there, which the cross-platform modules can call to during the lifecycle events.

Please let us know if you need further clarifications.

**Comment by madakk** [comment]
I see, I was not aware of this limitation. My problem specifically is that I need onNewInit, which isn't currently implemented and is pending under #2747, so I don't have a choice but to make my own Activity subclass.

I don't know too much about the Android run-time, but couldn't this limitation be overcome? Can't a Java class be generated for the JS subclass which would then resolve to the subclassed methods, which would then handle the inheritance chain entirely on the JS side?

**Comment by Pip3r4o** [comment]
@madakk not with the current implementation, no. And handling that would require a good amount of effort to ensure it isn't error prone.
