### ISSUE TITLE
Navigating on Android really slow.

### ISSUE THREAD

**Issue by dottodot** [NativeScript/NativeScript#4840]
### Tell us about the problem
On ios I have no issues my app runs perfectly, but on a android device (genymotion emulator is fine) it's noticeably laggy, when navigating around it's at least 2 seconds before the navigation occurs sometime even longer.

The app is built using angular, and I've seen other reports of this issue but they suggest it was fixed in 2.4.0.

It also doesn't seem any different if it's a lazy loaded module or not.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.2.0
- Cross-platform modules: 3.2.0
- Runtime(s): 3.2.0

**Comment by tsonevn** [comment]
Hi @dottodot,
Thank you for contacting us.
Regarding the topic, in NativeScript 3.2.0 we have made some performance improvements, however, in your case I could suggest also to webpack your project and to snapshot it, which should also help you. Further info about this could be found [here](https://docs.nativescript.org/best-practices/bundling-with-webpack).

Let me know whether this help.

**Comment by dottodot** [comment]
@tsonevn It's already built using webpack and with snapshot.

**Comment by tsonevn** [comment]
Hi @dottodot,
Could you send us some sample project, which could be debugged locally? This will also help us to investigate, what is causing this slow navigation.

Thank you in advance for your cooperation.

**Comment by dottodot** [comment]
@tsonevn here's the full project.
https://github.com/dottodot/rsm

**Comment by tsonevn** [comment]
Hi @dottodot,
Excuse us for the delay in the reply,
After I reviewed your application I have some suggestions, which could improve the performance of the application. 
Firstly you could replace ngIf directive with the `visibility` property when you need to show and hide an elements dinamically. For example:
```
<StackLayout class="loading" [visibility]="isItemVisible ? 'visible' : 'collapsed'" verticalAlignment="center">
        <Label class="h1 text-center" text="Sending..."></Label>
    </StackLayout>
```
Using ngDirective could lead to an issue with the view recycling as it is described [here](https://medium.com/@alexander.vakrilov/faster-nativescript-listview-with-multiple-item-templates-8f903a32e48f).

Another improvement could be to optimizing your views in the HTML code in the application. regarding that, you could review this article [NativeScript Angular - Performance Tips & Tricks](https://www.nativescript.org/blog/nativescript-angular-performance-tips-tricks).

Together with the above-mentioned optimizations, you could keep using [webpack snapshot](https://docs.nativescript.org/best-practices/bundling-with-webpack#introducing-webpack) and [lazy loading ](https://www.nativescript.org/blog/optimizing-app-loading-time-with-angular-2-lazy-loading) techniques.
Best regards,

**Comment by dottodot** [comment]
@tsonevn thanks for looking into this for me. Not sure replacing `ngif` made much difference really. I think my issues are probably more to do with having a `gridlayout` inside my `listview` items, but I can't see anyway I can avoid using it to get the layout I want. Think my only option is to hide the view until navigation is complete.

Also would I have the same issue on a native app?

**Comment by x00** [comment]
from my performance testing angular just slows things to the point where all of the nicety you get doesn't justify using it.

**Comment by NickIliev** [comment]
Hey, @x00 @dottodot it really depends on the implementation and the optimizations used.
For example using
``
tns run android --bundle --env.uglify --env.aot --env.snapshot
``
[for this application](https://github.com/NickIliev/nativescript-ng-cosmos) is resulting approx 1.8s startup time and fast page in-app navigation

**Comment by x00** [comment]
@NickIliev  I would love to be convinced becuase I have to consider redoing what I have already done but I ran the test using the angular demo which is very light an basic. I did so with bundle minify and snapshot and well as full release with not options and with ally eh same options. It still took 5 second. Much slower than many complex apps on my phone. 

I wish it was performing but if it potentially perform less well than if angular was running in a web view you have to wonder the benefit of using angular.

I understand it is tied to the amount of layouts and view tag but it even if you can get them down it is not always easy to reduce the number, even with optimisations. The angular demo should has very few of them. 

This was on the Moto X play which not that old, and a fair decent mid range phone. Ok the processor so so, but I'm comparing to other apps.

**Comment by x00** [comment]
The original tests
https://discourse.nativescript.org/t/slow-loading-with-dev-bundle-uglify-snapshot-release-builds/4083

**Comment by x00** [comment]
@NickIliev your app  build as specified loaded in ~5 second on a moto X-play 

CPU 	1.7 GHz 64-bit Octa-core
GPU 	Adreno 405
Memory 	2 GB LPDDR3 RAM

**Comment by x00** [comment]
@NickIliev what would be good to find out is why it is almost three times as slow in my phone using the same example and it get worse with the minimum amount of complexity. Once you are waiting 5 or so seconds for a page to load then you have to wonder what is going on. 

What are your phone specs if you don't mind me asking? 

The question is is if this is the most efficient implementation of angular and if there bugs or efficiencies that could be made. If there is soemthign that is causing a scaled economy that could be overcome that is worth investigating. If it simply three is not other way to model angular then that undermines its uses as a development framework for native script.

**Comment by dali-gharbi** [comment]
Hi, i used tns run android --bundle --env.uglify --env.aot --env.snapshot
 to build my project but the problems of freez when navigating from one page to another persist.
so i did the profiling using timeline-view and here is my report  without --bundle : 
[times.log](https://github.com/NativeScript/NativeScript/files/1759051/times.log)

- motion event 16 ms

- MarkReachableObjects: com.tns.gen.android.app.Application_ActivityLifecycleCallbacks 4098.748046875ms 1

- MarkReachableObjects: com.tns.gen.android.view.GestureDetector_SimpleOnGestureListener_frnal_ts_helpers_l58_c38__TapAndDoubleTapGestureListenerImpl 4101.887939453125ms 1

- PageRouterOutlet.activateWith [object Object] 304ms 1

any leads ? 

![unknown](https://user-images.githubusercontent.com/9580152/36677167-cf7d341c-1b0d-11e8-8f43-11a09231b95e.png)

**Comment by ventr1x** [comment]
It's kind of interesting that some here shove the problem to angular.
Angular is for example WAY more performant than react, especially when it comes to rendering big data.
Navigation and native ui have not much to do with angular.
The navigation is terribly slow, I have up to 4 seconds delay on my Huawei Mate9 on every page transition that is more than just some text.
It is for me currently the main concern as I would never be able to publish my product in this state. Sadly there seems to be no solution for this (like for most of the things in nativescript). 

Linking demo apps and saying "hey, this is kinda fast enough, so it's all your fault" is not very nice. Especially if the demo apps also have up to 2 seconds delay/frame drops on transitions.

**Comment by relez** [comment]
Well reading about this issue, I would like to tell my story... in the company I work for we have been using Telerik products for years, we developed a nice bunch of apps using Cordova/Kendo UI. Suddenly they (Telerik) forced us to use NativeScript or Cordova CLI (imagine if someone leaves you in the middle of the ocean with a small boat and surrounded by sharks). We decided to go for NativeScript over React Native because it (NS) seemed to be very well backed by Progress. 

Working for some months, were are about to release our apps and guess what? Testing the Android performances we discovered that navigation/complex views are very slow, some of our pages have very complex view with long list of data using listviews.

Some points I want to be clear out:

- Using webpack/uglify, snapshot does not speed up the app.
- Using Angular does not takes advantage of the cool features, the app performance is slower.
 
I honestly believe what Telerik did was not professional at all, considering that they pulled us to use their expensive (yes, they are expensive) products (Kendo UI/Kendo UI Mobile) and then forcing you to change what you worked for. 

I am seriously considering to bump NativeScript and start working on React Native.

**Comment by NickIliev** [comment]
@ventr1x sorry for my late reply! (I've missed this thread somehow)

I've used the demo app as an example for application with a fairly complex structure (and not just a blank template with master-details) and based on my observations the application does not have issues like slow in-app navigation even in the cases where I am using async operations to load data on component initialization. I am testing on several devices mainly on Lenovo with  1GB RAM and Android 5 and on LG Nexus 5x with Android 8 (2GB RAM) and also on Pixel. Still, there is no occasion where I am experiencing 4 seconds delay in the navigation. 

I am not a specialist on [react-native startup time](https://stackoverflow.com/questions/47679773/how-to-decrease-startup-time-on-react-native-android-applications) but you can use [**timeline-view**](https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements) to actually see the timings in your NativeScript app (including in-app navigation). In NativeScript the startup time means when **the app actually shows the landing page** (and not when the splash screen is shown as some other products are doing).

@ventr1x  @dottodot @gabitoesmiapodo @amoswachanga @Bessonov @Fiontan @relez @adenovan @weijyewang @pacome2017 If anyone of you guys can provide a sample application that is hitting slow navigation please contact me here (or in the community slack username: **niliev**) and provide me with a sample application or [Playground demo](https://play.nativescript.org/) that can illustrate the issue. I will be happy to investigate your cases and see what is causing the issue and how the app can be optimized. Apart form the used codebase please also include information about what device you are testing on (or if emulator what emulat/Android API Level)

.

**Comment by Bessonov** [comment]
@NickIliev I tried it now on my Nexus 4/Android 4.4.4 with NativeScript Preview from PlayStore version 1.18.0 from 11.12.2018. It feels still bad on navigation. For example to ListView and back. Its even slower than an AngularJS app in Cordova :(

**Comment by NickIliev** [comment]
@Bessonov can you share the Playground demo used? Keep in mind that the Playground app is actually running without any optimizations at all (no Webpack, uglify, AOT or snapshot). And these optimizations are a great deal - e.g. the starting time can be under 2 sec with all options vs 7-8 or even more seconds with a pure build.

**Comment by Bessonov** [comment]
@NickIliev this one: https://play.google.com/store/apps/details?id=org.nativescript.preview&hl=en_US It is not optimizing?

**Comment by RichardLindhout** [comment]
> It's kind of interesting that some here shove the problem to angular.
> Angular is for example WAY more performant than react, especially when it comes to rendering big data.
> Navigation and native ui have not much to do with angular.
> The navigation is terribly slow, I have up to 4 seconds delay on my Huawei Mate9 on every page transition that is more than just some text.
> It is for me currently the main concern as I would never be able to publish my product in this state. Sadly there seems to be no solution for this (like for most of the things in nativescript).
> 
> Linking demo apps and saying "hey, this is kinda fast enough, so it's all your fault" is not very nice. Especially if the demo apps also have up to 2 seconds delay/frame drops on transitions.
> I also think that around 2 seconds startup for a simple app with a few pages is way too much.
> You can get react native to under 0.5s (try any fb app, twitch, airbnb..) startup and even webapps to around 1s (angular..).

Airbnb does only use React Native for specific screens, same for Facebook etc. Also Airbnb stopped using React Native a while ago.

However it's true that performance is better in React Native because they have native animation:
https://facebook.github.io/react-native/blog/2017/02/14/using-native-driver-for-animated

And if you want the real native implementation of navigation they have:
https://github.com/wix/react-native-navigation

**Comment by NickIliev** [comment]
@Bessonov no - the Playground is not using bundle or other optimizations.

**Comment by raulbojalil** [comment]
I was having this issue too. This issue coupled with others (mainly memory issues) made me go full native and never look back. All these cross-platform frameworks sound cool on paper, but in practice there a lots of issues (and no solutions), they will simply never beat true native development. I'll still use NativeScript though, but for really simple applications (which are not the majority).

**Comment by RichardLindhout** [comment]
@raulbojalil Flutter.io is really cool though. I could not see any performance differences with a real native application.

**Comment by raulbojalil** [comment]
@RichardLindhout Cool, thanks for the heads up, I'll be sure to check that out.

**Comment by leoc11** [comment]
@NickIliev is there any Playground apk that have used the optimizations you have mentioned?

**Comment by andrewm-mitchells** [comment]
This thread is old but I believe the issue all you guys are experiencing is the same as the one I experienced and I spent 4-5 days looking for different solutions, testing other templates and trying out non Angular builds (NS Core).
The issue seems to be in garbage collection/lack of it. Adding `"markingMode": "none"` in `package.json` in the `src` folder fixed the problem for me and now Android is very close in terms of performance to iOS.

**Comment by aranmohyeddin** [comment]
` tns run android --bundle --env.uglify --env.aot --env.snapshot` made a huge deference for me

**Comment by csimpi** [comment]
@NickIliev Still no improvements on this? Our app is a major app and got to be extremely slow. There are no bottlenecks, and after I click through all of the tabs the navigation is slightly better, so this is not on our side, it's on your side. Please improve this or you'll loose your devs. I'm with NS for 2 years but considering to drop it and redo everything on Flutter :(

**Comment by NathanaelA** [comment]
@csimpi - We personally run multiple applications for multiple clients all the time (and I personally have a app I built on my own phone that runs 99% of the time), and I never see any slow downs.   

Normally if you are seeing navigation slow downs this is caused by one of two things:
1. You not releasing memory refs when you navigate away from screens so that your memory usage is climbing on each navigation, causing it to get slower.   I have fixed many apps for external developers where this was the primary cause of issues. 
2. You are using very complex layouts, which if you simplify will speed up the initial load, or if you defer the layout of off-screen pieces if can also effect the application speed.  (Example: I had one application I worked on that had like 100 different settings in a side navigation for filtering and sorting data, when the screen was being rendered the first time it was painful (like 5 secs).  I pulled the search/filter side menu out of that layout, and added code so that the first time the side menu is pulled out it then built it.    The app become instant nav to that screen and instant build of the side nav when it was needed.    Night and day difference.)

Btw, if you want to go use Flutter, it is a awesome framework for the **developer** experience, I don't believe it is a great framework for the end user / end result.   The number of core design issues and bugs, are something that effected both Flutter apps I created for clients.     If I was going to switch frameworks, I would either go Kotlin/Swift or React Native (and I really dislike React), they are by far much, much, much better frameworks than Flutter.

**Comment by csimpi** [comment]
@NathanaelA  Wow thank you! I'm glad you are still on the board, I was afraid NS is abandoned for now.

1. If you take a look at my comment you can see that even the opposite is true. When I go through all of the tabs, then the app gets a bit faster, smoother. If this would be a memory issue, it should be slower as I'm using the app.

2. Last week I went through the layout with the overdraw debugger, there's no real complexity anymore, I decreased the overdrawing very aggressively with this tool. Even changed the base style of NS (more info here: https://github.com/NativeScript/nativescript-angular/issues/2325) .

I'm very excited this part though:
,,I pulled the search/filter side menu out of that layout, and added code so that the first time the side menu is pulled out it then built it."

Can you please elaborate on this? What does that mean pulled out / added code?

**Comment by mykone** [comment]
Hello @NathanaelA I am having a similar issue.. But mine is a little different. When my modal loads the first time, it loads fast.. When I load it the second time, it takes about 3 seconds to load, and something is blocking even my loading progress to show..

I tried your releasing refs.. Like so.

```
    this.$refs.scrollView1 = null
    this.$refs.scrollView2 = null
```

But the same experience is happening. My nesting isn't very deep, so it's not too complex. But I agree.. Something isn't released in memory, but I can't seem to find what it is.

**Comment by NathanaelA** [comment]
> Can you please elaborate on this? What does that mean pulled out / added code?

Basically rather than have the main layout create this menu as part of the layout, I put it into a separate component that I loaded and created on demand.    Once it was created, I cached it while on the screen, so I wouldn't have to recreate it while the screen was still open, however, when I closed the screen I killed the refs to it so that it


>     this.$refs.scrollView1 = null
    
This probably will do nothing, unless you are manually creating the $refs.* stuff.   What I'm talking about is more along the idea of this.somex = this.page.getById("someid"); so the if the page is never released properly, the someid is never released properly...     A lot of people assume NativeScript is like a Browser, where when you navigate to a different page; everything on the prior page is cleared.   NativeScript is more like a SPA (Single Page App), where everything is retained in memory unless you tell NS to clear it .
