### ISSUE TITLE
Stop event propagation in NativeScript ios tap event

### ISSUE THREAD

**Issue by saikumar-madana** [NativeScript/NativeScript#4883]
I have a `tap` event in my code. Its parent(not an immediate parent) also has `tap` event. In `Android`, everything works fine. But in `ios`, the `event` is propagating upwards to that parent. How to stop that `event propagation` (such as `event.stopPropagation()` in javascript).

Sample XML code:
```
<StackLayout  tap="newsDetails" data-args="{{ $value }}">
     <StackLayout orientation="horizontal" >
         <Label text="Share" class="icon" tap="shareNews" data-args="{{ $value }}"/>
     </StackLayout>
</StackLayout>
```

**Note: I am using NativeScript core**

Please help me find the solution.

**Comment by NickIliev** [comment]
This question is answered [here](https://stackoverflow.com/questions/46403682/stop-event-propagation-in-nativescript-ios-tap-event).

please use this repository for posting issues, bugs, and feature request. For how-to related question use the community channels like [https://discourse.nativescript.org/](https://discourse.nativescript.org/)

**Comment by saikumar-madana** [comment]
@NickIliev, actually the question in `StackOverflow`(which you shared above) was asked by me only. The answer did not solve my problem.  That's why I asked here. Please help me to solve this.  I searched thoroughly for a solution.  But, I did not get. 

Thank you.

**Comment by saikumar-madana** [comment]
@NickIliev ,  please open the issue as it is not solved in the link you mentioned and I don't find a solution anywhere else. I need a solution to this.

**Comment by NickIliev** [comment]
@saikumar-madana as discussed in the SO thread - this is the way the event propagation works on IOS. The only solution is to use `isUserInteractionEnabled` to disable the event propagation. The solution is to avoid using identical events in the same space and change the logic so that taps won't overlap. From UI perspective using different taps in the same area would lead the user to confusion as it would trigger two different actions with one tap. 

As this is the expected native iOS behavior the issue is not considered a bug.

Alternative solution:
You can use [this approach ](https://github.com/NativeScript/NativeScript/issues/3006#issuecomment-258077802)and extend the gesture recognizer while implementing your own logic.
