### ISSUE TITLE
Memory leak when using Google map on real device iOS (app falls)

### ISSUE THREAD

**Issue by newapx** [NativeScript/NativeScript#4889]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes

### Tell us about the problem
The problem when using Google maps, application on iOS on the real device (iPad 2, iOS 9.3.2)  falls without any messages (including in device logs). 
Application actively uses cards on different screens.

I created test application for the analysis which consists of two screens, from the first causes the second on which Google map is connected.

Having analyzed a situation (I used Xcode for monitoring) I see:
Switching between screens considerably increases busy memory application (from 50 to 100 Mb), in case of return on the first screen it is released not directly, and after some time, repeated opening of the second screen increases busy memory again and so on, as a result consuming of memory reaches some limit when application falls.

I tried to use maps:
- by means of https://github.com/dapriett/nativescript-google-maps-sdk plug-in;
- by means of Placeholder and creation in a code.
Results almost identical - application falls uses after a while.

Having created test native application for iOS (also two screens), in native application when closing the screen with a map and return on the first screen memory is released correctly.

### Which platform(s) does your issue occur on?
iOS Angular

### Please provide the following version numbers that your issue occurs with:
```
┌──────────────────┬─────────────────┬────────────────┬─────────────┐
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.2.1           │ 3.2.1          │ Up to date  │
│ tns-core-modules │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-android      │ 3.2.0           │ 3.2.0          │ Up to date  │
│ tns-ios          │ 3.2.0           │ 3.2.0          │ Up to date  │
└──────────────────┴─────────────────┴────────────────┴─────────────┘
```

```
"nativescript-angular": "^4.2.0",
"nativescript-google-maps-sdk": "^2.3.2",

```
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

https://github.com/newapx/nativescript-test-map-leak

**Comment by NickIliev** [comment]
@newapx the Placeholder module is meant to be used only in NativeScript Core application and should never be used in an Angular application. 
Instead of Placeholder use the Angular way - by using **selectors**.
Removing the Placeholder will resolve your memory leak.

For example, [here we are creating a component that will be reused via its selector](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/81f4e0c5408b9c85ddcf897cf4ce68f0451a4c3e/app/ui-category/listview/update-child-component/update-child-component.component.ts#L5).
The component is reused [here](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/81f4e0c5408b9c85ddcf897cf4ce68f0451a4c3e/app/ui-category/listview/update-child-component/update-child-component.component.html#L6).

**Comment by pauly815** [comment]
I'm observing this issue as well with the MapView.

**Comment by newapx** [comment]
I tried to use directly adding of addSubview of the created view map (and Apple and Google) the situation with consuming of memory is even worse than with Placeholder
