### ISSUE TITLE
WebView no sound on iOS11

### ISSUE THREAD

**Issue by gregersen79** [NativeScript/NativeScript#4940]
If setting the src of WebView to ex. www.youtube.com, and then play a video, there is no sound on iOS11. 
iOS10 works fine.

### Which platform(s) does your issue occur on?
iOS11 (haven't tested on Android)

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.21
- Cross-platform modules: 3.2.0
- Runtime(s): 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Create a new project, insert a WebView with src="https://www.youtube.com".
And play a video on youtube.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
<Page class="page"
    navigatingTo="onNavigatingTo"  
    xmlns="http://www.nativescript.org/tns.xsd">

    <GridLayout rows="*">
        <WebView id="webView" src="https://www.youtube.com" />
    </GridLayout>
</Page>
```

**Comment by NickIliev** [comment]
@gregersen79 I have created [this test project ](https://github.com/NickIliev/NativeScript-Issues-2017/tree/master/NativeScript/issue_4940)and can confirm that indeed there is no sound on iOS11 real device. However, thеre is a sound when running on iOS 11 emulator and I have noticed that this issue is observed by native iOS developers (post [here](https://forums.developer.apple.com/thread/79053)) so it might be related to native iOS 11 bug. 

We will investigate further and post any related information on this issue.

**Comment by gregersen79** [comment]
@NickIliev Thank you.

**Comment by gregersen79** [comment]
This is a bit embarrassing, but just noticed the Ring/Silent button on the side of the iPhone was set to silent, after switching it on, I got sound on iOS11 ("unfortunately" all of our 3 iOS11 test devices where set to silent).
@NickIliev could this also be the case in your end?

**Comment by NickIliev** [comment]
@gregersen79  Strangely enough, this was not the case on our iOS 11 device - will retest and come back with more info.

**Comment by NickIliev** [comment]
@gregersen79 Update: it appears that indeed the sound is by default turned off and only after manually pressing the ring hardware button the sound is turned on. Closing this issue as expected behavior for iOS.
