### ISSUE TITLE
CSS padding property cuts off text

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/NativeScript#5080]
### Tell us about the problem
I've run into an issue where it seems that the space calculation does not work properly when using CSS padding and sentences are "cut off" on iOS (haven't tried Android yet)

### Which platform(s) does your issue occur on?
iOS (will check Android later today)

### Please provide the following version numbers that your issue occurs with:
```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.3.0           │ 3.3.0          │ Up to date    │
│ tns-core-modules │ 3.3.0           │ 3.3.0          │ Up to date    │
│ tns-android      │                 │ 3.3.1          │ Not installed │
│ tns-ios          │ 3.3.0           │ 3.3.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

### Please tell us how to recreate the issue in as much detail as possible.
See the example below (also available [here](https://github.com/abhayastudios/test-css))

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

The first `WrapLayout` without the padding renders correctly, but the text in the second `WrapLayout` with the padding is cut off.

```
import { Component, OnInit } from "@angular/core";

@Component({
  template: `
    <StackLayout horizontalAlignment="center">
      <WrapLayout>
        <Label class="wrap text" textWrap="true" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin malesuada, dolor et vulputate condimentum, sapien sapien semper ligula, eget imperdiet turpis est efficitur ipsum."></Label>
        <Label class="wrap text open-sans" textWrap="true" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin malesuada, dolor et vulputate condimentum, sapien sapien semper ligula, eget imperdiet turpis est efficitur ipsum."></Label>
      </WrapLayout>
      <WrapLayout>
        <Label class="wrap text padding" textWrap="true" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin malesuada, dolor et vulputate condimentum, sapien sapien semper ligula, eget imperdiet turpis est efficitur ipsum."></Label>
        <Label class="wrap text padding open-sans" textWrap="true" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin malesuada, dolor et vulputate condimentum, sapien sapien semper ligula, eget imperdiet turpis est efficitur ipsum."></Label>
      </WrapLayout>
    </StackLayout>
  `,
  styles: [`
    .text { 
      margin-top: 20; 
      font-size: 14;
      text-align: left;
      vertical-align: top;
    }
    .wrap { width: 40%; }
    .padding { padding: 0 10; }
    .open-sans { font-family: "Open Sans", OpenSans-Regular; }
  `]
})
export class TestCssComponent implements OnInit {
  constructor() {}

  public ngOnInit() {}
}
```

**Comment by NickIliev** [comment]
@abhayastudios  confirming this as unexpected behavior.
Steps to reproduce use the above snippet or [this test application](https://github.com/NickIliev/NS-Issues/blob/master/NativeScript/issue_5080/app/item/items.component.ts)

Result: When `padding` is applied to `Label` inside a dynamically sized layout (without set `height`) and with `textWrap` set to `true` the content is clipped instead of the height being adjust accordingly. Observed with WrapLayout and GridLayout.

Remove the `padding` and the content text will fit.
**Observed on iOS only -** works as expected on Android.

**Comment by RobertCrowdis** [comment]
I'm having this issue too. It's driving me nuts! If I assign a height, then the text will display. But then it gets centered to it's "height" and I cannot push it around - even if it is in another container. Would love to see a fix.

**Comment by stefan-kolb** [comment]
For me this also cuts off in Android with a construction like this:
```
<StackLayout class="p-10" verticalAlignment="center">
        <GridLayout rows="auto" columns="10, *, 10">
            <Label row="0" col="0" text="&#xf0d9;" class="fa" verticalAlignment="center" visibility="hidden"></Label>
            <Label row="0" col="1" class="p-10" text="{{ today | date: 'MMMM' }}" textAlignment="center" fontWeight="bold">/Label>
            <Label row="0" col="2" text="&#xf0da;" class="fa" verticalAlignment="center" visibility="hidden"></Label>
        </GridLayout>
</StackLayout>
```

**Comment by Manbearpixel** [comment]
Noticing the same behavior reported:

#### component.html
```
<FlexboxLayout class="page">
  <ScrollView>
    <ContentView class="card">
      <StackLayout>
        <Label class="h2" textWrap="true" text="Heading"></Label>
        <Label class="body" textWrap="true" text="Content"></Label>
      </StackLayout>
    </ContentView>
  </ScrollView>
</FlexboxLayout>
```

#### component.scss
```
.card {
  background-color: #eeeeee;
  width: 100%;
  padding: 7;
  box-sizing: border-box;
}
```

The only workaround I currently see working is applying the same padding amount to the bottom of the final content piece within the `ContentView`:

```
.card {
  ...
  .body {
    padding-bottom: 7;
  }
}
```

**Comment by NickIliev** [comment]
I am no longer able to reproduce the issue (e.g by using [this Playground](https://play.nativescript.org/?template=play-ng&id=dTmk6T&v=2) it seems that everything is working as expected)

@abhayastudios not sure why you are using `ContentView` and not directly applying the CSS class to the stack layout. Nevertheless, while using [this Playground demo](https://play.nativescript.org/?template=play-tsc&id=K8wytl&v=3) I am not able to reproduce the issue (replaced the CSS class `p-10` with explicit padding for better demonstration).

@stefan-kolb same case- I've created [this Playground](https://play.nativescript.org/?template=play-tsc&id=K8wytl&v=2) and the issue seems not to be reproducible anymore
