### ISSUE TITLE
Nativescript architecture question

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5138]
### Did you verify this is a real problem by searching [Stack Overflow]
Yes

### Tell us about the problem
Hello guys I searched on stackoverflow 2 days ago, but noone is answering ,
I have 2 quick questions:
1. Does apk file I generate with "tns build android" support 32bit and 64bit architecture??
2. How can I implement login details,
On iphone it is that way that you can remember the login to apps if the phone itself is protected by a code.How can I implement it on Android and Iphone , to allow to remember the login if the phone is anyhow protected by a code.

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.1

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by NickIliev** [comment]
@markomiljkovic you can see the supported architectures for which NativeScript build [here for Android](https://docs.nativescript.org/runtimes/android/requirements#supported-application-binary-interfaces-abi) and [here for iOS](https://docs.nativescript.org/runtimes/ios/requirements#supported-application-binary-interfaces-abi). 

Regarding your second question, I would advise posting a how-to related question in the community channels in order to keep this repository for logging issues, bugs, and feature requests. 

As far as I understood the problem you are trying to solve, you need your application to "remember" the login information for future reuse - if that is the case one simple way to do that is to use the [application-settings](https://docs.nativescript.org/cookbook/application-settings) module

**Comment by markomiljkovic** [comment]
Ok thank you very much,
sorry but I have one more question:
I have built my apk file and installed it on my mobile devices,
but on samsung S5 app is running ok , but on samsung s8 its running very slow
is it maybe problem that Galaxy S5 chipset architecture is 32bit and Galaxy S8 has 64bit architecture.
and how can I fix that, how could I generate another apk file ???
