### ISSUE TITLE
Android Emulator Can't Run

### ISSUE THREAD

**Issue by npmtan** [NativeScript/NativeScript#5145]
I kept having this issue when trying to run my Android Emulator using Android Studio
Event Log message:
Emulator: Process finished with exit code -1073741819 (0xC0000005)

I've built my project using this command: 
tns build android --sdk 26

My emulator device also runs API 26.

Please advise

**Comment by tsonevn** [comment]
Hi @npmtan,
If I understand you correctly you are able to build successfully your project, however, you  are unable to start the Emulator via Android Studio. 
If this is the case it seems that the problem is related to Android Studio in the machine.
Something that could help to resolve the issue is to update your tools with SDK manager. Regarding that, you could review [the article from the official Android docs.](https://developer.android.com/studio/intro/update.html#sdk-manager)

Another option could be to increase the ram of the AVD virtual emulator.


Hope this helps
