### ISSUE TITLE
[iOS] ListView inside AbsoluteLayout resize issue

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#5152]
If you have a ListView inside an AbsoluteLayout, both of them having width and height set to 100%, on orientation change the ListView doesn't refill completely the AbsoluteLayout.

Example app available:

```
git clone https://github.com/surdu/BugReportApp.git
git checkout listview-resize
```

How to reproduce:

1. run the example app on iOS device (tested on iPhone 6 plus, ios 11.0.1 and several others)
2. change the orientation of the phone (from any orientation to the other)
3. notice how the list view (green) doesn't fill the AbsoluteLayout anymore (red)

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 3.3.1           │ 3.3.1          │ Up to date    │
│ tns-core-modules │ 3.3.0           │ 3.3.0          │ Up to date    │
│ tns-android      │                 │ 3.3.1          │ Not installed │
│ tns-ios          │ 3.3.0           │ 3.3.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘

```

**Comment by tsonevn** [comment]
Hi @surdu,
Thank you for contacting us. 
I reviewed your case and it seems that this is expected behavior while using AbsoluteLayout for a ListView's container. As it is mentioned in the [documentation ](https://docs.nativescript.org/ui/layout-containers) - "The AbsoluteLayout will not enforce any layout constraints on its children and will not resize them at runtime when its size changes.". 
Regarding that, I would recommend using GridLayout, which will set the width and height of the ListView to be 100%, every time when the orientation is changed.
```
<GridLayout>
     <ListView>
     </ListView>
</GridLayout>
``` 

Let me know if this is applicable to your case.

**Comment by surdu** [comment]
Hello @tsonevn ,

Sorry, my bad 😞 . I thought because it worked for the others must be a bug and didn't check the documentation.

Would GridLayout be the way to go about overlaying a loading screen over the ListView? It works, I was just wondering if it's the "correct" way.

**Comment by tsonevn** [comment]
Indeed using the GridLayout would be the easiest way to overlaying a loading screen over the ListView.
