### ISSUE TITLE
How to setFocusable() in nativescript?

### ISSUE THREAD

**Issue by dyazincahya** [NativeScript/NativeScript#5171]
I want to set focus, because if the focus in textField, when I open the page then keyboard always show first and my screen so narrow.

Here I use this code for set the focus, but I don't know why this code not working in my place
let foc = page.getViewById("my-text-field");
foc.android.setFocusable(false);

| Component            │ Current version │ Latest version │ Information      │
│ nativescript           │ 3.2.1                  │ 3.3.1               │ Update available │
│ tns-core-modules │ 3.2.0                  │ 3.3.0               │ Update available │
│ tns-android           │ 3.2.0                  │ 3.3.1               │ Update available │
│ tns-ios                   │                          │ 3.3.0                │ Not installed  

Please help me,
Thank you

**Comment by tsonevn** [comment]
Hi @dyazincahya,
Perhaps you are calling `setFocusable`  method too early, while the native instance of the component is still not initialized. Regarding that, it would help if you provide some more info about the problem and sample project, which could be debugged locally.

In the meantime, if you need to hide the keyboard, which is shown because of the focused field, you could use [utils module](https://docs.nativescript.org/core-concepts/utils#platform-specific-methods) and its `dismissSoftInput` method

**Comment by dyazincahya** [comment]
Sorry late response,,,
I was use that, but i don't know in my place is not working. Are you have the example for in this case?

**Comment by tsonevn** [comment]
Hi @dyazincahya,
I reviewed your case one more time and at a second glance through the issue, it seems that you are looking for TextField's `isEnabled` property.
For example:
```
<TextField loaded="tfloaded" isEnabled="false" hint="" text="test1" />
```
