### ISSUE TITLE
notify function doesn't work from nested component

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5204]
Hey guys,

I am trying to so something not so obvious with nested component and I kind of stuck and I think you can help me... :slightly_smiling_face:

I want to create a click animation in some element with directive that takes that referenced element and listen to touch event and invoke the animation, something like this - `<StackLayout clickAnimation></StackLayout`

the click animation looks like this:
```
this.view.on('touch', (args: TouchGestureEventData) => {
    if (args.action === TouchAction.down) {
        this.view.animate({ scale: { x: 0.9, y: 0.9 }, duration: 50 });
    }
    if ((args.action === TouchAction.cancel || args.action === TouchAction.up)) {
        this.view.animate({ scale: { x: 1, y: 1 }, duration: 50 });
    }
});
```
Very simple...

The thing is that when I have a component inside this element, like this ->
```
<StackLayout clickAnimation>
    <rounded-picture></rounded-picture>
</StackLayout
```
the touch event is not bubbling up...stuck on the component...

Now, I am familiar with the `Output` thing...But `Output` just let me hook to any kind of event...and this is not the wanted behaviour...as you understand I actually want to raise up the `touch` event for the `StackLayout`, because this is the only way that the directive can catch the event

So I taught about nice workaround that I really hope that going to work...:)

The idea is to make a directive that going to be in the most up level of the nested component HTML that will listen to the `touch` event and programmatically notify his parent with the `touch` event

Let me add a code sample just to be sure you understand me correctly

rounded-picture HTML:
```
<StackLayout passTouchEvent>
    <Image #image class="full-stretch" backgroundColor="#f2f2f2" [width]="pictureRadius*2" [height]="pictureRadius*2" [borderRadius]="pictureRadius" [borderWidth]="borderWidth"
    [borderColor]="borderColor" (tap)="onTap()" stretch="fill" [src]="source"></Image>
</StackLayout>
```

passTouchEvent directive:
```
...
ngAfterViewInit() {
    //used to set the starting position.
    this.view.on('touch', (args: TouchGestureEventData) => {
        const parent = (<ViewBase>this.view.parent.parent); // I take the parent of the parent because this is the actual View parent
        parent.notify({ eventName: 'touch', object: parent });
    });
}
...
```

Now, just so you know what is happening right now...I can get the parent, but it seems not to success with the `notify`

I tried to do the following in the outer HTML:
```
<StackLayout (touch)="onTouch()">
    <rounded-picture></rounded-picture>
</StackLayout
```

and in the TS file I've done this:
```
public onTouch(args) {
    console.log("heyyy");
}
```

But is seems not to call the onTouch function

Very sorry for the long post... lol :sweat_smile:

**Comment by NickIliev** [comment]
Hey @shabib3 in Angular you have [EventEmitter](http://learnangular2.com/outputs/) which will do this job for you (will notify the parent for emitted events).

In [this demo application](https://github.com/NickIliev/nativescript-ng-cosmos) you can find basic example. Below are the steps that explains how the emitting works:
- [create our nested layout ](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/toolbar/toolbar.component.html)(called `toolbar`)
- [create the Output emitter](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/toolbar/toolbar.component.ts#L12) (in this case called `notify`)
- on each separate `tap` [tell the emitter what to emit](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/toolbar/toolbar.component.ts#L14-L32) (in this case some different string values)
- in the parent layout apply the [nested layout along with the emitter and its callback](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.html#L12) (again the emitter is called 'notify' just because we choose this name)
- finally[ create the business logic what to happen on each separate tap emitted from the nested view](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/pages/apod/apod.component.ts#L68-L99)

Please note that this repository is for reporting issues, bugs, and features related to NativeScript.
For how-to related questions use the community channels like [discourse.nativescript.org](https://discourse.nativescript.org/), the [community slack channel](https://nativescriptcommunity.slack.com/messages/general) or [SO](https://stackoverflow.com/questions/tagged/nativescript)

**Comment by shabib3** [comment]
@NickIliev - Did you see what I wrote about the `Output` solution?

Like I said, the `Output` solution doesn't give me a natural "bubbling" event to container elements witch doesn't allow me to hook the `touch` event on the wanted element.

**Comment by shabib3** [comment]
It seems to me that the `notify` function not working or that I don't get how to use it...
Now I tried the simplest code for trying to notify on "tap" event and it didn't work

let me write you the code example:

HTML:
```
<StackLayout id="1" (tap)="tapOnFirst()">
    <Label text="first"></Label>
</StackLayout>

<StackLayout (tap)="tapOnSecond()">
    <Label text="second"></Label>
</StackLayout>
```

TS:
```
tapOnFirst() {
   console.log('first');
}

tapOnSecond() {
    console.log("second");

    const view = <View>this._page.getViewById("1");
    view.notify({ eventName: "tap", object: view });
}
```

Now when you tap the second element you should see:
```
second
first
```

but you won't see this and you will see this:
```
second
```

**Comment by shabib3** [comment]
Like I said - I want to invoke all the eventListeners of "tap" on a specific element, even if the eventListener is in directive which not available for the component.

Understand me? :)

**Comment by NickIliev** [comment]
@shabib3 use `notify` for your custom events.

Your case can be resolved with [nativescript-dom](https://github.com/NathanaelA/nativescript-dom) plugin but I am not sure if it has Angular support. More information [here](https://stackoverflow.com/questions/42662511/how-do-i-programmatically-simulate-a-tap-event-on-a-view-in-nativescript)

**Comment by shabib3** [comment]
Awesome @NickIliev I will take a look! (:
