### ISSUE TITLE
How to closing a fullscreen modal page with tap()? Only iOS

### ISSUE THREAD

**Issue by BeatPots** [NativeScript/NativeScript#5212]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Didnt find any record for this issue.

### Tell us about the problem
In iOS, I need to close my modal page when I tap in any point of the page.
'cause in iOS the modal page is always fullscreen, how can i do? It's possible?

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.3.0
- Cross-platform modules: 3.3.0
- Runtime(s): 3.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Just create in iOS a modal page (fullscreen:true in modal options) and tap outside the modal.
I tried to insert a tap() on the parent gridlayout of the modal page but this event is not triggered when i tap out of the gridlayout.

<GridLayout rows="auto,auto" class="grdLayParent" (tap)=closeModal()>
    <Label [text]="'SORTING_TYPE' | translate" class="margin-bottom"></Label>
    <GridLayout row="1" rows="auto, auto, auto">
	[..]
    </GridLayout>
</GridLayout>

**Comment by NickIliev** [comment]
You can closse the modal by triggering the `closeCallback()` method from `ModalDialogParams`

Demonstration can be found in [this example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/master/app/modal-page/sample-modal-page-module-example/modal-view.ts#L35)

**Comment by BeatPots** [comment]
Yes,
I know I have to use this method (closeCallback, sorry for the missing quotes around), but my problem is that the parent gridlayout doesn't cover all the blank modal page, therefore the tap on the this gridlayout is fired only in the middle of the page. I want that the tap works at any point in the page. Can you understand me? Sorry for my english . .

**Comment by NickIliev** [comment]
@BeatPots can you provide [Playground demonstration](https://play.nativescript.org/) of your issue

**Comment by BeatPots** [comment]
OK Nick,
I have created an example on playgroud, this is the link:
https://play.nativescript.org/?template=play-ng&id=rOcNny

Well, if you use an android device, you can close the modal page tapping in any point out of the grey gridlayout; if you use an ios device, the modal page is fullscreen and there is no way to do this . .

**Comment by NickIliev** [comment]
@BeatPots thank you for providing the PlayGround link which helped a lot to understand the issue you are dealing with.

What is actually happening is that you are applying a CSS rule for your parent GridLayout as follows:
```
.grdLayParent{
    vertical-align: center;
}
```

Now because the GridLayout does not have predefined sizes you are actually shrinking the size of the Grid to take just as much space as needed (you can better illustrate the situation by applying contrast background colors to your GridLayouts e.g. green for the outer one and red for the inner one)

The solution would be to either provide size that takes all the available space for the parent grid (and then vertically and horizontally center the inner Grid) or to directly center the inner grid using the **rows** and **columns** properties

For example - remove the vertical-align CSS rule and apply the following:
```
<GridLayout rows="2*, *, 2*" columns="*, *, *" (tap)="closeModal()" backgroundColor="green">

	<Label row="0" text="SORTING_TYPE" ></Label>

	<GridLayout row="1" col="1" rows="auto, auto, auto" backgroundColor="red" color="white">
		<StackLayout orientation="horizontal" horizontalAlignment="left" (tap)="onAlphaTap()" >
			<Label text="SORTING_TYPE_ALIAS"></Label>
		</StackLayout>
		<StackLayout row="1" orientation="horizontal" horizontalAlignment="left" (tap)="onPlateTap()">
			<Label text="SORTING_TYPE_PLATE"></Label>
		</StackLayout>
		<StackLayout row="2" orientation="horizontal" horizontalAlignment="left" (tap)="onNearnessTap()">
			<Label text="SORTING_TYPE_NEARNESS"></Label>
		</StackLayout>
	</GridLayout>

</GridLayout>
```
The above is just one way to create a centered inner child .. now if you apply the vertical-align to the outer Grid (the parent one0 you will see that it will shrink and you will again have an area that is not tappable.

Variant without vertical-align
[https://play.nativescript.org/?template=play-ng&id=rOcNny&v=2](https://play.nativescript.org/?template=play-ng&id=rOcNny&v=2)

The same scenario with vertical align papplied to the parent layout will shrink the layout as it will only take the space needed and vertically center the layout.
[https://play.nativescript.org/?template=play-ng&id=rOcNny&v=3](https://play.nativescript.org/?template=play-ng&id=rOcNny&v=3)

**Comment by BeatPots** [comment]
Thank'you Nick, now my tap works on the entire modal page!
Last thing: there is a way to avoid calling the closeCallback twice?
 (this happens when I tap in a one of the stacklayouts, onAlphaTap, onPlateTap . .)

**Comment by NickIliev** [comment]
@BeatPots there is a conceptual difference in how event propagation works on iOS and Android.
So if you remove the call to `this.closeCallback` the callback will be called only once on iOS (and will work as expected) however it won't be fired from the nested components with `tap` event on Android. On Android, the event propagation is implemented so that only the topmost component will trigger an identical event (tap in our case) while on iOS all overlapping components might trigger the same event.

To overcome this and in the same time execute `closeCallback` only once but then make it work on both Andriod and iOS we can wrap the call to `closeCallback` inside the nested taps in a platform-specific code.
e.g.
```
import { isAndroid } from "platform";
...

    onAlphaTap() {
        console.log("onAlphaTap()");
        if (isAndroid) { 
            this.closeModal();
        }

    }

    onNearnessTap() {
        console.log("onNearnessTap()");
        if (isAndroid) {
            this.closeModal();
        }
    }

    onPlateTap() {
        console.log("onPlateTap()");
        if (isAndroid) {
            this.closeModal();
        }
    }

```

[Demo Playground link](https://play.nativescript.org/?template=play-ng&id=rOcNny&v=4)

**Comment by BeatPots** [comment]
Ok!! Thank'you very much!
Now my understanding of events is better!
Ola!
