### ISSUE TITLE
Couple of issues on Mac OS Sierra after using NativeScript Setup Command 

### ISSUE THREAD

**Issue by inglesuniversal** [NativeScript/NativeScript#5222]
Hello: 

I installed NativeScript with the following command:

ruby -e "$(curl -fsSL https://www.nativescript.org/setup/mac)"

And I have a couple of issues that I have been trying to fix, but still I'm a little stuck on that...

on ios, the command 'tns run ios' works fine, but only if I open the emulator prior to running this command or unless if I retype this command twice.

the message I get on the terminal is this:

Searching for devices...
Unable to find applicable devices to execute operation. Ensure connected devices are trusted and try again.

now on android, after running the command 'tns run android' it shows the following message but it never opens... it kind of times out...

Searching for devices...
Starting Android emulator with image Nexus_5X_API_25
Cannot find connected devices.
Emulator start failed with: Cannot run your app in the native emulator. Increase the timeout of the operation with the --timeout option or try to restart your adb server with 'adb kill-server' command. Alternatively, run the Android Virtual Device manager and increase the allocated RAM for the virtual device.
To list currently connected devices and verify that the specified identifier exists, run 'tns device'.
To list available emulator images, run 'tns device <Platform> --available-devices'.

I was VERY excited to discover your Project, and I like the fact that is very well organized in all aspects. Hope I can be part of this community and look forward to hearing from you.

Happy coding on 2018!!!

**Comment by tsonevn** [comment]
Hi @inglesuniversal,
Thank you for contacting us and for your interest in NativeScript,

Regarding the first issue with iOS, could you provide some more info about the problem and if there is an error which is thrown while running `tns run ios` for the first time.

About the `tns run android` this seems to be related to the Android itself and not with the NativeScript Installation script. Most probably the problem is caused due to missing HAXM on your machine, which is needed while starting a simulator. 
To fix this issue you could install it manually by opening following dir `open $ANDROID_HOME/extras/intel`. There you will find `Hardware_Accelerated_Execution_Manager` folder. Open it and install `.dmg` file. Then restar the mashine and try again to run the project with `tns run android`.

Let me know if the problem still persists.
