### ISSUE TITLE
Visibility attribute is not working in onResume Event..

### ISSUE THREAD

**Issue by priyangamani** [NativeScript/NativeScript#5225]
In onResume event  i tried to visible some layout but it's not working &  tried to used the application setting also but it doesn't work.What is the problem with this layout and js?

///<XML>
```
<GridLayout row="2  visibility="{{ screen=='open'  ? 'visible' : 'collapsed' }}" >
<Label row="0" text="Message"  horizontalAlignment="center" verticalAlignment="bottom"  />
</GridLayout>
```
///<JS>
```
app.on(app.resumeEvent, function (args) {
  pageData.set("screen", open);
   page.bindingContext = pageData;
});
  ```

**Comment by tsonevn** [comment]
Hi @priyangamani,
Thank you for contacting us.
For your case, I would suggest using the page loaded event and on the second load of the page to show the needed Layout. 

This solution will work for Android, however, on iOS this event will not be fired on every app resume. This is a known issue which is fixed in the upcoming version. As a workaround, you could get the instance of the current page on resume event while using the Frame module.

Both scenarios with page loaded event and the workaround for iOS are shown in the below-attached sample app.
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1599767/Archive.zip)

**Comment by tsonevn** [comment]
Hi @wongwingho,
I tested your case while using the latest version of NativeScript 3.4, however, was unable to recreate an issue with the WebView and loading local files on it. For your convenience, I am attaching video and sample application. Please review it and make the needed changes, which will allow us to recreate this problem on our side.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/1599863/Archive.zip)

[ios_video_test.zip](https://github.com/NativeScript/NativeScript/files/1599870/ios_video_test.zip)
