### ISSUE TITLE
Question about plugin using native lib NS 3.4

### ISSUE THREAD

**Issue by mobilemindtec** [NativeScript/NativeScript#5254]
Hi, 

I updated one app to NS 3.4 and my plugin `nativescript-background-task` did broken. So I changed  android native lib that was at `nativescript-background-task/platforms/android/libs` to `nativescript-background-task/platforms/android` and change of `.jar` to `.aar` then it worked. Searching in release notes I'm not found nothing about this. Had any changes about lib location in plugins?

Thanks!

**Comment by tsonevn** [comment]
Hi @mobilemindtec,
Thank you for contacting us.
As you can see in the [plugin's](https://docs.nativescript.org/runtimes/android/plugins/plugins#android-plugin-elements) article, the directory that should contain the `.aar` or `.jar` files are as follow:
> platforms\android\MyLibrary.aar
> platforms\android\MyLibrary.jar

Hope this helps.

**Comment by tsonevn** [comment]
Hi @mobilemindtec,
Excuse me for the misunderstanding,
At this time there is an issue in android with the metadata, which is not generated for plugin's jar dependencies in platforms/android folder. This problem is already fixed with PR [918](https://github.com/NativeScript/android-runtime/pull/918) and it is available in @next android-runtime.

Hope this helps.

**Comment by mobilemindtec** [comment]
Ok, thanks!

**Comment by tsonevn** [comment]
Hi @mobilemindtec,
I just want to let you know that `tns-android` version 3.4.1 is already available.
Best regards
