### ISSUE TITLE
Documentation versioning

### ISSUE THREAD

**Issue by krisidmisso** [NativeScript/NativeScript#5255]
I love this framework {N} + Angular!! Recently I noticed that I struggled to find something in the documentation related to an older version. My suggestion is not to update the documentation, but to create a new one related to the new version, i.e webpack usage. Also a date of the updated document can help.

_Sample: [https://laravel.com/docs/5.5](https://laravel.com/docs/5.5) - You can see that most of their documentation is almost the same... but there are parts that are updated specific to the version you select in the top right corner._

Keep up the great job 👍 I am suggesting this framework to everyone i know

**Comment by tsonevn** [comment]
Hi @krisidmisso,
Thank you for the feedback,
This issue is already logged in the [docs repository](https://github.com/NativeScript/docs/issues/86). I would suggest leaving your comment on the old issue, where also the other user could vote for this feature.
For further info, you could keep track on the issue [#86](https://github.com/NativeScript/docs/issues/86)
