### ISSUE TITLE
FormattedText Span style does not override parent styles

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/NativeScript#5265]
### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem
If you have a `label` with an applied class and then you have defined `FormattedText` with couple of spans that apply different color for example, those specific styles are not applied. 

### Which platform(s) does your issue occur on?
Tested only on iOS, but problem is probably for android as well. 

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4
- Cross-platform modules: 3.4
- Runtime(s): 3.4

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-tsc&id=VKNU09&v=2

**Comment by tsonevn** [comment]
Hi @PeterStaev,
Thank you for logging this issue.
I tested this case and this issue seems to be reproducible only iOS. Also, I think that this issue is duplicated with [#4992](https://github.com/NativeScript/NativeScript/issues/4992). 
I am closing this one and would suggest leaving your comment on the old issue.

However, let me know if you think that the case is different and will reopen it.

**Comment by PeterStaev** [comment]
Thanks @tsonevn ! Yes, seems the same issue and yes seems it happens only on iOS
