### ISSUE TITLE
Feature Request - SVG for UI

### ISSUE THREAD

**Issue by jamesharvey2** [NativeScript/NativeScript#5278]
Hi NativeScript. 

Is there any way for you guys to let us freely use SVG HTML code inside NativeScript's XML UI ?

For instance, React Native has SVG plugin which can help us using SVG directly on UI 

https://www.npmjs.com/package/react-native-svg

We need something similar for NativeScript. 

Please make Canvas API plugin, SVG plugin... and implement more CSS3 styles to NativeScript. 
Currently, UI design elements of NativeScript is really minimum. Only basic UI can be created on NativeScript. I like functionality of NativeScript but I don't want to make something looks so basic.

Thanks,

**Comment by jamesharvey2** [comment]
and users should be able to animate any of SVG's properties using CSS3 keyframes.

**Comment by jamesharvey2** [comment]
SVG is mobile optimized and I see it as the best solution for UI design...and it can be 100% code.

**Comment by tsonevn** [comment]
Hi @jamesharvey2,
In case you need to use SVG graphics in NativeScript application, I would suggest using nativescript-svg plugin. 
Also, I would like to mention that the current version of npmjs will not work properly, because of some an error while the TypeScript files are transpiled in  JavaScript.  

Regarding that, I made some changes and uploading tgz file, which could be used in your project.

For your convenience, I am also attaching sample project, which demonstrates, how the plugin could be used. Also to the SVG Image you could also apply some of the available in [NativeScript animations](https://docs.nativescript.org/ui/animation).
[Archive.zip](https://github.com/NativeScript/NativeScript/files/1638703/Archive.zip)

**Comment by NickIliev** [comment]
Closing as duplicate to [https://github.com/NativeScript/NativeScript/issues/944](https://github.com/NativeScript/NativeScript/issues/944) (where the linked plugin is also posted)

**Comment by wanpeng2008** [comment]
Hi @tsonevn, 
I am also looking for a valid svg plugin. But the nativescript-svg@1.3.4 doen't work properly.
So your tgz file will be of great help. Could you please share it?  I can't find it in above links.
