### ISSUE TITLE
Activity Indicator not work if animation duration scale is disable.

### ISSUE THREAD

**Issue by mauriciosouza** [NativeScript/NativeScript#5308]
Activity Indicator does not work if in developer options-> animation duration scale- is not enabled. It would be a problem, because if you disable this option, the user does not see a loading for loading a list for example.

![photo5125277838772119502](https://user-images.githubusercontent.com/386078/35195694-8ef57434-feae-11e7-839f-2494735757fa.jpg)

**Comment by NickIliev** [comment]
@mauriciosouza this is expected behavior and it will affect only people that are aware what the developer option "animation duration scale" is doing - this you should not worry about people who are reseting their duration scale to OFF (or 0) (practically meaning no animation duration). By default, all Android users have "animation duration scale"  set to **1x**

In native Android, the ProgressBar (which stands behind ActivityIndicator for Android in N) is acting the same as in NativeScript - showing a default still  arrow photo
![progressbar](https://user-images.githubusercontent.com/18008302/35209520-1e2270b4-ff57-11e7-9628-4cadedfc9215.png)

Here is the ActivityIndicator  in NativeScript with "animation duration scale"  set to OFF
![progressbar-nativescript](https://user-images.githubusercontent.com/18008302/35209616-902a7422-ff57-11e7-92b0-cdb0a75854d5.png)

**Comment by mauriciosouza** [comment]
it's invisible to me
