### ISSUE TITLE
Android WebView <input type="file"> does not show 'Choose an action' upload options

### ISSUE THREAD

**Issue by btulsi-ygrene** [NativeScript/NativeScript#5313]
Android WebView `<input type="file">` does not show 'Choose an action' upload options

iOS WebView shows options
Android Chrome shows options, see image:
![image](https://user-images.githubusercontent.com/18336973/35295790-fa403400-002e-11e8-9fb2-a00ea6881394.png)

I have tried overriding `openFileChooser() ` and `onShowFileChooser()` in my working custom WebViewClient, but these methods appear to be hidden and are never called

**Comment by tsonevn** [comment]
Hi @btulsi-ygrene,
Thank you for contacting us.
In Android the WebView embedded browser control, but it's not fully autonomous and some actions will not be fully performed. Regarding that indeed [WebViewClient should be overwritten while implementing some extra methods.](https://stackoverflow.com/questions/5907369/file-upload-in-webview)
Regarding that, It would help if you provide more info about the case and why you need to use WebView with file input instead of [nativescript-file-picker](https://www.npmjs.com/package/nativescript-file-picker) or [nativescript-imagepicker](https://www.npmjs.com/package/nativescript-imagepicker).

Also, it would help if you provide sample project, which shows, how you extend WebViewClient

**Comment by btulsi-ygrene** [comment]
Hi @tsonevn,

Thank you for reviewing the issue.

The mobile app loads a mobile site within WebView. Within that mobile site are places to upload documents. Since I need the documents uploaded through the site, I can not use the suggested plugins.

I have created a sample project with an extended WebViewClient: [https://github.com/btulsi-ygrene/ns-debug/blob/master/app/home/home.component.ts](https://github.com/btulsi-ygrene/ns-debug/blob/master/app/home/home.component.ts)

`shouldOverrideUrlLoading()` is fired, but `openFileChooser()` is not.

**Comment by tsonevn** [comment]
Hi @btulsi-ygrene,
I researched your case and found that the openFileChooser method will be fired for Android 4.1 + and for 5.0+ should be used `shouldOverrideUrlLoading`. More about this topic could be found [here](shouldOverrideUrlLoading).

To be compatible with the older as well as the newer Android devices, you should implement both methods.

Hope this information helps.

**Comment by paulfrench** [comment]
The "here" link is a 404

**Comment by tsonevn** [comment]
the link is updated

**Comment by straweb** [comment]
Input type file is not working with latest nativescript version. Is there any solution with typescript?
