### ISSUE TITLE
ActionBar flat is causing bouncing

### ISSUE THREAD

**Issue by b4rtt** [NativeScript/NativeScript#5325]
Hi,

I realised that <ActionBar flat="true"> is causing boucing problem of page content when you use transition between pages. 

https://www.youtube.com/watch?v=ZlqmFXDWlc8&feature=youtu.be

When I remove flat="true" everything is fine. 

This is template code.
Is possible to get real ActionBar color without use flat="true" until it will be fixed?

Thanks and cheers from Czechia 🇨🇿

**Code:**
https://pastebin.com/eerKR2Z5

**Comment by tsonevn** [comment]
Hi @b4rtt,
First of all thank you for your interest in NativeScript.
We tested your case, however, was unable to recreate the exact same scenario
To investigate further this scenario please provide more info about your environment (CLI modules, runtime versions) as well as a sample project, which could be debugged locally.

In the meantime, I would suggest using the [TabView ](https://docs.nativescript.org/angular/code-samples/ui/tab-view) component instead of creating this custom created one.

In the future, it would help if you follow the template while logging new issue.

**Comment by b4rtt** [comment]
@tsonevn @NickIliev 
Yes I know that's better to use TabView but the strange problem is that problem is causing only use of flat="true".
