### ISSUE TITLE
Routing without angular and angular size

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [NativeScript/NativeScript#5403]
I just need one single example of how to navigate between pages without using angular, the only thing I found was something using ui/frames which opens a modal and thats not what I want. 

Obs: why do people use angular? It almost doubles the application size. Drawer template with typescript: 14mb. Drawer template with angular: 27mb. What the hell is up with that?

**Comment by diego-lipinski-de-castro** [comment]
My navigation problem was solved by using ui/frame.

But I still leave the angular question. Isnt it weird?

**Comment by NickIliev** [comment]
@diego-lipinski-de-castro the reason many people choose Angular instead of NativeScript Core is simply that the abstraction is already pretty familiar (web-developers with rich web knowledge). You can also have a single code base and ease the process of creation of web and mobile projects.

The choice whether to use TypeScript, plain JavaScript, Vue.js or Angular based projects is dictated by the developer personal preferences. Keep in mind that creating a build in release with bundling with Webpack, uglify, snapshot and AOT will decrease the package size.

If you choose to use NativeScritp Core you can refer to the [NativeScript Core documentation](https://docs.nativescript.org/) - notice that the first tab is selected ("NativeScript Core").

Here is [the navigation article](https://docs.nativescript.org/core-concepts/navigation#navigation) for the Core functionality. 
[Some additional examples](https://docs.nativescript.org/cookbook/ui/frame) in the Core Cookbook (examples only for NativeScript Core)

You can also use the TypeScript or JavaScript master-detailes templates as a reference on how to navigate and pass context. For example [here is the TypeScript master-detail template](https://github.com/NativeScript/template-master-detail-ts) and [specific example ](https://github.com/NativeScript/template-master-detail-ts/blob/d5696f4976c8707bf1adb0f605925a16f0ae19aa/cars/cars-list-page.ts#L44-L53)for navigation with page transition and passing context
