### ISSUE TITLE
Plugin android.view not showing in StackLayout

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#5434]
_From @RVEIII on February 15, 2018 21:49_

I have a plugin that I call into to give me some party android views that I wish to display on a {N} page's StackLayout.  This works for iOS.  We simply grab the UIViews and are able to set them using stackLayout.ios.addSubview.  To get the sizing correct so it fills the entire screen, we also do some stuff with setting the frame equal to the stackLayout.ios.bounds and setting the autoresizingMast to be flexible.

We're trying to integrate our solution with Android now.  I don't have a dev application but have some very simple code that displays the problem.  My plugin Java has a method that does this:

```
        TextView textView = new TextView(this.context);
        textView.setText("This is a test");
        textView.setLayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT));
        return textView;
```

And on the {N} side, we have a Page that contains a ScrollView as the content.  The content for that scrollview is a vertical StackLayout where I'm trying to set the TextView to be shown(oControl.view() returns the TextView):

```
            let stackLayout = new StackLayout();
            stackLayout.orientation = 'vertical';
            const linLayout = android.widget.LinearLayout;
            let layout = new linLayout(app.android.context);
            let layoutParams = new linLayout.LayoutParams(linLayout.LayoutParams.MATCH_PARENT, linLayout.LayoutParams.MATCH_PARENT);
            layout.setLayoutParams(layoutParams);
            layout.addView(oControl.view(), layoutParams);
            stackLayout.nativeView = layout;
            return stackLayout;
```

I've tried just about every different thing I could think of to make this work.  This is just the latest try.  The page shows but is blank. The one thing that is different that iOS is that the layout's Android native view returns as undefined at this point where the iOS equivalent is ready to be used at this point...I'm assuming it is just a difference in lifecycles.  But in this try here I try to set it myself

CLI: 3.4.0
Cross-platform modules: 3.4.0
Runtime(s): 3.4.1
Plugin(s): My plugin uses 3.4.0 cross platform.

I've been through the Slack channel and the {N} documentation and I can't find anything that clearly states how an android.view can be added to a StackLayout.  Please provide me with details on how to do this.  Thanks!

_Copied from original issue: NativeScript/android-runtime#951_

**Comment by tsonevn** [comment]
_From @NathanaelA on February 16, 2018 0:7_

@RVEIII - I would highly recommend you look at some of my visual plugins.    I have added android views to other android views fine.    

 However, maybe a even better resource for this is http://searchcode.nativescript.rocks and then do a search for LinearLayout, setLayoutParams, , addView, etc...

**Comment by RVEIII** [comment]
Hi @tsonevn, while you are looking at this, do you have any instructions you can give me as to how this *should* be implemented on my side?  I've tried many things and they all give me one of the following results:
- Page displays but is blank.
- ```java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.```

This is a blocker for the project I'm working on.  Any documentation you can provide as to how embedding pure native views in a {N} application for Android would be very helpful.

**Comment by vakrilov** [comment]
Hi @RVEIII 
The recommend approach in such cases is to create a custom component where you will have a complete control over the native UI that is created. You can read the [Building UI Plugins using Custom Components documentation article](https://docs.nativescript.org/plugins/ui-plugin-custom) for detailed explanations on how to do that. There you can create and setup the UI you need in the appropriate methods - for example `createNativeView()`.

Adding native UI the existing StackLayout directly in not recommended because of the following reasons: 

- There will be no NativeScript View instance associated to it, so this will break the cross-platform abstraction
- It might lead to unexpected behavior when adding other views (for example from XML) to the same `StackLayout`. In other words the NativeScript view tree wouldn't know about the native elements you have manually added.
- Styling with CSS and layouts might also not work properly for the same reason.

It would be helpful to share a bit more about your exact scenario, so that we can provide some more specific advices.

**Comment by RVEIII** [comment]
Hi @vakrilov - Wrapping our plugin in a {N} View as suggested in that article worked.  Thanks for the info!
