### ISSUE TITLE
[iOS] Custom ActionBar and rotation

### ISSUE THREAD

**Issue by demetrio812** [NativeScript/NativeScript#5453]
Hello,
I was testing the custom title view example written here:

https://docs.nativescript.org/angular/ui/action-bar#using-a-custom-title-view1

If I take it as it is it works (even if the title attribute in the ActionBar is not needed) but if you put stretch="none" to the image or if I remove the image completely, it is shown correctly when the view is opened but on rotation the text goes on the right, and stays there even if I rotate the phone back in portrait.

This is the sample code:
```
<ActionBar>
    <StackLayout orientation="horizontal"
                 ios:horizontalAlignment="center"
                 android:horizontalAlignment="left">
        <Label text="NativeScript"  class="action-label"></Label>
    </StackLayout>
</ActionBar>
```
**First run:**

![one](https://user-images.githubusercontent.com/385644/36540732-5ffacf60-17d3-11e8-8803-a55a1805d049.png)

**Rotate:**

![two](https://user-images.githubusercontent.com/385644/36540743-69e16796-17d3-11e8-8ea9-88a0ab04bb16.png)

**Rotate back:**

![three](https://user-images.githubusercontent.com/385644/36540751-6f64c960-17d3-11e8-9d4c-3ec92acd41a5.png)

I've asked on the forum before adding this issue:

[https://discourse.nativescript.org/t/ios-custom-actionbar-and-rotation/4597](https://discourse.nativescript.org/t/ios-custom-actionbar-and-rotation/4597)

It looks like a bug...

This is my environment:

```
│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.2           │ 3.4.2          │ Up to date  │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-android      │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │
```

Thanks,
Dem

**Comment by NickIliev** [comment]
@demetrio812 I can confirm that indeed this is unexpected behavior and is definitely a bug.
The good news is that this one is already fixed and the fix is merged into the master branch.
The fix will be included in our next official release. 
Meanwhile, you can test it at your side by using `[tns-core-modules@next](https://github.com/NickIliev/NS-Issues-2018/blob/master/NativeScript/issue_5453/package.json#L14)`.

Demonstration test application using the `next` modules can be found [here](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5453)
