### ISSUE TITLE
Android: backgroundSpanUnderStatusBar does not work? 

### ISSUE THREAD

**Issue by lin-brian-l** [NativeScript/NativeScript#5481]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

On iOS, setting a background image on the page and using `page.backgroundSpanUnderStatusBar = true` will cause the status bar to match the background image. However, this does not work on Android. 

My core question is this: **how can the Android action bar be made transparent?** I tried experimenting with transparent CSS color codes in `page.androidStatusBarBackground`, but had no success.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.1 for both Android and iOS

### Please tell us how to recreate the issue in as much detail as possible.
Clone and run [this repo](https://github.com/lin-brian-l/backgroundSpanUnderStatusBar_test). The background mountain image will not show through to the status bar on Android, but it will on iOS. Since this was made from the "Hello World" angular template, the pertinent code is in the items.component.ts file. There are screenshots illustrating the difference below and in the root of the repo.

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

The code is in the repo above, inside items.component.ts. 

iOS Screenshot (transparent action bar):
![ios](https://user-images.githubusercontent.com/29388364/36812364-97538a52-1c96-11e8-981f-1b0a85a252af.jpg)

Android screenshot (not transparent action bar):
![android](https://user-images.githubusercontent.com/29388364/36812370-99db6dbc-1c96-11e8-9eee-a0e3a80ebfcc.png)

**Comment by lin-brian-l** [comment]
Thanks for the help and the code, @tsonevn! Sorry for not realizing that `backgroundSpanUnderStatusBar` was platform-specific and that it's working as planned. I've been posting with a lot of problems that I've been having, and you and the rest of the Nativescript team have been incredibly supportive. I appreciate the help, thanks again!

**Comment by princy05** [comment]
Hello,

I used the same code but still I am facing the same issue for android. 

<img width="395" alt="screen shot 2019-01-05 at 3 10 13 pm" src="https://user-images.githubusercontent.com/16576656/50729242-37792500-10fc-11e9-8476-8c55383c54a5.png">

**Comment by vahidvdn** [comment]
@tsonevn This didn't work for me too. Would you please reopen the issue?

**Comment by jpnobrega** [comment]
+1

**Comment by Sunhat** [comment]
+1 

documentation does not state this is platform specific.

**Comment by Sunhat** [comment]
How does one change the colour of a status bar.

default install of nativescript
`backgroundSpanUnderStatusBar` does nothing

and 
`androidStatusBarBackground` does nothing either.

Fix your documentation or just abandon the product.

**Comment by NathanaelA** [comment]
@Sunhat - Marcus, documentation mistakes happen all the time, especially when new features are added.  However you can help all of us in the community by spending a few minutes and help fix any documentation issues you find...

On every page of documentation we have a link 
![image](https://user-images.githubusercontent.com/850871/89110147-64430a80-d40d-11ea-8eb8-1d27959aec8b.png)
 to allow the community to help maintain the documentation so that it can be changed easily..

**Comment by Sunhat** [comment]
@NathanaelA In the Medical field, 3 doctors are required to verify an x-ray. Think about how bad it would be if they got their diagnosis wrong. Mistakes happen, but this is reflective if your process.

Take for example installing Nativescript Vue following the Nativescript documentation vs installing it using the vue-cli template. Start going to use the former, and you'll find that `androidStatusBarBackground` does not work out of the box. How many other developers have repeated this painful mistakes? Literally hundreds of thousands of $$$ worth of dev hours wasted by what you call mistakes.

Here's the best help I can give you: Building a product and documentation is a mindset. The primary goal of your product should be to make the app development as painless as possible from start to finish. Everything should be orientated around ease-of-use. 

This is currently annoying, and honestly, the product and documentation lacks the worldview that Vue was built on. Evan and Taylor Otwell can make excellent documentation, guides and code, take a page out of their book.

**Comment by NathanWalker** [comment]
@Sunhat We agree the documentation needs revamping and as long time community users of the framework we also feel where you're coming from and just took over the framework on June 1 as a purely community driven open source project. Documentation is under works but it's summer 2020 in middle of a pandemic (all of us have family with children) and it's going to take us a bit to get them revamped. Settle down. This is a community full of tremendous people that are more than willing to put their personal matters aside and help you. We'll see what we can do to investigate the issue you raise as it's a point worth digging into for sure.

I **do** have time to respond to your pretentiousness, and here's the help I can give you, lighten up.

**Comment by Sunhat** [comment]
I work 12 hours a day, 7 days a week

**Comment by NathanaelA** [comment]
@Sunhat - Please note you fund the doctors time either directly or via tax dollars, and so of course they have tremendously more financial resources to allow it to be more accurate (not to mention the whole life & death vs creating apps is a rather big difference).   NativeScript is a 100% OPEN source project where people who want to actually be contributing members can **OPTIONALLY** contribute their time or money to helping make it a better project.    Their is a huge difference between the two worlds.

Instead of complaining that X is wrong, if you discover X is wrong simply fix the docs and be part of the **solution** that you are complaining is missing.   That is what being part of the community and using a open source project is all about.   If you can't help; then you are just as much a part of the problem.  You obviously saw a issue (to complain about it) and you didn't fix it either, so it is being very hypocritical of you, to complain, yet do nothing to help the **next person** who might run into this issue when it would have taken you less time to fix the docs issue than write your initial complaint and respond to this thread...  

In addition, if you have no "time" to help, another constructive direction is you can become a subscriber to the NativeScript OpenCollective and specify that you would like to earmark your money towards better docs.   Again, it is the community helping the community, that is the whole purpose of a open source project.  

Finally, one word of advice --- even if you are a really nice guy, threads like this really tarnishes your reputation.  Just complaining and insulting the hard work others did; makes you look like a spoiled and entitled person -- I assume that is not your intention...
