### ISSUE TITLE
How to refresh image 

### ISSUE THREAD

**Issue by bigradish** [NativeScript/NativeScript#5493]
I found if the src property (image path) of the Image class keeps same, while the image file is replaced, the Image class still display the first image file.
Imagine this: a user changes his avatar, he will not see his new avatar until the next app start.
How to refresh an image when src is unchanged?
Thank you.

**Comment by NickIliev** [comment]
@bigradish 
Instead of changing the image (while preserving the same URI) you could change the source (e.g. via binding and change your `src` value through the Observable model). The user won't make a difference and you can always remove the old avatar file.

For example:

```XML
<Image src="{{ mySrc }}" />
```

```
const viewModel = new Observable();
viewModel.set("mySrc", "my-avatar-uri.png");

page.bindingContext = viewModel;

// and then when needed to change the Uri
viewModel.set("mySrc", "new-avatar-uri.png");
```

More about data binding [here](https://docs.nativescript.org/core-concepts/data-binding) and in the startup templates (e.g. `tns create myApp --tsc`)

**Comment by bigradish** [comment]
@NickIliev 
I think you didn't understand my question.
What I mean is: If the src of an Image tag keep same, while the image file is replaced (for example., by a user's changing his avatar), Nativesript still diaplay the old image.
If I want to keep the src unchanged, how to refresh the image?
Thank you.
