### ISSUE TITLE
Testing with Appium

### ISSUE THREAD

**Issue by paranoid-android** [NativeScript/NativeScript#553]
I am trying to learn how to test my app via Appium. From my understanding, that is what the NativeScript team uses. However, I can't find any details. It looks like others have the [same question](http://stackoverflow.com/questions/31507719/testing-nativescript-app-with-appium)

**Comment by dtopuzov** [comment]
Hi,

We have two different types of testing in NativeScript:

UnitTesting 
For UnitTesting we use internal framework. 
You can find some tests here: https://github.com/NativeScript/NativeScript/tree/master/apps/tests

Functional Testing:
We build some sample apps and then use Appium to automate real user actions.
With Appium you have no access to internals of your app and your classes.
Unfortunately we do not have plans to make your Functional Testing solution public, but here you can find how Appium works: http://appium.io/

**Comment by dturing** [comment]
Although this is long closed, people still end up here, so: Telerik's "Functional Testing solution" is now open: [https://github.com/NativeScript/functional-tests-core](https://github.com/NativeScript/functional-tests-core), or see [this blog post](https://www.nativescript.org/blog/nativescript-open-source-functional-testing-framework).

**Comment by kamok** [comment]
@dturing @dtopuzov It'd be nice if `tns init test` does both Unit Testing and Functional Testing set up for you. I'm just getting started with NativeScript, and though Unit Testing is nice, it's not enough. 

I'm having great difficulty digesting the new technologies, and wish it was just as easy as looking up a single doc and writing specs rather than all the set-up work as well. 

Additionally, it would be much easier and better for users of NativeScript to have a set-up guide for TNS Angular, as I believe the post is only for pure NS?

**Comment by dtopuzov** [comment]
Hi @kamok,

Thanks for the feedback.
I've just logged the idea for functional testing as feature request in CLI repo: https://github.com/NativeScript/nativescript-cli/issues/3000
