### ISSUE TITLE
Cannot vertically center Label in flexboxlayout with non-fixed height

### ISSUE THREAD

**Issue by Burgov** [NativeScript/NativeScript#5623]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Y

### Tell us about the problem
I'm unable to vertically align an element in a layout within a GridLayout with row height auto. See https://play.nativescript.org/?template=play-js&id=GdUADF

The first row of the gridlayout gets its height from the four labels in the StackLayout. The FlexboxLayout gets the same height, but the text within it is not vertically centered. If I change the rows property from "auto,auto,auto" to "200,auto,auto", the text is vertically centered.

### Which platform(s) does your issue occur on?
Only tested on Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.3
- Cross-platform modules: ^3.4.1
- Runtime(s): 3.4.2

### Please tell us how to recreate the issue in as much detail as possible.
See playground

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
See playground

**Comment by Burgov** [comment]
Something similar happens with a GridLayout: https://play.nativescript.org/?template=play-js&id=ivQ2Du. I'd expect the text to be vertically centered, but it isn't

**Comment by NickIliev** [comment]
@Burgov the first case can be resolved by using `verticalAlignment="center"` - PlayGroundDemo [here](https://play.nativescript.org/?template=play-js&id=GdUADF&v=2) - I have used different background color for better visualization of what is really happening - notice that as the cell is auto and the flexbox layout does not have predefined size it occupies only the space needed..

The second scenario seems identical (Playground demo [here](https://play.nativescript.org/?template=play-js&id=ivQ2Du&v=2)).

Of course, if you need to vertically center the Label inside the parent layout instead of using shrinked-vertically-centered layout you can change the logic so that the layout takes some predefined space and use verticalAlignment, textAlignment properties on Android.
