### ISSUE TITLE
file:///app/tns_modules/wake_on_lan/wake_on_lan.js:47:45: JS ERROR TypeError: net.isIPv6 is not a function. (In 'net.isIPv6(address)', 'net.isIPv6' is undefined)

### ISSUE THREAD

**Issue by d3mac123** [NativeScript/NativeScript#5650]
Hi, 

Is NS compatible with Node Net module? I am trying to use the wake_on_lan module but I still keep getting this error message:
`file:///app/tns_modules/wake_on_lan/wake_on_lan.js:47:45: JS ERROR TypeError: net.isIPv6 is not a function. (In 'net.isIPv6(address)', 'net.isIPv6' is undefined)`

I have used nativescript-nodefy plugin to install the wake-on-lan package (https://www.npmjs.com/package/wake_on_lan).

Thanks!

**Comment by tsonevn** [comment]
Hi @d3mac123,
The `nativescript-nodeify` plugin makes most npm packages compatible with NativeScript, however, some of the plugins in npm will not work because of their dependencies.
Regarding the topic of the issue, this feature seems to be a perfect candidate for a new plugin. I would suggest reviewing the below-attached article:
https://docs.nativescript.org/plugins/building-plugins
