### ISSUE TITLE
Closed Source "nativescript-ui"

### ISSUE THREAD

**Issue by pedromorgan** [NativeScript/NativeScript#5652]
I have just discovered (via slack chat) that the ["nativescript-ui" module](http://docs.telerik.com/devtools/nativescript-ui/api/) is **closed source**.

This is quite alarming, as I "assumed" they were under the same [License](https://github.com/NativeScript/NativeScript/blob/master/LICENSE)

So can a big notice be placed on the website to indicate this fact and not mislead developers.

Also are there any plans to OpenSource the modules, and if so a notice to that effect?

**Comment by NathanaelA** [comment]
The last I heard, they are working towards open sourcing it.   Legal issues always slow down the process.

**Comment by sipacate** [comment]
NativeScript-UI is an optional package. You aren't required to use it.

We used to sell NativeScript-UI, but late last year decided to make it free of charge. The package shares code with some of our other commercial products thus open  sourcing it isn't straightforward.

If it were me, I wouldn't get too bothered by this. The licence covers your usage. However, if you have a mandate to use only 100% open source software, no problem, just skip NativeScript-UI.

**Comment by pedromorgan** [comment]
@sipacate What you are saying is that:-

- the nativeScript-ui part is proprietary and now $£ free  (which is appreciated)
- Do not use if you are concerned about FOSS license
- I do not know what will happen if future (maybe you start charging on next iteration, bait and switch its call).
- There is nothing to indicate the Proprietary Licence in the docs, which is misleading
- And thanks for closing the issue !!!

... means I'm not skipping NativeScript-UI (essential components for me) but probably NativeScript as a whole as I have lost trust.

**Comment by pedromorgan** [comment]
https://www.reddit.com/r/nativescript/comments/8bb8sa/beware_parts_of_nativescript_is_closed_source/

**Comment by NathanaelA** [comment]
@pedromorgan - 
Pete,   First I don't work for Progress/Telerik; I'm a independent contractor.   So all this comes from someone who has just been in the NS eco-system for a long time.  :grinning: 

First, I'm going to continue to call it NS-Pro-UI; because that is what it was called in the eco-system from the start.   So I am very used to writing NS-Pro-UI.  :grinning:   However I will grant you its new name "UI-For-NativeScript" is a bit misleading in that you might think that the entire UI is part of this.   That would be false (and something I'm not sure the NativeScript team thought of when they renamed the plugin).    This *EXTRA PLUGIN* only contains a couple EXTRA components, it is not the ENTIRE NativeScript UI.   The actual NS UI contains a wide range of fully open source components, all UI code is at https://github.com/NativeScript/NativeScript/tree/master/tns-core-modules/ui  and documentation is https://docs.nativescript.org/api-reference/globals (look at Ui/*)

- First the NS-Pro-UI  originally had some parts of it paid and others free; but they released all of it free last Sept.   This really streamlined being able to use it for any project...
- Second issue with NS-Pro-UI was that everything was one large plugin; recently they separated out the pieces making it easier to consume for apps that might only need one of the features.    (in other words; they are listening to the feedback, and fixing issues that are a major pain to the community)
- Third, there are people outside of Progress that can make changes to the source (so not open source yet; but it now can be contributed to by trusted third parties)
- Forth; they (the NS team) did announce they were attempting to move it to fully open source; but that they had to clear multiple legal issues do to what Dan (who works for Progress) mentioned above.   This may NOT ever happen, but they are investigating it and I believe them when they say they are trying.   Larger companies can't turn around on a dime and it takes a while for some things to clear certain legal hurdles and I bet there are even some interesting political hurdles since the base code is used by multiple teams in Progress for multiple commercial products.  So even if they fail at that; I'm actually really impressed that they managed to get it 100% free for NativeScript users.  


>I do not know what will happen if future (maybe you start charging on next iteration, bait and switch its call).

Despite not working for Progress; this one is like about as remote as Microsoft charging for VSCode.   Sure either can happen, but the odds are so remote that I don't worry about MS closing off VSCode any more than I worry about Progress closing off the UI.  This is probably the last thing I would worry about Progress doing.  :grinning:   I have had many issues with Pro-UI over the years; and I am one of the more outspoken critics of it (but they have slowly been fixing the issues I've complained about).  But this is not one area that even ranks as even a possible blip on my radar.  :grinning:

>There is nothing to indicate the Proprietary Licence in the docs, which is misleading

The *separate* NS-Pro-Ui doc site is missing it; but the Pro-UI license is in a couple places:
- https://github.com/telerik/nativescript-ui-feedback/blob/master/LICENSE.md
- Included in the plugin when you install it.
I would agree that the Pro-UI doc site should have a link to the license; but that is a failing of the Pro-UI doc site; not a failing of NativeScript.   

Now as to your link and that statement on reddit is **100% false**.   NativeScript-Pro-UI  is NOT actually a part of NativeScript.  It is and it has always been a **First-party plugin** \*.   It does NOT actually ship with NativeScript; and has not-nor ever was actually part of NativeScript.   Again it has ALWAYS been a **First** Party plugin, that YOU can choose to add to your app.   Out of all the apps I've done in NativeScript; I think only one (maybe two???) has ever used any of the NS-Pro-UI in it.     The rest just use the standard open source UI components included in NativeScript and maybe other components that either I or other developers have created and are listed on the thriving third party plugins site (https://plugins.nativescript.rocks).   

\* First party; meaning; that the creators of NativeScript created the plugin (i.e. first party).    If you check the plugins site; you will see there are a huge number of open source plugins for NativeScript; some of them are first party; but the vast majority are third party.

**Comment by pedromorgan** [comment]
@NathanaelA Thanks for the reply, and making the position clearer (I also read wikipedia)

However, as a newbie to **{N}**
- I started off (with my collegues) at the [docs here](https://docs.nativescript.org/ui/rich-components) and its got **nativescript-pro-ui** and absolutely no mention of its closed source nature.
- Some of the  templates-* also dont mention it uses closed source components.
- The [app were developing](https://github.com/gstl-geotechnical/gstl-mobile-ns) will require all the "pro-ui" components.
- "NativeScript-Pro-UI is NOT actually a part of NativeScript" - How was I supposed to know that !!!

**Comment by NathanaelA** [comment]
Congrats on picking up NS.    If you want a rich UI that allows you to use your web skills with the ability to easily add more native UI components; NS is truly one of the best platforms despite annoying things like this.  :grinning:   

- On your first link -- that is interesting; looks like you are correct -- that does add to the confusion.  I hadn't realized they had mixed the Pro-UI components into some of the general docs.   They still have a separate docs page, which is what I was used to and use.   
Dan/T.J. - That really probably should be clearer that the Pro-UI stuff is a separate plugin and under a separate license, or maybe even better it should rather than be mixed in the general docs; be a blurb about the cool UI plugin that they can install and then link to the separate pro-ui docs so it is clear it is two separate products.     Mixing the two does lead people to believe that parts of NS are not open source, especially with the "UI for NativeScript" name...

- Templates; yeah; the readme on any template that uses Pro-UI should also be updated.   I'm pretty sure it is just oversight; too many things for the team to do; and just totally forgot to do something simple like that... @tjvantoll - You probably should get the templates that use Pro-UI updated with a blurb and link to the Pro-UI license.  This is a valid complaint to have the license be totally different that what everything that is stated in the normal user facing stuff...   I would be pretty ticked also; if I started using something where the real license seemed to be hidden...  :grinning:

- The app you are developing; if you need the Pro-UI; then you need the Pro-UI.   It is free and under a permissive license.   There is a couple components in it that are unique currently in the eco-system.   There are also several that there are 3rd party plugins that do the same (& better or worse) that the Pro-UI; all depends on which piece(s) you need.   Also their is nothing stopping you from wrapping a 3rd party Native Android/iOS plugin into NativeScript to do the same functionality.    For example; I helped wrap a different third party chart program into NS.   A large number of the open source plugins in NativeScript are just wrapped native Android/iOS plugins.   

- Yeah, I can understand your confusion; it isn't really clear for new users that Pro-UI is a separate product; when it was first released it was very easy to see it was a separate product -- since it was called NS Pro UI and cost money...   Now I can see how you can be very easily mislead.     I wasn't trying to come down hard on you; just wanted to make sure anyone coming to this thread was 100% aware that they are separate products with separate licenses despite the poor naming and lack of license links.   (Which the links can be easily fixed).    Renaming; I doubt the team wants to change NS-Pro-UI's name another time.  :grinning:

**Comment by pedromorgan** [comment]
I only `dicovered` the problem when I filed [this sidedrawer issue](https://github.com/telerik/nativescript-ui-feedback/issues/614) and decided to look at the source, which did not exists!

Apart from that am very happy with **{N}**

**Comment by EmilStoychev** [comment]
@pedromorgan thanks for bringing our attention to this issue. Indeed, we could have done a better job noting that NativeScript UI is closed source throughout our documentation and resources since, as in your case, this could be of significant importance.

We already took appropriate actions to make this more clear on the [documentation site](https://docs.nativescript.org/ui/rich-components) and in the [template readmes](https://github.com/NativeScript/template-drawer-navigation-ng/commit/63e75da03eacc1e337b08bb7340f4fa53613ab9f#diff-04c6e90faac2675aa89e2176d2eec7d8).

In terms of packaging, NativeScript UI (aka Pro UI) used to be a [single package](https://www.npmjs.com/package/nativescript-pro-ui) distributed via NPM. Recently, all components [were split into their own packages](https://www.nativescript.org/blog/professional-components-from-nativescript-ui-the-big-breakup). They all still share the same closed-source [license](https://github.com/telerik/nativescript-ui-feedback/blob/master/LICENSE.md). 

Let me use this opportunity to shed some light around making NativeScript UI open source. As @NathanaelA correctly pointed out above, in Sept 2017 we announced NativeScript UI becoming free and working with our legal team to make it open source. 7 months later, the chances to open source the components seem very low. Although we made the best effort to make this happen, there are risks associated with open sourcing the components that we (Progress as a company) don't see reasonable to take. Given that, I'd recommend you to think that NativeScript UI will NOT become open source. Instead, we are working on other ways to accept community contributions and speed up the development of the components. We are very close to finalize this process and will follow up with a blog post shortly on that. Stay tuned.

Thanks again for bringing this up and to @NathanaelA for the clarifications!
