### ISSUE TITLE
[iOS] ActionBar styling issues

### ISSUE THREAD

**Issue by JimGreenberg** [NativeScript/NativeScript#5696]
While my examples are angular only, I wasn't sure if this was an issue with angular or not so I opened the issue here.

### Issue
While I'm presenting 2 issues here- I highly suspect they are simply 2 different occurrences of the same issue. 
I'm attempting to style the actionbar for my app, I'd like to change the color of the system icons- and on one page, remove the small border at the bottom of the action bar (UINavigationBar.shadowImage). This is achievable using `topmost().ios.controller.navigationBar.setTintColor(color)`- however under two conditions I notice that this style is being overridden:

1. When navigating to OR from another component (in this case, one WITHOUT an ActionBar in its html) you will see the default blue color flash on the icon before the actionbar disappears. Shown in this gif:
![giphy](https://user-images.githubusercontent.com/20466273/38893609-c9b41380-4258-11e8-8cb1-454aef90267b.gif)
We're navigating back and forth from the red page without an actionbar, to the blue page with an actionbar that has been styled to have tintColor be pink.

2. When modifying the actionbar dynamically, we also lose our styling. In this gif, I'm using an ngIf to add another ActionItem to the bar (it is hard to see, but the yellow square is in fact a button- you can see the button text flashing as it is pressed causing the item to appear). The bar is pink to begin with, and then turns default blue when the item is added:
![giphy-1](https://user-images.githubusercontent.com/20466273/38893710-16985742-4259-11e8-9499-18d4dd199bd4.gif)

### Solutions I've Attempted
I tried setting an app-wide css selector on the ActionBar itself. This will works to an extent, however it has limitations: for one, I am unable to have it apply to ONLY the action items and not the title this way. Additionally, using css to remove the shadowImage is not possible.

I've also tried cleverly removing the entire bar on page/navigation hooks, this solution leaves an ugly white square where the ActionBar used to be for the brief period during the navigation. I also wasn't able to remedy the navigating TO case, only navigating FROM.

Other posts here and in the nativescript-angular github page, as well as on stackoverflow have touched on this issue in a similar way, but not quite the same. Furthermore, none yielded solutions.

### Conclusion
It seems that nativescript is spinning up a new version of the controller causing it to lose its styling, or maybe a bug in actionbar.update? I'm going to be spending some time reading through nativescript's implementation. Thanks for reading.

[testapp.zip](https://github.com/NativeScript/NativeScript/files/1921498/testapp.zip)

**Comment by tsonevn** [comment]
Hi @JimGreenberg,
First of all, thank you for your interest in NativeScript.
Regarding the above-described scenarios, it seems that this issue is related to the fact you are setting the tintColor directly on the native property. This native property will be set up again while the second ActionBar Item is shown while using the CSS specify for this component. When it is missing, it will set up the default style. The case is similar while navigating back, while the ActionBar is unloaded.

Bear in mind the scenario with accessing the native properties for providing a style for the ActionBar should be avoided, when it is possible.

The solution in your case is to set up the color CSS property to the ActionBar component instead of using the native tintColor and to setup custom title view which will allow you to style further the ActionBar title. This is demonstrated in the sample below

**Comment by JimGreenberg** [comment]
Thank you for the quick response! While this solution does tick all the boxes from my previous post I am noticing a new issue:
![apr-18-2018 10-40-50](https://user-images.githubusercontent.com/20466273/38940475-36a4317e-42f8-11e8-9565-63551caf1728.gif)
It's difficult to see, but the title is "flashing" on navigating, if you look on the right side. This issue is remedied by removing transitions on navigates- which I'd like to avoid. I tested this with two separate transition types, both producing the same effect.

**Comment by diadal** [comment]
any possibility of making this work with iOS <ActionBar :class="appcolo + ' c-white'"> it works with Android
