### ISSUE TITLE
getFile() and getFolder() methods in file-system module create files/folders

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#57]
_From @vakrilov on April 2, 2015 11:33_

Consider having separate methods for **creating** files/folders and use those methods only for **getting**.

_Copied from original issue: NativeScript/cross-platform-modules#245_

**Comment by vakrilov** [comment]
Implementation proposal
----------------------------------
Add an optional `createNew` parameter to the `Folder.getFile()` and `Folder.getFolder()` methods. It should work the following way:
 * createNew === true:
   * If the file exists - truncates it.
   * if the file does not exist - creates new.
 * createNew === false:
   * If the file exists - open it.
   * if the file does not exist - exception is thrown.

The default option is `true`.

**Comment by hshristov** [comment]
I think that if createNew === true and file exists - we should throw an exception. truncating silently file is asking for troubles.

**Comment by hamorphis** [comment]
You can check whether a file/folder exists by using the `File.exists` / `Folder.exists` methods. I think we should leave the `getFile` and `getFolder` to create the file/folder on demand instead of complicating the API with an additional parameter and making breaking changes. Furthermore, no single community member has commented on this issue or opened a new issue for this problem for almost an year which means that this functionality is fine and people have absolutely no problems with it.

**Comment by NathanaelA** [comment]
@hamorphis Well I wouldn't say others have no problems, I find a lot of the FS code to be fairly brain dead and I just always use the FSA methods and just bypass the FS methods...
