### ISSUE TITLE
Nativescript 4.0.0, console.logs not working ???

### ISSUE THREAD

**Issue by markomiljkovic** [NativeScript/NativeScript#5711]
### Did you verify this is a real problem by searching the [NativeScript Forum]
Yes

### Tell us about the problem
Hello guys I have updated my project to NS version 4.0.0 and it seems that console.logs are not working any more ??? Has anybody experienced simmilar issue ??

### Which platform(s) does your issue occur on?
Only tested on android

### Please provide the following version numbers that your issue occurs with:
My package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.test.test",
    "tns-ios": {
      "version": "3.4.1"
    },
    "tns-android": {
      "version": "3.4.2"
    }
  },
  "dependencies": {
    "font-awesome": "^4.7.0",
    "moment": "^2.19.1",
    "nativescript-audio": "~4.3.4",
    "nativescript-drop-down": "^3.2.0",
    "nativescript-phone": "^1.3.1",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-ui-listview": "^3.5.4",
    "nativescript-vibrate": "^2.0.2",
    "tns-core-modules": "^4.0.0"
  },
  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11"
  }
}

**Comment by markomiljkovic** [comment]
Ok, I updated ClI and changed in package.json 
"tns-android": {
      "version": "4.0.0"
    }
but I have one more question an we can close the issue;
why is when I change  tns -android to 
"tns-android": {
      "version": "^4.0.0"
    }

or to 
"tns-android": {
      "version": "~4.0.0"
    }
its not working it says "Invalid Version: ~4.0.0"

**Comment by NickIliev** [comment]
The thing is that symbols like tilde(`~`), caret(`^`) and others used in NPM for versioning are not allowed for the runtime versioning (for `tns-android` and `tns-ios`) as, in fact, they are **not** NPM dependencies

Also minor glitch in 4.0.0 in `tns-ios` was fixed with a patch version and now the official runtime version is 4.0.1. To avoid this kind of troubles, please use the following command
```
tns platform add android
tns platform add ios
```

The above command will always take the latest official version of both runtimes. If you want to remove a platform you could use `remove` command
```
tns platform remove android
tns platform remove ios
```

A specific runtime version can be installed as well
```
tns platform add android@next
// or
tns platform add android@latest
// or tns platform add androoid@4.0.1
```

**Comment by markomiljkovic** [comment]
@NickIliev 
Thank you very much for detailed and  clear explanation :)
