### ISSUE TITLE
IOS: multiple modal dialog bug

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#5796]
Hi,

4.0.2 - NSAngular - only on IOS.

 I have a flow that require open multiple modal dialog...and I want that the "Done" button on the second Modal Dialog will done the flow and close all modal dialog and send the data for the "page" that opened the modals...something like this:

`first Modal Dialog:`
```
public next() {
    const options = {
        viewContainerRef: params.vcRef,
        fullscreen: true
    }
    this._modalService.showModal(SecondModalDialogComponent, options).then(result => {
        this.params.closeCallback(result);
    });
}
```

`second Modal Dialog:`
```
public submit(answer: string) {
    this.params.closeCallback(answer);
}
```

In Android it works like charm, but in IOS it leaves a blank screen and crash the app...
For workaround I did a double "submit" - every modal close it self and return the data...

Thanks! :)

**Comment by NickIliev** [comment]
Confirming that the described scenario is not working as expected on iOS. Tested with `latest` and `next` (4.0.0.-2018-05-04-01) and the issue is fully reproducible on iOS. 

Steps to reproduce:
- Use [this test application](https://github.com/NickIliev/NS-Issues-2018/tree/master/NativeScript/issue_5796_ng)
- Open the first modal and then the second modal and tap `submit`

Result: on iOS, a blank screen shows up instead of the main page

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/nativescript-angular#1325
