### ISSUE TITLE
ObservableArray.reduce fails without initial value

### ISSUE THREAD

**Issue by danbockapps** [NativeScript/NativeScript#5868]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?
Yes

### Tell us about the problem

ObservableArray.reduce fails without initial value

### Which platform(s) does your issue occur on?
Both

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.0.2
- Cross-platform modules: 4.0.1
- Runtime(s): 4.0.1

### Please tell us how to recreate the issue in as much detail as possible.
https://play.nativescript.org/?template=play-ng&id=iRu1Lq&v=4 (see HomeComponent.ngOnInit)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
```
        let maxObsArrayMetric: number = myObsArray.reduce(function (prev, current) {
            return (prev.metric > current.metric) ? prev : current;
        }).metric;
```

It works if you add an initial value, e.g.:

```
        let maxObsArrayMetric: number = myObsArray.reduce(function (prev, current) {
            return (prev.metric > current.metric) ? prev : current;
        }, myObsArray.getItem(0)).metric;
```

**Comment by tsonevn** [comment]
Hi @danbockapps,
This issue seems to be a perfect candidate for PR. You can review the current implementation of the [ObservableArray](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/data/observable-array/observable-array.ts), and you can provide the needed fix. Also, you can review our [contributing guidelines](https://www.nativescript.org/contribute).

**Comment by rakeshgirase** [comment]
I have a fix ready for this issue. Please let me know if I can create a PR.
