### ISSUE TITLE
ListView with multidimensional array (Angular)

### ISSUE THREAD

**Issue by felicks** [NativeScript/NativeScript#5946]
Hi everyone, 
I a have following data structure: 

```
days = [{ "name": "Monday",
                "rooms":[{
                         "name": "Room A",
                         "session": [{
                                  "name":"Session A"
                          }]                      
                   }] 
               }]

```
with that I want to achieve a List View App with **_Angular_** with the room names as a header and the session names as list items as well as swiper for the selecting the day. Similar to this:

![image](https://user-images.githubusercontent.com/40235607/41348903-680362fc-6f0e-11e8-88c1-06a9d3da8f0c.png)

This is what I tried so far (Im seeing the day headers, not the sessions though):

```
<ListView height="100%" row="0" [items]="activeDay.rooms" itemTap="onItemTap" class="list-group">
    <ng-template nsTemplateKey="header" let-room="item">
        <Label [text]="room.name" class="list-group-item bg-primary" isUserInteractionEnabled="false" color="white" fontSize="24"></Label>
    </ng-template>
    <ng-template nsTemplateKey="cell" let-session="room.sessions">
        <StackLayout class="list-group-item">
            <Label [text]="session.name" class="list-group-item-heading"></Label>
        </StackLayout>
    </ng-template>
</ListView>

```

**Comment by NickIliev** [comment]
@felicks you do not see `session` because you should use your `item` (and not 'room.sessions' which has no meaning in Angular) as binding source and differ the templates based on the `nsTemplateKey` value.

For example, lest look [at this sample case](https://github.com/NativeScript/nativescript-sdk-examples-ng/tree/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/common-screens-category/lists-category/multi-line-grouped) where item templates are created based on the rule from `nsTemplateKey.`

- There [are three item templates](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/common-screens-category/lists-category/multi-line-grouped/multi-line-grouped.component.html#L6-L16) (header, footer, and cell). All of them are using the following syntax
```
let-header="item"
let-footer="item"
let-country="item"
```
And based[ on the code-behind logic](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/common-screens-category/lists-category/multi-line-grouped/multi-line-grouped.component.ts#L14-L16) each item is renedring only what is needed for the template. Following this logic, this means that it would be easier for you to normalize the source array and create logic that loads the needed information in the different templates (e.g., by using different exposed properties).

Another possibility is to use `setupItemView` for further customization of your list view variables. [This example](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/common-screens-category/lists-category/multi-line-big/multi-line-big.component.ts#L41) is demonstrating how to create a **_third_** variable that will be used[ in the list view to ease the handling of each third cell](https://github.com/NativeScript/nativescript-sdk-examples-ng/blob/0b0722025e83126efdf42433f25d1d4a676f9fc0/app/common-screens-category/lists-category/multi-line-big/multi-line-big.component.html#L19-L20).

Combination of both techniques above can provide you with enough power to fully customize the list view templates.


Closing as how-to related quesiton - 
For how-to related questions please use the community channels like [the NativeScript forum](https://discourse.nativescript.org/), [SO ](https://stackoverflow.com/questions/tagged/nativescript)or [NativeScript community slack](https://nativescriptcommunity.slack.com/messages/general)
