### ISSUE TITLE
Calling 'getJSON' for address that has [protocol] redirect causes exception 

### ISSUE THREAD

**Issue by VladimirAmiorkov** [NativeScript/NativeScript#5982]
### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Yes

### Tell us about the problem
Calling the getJSON for an link address that has a redirect causes exception rather than retiring the redirect.

### Which platform(s) does your issue occur on?
Android

Tested only Android

### Please provide the following version numbers that your issue occurs with:
- CLI: `4.0.0`
- Cross-platform modules: `"tns-core-modules": "^4.1.0"`
- Runtime(s): 
```
    "tns-ios": {
      "version": "4.1.0"
    },
    "tns-android": {
      "version": "4.1.1"
    }
```
- Plugin(s): (look for the version number in the `package.json` file of your
project)

### Please tell us how to recreate the issue in as much detail as possible.
The best approach would be to get your code running in the [NativeScript Playground](https://play.nativescript.org) and share the link with us, along with any additional details or steps to reproduce needed for examining the issue there. 

Calling the getJSON for this ([http://www.telerik.com/docs/default-source/ui-for-ios/airports.json?sfvrsn=2](http://www.telerik.com/docs/default-source/ui-for-ios/airports.json?sfvrsn=2)) address causes exception: 

> Unexpected end of JSON input

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.

```
const request = {url: "http://www.telerik.com/docs/default-source/ui-for-ios/airports.json?sfvrsn=2", method: "GET", dontFollowRedirects: false };
http.getJSON(request).then((res: AirportJSON) => {
    const airportsCollection = res.airports;
}).catch((err) => {
    const message = 'Error fetching remote data: ' + err.message;
    console.log(message);
    alert(message);
});
```

**Comment by manoldonev** [comment]
I was able to reproduce only "Error: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection." as you are trying to load http resource and by default only https calls are allowed in iOS apps.


If arbitrary loads are allowed in info.plist via 
```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

The http json resource loads correctly. Other than that redirects seem to be working correctly on our end at the moment.

**Comment by manoldonev** [comment]
The problem is related to the fact that your url http://www.telerik.com/docs/default-source/ui-for-ios/airports.json?sfvrsn=2 redirects to https://www.telerik.com/docs/default-source/ui-for-ios/airports.json?sfvrsn=2 i.e. it is changing protocol from HTTP to HTTPS and by design java.net.HttpURLConnection [does not follow redirects from https to http or vice versa](https://developer.android.com/reference/java/net/HttpURLConnection#response-handling).

We could [hack a solution](https://stackoverflow.com/a/26046079/9332825) around this but I'm not too comfortable with this option so I'd stick with the HttpURLConnection behavior at the moment. Moreover, this specific issue can be avoided by making requests using the desired post-redirect protocol, be it HTTP or HTTPS, so that redirects don't change protocols.
