### ISSUE TITLE
pie chart legend height are not updating on data change

### ISSUE THREAD

**Issue by giorgi-abashidze** [NativeScript/NativeScript#5985]
pie chart legend height are not updating on data change, for example if I have data with 2 legend and then update to more big data with 8 legends

the legend container have same height after update, it shows only 2 legend names

**Comment by NickIliev** [comment]
@giorgi-abashidze please note that this repository is for logging issues, bugs and features related to NativeScript framework. Use [nativescript-ui-feedback](https://github.com/telerik/nativescript-ui-feedback/issues) repository to log issues related to the nativescript-ui-chart plugin. Also is the issue is how-to related I would advice using the community channels (SO, discourse,nativescript.org and slack) to ask the questions (along with the provided codebase of what has been achieved so far)

**Comment by giorgi-abashidze** [comment]
@NickIliev ok, thank you.
