### ISSUE TITLE
Dialogs Prompt : persist opening when inputTe is empty

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#6002]
Hi,

can we keep dialogs.prompt open until we enter (length) of digits minimum ex: disable ok button ?

Thank you.

**Comment by tsonevn** [comment]
Hi @kefahB,
By design, the dialogs for Android does not provide functionality, which allows cancelling the dismiss option. However, you can review the solution in [this ](https://stackoverflow.com/a/45691216) StackOverflow thread, which might be applicable for the dialogs as well. 
For further question, please use our [forum](https://discourse.nativescript.org/) or StackOverflow [thread](https://stackoverflow.com/questions/tagged/nativescript).
