### ISSUE TITLE
How to use the file system in NativeScript?

### ISSUE THREAD

**Issue by dreadshade** [NativeScript/NativeScript#6010]
Hi all,

I am trying to understand how the file-system works in Native Script.
I created a method to parse the document but it returns "undefined". I think my problem is the path i am sending. And here is my problem. How do i identify the correct path of my file? 

This is my file reader:
`import * as fs from "file-system";

export class FileReader {

    public static readJSON(): Promise<Object> {

        var documents = fs.knownFolders.documents();
        var path = fs.path.join(documents.path, "pages.json");
        var file = fs.File.fromPath(path);

        return new Promise<Object>((resolve, reject) => {
            file.readText().then((content: string) => {
                let data = <Array<Object>>JSON.parse(content);
                resolve(data);
            })
                .catch((err) => {
                    reject(err);
                });
        });
    }
}`

And it is used here:
`        FileReader.readJSON()
            .then((response) => {
                results = response;
            })
            .catch((err) => {
                console.log(err);
            });`

Now regarding the correct path to my json file. I have this file "pages.json" in my project under ./tools/assets/

**Comment by tsonevn** [comment]
HI @dreadshade,
If I understand your case correctly, you are trying to read JSON file, which exists inside of your project `app` folder. If this is the case you should use `fs.knownFolders.currentApp()` instead of `fs.knownFolders.documents()`. The currentApp will return the path to the project folder. For more info, you can review the [documentation](https://docs.nativescript.org/ns-framework-modules/file-system).  
Also, bear in mind that you can requre the needed JSON file directly in the project(`var test = require("./test.json");`), there is no need to use the FileSystem module in this case.

**Comment by kkbaluyot** [comment]
what if it is not json but files like pdf. Im been struggling for days with very confusing articles of tns file-system. I place it in my root folder, at app/assets/pdf/test.pdf but when I call the fs.File.exists for the latter path, it turns false but the app/assets is true. Why I cant get the path correctly and im using currentApp already. Did I miss some config? I use webpack

**Comment by tsonevn** [comment]
@kkbaluyot Can you send us a sample project that shows the issue, that you are facing and can be used for debugging?

**Comment by kkbaluyot** [comment]
I found my answer and posted it in stackoverflow.
https://stackoverflow.com/questions/55879029/read-local-pdf-stored-in-app-to-pdf-viewer-in-nativescript

Thank you for your responsiveness :)
