### ISSUE TITLE
Provides support for 4.0 sharing plug-ins.

### ISSUE THREAD

**Issue by zuohuadong** [NativeScript/NativeScript#6025]
![image](https://user-images.githubusercontent.com/11203929/42271973-53147520-7fb7-11e8-8795-5efec60aeb0f.png)

Many plugins are missing functionality and lack of maintenance.

**Comment by tsonevn** [comment]
Hi @zuohuadong,
You can create your own plugin, which provides support for the needed functionality. You can review the article [here](https://docs.nativescript.org/plugins/building-plugins), where it is described how to create a plugin.
Regards,
@tsonevn

**Comment by zuohuadong** [comment]
![image](https://user-images.githubusercontent.com/11203929/42274154-39c49594-7fbe-11e8-99d7-b7f4a339f3e6.png)
![image](https://user-images.githubusercontent.com/11203929/42274167-47d16d56-7fbe-11e8-898d-ba35c05fd5b2.png)
![image](https://user-images.githubusercontent.com/11203929/42274266-9e5a67ea-7fbe-11e8-87fc-d7a1beffa0a7.png)

Flutter, react native, ionic all provide a number of related plug-ins.

Why don't developers like Nativescript?

**Comment by tsonevn** [comment]
Hi @zuohuadong,
You can check [nativescript-social-share](https://www.npmjs.com/package/nativescript-social-share), which seems to provide the necessary functionality to share content in the social media. If something is missing as functionality in this plugin, you can always contact the plugin's author by logging new feature request in the plugin's [repo](https://github.com/tjvantoll/nativescript-social-share/issues). You can also make your PR to the plugin.
About the plugin request. Regarding the fact that similar plugin already exists, in my opinion, it is better to improve existing one instead of creating a new plugin. 

Let me know if I am missing something.
