### ISSUE TITLE
Background gradients removes button's shadow

### ISSUE THREAD

**Issue by vahidvdn** [NativeScript/NativeScript#6043]
When I want to use Nativescript background gradient in a button , It remove's button's shadow. Any idea?

![photo_2018-07-09_18-11-52](https://user-images.githubusercontent.com/11078601/42454021-ab24efb6-83a3-11e8-8e34-b875d5de5df1.jpg)

**Comment by NickIliev** [comment]
@vahidvdn this is kind of expected as by design on Android the Button is creating the default native look by using drawables (for the shadow and the ripple effect).  The linear gradient implementation is [also using a background image](https://github.com/NativeScript/NativeScript/blob/9d21a743c4357b413dd3f455bb21969f94d71dcf/tns-core-modules/ui/styling/background.android.ts#L180-L182). So applying a gradient for a `Button` will overwrite the native behavior and thus removing the shadow and the ripple effect.
