### ISSUE TITLE
Splash screens on iOS

### ISSUE THREAD

**Issue by maknz** [NativeScript/NativeScript#607]
In [this comment](https://github.com/NativeScript/nativescript-cli/issues/764#issuecomment-129833907), @ligaz mentioned it's possible to put launch/splash screens into `App_Resources/ios`. However, it doesn't seem to work off the bat (the default ones that shipped with {N} don't work either). Are there any guides available for how to achieve this?

**Comment by ligaz** [comment]
Hey @maknz,

The issue is that the default iOS project template includes a [LaunchScreen.xib](https://github.com/NativeScript/ios-runtime/blob/master/build/project-template/__PROJECT_NAME__/en.lproj/LaunchScreen.xib) file which takes a precedence over the defined splash screens resulting in white splash screen. We will have to double check do we still need this file to be in there by default. 

//cc @fealebenpae and @PanayotCankov

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#281
