### ISSUE TITLE
android 8 compatiblity

### ISSUE THREAD

**Issue by peppeg85** [NativeScript/NativeScript#6078]
hi all, i have some problems with android 8, if the app was yet installed on the smartphone it still works, if i try to install a newer version it won't install.... how can i build for oreo? just installing the android api level 26?

**Comment by NickIliev** [comment]
@peppeg85 the issue seems related to [https://github.com/NativeScript/nativescript-cli/issues/3602](https://github.com/NativeScript/nativescript-cli/issues/3602)

Closing as duplicate to [https://github.com/NativeScript/nativescript-cli/issues/3602](https://github.com/NativeScript/nativescript-cli/issues/3602)
