### ISSUE TITLE
Feature: TabView tabItemTap event

### ISSUE THREAD

**Issue by ddfreiling** [NativeScript/NativeScript#6095]
Right now there is only a `selectedIndexChanged` event for TabView. It would be nice with a Tab selection event, so that we could implement custom behavior when the currently active Tab is tapped again.

Examples:
- Double tap Tab to reset its history. This works now on iOS, but not on Android.
- Double tap Tab to scroll it to top (Twitter does this).

Suggestion:
As discussed with @sebawita , a simple `onTabTapped` event, which would trigger with: `currentTabIndex` and `newTabIndex`, would do the job. Naming could be improved :)

**Comment by vchimev** [comment]
A follow up [here](https://github.com/NativeScript/NativeScript/pull/6239#issuecomment-422357834).

**Comment by vchimev** [comment]
After a discussion within the core team and as suggested above, we would suggest exposing a `tabItemTap` event. It will raise before `selectedIndexChanged` and will allow developers to implement custom behavior.

**Comment by logan-jobzmall** [comment]
@vchimev Any idea when this will be released?

**Comment by Ahnert1** [comment]
As a workaround, I am turning off the event listener, setting the selected index to NULL, and then turning the event listener back on.  Then the next time any tab is tapped, even the currently selected tab, the event is still captured because it thinks its a "new selected index"

`@ViewChild("tabView") tabView: ElementRef;`

`onSelectedIndexChanged(args: SelectedIndexChangedEventData){`
`...`
`this.tabView.nativeElement.off(TabView.selectedIndexChangedEvent);
this.tabView.nativeElement.selectedIndex = null;
this.tabView.nativeElement.on(TabView.selectedIndexChangedEvent, this.onSelectedIndexChanged, this);`
`...`
`}`

Warning: I have 2 lines of code that will not work when using this "hack/workaround":
`let sideDrawer = <RadSideDrawer>app.getRootView();`
`sideDrawer.gesturesEnabled = args.newIndex == 0 ? true : false;`
I am trying to make my global side drawer only available on the first tab, and none of the others.
When removing the "workaround", these 2 lines of code work as expected.

**Comment by Mubashir-Mohamed** [comment]
is tabItemTap event implemented?

**Comment by patrikengborg** [comment]
I'm also very interested to get this working.

**Comment by vahidvdn** [comment]
Will this be a part of tab redesign in version 6.0?

**Comment by AlexisWalravens** [comment]
I'm also interested in this being implemented. Any News ?

**Comment by vahidvdn** [comment]
@AlexisWalravens as mentioned in new TabView re-design, it will be a part of version 6.1 (check the link in my previous comment)

**Comment by vahidvdn** [comment]
I think this can now be closed as nativescript 6.1 released with tap event for new bottomNavigation component.

**Comment by delino12** [comment]
The feature is out saw it on the nativescript bottom navigation docs. [Click here](https://docs.nativescript.org/angular/ui/ng-components/bottom-navigation)
