### ISSUE TITLE
Android - Gradle - Conflit version between plugins

### ISSUE THREAD

**Issue by pboulch** [NativeScript/NativeScript#6128]
Hi ! I use the plugin Firebase ([https://github.com/EddyVerbruggen/nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase)) and the plugin Wonderpush : [https://github.com/wonderpush/wonderpush-nativescript-sdk](https://github.com/wonderpush/wonderpush-nativescript-sdk) . But when I try to compile for Android, I get an error : 

```
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[11.0.4,11.0.4], [15.0.1,15.0.1]], but resolves to 15.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```
I think it's because Firebase plugin uses version 15.0.1 of the library while Wonderpush uses version 11.0.4.

It's possible to fixed this type of conflict into my NativeScript projet ?  

Thanks

**Comment by NickIliev** [comment]
@pboulch you can [explicitly set the Google Pay Sevices library version](https://github.com/EddyVerbruggen/nativescript-plugin-firebase#google-play-services-version) and export it. This would work for Firebase as the plugin will respect the version due to these lines in its include.gradle.

In this POC application, I am explicitly [requiring the dependency in the project's app.gradle](nativescript-ng-cosmos) and then [exporting the version](https://github.com/NickIliev/nativescript-ng-cosmos/blob/master/app/App_Resources/Android/app.gradle#L16) so other plugins can use the very same version.

However the above would work only if the plugin's author has written the plugin so it recognizes the `googlePlayServicesVersion` property set in the app gradle. If this is not the case then you can get the plugin source and introduce the property in the source where the dependency is added as done [here](https://github.com/dapriett/nativescript-google-maps-sdk/blob/master/src/platforms/android/include.gradle#L5-L8). Then repack the plugin and use the modified version.
