### ISSUE TITLE
Label - Scale Animation issue

### ISSUE THREAD

**Issue by shabib3** [NativeScript/NativeScript#6138]
Hi guy,

I want to create some `StackLayout` that reduce his width, inside that `StackLayout` I have `Label` that I want to also reduce his size.

So, for the `StackLayout` width reduce process there is no available animation so I do it inside of a `setInterval` (it was kind hard for me to get that it is done be `setInterval` and doesn't have a proper width/height change animation - but this for other issue).

Now, for the `Label` I first did a scale animation but the scale doesn't working properly, the Label element has his container (didn't mean an element parent container - I mean his own natural container) that seem to reduce his size but it seems that after the reduce the Label text fontSize now can't fit the Label width so he put three dots (example: `HI YO...`) in the end of it.
So, for solving this I again did a `setInterval` animation (I now mention again the I hate to do so - it is so ugly) on the Label fontSize, I am reducing his fontSize gradually to the wanted size - but the animation isn't looking good at all.

[His is an example of the issue in PlayGround](https://play.nativescript.org/?template=play-ng&id=CF5wwc&v=2)
in the example first you see the bad `scale` animate with the three dots(...), after go to `animate` function in the ts file and comment the bad animation and uncomment the "good" animation with the fontSize reduce by `setInterval` - I put an instruction there.

How can I it right?

Thanks a lot!

**Comment by tsonevn** [comment]
HI @shabib3 
We investigated further this case and found that this is expected behaviour while scaling the component. The component will be taken as a bitmap which will be animated. Which means that the element will be scaled,  however, this will not affect the other component's properties(e.g Label's text and its font-size). Regarding that, the solution is as you have suggested, to animate the changing of the font-size as well. You can also check our examples [here](https://docs.nativescript.org/ui/ns-ui-widgets/animations) in the docs.
