### ISSUE TITLE
toBase64String() Compression Not Working on iOS

### ISSUE THREAD

**Issue by NatanijelVasic** [NativeScript/NativeScript#6147]
Hi everyone :)

### Did you verify this is a real problem by searching the [NativeScript Forum](http://forum.nativescript.org) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

Issue also reported here:
https://discourse.nativescript.org/t/jpeg-compression-not-working-imagesource-to-base64-string/7172/4

### Tell us about the problem

`toBase64String()` generates a base64 encoding, but no matter what the quality number I enter (0-100), it always uses the maximum quality setting (100)

### Which platform(s) does your issue occur on?
iOS

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.1.2
- Cross-platform modules: 4.1.1
- Runtime(s): iOS: 4.0.1, android: 4.1.3
- Plugin(s): 

### Please tell us how to recreate the issue in as much detail as possible.

1. Create an `ImageSource` by the name `photo` . This is the test image that we want to convert to a base64 string.
2. Run `var photoEnc64String = photo.toBase64String("jpg", 30);`
3. Vary the quality setting (1-100). The output sequence is not compressed, and always uses the maximum quality setting regardless of what you input. Verified by looking at the output size, and by converting the string to JPG and seeing no compression artefacts.

**Comment by tsonevn** [comment]
Hi all,
I researched further the case and found that this issue is already fixed with the next version of the modules. To test it on your side you can add the upcoming modules version while following the below-attached steps.

1. `tns plugin remove tns-core-modules`
2. `tns plugin add tns-core-modules`
3. delete `platforms`, `node_modules`, `hooks` and `package-lock.json`
4. rebuild via `tns run ios`
