### ISSUE TITLE
Build failed: Only 8, 16, 24, or 32 bits supported: 872.

### ISSUE THREAD

**Issue by delanick** [NativeScript/NativeScript#6157]
Hi all, I've researched this issue with my keystore file - I've seen and tried the suggestions in the articles about converting it and every attempt has failed. This is painfully frustrating and it's the last item on my project list before going live. Can someone please advise? Even if I need to send my .keystore to the {N} team and you guys do it for me - please!

**Comment by NickIliev** [comment]
@delanick based on the information you have provided almost no information is provided so there is a little anyone can do to resovle your problem. 

Still even a base search lead me [to this page](https://docs.nativescript.org/sidekick/troubleshooting/known-issues) which shows that you are probably having issue with the used keystore.


> When you use .keystore or .jks certificates, the Release Cloud build for Android fails and the following error message appears: **Only 8, 16, 24, or 32 bits supported: 872.**
> **Workaround: Use .p12 certificates instead. You can convert .keystore and .jks files to .p12 by following the steps outlined in[ this article](https://www.tbs-certificates.co.uk/FAQ/en/627.html).**

Note: make sure you are using a **release** certificate before publishing the app with the converted p12.

Closing as the issue seems related to using keystore during cloud buids and is how-to related. If the above is not helpping you then please post your requst for external help in the community channels  so we could keep the repository clean and for looging issues, bugs and features related to NativeScript modules.

**Comment by NickIliev** [comment]
@ggarabedian ^^^

**Comment by delanick** [comment]
@NickIliev Please don't close this! I have tried that article, which is why my question included the fact that I've seen the suggestions and tried them. I have tried every article on there, I've gone as far as searching the java site as well as Oracle's site. There is no real info out there related to Nativescript's specific issue with .keystores other than converting them - which isn't working for me. Please keep this nopen so someone can help.

**Comment by NickIliev** [comment]
@delanick it is not a good practice to open issue on multiple repositories - just a single issue is enough - in  this case, the sidekick repository seems the most proper place so [the one there ](https://github.com/NativeScript/sidekick-feedback/issues/244)is the one that should stay open - I've also noticed that you have already opened the same issue in the community channel and in other related issues.

**Comment by delanick** [comment]
@NickIliev Apoloigies, I thought we were chatting on the Sidekick issue. Yes, I opened them in numerous places to ensure I get the attention this app needs to go live next week and I'm freaking out a bit :)

Thanks though! Will continue on the other one.
