### ISSUE TITLE
When using hotspot via Bluetooth on iOS, Connectivity type is returned as none on Android device

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6158]
_From @phatakrajan on August 7, 2018 9:2_

### If there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
iOS

### Please, provide the following version numbers that your issue occurs with:

This issue occurs when we start monitoring the connectivity and connect our tablet to a hotspot created via iPhone. Here are exact steps to reproduce
1. Take tablet/phone without SIM/mobile network.
2. Take iPhone and enable hotspot. 
3. Pair iPhone with the tablet/phone on which we are testing the app.
4. Connectivity services is started. You will be able to get connection type as none even though you are able to access internet from tablet/phone

_Copied from original issue: NativeScript/nativescript-angular#1475_

**Comment by NickIliev** [comment]
@phatakrajan using the exact same workflow (Bluetooth HotSport and disable WiFi on my test iPhone) and[ this test app](https://play.nativescript.org) the connectivity module is returning connection type WiFi on my side.

**Comment by phatakrajan** [comment]
@NickIliev I am not clear how you have setup connectivity.
In my scenario, I have Verizon Samsung tablets where i can't add a SIM card since its a locked device. (However i don't think you always require a locked device to generate this scenario.
I am using iPhone just to get internet connectivity on my tablet via hotspot. When we enable Hotspot, iPhone provides 3 options.
![image](https://user-images.githubusercontent.com/5074933/43788194-765d5a40-9a8a-11e8-8d01-f2c20e1e5911.png)

I am using option 2 here. I don't see a WiFi signal or mobile signal on my tablet. It just shows bluetooth pairing signal. However it still have connectivity via bluetooth

**Comment by NickIliev** [comment]
@phatakrajan thank you for the clarification - so in your case, the iPhone is sharing a Bluetooth internet connection to the Android device (Samsung) and the connectivity module on Android is the one that can't recognize that there is a connection established.

That said I think the issue is related to the code [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/connectivity/connectivity.android.ts#L28-L48) where the connection type will default to none if it is not of the known types (wifi, ethernet, mobile). So the fix would be to provide a Bluetooth type as well for the Android implementation. The implementation is using the Android's NetworkInfo **getTypeName** method which can also return type names like `BLUETOOTH`, `WiMAX` or others.

All supported Android connection types [here](https://developer.android.com/reference/android/net/ConnectivityManager#TYPE_BLUETOOTH)


The issue will be resolved via t[his PR ](https://github.com/NativeScript/NativeScript/pull/6162)which will enable Bluetooth as connection type for Android.
