### ISSUE TITLE
Will nativescript close the project because of flutter?

### ISSUE THREAD

**Issue by zuohuadong** [NativeScript/NativeScript#6163]
Have to admit, flutter for Chinese support too good, development friendly, preview release only one months, in China's developers are more than Nativescript, will also be more than ionic.

The nativescript update was too slow and so bad that I couldn't find any Chinese plug-ins.

Although the Nativescript design concept is very good, but it is too difficult for developers, there are too many problems.

I don't think Nativescript has any chance of surpassing other mainstream frameworks in this bad experience (development costs are even higher than native). 

 Do you have any plans to make typescript version of Flutter, which I think is a better idea?

**Comment by radeva** [comment]
Hi @zuohuadong and thanks for your feedback! 

The NativeScript framework is built to leverage the skills of the web developers and give them the opportunity to build their mobile apps without the need to learn any other language.
The team is working hard to provide better developer experience and this is visible in the last few releases of NativeScript. You can review the details in our blogs posts for [4.1](https://www.nativescript.org/blog/announcing-the-nativescript-4.1-release) and [4.2](https://www.nativescript.org/blog/nativescript-4.2-is-here). 


Speaking about Flutter - currently we don't have any plans to extend it or integrate it somehow with NativeScript.

Thanks for your ideas and suggestions. I hope this answers your questions. I'll now close this issue since it's not a valid bug or feature. In case you experience any specific issues with NativeScript, feel free to open a new one.
