### ISSUE TITLE
The Frame element behaves differently on iOS and Android

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#6198]
Please refer this playground app:
https://play.nativescript.org/?template=play-js&id=3gxfjn
On Android, it works as expected, you can see the top bar and switch between tabs.
On iOS, the Frame element takes up all available space (Frame is not ignoring row property because the result is same even when I used a StackLayout as root element)

Expected: The layout should look same on both platforms
Current: On iOS the Frame element takes up the whole page.

The current workaround is to wrap the frame inside another layout:
https://play.nativescript.org/?template=play-js&id=3gxfjn&v=2

**Comment by tsonevn** [comment]
Hi @shiv19,
This difference seems to be expected. While setting up the Frame in the NativeScript project, a new UINavigationController is created. By design, the native controller will always take the whole available space on the screen, which means that the Frame will overlap the other components. The right solution in your scenario is to set the Frame inside some of the available Layouts(GridLayout, StackLayout, ......). This will allow you to config the row for the Frame on both platforms.

**Comment by shiv19** [comment]
@tsnonevn
Ah! Thank you for clarifying that ^_^
The second playground example does exactly that
