### ISSUE TITLE
Property `automationText` not possible on all elements

### ISSUE THREAD

**Issue by Johanneke** [NativeScript/NativeScript#6274]
### Tell us about the problem
Property `automationText` is not possible on all elements.

### Which platform(s) does your issue occur on?
Both iOS and Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 4.2.2
- Cross-platform modules: 4.2.0
- Runtime(s): 4.2.0

### Please tell us how to recreate the issue in as much detail as possible.
Adding an `automationText` property to a `NavigationButton`, `ActionItem`, or a child of a `ListView`, does not show up in the app. This means those elements are not accessible, and they can't be found with Appium using an accessibility id.

**Comment by tsonevn** [comment]
Hi @Johanneke,
I tested your case, however, was unable to recreate an issue with the `automationText ` property and its usage in this ListView child elements. For your convenience, I am attaching a sample project. 

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2391317/Archive.zip)
 
About the NavigationButton and ActionItem. Both elements do not support this property. As it is mentioned in the feature request [here](https://github.com/NativeScript/NativeScript/issues/2621), the `automationText` property is added to the View class. Regarding that, the NavigationButton and ActionItem will not have the property, because they do not inherit the View class. You can check the code [here](https://github.com/NativeScript/NativeScript/blob/05c2460fc4989dae4d7fa1ee52f6d54e0c3113f5/tns-core-modules/ui/action-bar/action-bar.d.ts#L92).

**Comment by Johanneke** [comment]
And no plans to support automationText on those elements in the future?

In your example, the `automationText` is on the `Label`, not on the `StackLayout`. Because Appium cannot read the original text anymore when you add an `automationText` on a `Label`, we would like to add the text to the `StackLayout`. At least on iOS, this doesn't work with Appium.

**Comment by FBorgonjen** [comment]
Hi @tsonevn, 

I've tested your proposed solution. The good news is, the element is accessible. The bad news is that the contents of the elements are no longer available for evaluation. 

Here is a code snippet of the StackLayout when it is not accessible:
```
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="196" width="375" height="54">
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Account name" name="Account name" label="Account name" enabled="true" visible="true" x="12" y="196" width="96" height="53"/>
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value="Personal account" name="Personal account" label="Personal account" enabled="true" visible="true" x="206" y="196" width="140" height="53"/>
  <XCUIElementTypeStaticText type="XCUIElementTypeStaticText" value=">" name=">" label=">" enabled="true" visible="true" x="345" y="211" width="18" height="24"/>
</XCUIElementTypeCell>
```

And here when it is set to accessible:
```
<XCUIElementTypeCell type="XCUIElementTypeCell" enabled="true" visible="true" x="0" y="196" width="375" height="54">
  <XCUIElementTypeOther type="XCUIElementTypeOther" name="ACC_ID" label="ACC_ID" enabled="true" visible="true" x="0" y="196" width="375" height="54"/>
</XCUIElementTypeCell>
```

Do you have any clue of what is happening with the contents? It looks like a completely different element is attached instead.
