### ISSUE TITLE
Ability to dismiss a dialog

### ISSUE THREAD

**Issue by kkoates** [NativeScript/NativeScript#6319]
Please consider adding the ability to dismiss a [dialog](https://docs.nativescript.org/ui/dialogs) programmatically.

I understand the  intended use of a dialog is to alert or capture feedback from the user so from a traditional sense there is no need for this functionality.  

However (my use case):

If this functionality is added I would be able to easily use a confirm dialog to notify a user their session is about to expire.  When the session expiration occurs I would be able to dismiss the dialog.  Currently all dialogs require user interaction to dismiss.

**Comment by bradmartin** [comment]
This has come up a few times with decent use cases IMO. Android has a dismiss method on its dialog. iOS I believe provides some way with the view controller to close dialogs but not certain 😁.

**Comment by tsonevn** [comment]
Hi @kkoates,
In your case, you can create a custom modal view, which can be shown instead of dialog. You can close the modal view every time you need by calling `closeModal ` method. More about the modal views can be found here.

Another option is as @bradmartin suggested to use the android native dismiss method to close the dialog programmatically.  Check out [this](https://stackoverflow.com/questions/18136342/how-to-close-a-dialog-in-android-programmatically) thread in StackOverflow. It seems that similar [method also exists for iOS] (https://stackoverflow.com/a/31857599/6133327).

**Comment by bradmartin** [comment]
@tsonevn - I only glanced at the dialog source last week, so I could be wrong, but I don't think they return a reference to the dialog in order to do this correctly.
