### ISSUE TITLE
[android] recyclerview slow scroll on first run

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#6321]
I create that issue here because I need some help from the Nativescript team to figure out what is going on.

I am implementing an open source CollectionView plugin:
https://github.com/Akylas/nativescript-collectionview

I needed to fix issues in RadListView but as it is not open source I had to start writing my own.

The plugin is already working for nativescript/angular/vue. But I am facing a performance issue.

# The symptoms:
When I run my app on android the first time I can see a first scroll is lagging.Once that first scroll is done the list view is really really fast (faster than Nativescript list view).
If I close my app with "back" and open it again, It won't lag. 
if I "kill" my app and run it again, I get the lag.

I should mention already that I have tested and I see the same lag with RadListView

# The cause
My plugin uses a RecyclerView just like RadListView.
The ```onCreateViewHolder``` create a Nativescript View which is only "loaded" if necessary in the ```onBindViewHolder```. It is using the same patch system that RadListView uses so that It works in angular and Vue.

After some tests the lag clearly comes from the View "loading" (properties apply, nativeView creation...)

The weird thing which I can't wrap my head around is why this only happens on the "first run".

Also this does not seem to happen that much with Nativescript ListView which I really don't understand. I do see a lag but seems really "lighter"

Any help would be much appreciated. I should mention that any fix would benefit RadListView too.

# Testing

You can reproduce the issue using the "dev_demo" app from my plugin.
simply run ```tns run android``` from that folder.

You can also simply switch between ListView/CollectionView/RadListView in the xml file

**Comment by NathanaelA** [comment]
Hi Martin, 

If by first run, you mean the first time it loads that screen, then yeah this is unfortunately normal behavior on NativeScript Android.   The root of the issue is that during a navigation a lot of things happen which can cause very inconsistent variable times.  The biggest one is GC, if a GC occurs you will see widely varying times.   The JS is cached and parsed only once; so the first time you enter the screen it has the overhead of loading and parsing the JS.   Each additional time, it is already cached.

If you are using Angular; the times can be drastically worse just because the parsing overhead of is amplified by all the extra JS it has to parse and use to perform the same statement, and you are more likely to have a GC hit.

In addition because this is a recyclerview it has to instantiate each of the additional templates; each template that it needs it has to parse and create all the elements in it.   It will then start caching the templates and will reuse them, so the first scroll will always be slower because the optimal number of templates won't have been loaded and cached until you scroll.     Once they have been created and cached; scrolling will normally be instant as it then reuses the templates and no longer has to parse and create them.   If you have more than one template type; then this will take more creation time as each of the templates have to be parsed and created for each record that is in view.

In comparison creating a Textview is trivial and uses very little work and memory, so its time will be very consistent.

A couple possible solutions/hints:
1.  You can try using "markingmode: none" you can see if that will help stabilize some of the time.
2. Webpacking (especially if using Angular)
3. Moving some of the creation code of the Components into pure Java, their is a "price" to go over the bridge; so if there are say 10 lines of Java calls that has to be called for each template creation; this is much quicker of those 10 lines are in Java and you only make one call into the runtime.   (This is why TNS-Core-Modules-Widgets exists, because especially during creation of elements eliminating as many of the bridge calls can make a huge difference when you multiply it by the number of items being created).
4. Manually run a JS GC and a OS GC _before_ you navigate to the screen, this can make your time for performance testing a lot more consistent.

**Comment by farfromrefug** [comment]
@NathanaelA Thanks for the deep explanation. I do understand more now.

The first thing is I tried ```markingMode``` but it did not make any difference. My app is faster but no difference on the first scroll.

Now what bugs me is why is this not happening with Nativescript ```ListView```. Yes android ```ListView``` and ```RecyclerView``` are different. But they should not be that different.

I might have a clue though. 
Just used ```timeline-view``` and saw this:
<img width="1633" alt="screen shot 2018-10-01 at 15 08 16" src="https://user-images.githubusercontent.com/655344/46290456-3039fc80-c58c-11e8-9d99-79792a3d9443.png">
Could the issue be that I use a Javascript class extending a native one?

Will try without it to see

**Comment by NathanaelA** [comment]
@farfromrefug - Your welcome, gaining performance is one thing I love...   

I can't say I've ever seen extending cause a slow down; extending is normally a fairly simple op, so I'm going to "guess" you are seeing a GC hit, which is what is skewing your time.       But I could be wrong, maybe some regression has occurred when they moved from one v8 engine to another that nobody noticed.  

Well while measuring make sure you do a:
```
   global.gc();   // Trigger a JavaScript GC pass
   java.lang.System.gc();  // Trigger a Java GC Pass
  // Start your navigation to screen, or any other task you wish to measure
```
before you do anything.   If a GC occurs in the middle of Navigation (which does happen quite frequently in a navigation) your timing will be way off.   Remember the GC will PAUSE your running code, so if it triggers in the middle; something that is only 1ms can jump to 200ms for no apparent reason.   The two GC triggers "hints" to do a GC, but I've found most the time they actually do run.

**Comment by farfromrefug** [comment]
@NathanaelA tried with the GC, made no difference.

Also I actually realized  that in the same right condition (app killed, first run) this also happens with the ```ListView```.

I keep on investigating!

**Comment by NathanaelA** [comment]
I am surprised that running the GC didn't help.  Normally that fixes any of the weird inconsistent timings and they then always then start taking a consistant XXXms +/- 10ns

Yep, template inflation can be a killer speed issue.  (I made reference to templates a couple posts up, as I know it is a perf area that costs lots of time).    How are you testing the OnCreateViewHolder via Android; did you create a java module; or are you still using it via JavaScript?     

This is one of the reasons why the TNS-widgets exists; because of eliminating more bridging.   However, I'm not sure of a easy way to speed this part up since basically it is XML (parsed into JS calls) -> JS (Calls run and then bridged into Android OS calls)

**Comment by farfromrefug** [comment]
I still use nativescript to test ```OnCreateViewHolder```. That s on purpose. Seeing the improvement just by inflating through nativescript tells me that it can be improved.

**Comment by racknoris** [comment]
This is exactly what I've been searching for to help me solve performance issues with RadListView, will check if it helps.
@NathanaelA - regarding your solution of moving creation code to Java: could you please tell me where to look for an explanation?

**Comment by NathanaelA** [comment]
@racknoris - Not sure their is an explanation anywhere; just one of those things you figure out based on how things work.    In a nutshell their is a small "bridging" cost when JS talks to Native.   The cost is small; but it can add up as each call from JS to Native pays the cost.   So if you call 5 Java functions from JS; each of those calls has a small bridging cost.    If you put all 5 of those Java functions inside a single Java function and call a single Java function from JS; then you only pay the bridging cost once instead of 5 times.      This is why their is a tns-native-widgets library; because the majority of the setup for standard widgets is done in native code and eliminates as many "bridging" calls as possible.

**Comment by racknoris** [comment]
I see, thank you.
Tried `markingmode: none` / gc calls / webpack, and it didn't make much difference. As a workaround I set the opacity of the list to 0.01 at first, insert elements of each type to the list, then scroll with animation to some index, followed by removing all the elements and then setting the opacity to 1 - this does the trick, takes roughly 2 seconds
