### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by ucdstudent95618** [NativeScript/NativeScript#6357]
Hello NativeScript Team,

I want to translate the GitHub page to Spanish, is that something you would like to do?

Thanks,

Miguel

**Comment by tsonevn** [comment]
Hi @ucdstudent95618,
Can you provide some more info about your suggestion? 
> translate the GitHub page

Did you mean that you would like to translate the [README.md](https://github.com/NativeScript/NativeScript/blob/master/README.md) file in the NativeScript repository or the articles from NativeScirpt [docs](https://docs.nativescript.org/)([here](https://github.com/NativeScript/docs) is the repository)?

**Comment by ucdstudent95618** [comment]
Yea I was referring to the README.md.

**Comment by radeva** [comment]
Hi @ucdstudent95618 ,

I'm curious what's the need to have the readme also in Spanish?

**Comment by ucdstudent95618** [comment]
I'm not sure if you have been aware, but a lot of popular repos have translations in many languages. But, it's ultimately up to you, if you would like me to translate. I can also translate the Native Script docs that are within the repository.

**Comment by radeva** [comment]
Thanks @ucdstudent95618 for your offering! Currently we don't have such plans since it would be quite difficult for us to maintain the translation and also we consider that English is popular enough and is not an issue for Spanish native speakers. Nevertheless, we'll explore the need and if we identify such translation is required, we'll have you in mind.
