### ISSUE TITLE
Error in tns-core-modules when trying to get a video

### ISSUE THREAD

**Issue by odparraj** [NativeScript/NativeScript#6408]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2.0
 - Cross-platform modules: 4.2.0
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s): nativescript-mediafilepicker: 2.0.13

**Describe the bug**
it is a run-time error, I am trying to get a video using the nativescript-mediafilepicker plugin, it turns out that in the execution when I select the video sometimes an error is generated that blocks the application.

**To Reproduce**
launch the video file picker and select a video from the gallery, it does not always happen but surely if you do it 5 times repetitively you will find the error.

**Expected behavior**
the plugin makes a copy of the video to the application folder, should return the result of this operation and give the video data

**Sample project**
https://github.com/odparraj/nativescript-mediafilepicker

**Additional context**
the error happens only in ios, it does not happen in the emulator, but I try in a physical device and it fails most of the time with some videos.

attached an image of the errors that throws

![captura de pantalla 2018-10-12 a la s 6 45 40 p m](https://user-images.githubusercontent.com/9358581/46898425-43cc4980-ce4f-11e8-9606-3473a00fb8d6.png)

**Comment by NickIliev** [comment]
@odparraj the issue seems related to the nativescript-mediafilepicker plugn as it will return the following JS error

```
file:///app/tns_modules/nativescript-mediafilepicker/mediafilepicker.js:334:37: JS ERROR TypeError: null is not an object (evaluating 'urlAsset.URL')

```

It would also return the following native error prior to the error above.
```
Performing any operation from a background thread on UIView or a subclass is not supported and may result in unexpected and insidious behavior. 
```

Please consider opening an issue[ in the plugin's repository ](https://github.com/jibon57/nativescript-mediafilepicker/issues) while providing a detailed explanation and reference to the information needed to reproduce the issue. 

Closing this one as not related to `the tns-core-modules`
