### ISSUE TITLE
horizontalAlignment Not Working For StackLayout with horizontal orientation

### ISSUE THREAD

**Issue by rakeshgirase** [NativeScript/NativeScript#6410]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 4.2
 - Cross-platform modules:
 - Android Runtime: 
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
The horizontalAlignment  attribute doesnt work as expected when the StackLayout has Horizontal orientation in android as well as on ios.

**To Reproduce**
Checkout playground example https://play.nativescript.org/?template=play-tsc&id=lTkWt1&v=2
Here I have given two stacklayout with and without horizontal orientation and you can see the difference. 

**Expected behavior**
The three labels should be in the left, center and right in the StackLayout with horizontal orientation.

**Sample project**
https://play.nativescript.org/?template=play-tsc&id=lTkWt1&v=2

**Additional context**
None

**Comment by tsonevn** [comment]
Hi @rakeshgirase,
Thank you for the provided sample project.
Regarding the issue, while setting up the StackLayout with a horizontal orientation, the width of the container seems to be set to infinity. In this scenario, the  `horizontalAlignment` will have no effect on the child components(in your case the `Labels`). You can check the provided [example in the docs,](https://docs.nativescript.org/ui/layouts/layout-containers) where it is demonstrated, the usage of the Layouts. 
Regarding your case, I would suggest using a GridLayout instead of StackLayout. Check out the [example](https://play.nativescript.org/?template=play-tsc&id=lTkWt1&v=3).
