### ISSUE TITLE
Webstorm compatible webpack.config.js

### ISSUE THREAD

**Issue by andrewvmail** [NativeScript/NativeScript#6459]
Webstorm doesn't seem to like the default webpack.config.js when i open up webstorm i get this notice.

```
	Can't analyse webpack.config.js: coding assistance will ignore module resolution rules in this file.
				Possible reasons: this file is not a valid webpack configuration file or its format is not currently supported by the IDE.
				Error details:  You need to provide a target platform!
```
Everything seems to be okay except when refactoring an export const webstorm doesnt give out error messages until i open up files that uses that exported const manually. Although I can see the error in the tns run console messages.

**Comment by tsonevn** [comment]
Hi @andrewvmail,
I have created a sample NativeScript project using Webstorm and was able to build the project successfully with `tns run <platform_name> --bundle` without facing the problem mentioned above.
I also made some research and found a similar issue reported [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000166839-Webpack-coding-assistance-keeps-getting-disabled), however, I do not think that NativeScript is responsible for this error.

**Comment by andrewvmail** [comment]
Hi @tsonevn Thanks so much! 
I was Googling around I missed that.
Okay will figure it out from here. I'll post back when I have something.

**Comment by NathanaelA** [comment]
@tsonevn - Actually this is caused by the webpack config that NativeScript uses.
See: https://youtrack.jetbrains.com/issue/WEB-31627
Your line of code here:
![image](https://user-images.githubusercontent.com/850871/59328355-c1cc4300-8cb1-11e9-8922-e7ddce05b58c.png)
Causes this to fail to be evaluated inside the *storm editors...   

If you do this:
![image](https://user-images.githubusercontent.com/850871/59328705-af9ed480-8cb2-11e9-8410-ea33fe2dc588.png)

It works...  Because now the nativescript webpack config is no longer throwing an error, because the platform is set to "android".   :)

**Comment by Cclown98** [comment]
that solution does not work at all for me :(

**Comment by NathanaelA** [comment]
Yeah, things have changed in the webpack file since then.   For webstorm to read it properly you need to use the above fix; **and** you need to change:
`appPath = "src",`
to 
`appPath = "app",`

However, I don't know if webpack can actually build the app with that change -- I honestly haven't checked; just made Webstorm to read the webpack config file properly...

**Comment by Cclown98** [comment]
Thank you so much sir, the method actually worked like a charm, and it does compile on both Ios and android
