### ISSUE TITLE
Allow console.log in production mode?

### ISSUE THREAD

**Issue by vance** [NativeScript/NativeScript#6531]
**Is your feature request related to a problem? Please describe.**
console.logs appear to not work in prod mode

**Describe the solution you'd like**
A way to have prod builds not omit `console.log`. I'd like to have my onscreen console monkey patch work in prod so I can show console traces in prod... I also patch error, and would like to capture console.error as well.

**Describe alternatives you've considered**
firebase error logging, but slow and hard for reproducing certain errors.

**Comment by NickIliev** [comment]
@vance one of the reasons we disabled the console.logs in production is because console printing tends to be a resource consuming operation which might degrade the application performance. This is something no developer would want to happen in production so that said + the fact that there was never a console.log in production for iOS made us remove the console.log for Android production

**Comment by vance** [comment]
Oh, just thought of something... maybe if I reference the window.console it wont uglify those out.

**Comment by NickIliev** [comment]
@vance indeed the console is handled build time and depends on the release vs debug flag that is passed to the CLI (the actual PR that prevents the logs in release for Android [here](https://github.com/NativeScript/android-runtime/pull/1038/files)).
