### ISSUE TITLE
How Repeater.itemsLayout property should work?

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#6554]
This works as expected (without `<Repeater.itemsLayout>` and wrapped by `<StackLayout>`):

```
<GridLayout columns="auto, *" rows="auto">
    <Label text="Some Text" row="0" col="0" backgroundColor="orange"/>
    <StackLayout row="0" col="1" backgroundColor="green">
        <Repeater items="{{ items }}">
            <Repeater.itemTemplate>
                <Label text="{{ $value }}"/>
            </Repeater.itemTemplate>
        </Repeater>
    </StackLayout>
</GridLayout>
```
And this as NOT expected (with `<Repeater.itemsLayout>` and without wrapping by `<StackLayout>`):

```
<GridLayout columns="auto, *" rows="auto">
    <Label text="Some Text" row="0" col="0" backgroundColor="orange"/>
        <Repeater items="{{ items }}">
            <Repeater.itemsLayout>
                <StackLayout row="0" col="1" backgroundColor="green"/>
            </Repeater.itemsLayout>
            <Repeater.itemTemplate>
                <Label text="{{ $value }}"/>
            </Repeater.itemTemplate>
        </Repeater>
</GridLayout>
```

What is Repeater.itemsLayout property for? How and in what cases to use it?

**Comment by NickIliev** [comment]
@webleaf the `itemLayout` property is to actually change the default layout of the repeater (which is **StackLayout with vertical orientation**). For example look [at this Playground demo](https://play.nativescript.org/?template=play-tsc&id=d23cJm) where the default layout is changed to `horizontal` Stacklayout.

```
<ScrollView orientation="horizontal">
	<GridLayout columns="auto, *" rows="auto, *">
		<Label text="Some Text" row="0" col="0" backgroundColor="orange" />
		<Repeater row="1" items="{{ items }}">
			<Repeater.itemsLayout>
				<StackLayout backgroundColor="green" orientation="horizontal" />
			</Repeater.itemsLayout>
			<Repeater.itemTemplate>
				<Label text="{{ $value }}" padding="10" margin="8" color="white"
					backgroundColor="orangered" height="40" />
			</Repeater.itemTemplate>
		</Repeater>
	</GridLayout>
</ScrollView>
```


Note in your second example the row and cols properties of the grid should be applied to the Repeater and can't be applied to the itemsLayout container.

**Comment by webleaf** [comment]
@NickIliev There are also not documented that `<Repeater.itemTemplate>` can contain only one child. It's not obvious and don't produce any errors.
If you try to make `push()` to `ObervableArray` which is binded to `Repeater`, you don't get any error, until you wrap your `push()` method with `try/catch` block. It produce `TypeError: Cannot set property 'bindingContext' of undefined`. And `error.stack` contain:
```
JS: TypeError: Cannot set property 'bindingContext' of undefined
JS:     at Repeater.refresh (file:///data/data/com.test/files/app/tns_modules/tns-core-modules/ui/repeater/repeater.js:48:38)
JS:     at Repeater._requestRefresh (file:///data/data/com.test/files/app/tns_modules/tns-core-modules/ui/repeater/repeater.js:34:18)
JS:     at Repeater._onItemsChanged (file:///data/data/com.test/files/app/tns_modules/tns-core-modules/ui/repeater/repeater.js:54:14)
JS:     at Object.handler [as callback] (file:///data/data/com.test/files/app/tns_modules/tns-core-modules/ui/core/weak-event-listener/weak-event-listener.js:30:34)
JS:     at ObservableArray.Observable.notify (file:///data/data/com.test/files/app/tns_modules/tns-core-modules/data/observable/observable.js:110:23)
JS:     at ObservableArray.push (file:///data/data/com.test/fi...
```
I spend whole day to localize it.

**Comment by NickIliev** [comment]
@webleaf you can still wrap the repeater in whatever layout you want... the `itemLayout` property is actually setting the layout that the repeater will use to render the templates. Both are two different functionalities. The `itemTemplate` is defining the way the Repeater will layout. The outer layout is simply a container for your nested (child) components no matter if they are repeaters or labels or something else.

Regarding your question why the ListView does not support `ItemLayout` - well this can be logged as a feature request but the main reason for this one not to be implemented is because there is already [RadListView which supports a number of item layouts](https://docs.telerik.com/devtools/nativescript-ui/Controls/NativeScript/ListView/item-layouts).

You are right about the missing documentation about the single child that the ItemTemplates is supporting - I will take care of that and it a section to the documentation.

**Comment by NickIliev** [comment]
@webleaf, in my opinion, using proxy would be more limiting. Let's say for example that you want to have a Repeater and label inside a `DockLayout` and at the same time, you need to render your repeater items as `StackLayout`. Making the Repeater to proxy the parent will force you to create yet another wrapper.  It would also cause more confusion as the Repeater UX will depend on the parent layouts instead of its own internal properties.

On the other hand, exposing the property `itemLayout` is providing also more readability to the code - you will know that the repeater has this item layout and won't have to look for the parent (which if using custom component can be located in a totally different page). Or in cases, where the property is set dynamically (via code-behind) you still won't have to bother to look for the parent layout and would directly use the property.

**Comment by webleaf** [comment]
@NickIliev thank you for answers.
