### ISSUE TITLE
Add a bottom and right property for AbsoluteLayout

### ISSUE THREAD

**Issue by lscown** [NativeScript/NativeScript#662]
To be able to define the position from the bottom as well as right would mean that there's no guess work in DP and would work great with elements such as the Floating Action Button.

http://www.google.com/design/spec/components/buttons-floating-action-button.html#

**Comment by enchev** [comment]
Hey @lscown,

We have such button in our [Tasks app](https://github.com/NativeScript/sample-Tasks). Can you check if this will work for you?

Thanks

**Comment by surdu** [comment]
The Tasks app is now removed 😞

**Comment by neoswf** [comment]
+1

**Comment by xaamin** [comment]
+1

**Comment by ishitatsuyuki** [comment]
This is extremely annoying. I found **zero** workaround for my current positioning:

```
    left: 32;
    right: 0;
```

I need it for the calendar view (timeline view).

Please reopen, at least.

**Comment by surdu** [comment]
Why is this closed? 😞

**Comment by SephReed** [comment]
There is currently no known way to position an element at the bottom of a screen with content which goes under it.  I've currently got a swish which I can not seem to position at the bottom of the screen correctly.  In this render it's too far down because the parent height it got was too tall (not including padding).

It has a 200ms timeout before requesting parent height.  That's _insane_.  My next guess on what to do is literal _polling_.  

<img width="401" alt="Screen Shot 2019-04-12 at 11 15 04 AM" src="https://user-images.githubusercontent.com/14002040/56051465-4fbc9980-5d14-11e9-9cef-9b6da0b8ea48.png">

Unfortunately, it's not really possible to do bottom align on ios AFAICT.  You can't click through a parent but not a child, which means using a flex layout over the top is no good.  You can't wait for render events, which means that hard coding it is no good.  It seems this is a flaw with iOS more than nativescript, and it blows my mind.

**Comment by NathanaelA** [comment]
Actually on this one I would use a GridLayout.   It allows stacked items, and their is some other flags (like: `isUserInteractionEnabled` ) to enable click through on elements.

**Comment by SephReed** [comment]
You'd answered that here, and it works perfectly:

https://github.com/NativeScript/NativeScript/issues/5591#issuecomment-482640921
