### ISSUE TITLE
TabView.androidOffscreenTabLimit = 0 doesn't work as expected

### ISSUE THREAD

**Issue by doffltmiw** [NativeScript/NativeScript#6650]
I've noticed that the default value of `androidOffscreenTabLimit` changed from 0 to 1 when setting `androidTabsPosition` to `bottom`(61bda9ecdfb97c09427640cdce1474f92ce1ef1b). What is the rationale for that? Is it because setting `androidOffscreenTabLimit` to 0 doesn't work? It seems that its minimum value is 1 in ViewPager[1].

So, what is the recommended approach to avoid preloading tabs as of now?

The documentation also needs to be updated if this is the case. (https://docs.nativescript.org/ui/ns-ui-widgets/tab-view)

[1] https://stackoverflow.com/questions/10073214/viewpager-setoffscreenpagelimit0-doesnt-work-as-expected

**Comment by NickIliev** [comment]
@doffltmiw the preload option is only applicable when the tabView position is set to `top` (and that is why [the line you are referring to ](https://github.com/NativeScript/NativeScript/pull/6476/files)is checking if the position is top). When the TabView is top (native Android behavior) we have a slide animation and preloading is making sense to assure that the transition from one fragment to another with animation will work as expected.

On the other hand, the `bottom` functionality is similar to the iOS one (no transition animation) and that's why we don't need preloading when the tabs are positioned at the bottom.

I agree that this one needs to be described in the documentation in details so marking the issue as `docs-needed`

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/docs #1456](https://github.com/NativeScript/docs/issues/1456) via [**ZenHub**](https://www.zenhub.com/)

**Comment by doffltmiw** [comment]
@NickIliev No, the TabView with `androidTabsPosition` set to `bottom` preloads the tabs, it doesn't work like the iOS one. Setting `androidOffscreenTabLimit` to 0 doesn't help either.

I've created a playground demo here: https://play.nativescript.org/?template=play-js&id=tso5F2&v=2
Change tabs to see the console output. For example, selecting the tab4 from tab1 outputs "tab3 loaded" "tab4 loaded" "tab5 loaded".

**Comment by NickIliev** [comment]
@doffltmiw according to documentation ([here](https://docs.nativescript.org/angular/ui/ng-ui-widgets/tab-view))

> Setting the Tabs at the bottom will disable the swipe navigation and the items preloading functionality.

The thing is that by design on Android at least one tab will be preloaded so setting 0 will not work (which is why [this line](https://github.com/NativeScript/NativeScript/pull/6476/files) prevents settings 0 when the tab position is bottom). By disabling the preload functionality the documentation section means that effectively you can not change the number of preloaded tabs when the position is bottom

**Comment by doffltmiw** [comment]
@MartoYankov In most use cases for a bottom TabView interface, users wouldn't access tabs sequentially one after another, so preloading adjacent tabs will be a waste of resources. I also want the content of a tab reloaded from the server if it's not up to date as the user switches between them, but because of the preloading I can't do it in the page loaded event.

I should probably use the `selectedIndexChanged` event, but it gets tricky as this event can be fired even before the frame is constructed, so I guess something like this will work?

```
// attach this to each page in the tab items
export function onNavigatingTo(args: NavigatedData) {
  const tabView = <TabView>topmost().parent.parent;

  if (tabView.selectedIndex == 0 && args.isBackNavigation == false) {
    loadData();
  }

  tabView.on("selectedIndexChanged", (args) => {
    if (args.newIndex == 0) {
      loadData();
    } else {
      releaseData();
    }
  })
}
```

**Comment by MartoYankov** [comment]
@doffltmiw Yep, right now you will have to do something like this. We are aware of all the various problems with the component. Upgrading the TabView developer experience is on our immediate roadmap.

**Comment by Momazo7u7** [comment]
I was wondering why it androidOffscreenTabLimit didn´t work when i had the tabs at the bottom. Welp, time to wait for a possible fix
