### ISSUE TITLE
The TextView text will be cut while adding a new line

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/NativeScript#6658]
**Environment**
 - CLI: 5.0.2
 - Cross-platform modules: 5.0.5
 - iOS Runtime: 5.0.5

![screencast 2018-12-04 at 12 08 45 pm](https://user-images.githubusercontent.com/17448734/49435716-eb1a8c80-f7bf-11e8-9cd4-1996cde964d8.gif)

The text in the TextView will be cut when a new line has been added. When a second new line is added the text will be layout correctly. The layout problem can be noticed only when the user is typing. When the input is dismissed, the text will be sized properly.  I am attaching a sample project, which can be used for debugging.

[Archive.zip](https://github.com/NativeScript/NativeScript/files/2643458/Archive.zip)

**Comment by tsonevn** [comment]
Might be related to https://github.com/NativeScript/NativeScript/issues/6193

**Comment by manoldonev** [comment]
This problem seems to be related to the [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) native library (exposed via nativescript-iqkeyboardmanager plugin in NativeScript) that prevents issues with keyboard sliding up and covering your text inputs and not the NativeScript TextView component itself.

The provided workaround for a similar issue [in the native library repo](https://github.com/hackiftekhar/IQKeyboardManager/issues/547#issuecomment-232394664) does not solve the problem in our scenario (reported not working [here](https://github.com/hackiftekhar/IQKeyboardManager/issues/1285) as well) so find attached a sample application that works around the issue in a different way:

``` ts
    // only tamper with the contentOffset if we detect a new line (\n) has been inserted
    // with the current text change (diff implementation from fast-diff npm module)
    onTextChange(args) {
        if (isIOS) {
            const result = diff(args.oldValue, args.value);
            for (const chunk of result) {
                if (chunk[0] == 1 && chunk[1] == "\n") {
                    setTimeout(() => args.object.ios.contentOffset = new CGPoint(), 100);
                    return;
                }
            }
        }
    }
```

``` ts
    // opening the keyboard initially works as expected, but if you close it and try to 
    // open it again, textview is clipped, the onFocus handler fixes that
    onFocus(args) {
        if (isIOS) {
            setTimeout(() => {
                const iqKeyboard = IQKeyboardManager.sharedManager();
                iqKeyboard.reloadLayoutIfNeeded();
            }, 100);
        }
    }
```

[bl35.zip](https://github.com/NativeScript/NativeScript/files/2724624/bl35.zip)
