### ISSUE TITLE
iOS exceptions are not getting caught by uncaughtErrorEvent

### ISSUE THREAD

**Issue by KkevinLi** [NativeScript/NativeScript#6662]
**Environment**
```⚠ Update available for component nativescript. Your current version is 5.0.1 and the latest available version is 5.0.3.
✔ Component tns-core-modules has 5.0.5 version and is up to date.
✔ Component tns-android has 5.0.0 version and is up to date.
✔ Component tns-ios has 5.0.0 version and is up to date.
```

**Describe the bug**

No uncaughtError event is raised for native iOS errors such as NSInvalidArgumentException.

**To Reproduce**

I am using the following to test:
```  // hard crash -[NSArray objectAtIndex:]: method sent to an uninitialized immutable array object
  static iosCrashTest1() {
    console.log("IOS Crash Test 1");
    const foo: NSArray<any> = NSArray.alloc();
    foo.objectAtIndex(3);
  }
```

**Expected behavior**

Expected an uncaughtErrorEvent to be thrown (logging purposes). Right now I get a Javascript call stack followed by *** Terminating app due to uncaught exception 'NSInvalidArgumentException' ...***

**Comment by tsonevn** [comment]
Hi @KkevinLi,
We have checked your case and found that the iOS exceptions are not getting caught by `uncaughtErrorEvent`, because of a missing feature. Regarding that, I will mark the issue as a feature request and will move it in the ios-runtime repository, where we can keep the discussion about this feature. 
Also, there is an experimental branch, which enables this functionality in NativeScript. You can find it [here](https://github.com/NativeScript/ios-runtime/tree/bektchiev/throw-objc-exceptions-to-js).

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/ios-runtime #1029](https://github.com/NativeScript/ios-runtime/issues/1029) via [**ZenHub**](https://www.zenhub.com/)
