### ISSUE TITLE
App crashes navigating through tabs

### ISSUE THREAD

**Issue by wa05** [NativeScript/NativeScript#6687]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.3
 - Cross-platform modules: - 
 - Android Runtime: 5.0
 - iOS Runtime: -
 - Plugin(s): Mapbox / Localization

**Describe the bug**
App crashes navigating through tabs

**To Reproduce**
Tabs at the bottom.
Change tab, go back once or twice and application crashes without error on console or VueDevtools.

**Sample project**
https://github.com/wa05/nativescript-tabs-mapbox

I've tried to simulate it one the Playground but It works well.. maybe is one of the plugins.
I saw other similar issues but I couldn't understand if this is fixed or not.

**Comment by tsonevn** [comment]
Hi @wa05,
Thank you for the provided sample project.
I have tested the case and found that this problem with the project happens only while using the nativescript-mapbox. In my opinion, the issue is related to the plugin. Regarding that, I am moving the issue in the mapbox repository, where we can keep the discussion.

**Comment by tsonevn** [comment]
This issue was moved to EddyVerbruggen/nativescript-mapbox#285
