### ISSUE TITLE
Partial Android modal (non-fullscreen) is displayed with random animation transition

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#6689]
Open an Android modal page (not fullscreen) and observe the enter transition. By default, it will be fade but on random occasion, it will be a slide from the bottom right corner.

Steps to reproduce:
- Use[ the modal navigation demo ](https://github.com/NativeScript/modal-navigation-demo)
- [Modify the modal to have `fullscreen` option set to **false**](https://github.com/NativeScript/modal-navigation-demo/blob/master/app/home/home-page.ts#L21) (in the app the value is `true`)
- Open the modal page multiple times. In some occasion, it will open with fade transition but sometimes it will load with a slide (from bottom/right).

Possibly related to Android fragment logic in `ui/frame` ([details](https://developer.android.com/reference/android/support/v4/app/Fragment#onCreateAnimation(int,%20boolean,%20int)))

> Note that if setCustomAnimations(int, int) was called with Animator resources instead of Animation resources, nextAnim will be an animator resource.

Reported via t.1364642

**Comment by vakrilov** [comment]
We have investigated the issue. 
### The Problem
It occurs when there is a `Frame` as **root of the modal view** that is being shown. It happens seemingly randomly if the navigation in the `Frame` is triggered in the `shownModally` or if the Frame is loaded from XML. The "strange" (slide form bottom right corner) animation **always** occurs if you trigger the initial Frame navigation with a `setTimeout`. 

The random behavior is because sometimes the initial frame-navigation gets executed together with the dialog show navigation, but sometimes it is delayed and the dialog-show navigation is started while the frame still hasn't started the navigation and has no `Page` loaded in it. The second case results in the "strange" animation. 

### Workaround
**Fortunately there is an easy workaround** - wrap the `Frame` within a layout (ex. `GridLayout`). The result is that the dialog will always have a view ready(the grid) when it is showing. Event if the navigation in the `Frame` inside is delayed for some reason - this will not cause the "strange" animation.

Here is a [playground link](https://play.nativescript.org/?template=play-tsc&id=W10eM4&v=2) that you can see all of that.  It has a couple of buttons that show modal view:
- `XML Frame` - opens a dialog with `Frame` as root form XML. "Strange" animation happens randomly.
- `Code Frame` - opens a dialog with `Frame` as root form code. "Strange" animation happens randomly.
- `Code Frame with Delay` - opens a dialog with frame as root form code, but navigate in the `Frame` with `setTimeout`. "Strange" animation aways happens.

There is another set of buttons that do the same, but use a `Frame` wrapped in a `GridLayout` (the workaround). They always work as expected!

### "Real" fix
Unfortunately, we couldn't implement a out-of-the-box fix. The reason for this is that the `Frame` always waits for [`onAttachedToWindow`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/frame/frame.android.ts#L137-L141) event to trigger the initial navigation. The internal logic relies heavily on that. In the case of dialog this event is sometimes triggered by Android a bit too late and the show-dialog window animation is already started which leads to the "strange" navigation.

**Comment by NickIliev** [comment]
Closing this issue as the above comment is providing an applicable workaround and there is no suitable fix that can be applied. For solving this case, please use the workaround provided above (example in the snippet below).

```XML
<!-- Nest the frame from the modal view inside a GridLayout -->
<GridLayout>
    <Frame defaultPage="modal-content-page"></Frame>
</GridLayout>
```
