### ISSUE TITLE
repeater.d.ts don't have all methods of Repeater class

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#6704]
I want extend [Repeater](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/repeater/repeater.ts#L17), but not all methods of Repeater class [are defined](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/repeater/repeater.d.ts#L11). I need all of them.

**Comment by vakrilov** [comment]
Hey @webleaf,
Repeater is one of the oldest components and we haven't touched its definitions for a long time.

Are you willing to open a PR with a concrete suggestion of the APIs you need exposed in order to extend the `Repeater` class. Probably some of the methods can be made `protected` and exposed in the `d.ts` file.
You can check the [CONTRIBUTING.md](https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md) for more info on how to open a PR.

**Comment by Sumer312** [comment]
Hi, can I take on this issue ?

**Comment by rigor789** [comment]
Repeater no longer has a manually authored `.d.ts` file, the generated file should always contain everything authored in the `.ts` file.
