### ISSUE TITLE
Reference to a non-exported function in 'SocketIOModule'

### ISSUE THREAD

**Issue by Dhruvi109** [NativeScript/NativeScript#6716]
Error: Failed to compile.

ERROR in Error during template compile of 'AppModule'
  Reference to a non-exported function in 'SocketIOModule'
    'SocketIOModule' contains the error at nativescript-socketio/angular/index.ts(25,10).
below are the details of package json

 "tns-android": {
      "version": "5.0.0"
    },
    "tns-ios": {
      "version": "5.1.0"
    }

"@angular/compiler-cli": "~7.1.0",
"@ngtools/webpack": "~7.1.0",

we are facing above issue only in IOS when we execute following command 

tns build ios --bundle --env.aot --env.uglify;

Has anyone ever had this problem? Need help.

**Comment by tsonevn** [comment]
Hi @Dhruvi109 
The problem seems to be related to the nativescript-socketio plugin. I would suggest contacting the plugin's author by logging a [new issue ](https://github.com/triniwiz/nativescript-socketio/issues) in the plugin's repository. Meanwhile, I would recommend to check out the [plugin's demo here ](https://github.com/triniwiz/nativescript-socketio) and check if you will be able to recreate the issue with it.

Keep in mind that the NativeScript team does not support the plugin.
