### ISSUE TITLE
html-view doesn't open urls

### ISSUE THREAD

**Issue by sitefinitysteve** [NativeScript/NativeScript#672]
Urls seem to be formatted as links, but are not clickable?

Is this just me?

**Comment by enchev** [comment]
Hey @sitefinitysteve!

I believe that this is expected behavior since this component is only for displaying HTML. If you want interaction you can use WebView.

**Comment by sitefinitysteve** [comment]
Any chance of reconsidering or opening to public discussion?  This basically kills my app as I can't have like 5 webviews hanging out in the same page with no perfect hit... Not even like a tap event on the link that we could handle?

**Comment by TheBrousse** [comment]
What about if the html-view could do a `openUrl` when a `<a href...>` is clicked and let the browser tae over?

Although I may be a bigger fan of some sort of `link` event where the parameter would have a `url` property that you can use.

Here is a sample of what I have in mind. (I am coding this from memory, so please forgive any wrong syntax)
```javascript
hmtlView = require('html-view');

htmlView.html = 'Here is a link <a href="http://google.com">';

htmlView.on('link', function(e) {
    // do something with e.url
});
```

**Comment by enchev** [comment]
Hey folks,

The HtmlView component will just read the HTML as formatted text:
https://github.com/NativeScript/NativeScript/blob/master/ui/html-view/html-view.ios.ts#L18
https://github.com/NativeScript/NativeScript/blob/master/ui/html-view/html-view.android.ts#L13

In both iOS and Android this component is simple Label/TextView

**Comment by valentinstoychev** [comment]
@sitefinitysteve Can you please elaborate more on why you need to use HTML string in a NativeScript app, so that we can better understand your scenario?

**Comment by TheBrousse** [comment]
Well, so much for my idea then @enchev ;)

**Comment by hshristov** [comment]
@sitefinitysteve  I think you could use some 3rd party control for this purpose:
https://github.com/honcheng/RTLabel
or
https://github.com/Cocoanetics/DTCoreText

**Comment by sitefinitysteve** [comment]
The content is being pulled from the platform baas and Sitefinity directly exposed through ServiceStack. RadEditor and KendoUI editors allow the content editors to create html content (nothing complex,  basic lists and links).  So the content is created in the cms,  exposed to the app. 

So this all renders great in {N} except the links are not clickable... They render as blue links,  you just can't DO anything with them which is super confusing. 

So one of our Content Types had 5 of these html fields...

**Comment by sitefinitysteve** [comment]
What about the autolink Web option?http://stackoverflow.com/questions/18222433/how-to-make-normal-links-in-textview-clickable

**Comment by NathanaelA** [comment]
Great find!   I would agree this should be set by default.     I pushed #690 which adds this ability (and fixes <a href...> on both iOS and Android...

**Comment by sitefinitysteve** [comment]
Dude, you are awesome! :)

**Comment by enchev** [comment]
Hey @NathanaelA,

Great! Do you think that we can make this optional using [isUserInteractionEnabled property](https://github.com/NativeScript/NativeScript/blob/master/ui/core/view.d.ts#L263)?

**Comment by NathanaelA** [comment]
Yep, I could update the patch to take in account that variable; I would tend to think this variable should default to true and out of the box that is what I would expect; and then you would disable the functionality.    Let me know if you want me to patch the code to take in account that variable.

**Comment by sitefinitysteve** [comment]
+1 as default to true ...if the UI styles links to look like links, it'll just cause confusion for it to be manually enabled.

**Comment by NathanaelA** [comment]
@enchev I know how to check that property and I can easily disable it while setting the text.  But how can I override(?) & or capture the property change on the htmlview component so that I can trap it being changed and then enable/disable the clickability.   And also make sure to forward the change back up to the _super version of this variable.   The View has this as a defineProperty, not a function...   So I'm not sure what TypeScript I need to use to extend a defineProperty property...

**Comment by NathanaelA** [comment]
Maybe I should rewrite this a little cleared..   I can easily check the isUserInteractionEnabled when the text is being set and disable the interaction if isUserInteractionEnabled=false.   However, what I need to know is how can I trap isUserInteractionEnabled so that when it is changed to true again (or switched to false from true); I can run my code on the HtmlView to enable/disable the interaction on the HthmView..    the isUserInteractionEnabled  is a defineProperty all the way up on the base View object.  And I'm not sure how to override it on the HtmlView in TS code so that it still can call the _super method.   Any pointers where I can see a defineproperty being overridden on a descendant property in the code base.

**Comment by enchev** [comment]
@NathanaelA After internal discussion we've decided that it will be ok to be on by default! If you do not have any other changes I'll merge your pull request?
