### ISSUE TITLE
Android signed release apk still able to debug

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/NativeScript#6741]
**Environment**
nativescript 4.0.1
tns-core-modules 3.3.0
tns-android 4.0.1

**Describe the bug**
I have generated release signed apk using following command. 
`tns build android --release --key-store-path /Users/me/Desktop/my.keystore --key-store-password android --key-store-alias mykey --key-store-alias-password android`

Release signed apk suppose NOT debuggable. That means should not able to access data/data folder even on a rooted device.
When do the penetrate testing I found that the apk is still debuggable. What that means is I can access data/data folder. This leads to security threats. Please advice how to make NON debuggable release apk.
<img width="363" alt="screen shot 2018-12-30 at 11 16 07 am" src="https://user-images.githubusercontent.com/12458727/50544116-4f493880-0c26-11e9-820e-56cc8738415f.png">

Fyi: I tried to manually set `android:debuggable="false"` in Androidmanifest.xml which seems not allowed though.

**Expected behavior**
Release apk should not able to access data/data folder

**Comment by NathanaelA** [comment]
Just to correct one error you made; on a rooted device you can access everything!     

It doesn't matter what it is built with;  NativeScript, Java, Kotlin, Flutter, RN, Swift, ObjC, etc.    A Rooted device means you have full access to everything on the device.   Btw, this applies to iOS as much as it does Android.   

So unless you are able to access a Nativescript app's data folder from another app on a non-rooted phone, I don't believe this is a valid issue...   (And since the OS controls who has access during installation, I'm not sure how this can happen on a non-rooted device).

**Comment by smartsanja2013** [comment]
@NathanaelA thanks for the explanation. The real issue occurs due to [nativescript-securestorage](https://github.com/EddyVerbruggen/nativescript-secure-storage) plugin. I am using the plugin to store user name and password for offline login. During the penetrate testing we found that on a rooted android device we can access data/data/shared_prefs. Inside the shared_prefs we can see the crypto key which is being use for encryption. So, anyone can decrypt the username and password. Highly appreciate the suggestions if anyone faced this issue and found any solution.

**Comment by tsonevn** [comment]
Hi all,
Following the conversation, I assume that the problem is caused by [nativescript-securestorage](https://github.com/EddyVerbruggen/nativescript-secure-storage) plugin. Because of that, I will move the issue in the plugins repository and would suggest keeping the conversation in the other repository.

**Comment by tsonevn** [comment]
This issue was moved to EddyVerbruggen/nativescript-secure-storage#22

**Comment by NathanaelA** [comment]
@smartsanja2013 - Yeah, this is a known issue on all rooted devices (iOS & Android).   I commend you for starting the due diligence; most people are totally unaware of how insecure the app really is on a rooted device and what damage someone could do if they wanted to.    (Literally no security: Because root has access to everything).  

I actually have my own secure storage plugin, one of the notes I put in my code and docs; was that root = reduced security and mitigation's need to be used if you are concerned with root. :grinning:  

I only know of a couple possible mitigation's to this (however it really depends on the what & why as to which are best used for what):
- Using JSScrambler to obfuscate the JS code
- My own JS encryption solution (AppProtection.net)
- Adding a compiled module.
- public key security.

Please note there are ups and downs to each of these solutions (including mine); they all have strengths and weaknesses -- all depending on the why/what; and would require a bit longer of a conversation than github...

---

One final note; 
If all you are worried about is locking down the encryption key on a rooted device; you are missing the trees for the forest. :grinning:    You need to think a lot more devious about what you now have access to as root, when dealing with your app's security.      

So you might want to talk to someone that deal in security to get a better idea of your threat model with your app.  I know we (http://nstudio.io) can do this.    But, really just get anyone who deals with app security on Android and/or iOS should be able to help you get a better picture of the actual threat model you have.   As based on your questions it appears you only see a small part of your actual exposure when dealing with a rooted device.

**Comment by NathanaelA** [comment]
@tsonevn this really isn't about a specific plugin.  So I'm not sure it should be moved.   However, the issue can be closed; as their really is no "actionable" thing that NativeScript or Eddy can do about this.  This really is a "teaching" moment, for people who don't know this.  

The main issue that most people aren't aware of (and it obviously caught him by surprise too) is that if I have a rooted phone (which I have a couple of :grinning: ) and I have some way to install your app; I probably have everything I need to get the entire keys to your kingdom; if your app isn't written correctly. 
 
Anything you drop on google play (or apple app store); you really have to consider; the hacker now has full access to your entire source code.  (And again this isn't a NativeScript only issue -- I've personally decompiled ObjC, Java, RN, Cordova, and many others while doing security reviews and shocked people when I gave them their keys to the kingdom...  :grinning:)

**Comment by EddyVerbruggen** [comment]
Entirely agree with @NathanaelA. I've been involved with securing apps in several other stacks as well (native iOS and Android, and Cordova) and there's never a silver bullet. Usually, it involves adding several layers of security, like scrambling JS code, doing SSL pinning for exchanging (sensitive) data, not storing passwords, (and if you do) making sure they are encrypted and the key for one device can't be used to decrypt passwords on another device, and use public key encryption.

There was also a (high profile) client that needed the (Cordova web) assets signed and checked upon app launch every time in order to mitigate the risk of someone with a rooted device having injected code being run (which is _theoretically_ possible when connecting to an insecure WiFi network where a hacker scans for rooted devices that have your app installed, and add a bit of code to alter its behavior). Note that iOS does this for native code, but not for those assets (that's only done during installation from the App Store, not on every launch).

I've also encountered a client that wanted the app to detect rooted devices and don't allow installation in that case 🙃
