### ISSUE TITLE
Image asset options requested size does not act as either max or min.

### ISSUE THREAD

**Issue by lucboutier** [NativeScript/NativeScript#6752]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.0.3
 - Cross-platform modules: 5.0.5
 - Android Runtime: 5.0.0
 - iOS Runtime: 5.0.0

**Describe the bug**
I am not sure if that is a bug but when asking for specific width and height I am assuming that this should be max width or height.
This is confirmed by some elements of the implementation in `image-asset-common.ts` as the following (lines 52 and 53) get the min value from the image actual width and height and the requested ones.

```JS
var reqWidth = options.width || Math.min(src.width, screen.widthPixels);
var reqHeight = options.height || Math.min(src.height, screen.heightPixels);
```

However when computing the size reduction ratio line 41 we take the minimum ratio:
```JS
let aspectCoef = Math.min(widthCoef, heightCoef);
```

This means that when the image is bigger than the requested size one we will end-up with an image that has one of its dimension equal to the requested one and the other bigger than the requested one.

In my opinion we may expect to have the opposite behavior meaning that we should have one dimension equal to the requested one and the other smaller than the requested one.

What do you think ? Does that make sense ? Or should we add another parameter to the options to actually let the user choose ? If so what should the default behavior be ?

Thanks,

Luc

**Comment by NickIliev** [comment]
@lucboutier the logic in `getRequestedImageSize` (and in the used `getAspectSafeDimensions`) assumes that the default behavior will **always** respect the aspect ratio. That said the behavior is expected. 

Take a look at the following example (**_pseudo code_**)
```JS
original width = 800
original height = 600

requested width = 600
requested height = 400

widthCoef = 800/600 = 1.33
widthCoef = 600/400 = 1.5

aspectCoef = min 1.33 

final width = 600 (800/1.33)
final height = 450 (600/1.33) // the ratio is preserved
```

If you have a case where you want the final height to differ (e.g. in the case above to be different from 450) you can change the `keepAspectRatio` to `false` (which would distort the original width/height ratio).

You can also set  and explcit `height` (instead of setting requested `width`) if you want to be sure that the requested height is smaller or equal to the final one while keeping the ratio.
