### ISSUE TITLE
Make the modal Popover integration follow the same pattern as the fullscreen option so Angular and Vue can be integrated

### ISSUE THREAD

**Issue by dottodot** [NativeScript/NativeScript#6850]
**Is your feature request related to a problem? Please describe.**
 
The current implementation of popovers requires passing `UIModalPresentationStyle.Popover` in as an option however this is native code which isn't an option in Angular making it unusable.

If it was to follow the same pattern / or similar that's used for fullscreen it would allow for much easier integration.

**Describe the solution you'd like**

The current code is 
```
        if (options.fullscreen) {
            controller.modalPresentationStyle = UIModalPresentationStyle.FullScreen;
        } else {
            controller.modalPresentationStyle = UIModalPresentationStyle.FormSheet;
        }

        if (options.ios && options.ios.presentationStyle) {
            const presentationStyle = options.ios.presentationStyle;
            controller.modalPresentationStyle = presentationStyle;

            if (presentationStyle === UIModalPresentationStyle.Popover) {
                const popoverPresentationController = controller.popoverPresentationController;
                const view = parent.nativeViewProtected;
                // Note: sourceView and sourceRect are needed to specify the anchor location for the popover.
                // Note: sourceView should be the button triggering the modal. If it the Page the popover might appear "behind" the page content
                popoverPresentationController.sourceView = view;
                popoverPresentationController.sourceRect = CGRectMake(0, 0, view.frame.size.width, view.frame.size.height);
            }
        }
```
but if this was changed to the following the problem would be resolved.
```
        if (options.fullscreen) {
            controller.modalPresentationStyle = UIModalPresentationStyle.FullScreen;
        } else if (options.ios && options.ios.popover) {
            controller.modalPresentationStyle = UIModalPresentationStyle.Popover;
            const popoverPresentationController = controller.popoverPresentationController;
            const view = parent.nativeViewProtected;
            // Note: sourceView and sourceRect are needed to specify the anchor location for the popover.
            // Note: sourceView should be the button triggering the modal. If it the Page the popover might appear "behind" the page content
            popoverPresentationController.sourceView = view;
            popoverPresentationController.sourceRect = CGRectMake(0, 0, view.frame.size.width, view.frame.size.height);
        } else {
            controller.modalPresentationStyle = UIModalPresentationStyle.FormSheet;
        }
```
The existing code could also remain in place for backwards compatibility.

I'm happy to do a PR unless there some reason why this isn't a good idea.

**Comment by tsonevn** [comment]
Hi @dottodot,
Thank you for your research and the suggestion.
About the current implementation, some platform-specific options can be set up to the modal view(in this particular case UIModalPresentationStyle for iOS), which does not have their equivalents in the other one. Because of that, we introduced this functionality that allows setting collection of options to the modal. This helps the developer also specify only those of them, which are needed for the app. For more info, you can check the comments in the PR [here](https://github.com/NativeScript/NativeScript/pull/6409#issuecomment-439314127), where it is described, why this solution is taken. 

Regarding that, let us keep the conversation for Angular in the issue [here](https://github.com/NativeScript/nativescript-angular/issues/1709) because this feature requires some changes in nativescript-angular. Perhaps, a similar feature request can be opened in the https://github.com/nativescript-vue/nativescript-vue repository as well.
