### ISSUE TITLE
Icons in IOS ActionBar always appears in white color

### ISSUE THREAD

**Issue by ShaimaaKhamees** [NativeScript/NativeScript#6867]
i recently test my app in Ios and the icon in action bar appears in white color only
and it works fine in android
in android (icon in the left in white and red colors as expected)
![51622313_396926941097677_6929719957303328768_n](https://user-images.githubusercontent.com/26388652/52359142-f8632a00-2a41-11e9-8dfe-bfb328017f0f.png)

in IOS(icon in the left in white only  )
![51474368_302909990367879_6650514643175342080_n](https://user-images.githubusercontent.com/26388652/52359120-ef725880-2a41-11e9-9b5a-2e1849335354.jpg)

as shown the icon appear correctly in android but in ios appears in white color only
and i test in another emoji yellow icon and it appears in ios as white circle icon

![untitled](https://user-images.githubusercontent.com/26388652/52359011-b33ef800-2a41-11e9-9262-c37069260d59.jpg)

//-----------------------

√ Getting NativeScript components versions information...
‼ Update available for component nativescript. Your current version is 5.0.3 and
 the latest available version is 5.1.1.
‼ Update available for component tns-core-modules. Your current version is 5.0.5
 and the latest available version is 5.1.2.
‼ Update available for component tns-android. Your current version is 5.0.0 and
the latest available version is 5.1.0.
√ Component tns-ios has 5.1.1 version and is up to date.

**Comment by NickIliev** [comment]
@ShaimaaKhamees can you please provide [a sample Playground ](https://play.nativescript.org/)that illustrates the issue?

**Comment by ShaimaaKhamees** [comment]
https://play.nativescript.org/?template=play-tsc&id=RsC1fS&v=6&fbclid=IwAR32xa43EXcfMi-2Eef9-wN9ZK0BfymKJMn2pBFW0bUVCrD2mAZTBWBaZcg

**Comment by NickIliev** [comment]
@ShaimaaKhamees the thing is that in NativeScript the action items are created with [UIBarButtonItem](https://developer.apple.com/documentation/uikit/uibarbuttonitem?language=objc) in [this file](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/action-bar/action-bar.ios.ts#L242-L247). The UIBarButtonItem has different rendering modes which can be accessed via the native API (native solutions [here](https://stackoverflow.com/questions/1835260/can-i-have-a-uibarbuttonitem-with-a-colored-image) and [here](https://stackoverflow.com/questions/26854667/uibarbuttonitem-image-stays-blue-and-not-the-original-color-of-the-image)). 

Apart form the native solution to create an icon with different rendering mode, NativeScript provides a way to create a custom ActionBar by using layouts instead of `ActionItem` - just as you have done with the title Label nested within a StackLayout.

So that said you could introduce your icon like this:
```XML
<ActionBar title="Home" class="action-bar">
	<StackLayout orientation="horizontal">
		<Image src="~/images/reduser.png" height="40" width="40" />
		<Label text="WHAM Clinics" horizontalAlignment="center" class="headerTitle"></Label>
	</StackLayout>
</ActionBar>
```

**Comment by ShaimaaKhamees** [comment]
@NickIliev  thank you soooo much  :+1:  ...you save me

**Comment by ShaimaaKhamees** [comment]
@NickIliev  thank you sooooo much that solve my issue
