### ISSUE TITLE
How to get Emberjs + NativeScript support?

### ISSUE THREAD

**Issue by zinyando** [NativeScript/NativeScript#6956]
I see that NativeScript has support for building applications using both Angular and Vuejs and I'm interested in trying to get it to work with Emberjs. I see there is a related issue here #122 which didn't receive a proper answer so I'll try to ask a more specific and direct question here.

What is required on a high level to make a framework work with NativeScript? A non-framework specific overview of what needs to be done would be helpful in getting the work started. Feel free to add more information and links that might be relevant :)

**Comment by edusperoni** [comment]
I recommend checking the first commit of nativescript-vue that managed to get something working: https://github.com/nativescript-vue/nativescript-vue/commit/e8a4e395ea51ba81bed146ada96aa3a4866dee66

From my understanding, the main thing to implement is the renderer. Since we don't have a DOM, we have to change the framework's way of creating elements so it can create native elements. If you check that commit you'll see it was exactly that: a basic renderer that allows the framework to run.

You then have things like implementing your own `registerElement` to allow plugins and core elements to work with the framework.

From there on there are a few things that have to be reimplemented. For example, angular's httpclient has to use the native http module, so there are a few changes required, which is why we have NativeScriptModule, NativeScriptFormsModule, NativeScriptHttpClientModule.

Starting from the renderer, it's a matter of becoming feature complete by iteration.

I'm by no means expert in the subject, but I did my share of digging through code to see how things were dong. I'm sure the people who actively worked in nativescript-vue and nativescript-angular have better insight to give.

**Comment by NickIliev** [comment]
@zinyando @edusperoni  let's continue the discussion [in the original issue logged for Emberjs support ](https://github.com/NativeScript/NativeScript/issues/122)so this way all the information can be available in one single point.
