### ISSUE TITLE
TabViewItem icon is not shown correctly (iOS)

### ISSUE THREAD

**Issue by danicomas** [NativeScript/NativeScript#697]
The Small-Icon is the default icon of the app_resources @vakrilov

![captura de pantalla 2015-09-08 a las 18 14 25](https://cloud.githubusercontent.com/assets/4038192/9740551/a705a5a2-5655-11e5-9ee3-e4d1e8f5a936.png)

**Comment by manijak** [comment]
This is they way it works. You cannot use (colored) app-icons as tab-, navigation- or toolbar-buttons. Apple has specific guidelines when it comes to these icons and brand-icons. 

*A custom icon that you create for a toolbar, navigation bar, or tab bar is also known as a template image, because iOS uses it as a mask to produce the icon you see when your app runs. If you create a full-color template image, iOS ignores the color.*

*To design a custom bar icon, follow these guidelines:*

* Use pure white with appropriate alpha transparency.
* Don’t include a drop shadow.
* Use antialiasing.

More info here:
https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/BarIcons.html#//apple_ref/doc/uid/TP40006556-CH21-SW1

**Comment by danicomas** [comment]
Thanks @manijak
