### ISSUE TITLE
tns-platform-declarations - In objc!SafariServices.d.ts is declared the deprecated class SFAuthenticationSession instead of ASWebAuthenticationSession

### ISSUE THREAD

**Issue by alexmeia** [NativeScript/NativeScript#6992]
**Describe the bug**
Version 5.2.0 of _tns-platform-declarations_ still references to the deprecated class
[SFAuthenticationSession](https://developer.apple.com/documentation/safariservices/sfauthenticationsession) instead of the analogous, but not deprecated, [ASWebAuthenticationSession](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession).
SFAuthenticationSession will not be usable starting from iOS 13, so an update to the iOS platform declarations id needed.

**Comment by NickIliev** [comment]
This issue was moved to NativeScript/ios-runtime#1090

**Comment by mbektchiev** [comment]
Hi @alexmeia, the platform declarations include declarations for both classes. See [here](https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios/objc-x86_64/objc!AuthenticationServices.d.ts#L174) and [here](https://github.com/NativeScript/NativeScript/blob/master/tns-platform-declarations/ios/objc-x86_64/objc!SafariServices.d.ts#L9)

`SFAuthenticationSession` is indeed deprecated but still available in iOS 12.0. That's why we are exposing it. 

When we regenerate the declarations against iOS 13, it should automatically be removed.

**Comment by alexmeia** [comment]
Thank you @mbektchiev, I was looking in the wrong place.
