### ISSUE TITLE
Change Scrollview Scrollbar color ?

### ISSUE THREAD

**Issue by MopheusDG** [NativeScript/NativeScript#7034]
I tried a bunch of ways to change the scrollbar in the scrollview to change the color and I couldn't make it work. So I'm starting to think it's not possible ? Maybe someone can help...

I was able to:

    var scroll = args.object.getViewById("ourScroll");
    scroll.android.setScrollbarFadingEnabled(false);
    scroll.android.setVerticalScrollBarEnabled(true);
    scroll.android.setVerticalFadingEdgeEnabled(false);
    scroll.android.setScrollBarDefaultDelayBeforeFade(5000);
    scroll.android.setScrollBarFadeDuration(10);

And I tried creating a style, an XML shape, etc.... and couldn't get the scrollbar to change color.

It's possible or not ? If not, would love to see this new feature added (My app is dark background so the bar is almost invisible).

Thanks.

**Comment by tsonevn** [comment]
Hi @MopheusDG,
Currently changing the color of scroll indicator is not supported and I will mark the issue as a feature request.
For now, I would suggest keeping track on the issue for further info.

**Comment by KhalifaGad** [comment]
+1

**Comment by MopheusDG** [comment]
Thanks.

**Comment by wuilmerj24** [comment]
+1

**Comment by jeanpaulattard** [comment]
On android, you can change the scroll bar color as follows

In your `App_Resources/Android/src/main/res/values/colors.xml`

Add the following

`<color name="scrollbar">#454545</color>`

In your styles, under the `AppThemeBase` section add the following

```
 <style name="AppThemeBase" parent="Theme.AppCompat.Light.NoActionBar">
       ...
       <item name="android:scrollbarThumbVertical">@color/scrollbar</item>
 </style>
```

On iOS, unfortunately you need to make do with system default. You might want to disable dark mode in case your app does not support it, since in dark mode it uses opaque white scroll bars which might end up not visible on a white background.
