### ISSUE TITLE
Project trying to include a removed dependancy when compiling

### ISSUE THREAD

**Issue by tonyhogben** [NativeScript/NativeScript#7037]
### Which platform(s) does your issue occur on?

iOS 12.1 and Android 4.4.4

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.1.1
- Cross-platform modules: 5.2.2
- Runtime(s): 5.1.1 and 5.1.0 (ios/android)
- Plugin(s):
"dependencies": {
"email-validator": "^1.0.7",
"moment": "^2.18.1",
"nativescript-couchbase-plugin": "^0.9.0",
"nativescript-image-cache": "^1.0.6",
"nativescript-iqkeyboardmanager": "^1.1.0",
"nativescript-plugin-firebase": "^4.0.5",
"nativescript-telerik-ui": "^3.0.0-2017.6.22.5",
"nativescript-theme-core": "~1.0.2",
"nativescript-timedatepicker": "^1.2.0",
"tns-core-modules": "^5.2.2",
"tns-core-modules-snapshot": "3.0.1-5.5.372.32"
},
"devDependencies": {
"nativescript-dev-typescript": "^0.8.0",
"tns-platform-declarations": "^3.1.0",
"typescript": "~2.2.1"
}

### Please, tell us how to recreate the issue in as much detail as possible.

I have updated my project and upon discovering one of the plugins (nativescript-couchbase) has been abandoned, I removed it and replaced with the nativescript-couchbase-plugin.

The app will build and install on the device but then crashes with the message:

`java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.wholeschoolmeals.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Failed to find module: "nativescript-couchbase", relative to: app/tns_modules/`

I have attempted to reset the app by removing the node_modules, hooks and platform folders and running 'npm i', but it is still trying to include the removed plugin!?

[Here is a zip of the project](https://mtstudios.digitalpigeon.com/msg/GrVr4EDgEemx8gYtQsGbAw/CLWo8uaZoCWCeo7JBz-bDA/file/2942dad0-40e0-11e9-85e8-06e26140e7ff/download#)

Thanks in advance,

Tony.

**Comment by NickIliev** [comment]
@tonyhogben the link above (to the app) is not working. Apart from making a clean rebuild also try to explicitly delete any previous version of the app from the testing devices.

**Comment by tonyhogben** [comment]
@NickIliev, apologies, try this link instead... https://mtstudios.digitalpigeon.com/msg/Qgff4EcyEemBewbtG5M1VQ/HO8_Bapyhe_ZGasiCfY00Q/file/422c57d0-4732-11e9-817b-06ed1b933555/download# - Whole-School-Meals-v2.zip - Whole-School-Meals-v2.zip

I have tried deleting the app from the device to no avail.

**Comment by tonyhogben** [comment]
@NickIliev, sorry I missed your edit. I had already ran the upgrades, but just did it again to be sure. No dice I'm afraid, I still get the same error - it won't shake this couchbase plugin!

**Comment by NickIliev** [comment]
@tonyhogben the link contains an archive that is too big. Remove `node_modules`, `platforms` and `hooks` folders (all three) and rebuild the project and the old plugin should not be installed.  If you still experience the issue create a source control repo or an archive without the three folders.

**Comment by tonyhogben** [comment]
@NickIliev sorry about the large archive. [Here's another as requested](https://mtstudios.digitalpigeon.com/msg/YzxH8EpDEemTrwbtG5M1VQ/xPvSfOpPWQ3uzdIgx1xVWw/file/63618330-4a43-11e9-93af-06ed1b933555/download#).

Rebuilding from this generates the same error - hence my confusion!

**Comment by NickIliev** [comment]
@tonyhogben the transpiled JavaScript files are still containing the old source code with the old nativescript-couchbase plugin. Remove **all** JS files from the project and update your `typescript` to 3.1.1 and also `nativescript-dev-typescript` to latest. Them remove platforms and node_modules and update tns-android and tns-ios to latest (`tns platform add android`). After all of the above, the TypeScript code should be successfully transpiled to JS and you could build our project.

**Comment by tonyhogben** [comment]
Thank you @NickIliev. I followed the above, however, my project is not transpiling the ts files - I get no js files back?

**Comment by tonyhogben** [comment]
Any ideas @NickIliev

**Comment by NickIliev** [comment]
[Whole-School-Meals-v2.zip](https://github.com/NativeScript/NativeScript/files/3007503/Whole-School-Meals-v2.zip)

The project was using an old version of TypeScript and the transpilation was not passing. This means that when you try to build the project the `tsc` command was not producing new JavaScript files and you were left with the old ones (where the old code was present including the old plugin).

Overall there are many things that, you might need to update as the project seems to use versions of plugins that are no longer existing and also the porject uses a structure and methods that were deprecated (e.g. `app.start` is now replaced with `app.run` and using a `Frame`).

Here is a short list of changes that you need to consider.

- upgrade all depedencies to latest supprted versions
- [migrate from the deprecated `nativescript-ui-telerik` to the split libraries](https://docs.nativescript.org/ui/professional-ui-components/migration)
- migrate all[ short imports to full imports ](https://www.nativescript.org/blog/say-goodbye-to-short-imports-in-nativescript)
- update the logic in app.ts to use **run** instead of **start** ([here](https://docs.nativescript.org/core-concepts/application-lifecycle#application-run))
- remove the obsolete `bundle.ts` files

Attraching a sample project with some of the changes applied.

**Comment by tonyhogben** [comment]
Okay, clearly I left it far too long to come back to this project!

@NickIliev, I most certainly owe you a drink or 3!
