### ISSUE TITLE
span not working in ios (previously reported)

### ISSUE THREAD

**Issue by erjdriver** [NativeScript/NativeScript#7081]
Span feature is not working under ios - previously reported in #4992.

I'm still waiting for a fix for this..it's been over a year.

5.3 was released today - still not fixed...I just want to be sure that it's not lost and there's some hope of getting it fixed.

If someone can point me in the right direction maybe I can fix it.

**Comment by tsonevn** [comment]
Hi @erjdriver,
The issue is not lost, however, I can not commit to the exact time when it will be fixed. Also, I would suggest keeping the conversation in the [old issue](https://github.com/NativeScript/NativeScript/issues/4992).
Regarding the case, I found that you can set the span color with some delay, which seems to apply the property correctly. For example:
```
var span :Span = new Span();
    span.text ="test";
    setTimeout(() => {
        span.color = new Color("red");
    }, 100);
    // span.color = new Color("red");
    formattedString.spans.push(span);
    var newlabel  = new Label()
    newlabel.formattedText = formattedString;
```
It is not the best solution, but, it can help you to work around the issue.

**Comment by erjdriver** [comment]
Thanks - that's good enough for me.

It's amazing how many NS issues can be solved with this timing workaround.
