### ISSUE TITLE
Ability to apply background color for UI Switch in "off" state in IOS

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/NativeScript#7095]
@M-kothakapu commented on [Sat Mar 30 2019](https://github.com/NativeScript/nativescript-angular/issues/1773)

**Environment**
 - NativeScript-Angular
 
**Describe the bug**
I'm working on Nativescript Switch component. I found an issue while applying background colors when the switch state is ON/OFF (i.e, checked or unchecked).
Based on checked property, The background color of Switch should change. 
 
**Expected behavior**

      Background Color should change when checked property is false (off state).

**Current behavior**

     Background color is not applied to OFF state (unchecked) behavior of Switch.  

**Sample project**
https://play.nativescript.org/?template=play-ng&id=8DLLBY&v=14

**Comment by NickIliev** [comment]
@M-kothakapu 
In your code you trying to access the `checked` property via 
```HTML
(checkedChange)="switchChanged(sw.checked)"
```

However, you are not declaring the `sw` anywhere. To resolve simply add the id to the switch element
```HTML
<Switch #sw checked="false" (checkedChange)="switchChanged(sw.checked)"></Switch>
```

Here is a [Playground demo](https://play.nativescript.org/?template=play-ng&id=8DLLBY&v=15) showing the above.

**Comment by M-kothakapu** [comment]
@Nicklliev thank you for updating the id to the switch element. However, I verified this output. I’m posting a .gif file please verify. Somehow the issue is not resolved. Please observe the following steps: 
1. When the switch is turned on it changes to yellow color. Works fine. 
2. When the switch is turned off it changes to white background color as set by the IOS. But this should change to gray color instead which I’m exactly looking for.
3. When you try to slowly hard press the thumb/knob of the switch you will observe the background changes to gray color and disappears. This is the issue I wanted to mention.

**Comment by M-kothakapu** [comment]
![Switch](https://user-images.githubusercontent.com/17285726/55315942-05ddd480-5433-11e9-8694-2e8773887fa2.gif)

**Comment by NickIliev** [comment]
@M-kothakapu I see what you mean - indeed this looks like a bug in applying the `background-color` (different `color` work as expected). Reopening the issue and marking this one as a bug.

**Comment by NickIliev** [comment]
Reproducible in NativeScript Core as well - using [this playground app for testing the issue](https://play.nativescript.org/?template=play-tsc&id=x23Qmi)

**Comment by MartoYankov** [comment]
@M-kothakapu I've investigated the issue and it seems that this is the expected behavior of the iOS UISwitch widget. By default, the background color of the UISwitch sets the background in ON state and creates an animation for the OFF state. We can add a new property that will be iOS only that controls the background color in the OFF state. It will be called `iosOffBackgroundColor` and you will be able to access it in CSS via the `ios-off-background-color` rule. Will this work for you?

**Comment by MartoYankov** [comment]
Okay, it turns out that on iOS changing any of the background properties results in an animation that looks like a glitch. The only viable option for cross platform API that respects the native behavior on both platforms is to add `off-background-color` for Android too. This would mean that you won't have to do the `[checked]` selector.
