### ISSUE TITLE
Ability to set animation on TabView transitions

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#7096]
Since the addition of the ability to use TabView as a root level component, it became a much more often used building block. And while it relies on Frame component internally, it completely ignores Frame's animated transitions. We need to have this sort of eye candy to build consumer facing apps!

**Comment by NickIliev** [comment]
@sserdyuk what do you mean by "it completely ignores Frame's animated transitions... "? 
With the current Frame and TabView implementation, I am able to fully implement different navigation transitions when using TabView. Here is a Playground app demonstrating the above.

Notice, that the above example will have the frame navigaiton transitions. But there are some limitations related to the TabView itself as noted [here](The iOS and Android UX guidelines regarding the Tab controls differ greatly. The difference is described in the below points:

The iOS tabs have their tab bar, which will be displayed always on the bottom and does not allow swipe gesture for changing tabs.
The Android tabs are on top and will enable the swipe navigation between the tabs.
For Android, we have androidTabsPosition property which has two options top(default value) and bottom. Setting up this property to bottom allows mimicking Bottom Tab Navigation control(provided by android support library v25 release). Setting the Tabs at the bottom will disable the swipe navigation and the items preloading functionality) - meaning that changing the tabs via tab selected index or by tapping the new tab item will not apply the animation but the native behavior for the control.

**Comment by sserdyuk** [comment]
@NickIliev First of all, thank you for getting on the ticket so fast. Second, the animation you are referring is transition on navigation within the tab, where it works fine. The one I am referring to is the animation on transition between tabs. I am attaching a GIF below to show the effect I am looking for.

![ezgif-2-3779761a9009](https://user-images.githubusercontent.com/395998/55478733-63685180-55ea-11e9-89a5-9a41ad6e9644.gif)

**Comment by NickIliev** [comment]
@sserdyuk the feature in the screenshot is not supported in the current TabView implementation (as there is no iOS alternative to these transitions which are common for the native Android control). We are currently working on an entirely [new TabBar control](https://github.com/NativeScript/NativeScript/issues/6967) however so far the feature won't be included in the first implementations, however, keep an eye on the tracking issue for more details of the implementation.

**Comment by MrToxy** [comment]
I thought I'd just add something that's a quite simple workaround for this atm (easily done with Vue and angular, vanilla shouldn't be too hard as well), basically, If I want to transition between tabs, I simply bind a variable to the child element of the tabView appending a dynamic class based on the that variable, so that the active tab gets a class with an animation:

` <TabView
          :selectedIndex="activeTab"
          @selectedIndexChange="tabIndexChange"
        >
          <TabViewItem title="Information">
            <StackLayout class="project__container" :class="{'activeTab': activeTab === 0}">
            </StackLayout>
          </TabViewItem>
        <TabViewItem title="Options">
            <StackLayout class="project__container" :class="{'activeTab': activeTab === 1}">
            </StackLayout>
        </TabViewItem>
</TabView>
`
This is the `activeTab`  class:

`
.activeTab {
  animation-name: animateTabViewItem;
  animation-duration: 3s;
  animation-fill-mode: forwards;
  animation-timing-function: ease-in-out;
}
`
and the method that catches the tab index change:

`
tabIndexChange(e) {
      this.activeTab = e.value;
      console.log("active tab: ", this.activeTab);
    }
`
With a few more lines you can add a forward and backward transition by testing if the current tab index is < or > than the one coming from the callback.

here's a video (gif was too large ) of how the transition looks in ios:
https://drive.google.com/file/d/1M2yjV_VFC0-kOsu4lHjOA7lf7TGWMbTg/view?usp=sharing
