### ISSUE TITLE
Push Notifications Support

### ISSUE THREAD

**Issue by enchev** [NativeScript/NativeScript#71]
Hi

I am wondering how push notification are handled. and is there any documentation for this cross platform modules

_Copied from original issue: NativeScript/cross-platform-modules#153_

Please [vote for this feature](https://nativescript.ideas.aha.io/ideas/NS-I-36) in our ideas portal.

**Comment by enchev** [comment]
_From @MathieuDoyon on March 11, 2015 14:9_

+1

**Comment by enchev** [comment]
_From @roja on April 13, 2015 22:56_

+1 this goes for all events which traditionally perform a callback within a native app. I.e. Geo fencing etc...

**Comment by enchev** [comment]
_From @tiagordc on April 16, 2015 16:56_

+1

**Comment by enchev** [comment]
_From @Igcorreia on April 17, 2015 10:26_

+1

**Comment by Adiel-Sharabi** [comment]
+1

**Comment by MathieuDoyon** [comment]
+1

**Comment by hristoborisov** [comment]
In order to support push notifications, we need to create an easy to use cross-platform module that abstracts the complexity to deal with the different platform APIs to register and unregister the device for push notifications. We plan to develop a generic cross-platform module that helps developers retrieve device specific information and handle push notifications coming from the server, so that you can integrate NativeScript with any Push Notifications provider out there.

Further, we plan to integrate the cross-platform module directly in our Telerik Backend Services JavaScript SDK in order to make the integration a breeze. We plan to strictly follow the existing support for Push Notifications in Hybrid, and extend the support under the cover for NativeScript as well. It's important to note that our existing JavaScript SDK can be used both for Hybrid and NativeScript apps without any extra configurations.

We plan to support the following operations, and everything else in regards to push available today at http://docs.telerik.com/platform/backend-services/development/javascript-sdk/push-notifications/introduction

* Ability to register a device for Push Notifications:
```javascript
var el = new Everlive('your-api-key-here');
var pushSettings = {
    iOS: {
        badge: true,
        sound: true,
        alert: true,
        clearBadge: true
    },
    android: {
        projectNumber: 'GOOGLE_API_PROJECT_NUMBER'
    },
    wp8: {
        channelName: 'EverlivePushChannel'
    },
    notificationCallbackIOS: function(e) {
        // logic for handling push in iOS
    },
    notificationCallbackAndroid: function(e) {
        // logic for handling push in Android
    },
    notificationCallbackWP8: function(e) {
        // logic for handling push in Windows Phone
    }
};

el.push.register(
    pushSettings, 
    function successCallback(data) {
        // This function will be called once the device is successfully registered
    },
    function errorCallback(error) {
        // This callback will be called any errors occurred during the device
        // registration process
    }
);
```
* Ability to check if push notifications are enabled for this app by the device settings

```javascript
var el = new Everlive('your-api-key-here');
el.push.areNotificationsEnabled(customParameters, successCallback, errorCallback);
```

* Ability to enable badges, sounds, and interactive push notifications
* Ability to send push notifications either from the rich UI of the Backend Services or using the API

```javascript
var el = new Everlive('your-api-key-here');
el.push.send({ Message:'Hello' },
    function(data){
        alert(JSON.stringify(data));
    },
    function(error){
        alert(JSON.stringify(error));
    });
```

In this way, you will simply configure your Push notification certificates in our Backend Services, and start happily sending push notifications either from the server or from the client.

We would love to hear your feedback for our plans,
Hristo Borisov
the Telerik team

**Comment by rborn** [comment]
Please don't forget to make the module in such a way it can be used outside the Telerik platform.
Developers might want yo use their own server implementation :)
Thank you.

**Comment by hristoborisov** [comment]
Thank you for the feedback @rborn, this is exactly what we will try to achieve with our cross-platform module. Create a generic module that help you retrieve information for the device that you can use with your own service, and make sure our JS SDK for the Backend Services is giving you the best possible integration with minimum code involved.

**Comment by rborn** [comment]
Great, thank you :)

**Comment by ligaz** [comment]
@hristoborisov Can you share more details about the cross-platform module API as soon as you have something working? I think we can do some of the things better than the current Cordova Push Plugin.

**Comment by alejonext** [comment]
This is great !, but I think it needs to be native, because if [socket.io](https://socket.io) is used, there would be problems.

**Comment by closdesign** [comment]
+1

**Comment by closdesign** [comment]
What does the "soon" mean?  We are about to embark on a pretty substantial project using NativeScript and push notification are a good portion of this.  Any timeframe or deadline?    Any GIT repo specific to show the progress of the Push Notifications portion?

**Comment by zephraph** [comment]
I'd suggest taking a look at phone-gap's [PushPlugin](https://github.com/phonegap-build/PushPlugin) and checking to see if any of that code is portable. They use each device's respective push service, so there's a wide range of examples.

**Comment by valentinstoychev** [comment]
Hey @closdesign, please contact me at valentin.stoychev@telerik.com to see how we can help you out with your project. cc:/ @hristoborisov

**Comment by bradmartin** [comment]
Will this be possible alongside local notifications (status bar, notification tray)

**Comment by hristoborisov** [comment]
Hey guys, I am glad to inform you that the team just released push notification plug-in for NativeScript. You can find the official npm package here https://www.npmjs.com/package/nativescript-push-notifications and also try our easy to setup sample here https://github.com/NativeScript/sample-push-plugin. We are looking forward to hearing from you!

**Comment by alejonext** [comment]
YEAH!!!!

**Comment by jasononeil** [comment]
Fantastic news! Thank you :D

**Comment by spstratis** [comment]
@hristoborisov Is the nativescript-push-notifications package intended to be generic enough so that it can work with any push backend? For example if I needed to use a service such as Urban Airship or Carnival?

**Comment by bradmartin** [comment]
@spstratis - yes. I have a blog post on how to use GCM for Android using the plugin.http://bradmartin.net/2015/12/28/use-google-cloud-messaging-for-push-notifications-with-nativescript/

**Comment by spstratis** [comment]
@bradmartin Thanks I'll take a look, I actually saw this while doing some googling. Wasnt sure if it would work just the same when using 3rd party services like Urban Airship or Pushwoosh since they call GCM directly.

**Comment by hvadotnarola** [comment]
@hshristov how can i install Everlive sdk through In-Browser ? Can you please suggest some easy method or Reference to doc. ? Does it require account with subscription ?
