### ISSUE TITLE
True tree shaking support

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/NativeScript#7127]
**Environment**
- CLI:  all
 - Cross-platform modules: none
 - Android Runtime: all
 - iOS Runtime: all
 - Plugin(s): none

**Describe the bug**
{N} is not ```tree shaking``` compatible.
Even though it is mentioned on the ```nativescript-dev-webpack``` page that it supports tree-shaking, you wont get any tree shaking in {N} (almost none!)

This is kind of a big issue with a lot of sparated issues:
- {N} js product files for ```tns-core-modules``` or any other plugin are using commonjs ```require``` and not ```es2015``` ```import```. Which makes them incompatible with webpack [concatenation module](https://webpack.js.org/plugins/module-concatenation-plugin/)
- a LOT of ```tns-core-modules``` files have ```export * from '../../core/view``` or something like this. This create redondancy which implies a lot bigger concatenated modules (when module concatenation is possible). 
- [bundle-entry-points](https://github.com/NativeScript/NativeScript/blob/b436ecde3605b695a0ffa1757e38cc094e2fe311/tns-core-modules/bundle-entry-points.ts) requires all tns widgets even if they are not used. Because of that everything is always included, even the app only use half of the widgets

All 3 aspects can be handled /  fixed separately. But all of them are really necessary to get tree shaking to work as it should. Getting this to work would have multiple benefits:
- lower app bundle size
- lower vendor.js size in bundle => smaller snapshot / less memory / faster runtime
- faster start time as it is much faster to require everything. 

I have already started to work on the first 2 points. Two PRs are coming:
- es2015 module is small and without any real consequence
- fixing all {N} imports / exports to not use ```export * from ...``` is a bigger one with consequences for the user

The 3rd point needs to be addressed by the CLI in the sense that it should find out what widgets are used by the app (parsing XML, VUE files) and create a ```bundle-entries.js``` in consequence only importing what's really used

**To Reproduce**
build with webpack using args ```--display-used-exports --display-modules --display-optimization-bailout```

**Comment by vakrilov** [comment]
Hey @farfromrefug, it is awesome that you have opened this issue. This is definitely the direction we want to go with the `tns-core-modules` package (and for all the plugins in the NS eco-system as well). 

Here are my thoughts on the 3 issues that you have listed:

### Shipping `tns-core-modules` as `es2015` modules
Webpack can tree-shake `es2015` modules much better. The reason that we have not shipped `tns-core-modules` as `es2015` modules is that there are still people using NS **without** webpack. In order not to break them, we should support `import` in both IOS and Android runtimes, which is something that is not well tested and might cause problems (I think you already [hit some](https://github.com/NativeScript/NativeScript/pull/7129#issuecomment-481804441)).

As you know webpack will be the default build option for `5.4` and the **only** build options in `6.0`. So we decided to postpone migrating to `es2015` modules till `6.0` where everything will be handled by webpack and we would not have to worry abut compatibility.

### Using `export * from` syntax
I'm not sure if this is actually a problem. According to the [webpack docs](https://webpack.js.org/plugins/module-concatenation-plugin/#optimization-bailouts) `export * from "cjs-module"` syntax is only problem when pointed to commonJS modules. However, it should work OK if you are exporting from `es2015` module. Implementing the previous point should eliminate the need for changing the exports.

###  Removing `bundle-entry-points` requires
This is definitely on our radar. Requiring UI modules for the `builder` or for `angular-renderer` can be handled by a webpack plugin that will generate imports only for the ui widgets that you are using in your templates. 

## Next Steps
We will probably won't be able to merge you PRs in for 5.4 because of the breaking-changes and because we need to be back-compatible with non-webpack builds. 

Here are my suggestions of what comes next:
- [ ] [Anytime] Check if "remove `export * from`" is really needed if working with `es2015` modules
- [ ] [After `5.4`] Wait for release `5.4` and when **all** CI tests start running webpack build. Run all tests and application with #7128 to make sure everything is running as expected when using webpack + `es2015` core modules. 
- [ ] [After `6.0`] Develop the appropriate loaders for webpack that will replace `bundle-entry-points` (the reason this is `after 6.0` is that there will be a lot of changes in webpack/tooling for the major release and we will probably won't be able to squeeze this for 6.0). 
- [ ] [After `6.0`] Urge plugin authors to switch to `es2015` modules to make their plugins more tree-shakable

Does this sound like a good plan to you?

**Comment by farfromrefug** [comment]
@vakrilov we are on the same page. Great to hear that the {N} team is thinking about this issue ! Very open minded team ;)

About shipping as es2015 module, i understand. I actually thought ```import``` was  working well  in {N} on iOS and Android. Also for the time being i was thinking about publishing a ```tns-core-modules-es``` or something.

About the remove of ```export * from``` didn't see that in the doc. Might have something to do with the "compiled" ```tns-core-modules``` with ```es2015```. Will test

Thanks again @vakrilov . Can't wait to move forward on this.

**Comment by farfromrefug** [comment]
@vakrilov could we think about this for N 7 as it will have breaking changes ?

**Comment by vakrilov** [comment]
cc @vtrifonov @vmutafov

**Comment by farfromrefug** [comment]
think we can close this now!
