### ISSUE TITLE
SideDrawer crash on navigate from login to home

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#7134]
I work for the first time with Nativescript Drawer template .. I hop to know how the best practice to create page Like : Login and Register activate email, phone, password forgot... without the Drawer side bar ?

In my app.ts I loged user in a Frame login/login-page then if loged-in successful I redirect to home page.

Please find the playground [here](https://play.nativescript.org/?template=play-tsc&id=0oIQbk)

The problem is when I do navigate from login to home-page .. here no problem .. then if I click on Drawer icon to display rhe menu I receive error :

```
JavaScript stack trace:
1   onDrawerButtonTap@file:///app/home/home-page.js:12:26
2   notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:110:31
3   _emit@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:127:24
4   _raiseTap@file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar-common.js:259:19
5   tap@file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:34:28
6   UIApplicationMain@[native code]
7   _start@file:///app/tns_modules/tns-core-modules/application/application.js:275:26
8   run@file:///app/tns_modules/tns-core-modules/application/application.js:307:11
9   anonymous@file:///app/app.js:68:8
10  evaluate@[native code]
11  moduleEvaluation@[native code]
12  promiseReactionJob@[native code]
JavaScript error:
file:///app/home/home-page.js:12:26: JS ERROR TypeError: sideDrawer.showDrawer is not a function. (In 'sideDrawer.showDrawer()', 'sideDrawer.showDrawer' is undefined)
```

Please could you explain to me what the problem ?
Thanks

**Comment by NickIliev** [comment]
@kefahB you have the following logic

```

if (!logedIn)
    app.run({ moduleName: 'login-root' });
else
    app.run({ moduleName: 'app-root' });

```

So when you are logged in, your main Frame is created via **login-root.xml** and not via **app-root.xml**.
And in login-root.xml there is no RadSideDrawer at all, which means that the root view is not a drawer and thus the error you are receiving. Instead of having two different root files you could introduce a login check logic in your app-root.ts (for example in the `loaded` event of the root component)

Something like:

app-root.ts
```TSC
export function onLoaded(args: EventData): void {
    if (logedIn) {
        topmost().navigate({
            moduleName: "home/home-page",
            transition: {
                name: "fade"
            }
        });
    } else {
        topmost().navigate({
            moduleName: "login/login-page",
            transition: {
                name: "fade"
            }
        });
    }

    const drawerComponent = <RadSideDrawer>args.object;
    drawerComponent.bindingContext = new AppRootViewModel();
}
```

and the `app.ts` could be like
```TSC
app.run({ moduleName: 'app-root/app-root' });
```

Playground demo of the above [here](https://play.nativescript.org/?template=play-tsc&id=0oIQbk&v=2) - change the boolean value in app-root/app-root.ts to see the differently loaded pages.

**Side Note**: I am currently working on an article about extended navigation examples including the commonly used Login page that lands on the Main page and uses a RadSideDrawer. You can track [the article and the Playground examples here](https://github.com/NativeScript/docs/blob/niliev/extended-navigation/docs/core-concepts/navigation-extended.md) (so far I have 7 Core Playgrounds  + 3 Angular ones)

**Comment by kefahB** [comment]
HI @NickIliev  .. Thank you for your explanation...

So, doing check login on `loaded` event is the `best practice` for such case ? or you have another proposal to proceed ?

Thank's again for all

**Comment by NickIliev** [comment]
@kefahB there is no universal best practice as there are different scenarios - for example in the way you will "know" if the user is logged in or not.

If you depend on async service to obtain the information if the user is logged in or not (e.g. from Firebase or similar cloud backend) then it is possible to create a pre-loading screen in your login page and show the login options when the user is logged out (or navigate to the main page when the user is logged in). However, if you, for example, store the login information locally (e.g. a boolean flag in the application-settings) then perhaps the scenario for explicitly changing the navigation is a better approach. Still, storing the information if the user is logged in locally raises the question what would happen if the backend has automatically signed out the user (when this check will be created - is there an event listener to re-logout the user and show the appropriate UI) ..but those are purely an implementation details that should be handled per business case.

In any case, I would recommend avoiding changing the root file (app-root) - this would certainly not work if you try it with async method (e.g. Firebase async authorization)

**Comment by kefahB** [comment]
Grate @NickIliev, Thank you for the valuable informations .. I will close this and I am sure many peoples will be happy once found it :-)
