### ISSUE TITLE
Address sudden lack of background geolocation plugin

### ISSUE THREAD

**Issue by Yermo** [NativeScript/NativeScript#7162]
**Is your feature request related to a problem? Please describe.**

I do not know if this is the correct place to report this. If not, please let me know where I should post it. 

I have been told by TransistorSoft that they are discontinuing support for NativeScript so soon https://github.com/transistorsoft/nativescript-background-geolocation-lt will no longer be available.

I was unable to convince them to keep the plugin available and they have suggested I switch platforms. I like NativeScript and would like to find a way to continue using it.

The problem is that my application is completely based on background geolocation so I'm facing somewhat of a disaster.

**Describe the solution you'd like**

It should be possible to port the [Mauron85 Cordova background geolocation](https://github.com/mauron85/cordova-plugin-background-geolocation) plugin to NativeScript but doing that by myself may be more than I can get done in any kind of timely fashion without at least access to someone I can ask questions.

**Describe alternatives you've considered**

React Native?

**Additional context**

Without an available solid background geolocation solution a large number of potential developers will not be able to adopt NativeScript, which would be a shame. I like this platform.

**Comment by NathanaelA** [comment]
Hi @Yermo,

I'm not part of the NS team, but a plugin developer.  

1. Just because they are no longer going to support the plugin, doesn' t mean that you can' t download the npm plugin and continue to use it pretty much forever.   (npm info plugin_name; wget plugin_url from the info -- or grab it out of your computers npm cache)

2. There are a lot of plugin developers available on NativeScript; hope onto slack and you can ask several of us questions; if all you are doing it picking our brain.  Most of us do NOT like direct messaged; just drop a question in the `plugins` channel and typically someone will respond at some point when we have time, we are located all around the world; so some of us will be sleeping while you are awake.   So have patience.   :grinning:

3. There are also many of us plugin devs that will write plugins for money; a number of Eddy's plugins are payed for by Progress, and I probably have about 1/8th of mine were payed client projects, same thing with Osie, Brad & Nathan.  That pretty much covers the top 5 plugin authors in the eco-system.  ;-)    So a paid route is also easily done as their is availability to high quality plugin devs.

**Comment by Yermo** [comment]
Sadly, the TransistorSoft plugin is commercial closed source.

I'll check on Slack. Thank you.

**Comment by tsonevn** [comment]
Hi all,
There is another plugin called [nativescript-geolocation](https://github.com/NativeScript/nativescript-geolocation), which is officially supported by NativeScript Plugins team. You can check the demo in the repository [here](https://github.com/NativeScript/nativescript-geolocation/tree/master/demo) and verify if the plugin meets your app requirements.

**Comment by edusperoni** [comment]
I'd also like to add that `nativescript-background-geolocation-lt` and `background-geolocation-lt` are licensed under MIT, so there's nothing stopping you from forking and maintaining it yourself. It seems this plugins just uses their native API, which will not be discontinued.

**Comment by Yermo** [comment]
@edusperoni  Take a closer look. The java/objc libraries it relies on are closed source and will only work in release mode if you buy a license. 

@tsonevn I've carefully looked at that plugin. Sadly it does not support my needs.

There's the mauron85 plugin for react-native and cordova which is based on open source libraries for iOS and Android which look like they fit the bill. I am hoping to be able to create a NativeScript binding for those libraries.
