### ISSUE TITLE
Get back to root view in a TabView Frame

### ISSUE THREAD

**Issue by patrikengborg** [NativeScript/NativeScript#7177]
Prior to NS 5.3, a tap on the currently selected `TabViewItem` containing a `Frame`, took you back to the root view of that `Frame`. So when navigating deeper inside a `Frame,` you could always return to the root view again it by simply tapping on that tab. As of NS 5.3, this is no longer the case. Tapping on a `TabViewItem` that is already active does nothing.

It's a little tricky to explain clearly, so here are two videos to give you a better understanding of the issue.

The old (correct) behavior: [https://streamable.com/wn79e](https://streamable.com/wn79e)
The new behavior: [https://streamable.com/m3spa](https://streamable.com/m3spa)

I'm not really sure if this counts as a bug, but I can't see why this would have been removed on purpose. It's a great feature and also feels like standard iOS behavior. 

I would really appreciate if it could be brought back.

I'm using Nativescript Vue, but I think this is an issue with tns-core-modules.

**Comment by tsonevn** [comment]
Hi @patrikengborg 
Thank you for the provided videos.
I check the case in a sample non-Vue project and it seems that this is currently the expected behaviour while using TabView with Frames. I also found this feature request [here](https://github.com/NativeScript/NativeScript/issues/6095), which should provide a more flexible way to handle the item tap event and should also help in solving your case. I would suggest keeping track on it for further info.
