### ISSUE TITLE
ListPicker emits unnecessary selectedIndexChange on render

### ISSUE THREAD

**Issue by taras** [NativeScript/NativeScript#7179]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: N/A
 - Cross-platform modules: 
 - Android Runtime: 7, 8 & 9
 - iOS Runtime: 12
 - Plugin(s):

**Describe the bug**

When a ListPicker component is rendered with `selectedIndex` property bound, it immediately emits an `selectedIndexChange` even thought `selectedIndex` has not changed. 

**To Reproduce**

```html
<ListPicker 
    [items]="pokemons" 
    [selectedIndex]="5"
    (selectedIndexChange)="log($event.object.selectedIndex)">
</ListPicker>
```

1. Render a `ListPicker` component with a `selectIndex` bound. Make sure that the value is available before the component is rendered.
2. Bind `selectedIndexChange` event and add a console.log
3. Render the ListPicker component
4. Do not touch it
5. You'll see the event logged even though you didn't touch the ListPicker

**Expected behavior**

When there is no selection and selection did not change, there should not be an even emitted. This kind of strange behaviour is counter intuitive and can add up to very difficult to track down performance issues when `selectedIndexChange` handler has a heavy operation.

**Sample project**

https://play.nativescript.org/?template=play-ng&id=S8mnnb&v=2

**Additional context**

I looked at the source code for ListPicker and I suspect that event is the result of [`selectedIndex` having a default value of `-1`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/list-picker/list-picker-common.ts#L48). It probably should not have a default value or the default value should be the value that's passed to the component when it's rendered. 

Thank you

**Comment by NickIliev** [comment]
After discussion within the Core team, we've concluded that setting the default value to `-1` should be the default behavior and we should trigger the` selectedIndexChange` event for consistency within the framework. There are some widgets like `SegmentedBar` and `TabView` which are using the selectedIndexChange to trigger additional logic so this was one of the main historical reasons for the initial value to be set to -1. Also, changing the default value now could break existing projects and there is a workaround for the issue (checking the initial load) which lead us to believe that there is no need to change the value from -1 to 0.

Closing the issue as the described case is the expected behavior.

**Comment by taras** [comment]
@NickIliev thank you for taking the time to look into this. I agree that changing from `-1` to `0` is going to introduce change without much benefit. This actually wasn't what I was suggesting. 

The problem is that the property has a default value that is hardcode regardless of the initial value that the view is created with. An actual improvement would be to have a default value but allow the default value to be the value that the view was created with.

**Comment by Sothecom** [comment]
Hi @NickIliev you mentioned the workaround of "checking the initial load", please give some additional info on that. Thanks
