### ISSUE TITLE
[android] Flickering of some tab content when TabView's active tab changes to a distant tab and the "from" tab content is unloaded

### ISSUE THREAD

**Issue by sserdyuk** [NativeScript/NativeScript#7184]
**Environment**
```
tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.3.4 version and is up to date.
✔ Component tns-core-modules has 5.3.1 version and is up to date.
✔ Component tns-android has 5.3.1 version and is up to date.
✔ Component tns-ios has 5.3.1 version and is up to date.
```
```
tns plugin
Dependencies:
┌─────────────────────────────────────────┬─────────┐
│ Plugin                                  │ Version │
│ @angular/animations                     │ ~7.2.0  │
│ @angular/common                         │ ~7.2.0  │
│ @angular/compiler                       │ ~7.2.0  │
│ @angular/core                           │ ~7.2.0  │
│ @angular/forms                          │ ~7.2.0  │
│ @angular/http                           │ ~7.2.0  │
│ @angular/platform-browser               │ ~7.2.0  │
│ @angular/platform-browser-dynamic       │ ~7.2.0  │
│ @angular/router                         │ ~7.2.0  │
│ nativescript-angular                    │ ~7.2.1  │
│ nativescript-cardview                   │ ^3.1.1  │
│ nativescript-fresco                     │ ^5.2.0  │
│ nativescript-google-maps-sdk            │ ^2.7.0  │
│ nativescript-google-places-autocomplete │ ^1.0.3  │
│ nativescript-ngx-shadow                 │ ^6.4.0  │
│ nativescript-swiss-army-knife           │ ^4.0.2  │
│ nativescript-theme-core                 │ ~1.0.4  │
│ nativescript-ui-autocomplete            │ ^4.0.0  │
│ nativescript-ui-listview                │ ^6.1.0  │
│ reflect-metadata                        │ ~0.1.12 │
│ rxjs                                    │ ~6.3.0  │
│ tns-core-modules                        │ ~5.3.1  │
│ zone.js                                 │ ~0.8.26 │
└─────────────────────────────────────────┴─────────┘
Dev Dependencies:
┌─────────────────────────────┬─────────┐
│ Plugin                      │ Version │
│ @angular/compiler-cli       │ ~7.2.0  │
│ @nativescript/schematics    │ ~0.5.0  │
│ @ngtools/webpack            │ ~7.2.0  │
│ codelyzer                   │ ~5.0.0  │
│ husky                       │ ^1.3.1  │
│ nativescript-dev-sass       │ ~1.7.0  │
│ nativescript-dev-typescript │ ~0.9.0  │
│ nativescript-dev-webpack    │ ~0.21.0 │
│ npm-run-all                 │ ^4.1.5  │
│ prettier                    │ ^1.16.4 │
│ pretty-quick                │ ^1.10.0 │
│ tns-platform-declarations   │ ^5.2.2  │
│ tslint                      │ ^5.14.0 │
│ tslint-angular              │ ^1.1.2  │
└─────────────────────────────┴─────────┘
```

**Describe the bug**
When the controls are on the bottom, the TabView component is only keeping three tabs loaded - the current and two next to it. When active tab changes, the component dynamically unloads and reloads components from the tabs. This causes high frequency flickering in my application (see the video below, note that flicker is faster in real life). The flicker affects only the map area, so part of the issue could be related to the Map SDK or nativescript-google-maps-sdk plugin. I reviewed the plugin and didn't find any obvious suspects.

**To Reproduce**
Build and try the app @tsonevn already has access to its code due to another issue. The issue is easily observable on a Pixel 3 running Android 9 (API level 28) but not in the emulator.

![ezgif-2-c18236e384af](https://user-images.githubusercontent.com/395998/56820390-c7f98380-6819-11e9-9368-144b22d92ebc.gif)

**Comment by tsonevn** [comment]
Hi @sserdyuk,
I checked the issue on my side while using a brand new Android emulator API level 28, however, I was unable to recreate it. For your convenience, I am attaching a GIF file. You can review it and check if I am missing something. 
Keep in mind that, setting the Tabs at the bottom will disable the swipe navigation and the items preloading functionality. You can check the documentation [here](https://docs.nativescript.org/ui/ns-ui-widgets/tab-view).
![Screencast 2019-04-29 at 2 10 38 PM](https://user-images.githubusercontent.com/17448734/56893089-317fc900-6a8a-11e9-8979-dc6e85e3a5d6.gif)

Meanwhile, just for the test, you can try replacing the map with an image and check if the issue will be still. If the problem is reproducible only with the `nativescript-google-maps-sdk` plugin, you can log a new issue in the plugin's repository.

**Comment by sserdyuk** [comment]
@tsonevn Yes, i know it doesn't happen in the emulator, I indicated it in my report. I will file it with the plugin author, but I wanted to bring this to your attention first as it might be a subtle timing issue in TabView component. After all, the flicker only happens when you switch to a distant tab and the TabView unloads the tab content. Switching between neighboring tabs doesn't cause the issue, and I can switch from "Nearby" to "Search", then to "Favs" without the flicker.

**Comment by tsonevn** [comment]
@sserdyuk, I will build the project on a device and will check if I will be able to recreate the problem.

**Comment by sserdyuk** [comment]
@tsonevn I left bug/flicker branch with the state where it's most visible.

**Comment by tsonevn** [comment]
Hi @sserdyuk,
Excuse me for the delayed reply.
I spent some time testing the case and was able to recreate the issue only with the Map. As I suggested before, you can try, just for the test, to replace the map with an image. In this case, the issue is not reproducible on my side. In my opinion, the problem is more likely to be in the map plugin.
