### ISSUE TITLE
Cant build app with Kinvey Android config

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/NativeScript#7187]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 5.3.4
 - Cross-platform modules: 5.3.0
 - Android Runtime: 5.3.1

**Describe the bug**
Kinvey android starting guide https://devcenter.kinvey.com/android/guides/getting-started

Trying to add an Android service written using the Kinvey Android config (gradle deps, etc.) and the config works fine in android studio but fails with NativeScript build.

**To Reproduce**

Repo [here](https://github.com/bradmartin/kinvey-android-build) with the `libs` directory added and the deps added to the gradle file. It will fail to build. The app.gradle file includes two lines not in the Kinvey docs. When I did the setup in android studio and tried building against the Kinvey docs the android build threw an error about the `Annotation processors must be explicitly declared now.  ` So I've added two of those to the app.gradle but I still cannot figure out how to resolve this type of configuration for a NativeScript app to build.

Kinvey libs [here](https://github.com/bradmartin/kinvey-android-build/tree/master/app/App_Resources/Android/libs)

app.gradle [here](https://github.com/bradmartin/kinvey-android-build/blob/master/app/App_Resources/Android/app.gradle#L4)

**Expected behavior**
Build succeeds

**Sample project**

https://github.com/bradmartin/kinvey-android-build

**Additional context**

**Comment by bradmartin** [comment]
For better context, I started writing a service in android studio, with intention of putting it inside the `app_resources/android/..` of a NS app once I had things working.

So I followed the kinvey setup for android project in android studio, got past a few outdated issues from the docs there and ended up with this file as a working build.gradle https://github.com/Max-Mobility/KinveySaveIssue/blob/master/app/build.gradle

So that project builds fine with the Kinvey libs that are provided in the getting started.  If I drop the `libs` into the NS app, setup the gradle file similarly and try building errors will throw in the build process.

**Comment by bradmartin** [comment]
I've tried various ways to configure the gradle file but nothing seems to work within the NS app.

**Comment by bradmartin** [comment]
Even trying to override the behavior with 

```

     javaCompileOptions {
            annotationProcessorOptions {
                includeCompileClasspath true
            }
        }
```  will error with:

```
Note: Recompile with -Xlint:deprecation for details.
D8: Program type already present: io.realm.processor.ClassMetaData$1

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
  Program type already present: io.realm.processor.ClassMetaData$1
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Command ./gradlew failed with exit code 1
Brads-MBP:kinveytest bradmartin$ 
```

**Comment by vmutafov** [comment]
Hi, Brad! 
As I looked into the Kinvey tutorial, it seems to be not following best practices and including local jars rather than having proper dependencies configuration using some Java artifacts repository (e.g. MavenCentral). Personally, I think for NativeScript applications the preferable way to use a dependency would be not to include the jar in the `App_Resources/Android/libs`, but to depend against a remote repository. But if you want to include the jars in the libs directory, in your case, you should just have: 
`annotationProcessor ':pubnub-gson-4.18.0-all'`
`annotationProcessor ':realm-annotations-processor-3.2.1'`

without having the implementation declarations in the `app.gradle`. You don't need the `implementation` declarations as the gradle script in the Android runtime for building the app includes by default all jars and aars in the `App_Resources/Android/libs` as `implementation` dependencies. Having declared the jars as `implementation` dependencies in the app.gradle would include them twice and in your case breaks the build.

**Comment by bradmartin** [comment]
I'll try this later. I couldn't figure out why it was breaking after skimming the build.gradle in platforms so thank you very much for the info.
