### ISSUE TITLE
Issues of console.log  and setTimeout

### ISSUE THREAD

**Issue by DeanIfalo** [NativeScript/NativeScript#7193]
**Environment**
Devices: android 8.0.0 and ios 12.1.4
Using web playground with the latest playground and preview app.

**Describe and Reproduce**
*a. case [console.log]*
Look in to login-page.js in [this](https://play.nativescript.org/?template=groceries-js&tutorial=groceries-js&id=QY2L3w) playground.
Tap and watch the logs.
![log](https://user-images.githubusercontent.com/26296421/57066851-f981bb80-6cff-11e9-843b-46ebd33d0b3b.PNG)
The logs are often out of sequence.

*b. case [setTimeout] (test ios only)*
Look in to login-page.js in [this](https://play.nativescript.org/?template=groceries-js&tutorial=groceries-js&id=lhqWhI) playground.
Tap to trigger the callback of AudioServicesPlaySystemSoundWithCompletion.
However the callback of setTimeout will never be triggered.
![time](https://user-images.githubusercontent.com/26296421/57068158-795d5500-6d03-11e9-9403-85d3f749a868.PNG)

**Comment by tsonevn** [comment]
Hi @DeanIfalo,
Regarding the  `logs - out of sequence`. NativeScript Playground uses  [PubNub as a service](https://www.nativescript.org/blog/architecture-of-the-nativescript-playground?_ga=2.180599534.859318902.1557204683-2022237003.1548063582) while syncing the changes from the browser editor and the mobile device. This service uses different nodes while syncing the changes, which leads to printing a log out of sequence.  On that matter, the time for console.logs depends strictly on the  PubNub service and cannot be controlled by NativeScript. Keep in mind that this behaviour can be noticed only in Playground. The console.logs should be printed in the correct order while using project build with NS CLI.

About the second issue with the `AudioServicesPlaySystemSoundWithCompletion` native method, this problem seems to be something related in the modules. The `AudioServicesPlaySystemSoundWithCompletion ` is executed in another thread, which prevents from correct execution of the timeout. I will mark this as a bug, and we will investigate it further. As a workaround, you can try moving the callback method in the main thread as follows:
```
AudioServicesPlaySystemSoundWithCompletion(1352, () => {
       NSOperationQueue.mainQueue.addOperationWithBlock(() => {
           console.log(“111”);
           setTimeout(() => {
               console.log(“333");
           }, 2000);
           console.log(“222”);
      });
   });
```

**Comment by DeanIfalo** [comment]
Thanks @tsonevn.
This information and workaround is very helpful.

**Comment by tsonevn** [comment]
Hi @DeanIfalo,
We've introduced new functionality, that allows you to passed function for execution on the main thread. This new functionality is currently available in our `@rc` modules version and can be used as follows:
```
const mainthreadHelper = require("tns-core-modules/utils/mainthread-helper")
exports.tap = function () {
    console.log("---");
    console.log("000");
    AudioServicesPlaySystemSoundWithCompletion(1352, () => {
        mainthreadHelper.dispatchToMainThread(()=>{
            console.log("111");
            setTimeout(() => {
                console.log("333");
            }, 2000);
            console.log("222");
        })
        
    });
}
```
PR: https://github.com/NativeScript/NativeScript/pull/7220/

**Comment by tsonevn** [comment]
Docs PR - https://github.com/NativeScript/docs/pull/1657
