### ISSUE TITLE
FlexboxLayout dose not allow binding data with RadListView

### ISSUE THREAD

**Issue by kefahB** [NativeScript/NativeScript#7209]
Hi,

The `FlexboxLayout` dose not allow data binding with `RadListView` .. tested on IOS only.
Please see the [Playground](https://play.nativescript.org/?template=play-tsc&id=92UnSr)

Try to remove the FlexboxLayout every think work as expected the Data will be binding correctly.

Thanks

**Comment by tsonevn** [comment]
Hi @kefahB,
Thank you for the provided sample project. I checked the issue on my side and was able to recreate an issue with the `FlexboxLayout` on iOS, however, the problem does not seems to be related to the data binding. The issue is with the setting the correct width for the child component inside the Flexbox. Check out the [modified sample here](https://play.nativescript.org/?template=play-tsc&id=92UnSr&v=4). If you set width for the StackLayout(first child of the Flexbox), the RadListView will be shown correctly.

**Comment by tsonevn** [comment]
HI @kefahB, 
Can you confirm that this is the issue on your side as well or you are facing a different problem?

**Comment by kefahB** [comment]
Hi @tsonevn 

Thank's a lot .. every think work as expected :-)
