### ISSUE TITLE
TextView keyboard doesn't display hint

### ISSUE THREAD

**Issue by BigWillie** [NativeScript/NativeScript#7282]
**Environment**
Vue NativeScript. Using Sidekick

**Describe the bug**
I'm using TextField hints as "labels". The hint appears within the title of the keyboard. With TextView the hint does NOT appear within the title of the keyboard.

**Expected behavior**
For the TextView hint to also appear within the title of the keyboard

**Comment by tsonevn** [comment]
HI @BigWillie,
If I understand you correctly, you are facing an issue with the autocorrect functionality, which provides suggestions about the words above the keyboard.
I tested the scenario within a [sample project,](https://play.nativescript.org/?template=play-vue&id=7eVsl7) however, was unable to recreate the problem. If this is the case, please review the linked sample project and make the needed changes, that will allow us to reproduce the issue.

**Comment by BigWillie** [comment]
Hi @tsonevn 

Not the autocorrect functionality - but the hint. On TextField, the hint appears in the keyboard header as a label. But with TextView this does not happen

https://play.nativescript.org/?template=play-vue&id=V20qvp

Thanks,
Rob

**Comment by tsonevn** [comment]
Hi @BigWillie,
I' ve tested your case again and indeed the TextView hint will not be shown above the keyboard for iOS. However, this seems to be expected behaviour. By design, the UITextView does no have a hint/placeholder/(you can check the article [here](https://medium.com/@maximbilan/ios-placeholder-in-uitextview-e3c93ecb247a)) and we are using [custom code](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/text-view/text-view.ios.ts#L189-L197) to provide support for this feature. Regarding that, the iOS will not detect that there is a text used as a hint and will not display it above the keyboard(displaying the hint above the keyboard is controlled by the OS and we can not change its behaviour).

**Comment by BigWillie** [comment]
Cool :) I found https://github.com/tjvantoll/nativescript-IQKeyboardManager which addresses the issue.
