### ISSUE TITLE
[Request] Able to create a live streaming app

### ISSUE THREAD

**Issue by b02505048** [NativeScript/NativeScript#7292]
**Is your feature request related to a problem? Please describe.**
Since the LIVE streaming app is very popular now, hopefully {N} may support this feature soon.

**Describe the solution you'd like**
May refer to React Native, plenty of plugins for building the LIVE streaming app.

**Describe alternatives you've considered**
No alternatives, FOREVER SUPPORT NATIVESCRIPT!!! <3

**Comment by NickIliev** [comment]
@b02505048 NativeScript can work with native libraries and there are many choices that are providing live stream options. So that said, you could create your own plugin or directly use a library to create a live stream. 

For example,[ here is a library for both Android and iOS](https://kickflip.io/) which can be used as mentioned above. I guess there are many other native libraries that can be reused either directly in your app or by creating a plugin.

**Comment by b02505048** [comment]
Thanks @NickIliev !
I'm not sure how to use the libraries(SDK?) directly, may you show me some examples? Appreciate your help 3000!!!
