### ISSUE TITLE
Memory leak with background worker

### ISSUE THREAD

**Issue by mandar-bhong** [NativeScript/NativeScript#7338]
**Environment**

My working environment is as follows
Windows 8.1 (Development machine)
Building android application

Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 
√ Getting NativeScript components versions information...
√ Component nativescript has 5.4.0 version and is up to date.
√ Component tns-core-modules has 5.4.2 version and is up to date.
√ Component tns-android has 5.4.0 version and is up to date.
√ Component tns-ios has 5.4.1 version and is up to date.

**Describe the bug**
When application contain background worker then with live sync system memory is increases with every save operation. 
When application synced with device then changes in source file makes file changes detection by tns and it goes for recompilation and with hrm it update the changes. With every cycle of recompilation and sync system memory is getting increased. 

**To Reproduce**
Download the sample application 

Install dependency (`tns install`)

Open Task Manager to view the memory consumed by the application (keep eye on this memory whenever changes done in file)

Debug application with `tns debug android ` from cmd prompt
Once application is synced with device, 
open  /src/app/item/items.component.html file in any editor and change `[text]="item.id"` to `[text]="item.name"` and vice versa  (**Repeat this for multiple times** )

After some time development system memory will reach to its peak 

**Note**: Some time memory can be dropped by few MB's be but as trend it will increase continuously

**Expected behavior**
Development system memory should not be increase with every changes. (If increased then it should be dropped )

**Sample project**
For sample project find the link below
[Worker Memory Leak Sample Project](https://github.com/mandar-bhong/NativeScript-Worker-MemoryLeak)

Thanks

**Comment by NickIliev** [comment]
@mandar-bhong are you testing on a real device or on an emulator? There is a difference in how the emulators are releasing the occupied memory (as you are using the environment memory the GC is not so aggressive) compared to real devices (where the GC will be triggered on memory pressure). That said please test the memory consumption on a real device.

Also, you can see[ this article ](https://docs.nativescript.org/core-concepts/android-runtime/advanced-topics/memory-management)about advanced techniques you can apply to optimize your memory consumption.

**Comment by vcooley** [comment]
I'm experiencing these same issues as well after implementing workers in my app. Note that the issue seems to be in the CLI, as it is the node process that is reporting high memory issues. 

This can be mitigated by setting a larger max heap for node (see [this](https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory)), but it only pushes the problem down the road. I'm experiencing a typical ~200MB of extra memory usage between each sync.

In my particular case, the CLI crashes after about 6-8 syncs even with 4GB set as the max heap size for node.

**Comment by mandar-bhong** [comment]
Hello @NickIliev 
I am experiencing the memory leak is not about device (real or simulated) it is development machine as mentioned by @vcooley it is development machine (node.exe) if we keep eyes on "Task Manager" of windows machine.
With googling I am able to figure out that this issue is coming into picture when nativescript-angular environment is used (with background worker) 
The main culprit was **ts-loader**. 
(From webpack.config.js)
{ test: /\.worker.ts$/, loader: "ts-loader"} },

After adding "transpileOnly: true" options development machine memory is in normal state after multiple sync.
{ test: /\.worker.ts$/, loader: "ts-loader",options: {transpileOnly: true} },

But I think this is not good approach as it is disabling type checker. Other option to rescue from this situation is use of **fork-ts-checker-webpack-plugin**. But I am unable to use as it is giving compilation error.
Please suggest your thought on this. 
Thanks

**Comment by DimitarTachev** [comment]
Hi @mandar-bhong,

We've already updated the [`ts-loader`](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.typescript.js#L226) and the [`fork-ts-checker-webpack-plugin`](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.typescript.js#L263) in [the latest Typescript Webpack config](https://github.com/NativeScript/nativescript-dev-webpack/blob/master/templates/webpack.typescript.js).

I suggest you take a look at the above-mentioned config and apply the changes to your app. The ts-loader is now configured in `transpileOnly` mode and the `fork-ts-checker-webpack-plugin` plugin is configured in a single child process with increased memory limit (4GB) and `async: false` in order to execute a blocking incremental TypeCheck (`useTypescriptIncrementalApi: true`) without affecting the main CLI process performance and memory usage.
