### ISSUE TITLE
Change content of a TabView

### ISSUE THREAD

**Issue by gsarme** [NativeScript/NativeScript#7376]
I'm using nativescript with angular.
I have a TabView that has to have a dinamic content. 
I want to set the content from the code behind but when a try to get the layout that has to contain the data it gives `undefined` 

Here is my file.component.html
```
<TabView id="tabViewContainer" style="background-color:#E5E5E5">
    <StackLayout *tabItem="{title: 'In scadenza'}" id="tabInScadenza">
      <StackLayout id="inscadenza">
        <Label text="First Tab" textWrap="true"></Label>
      </StackLayout>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Scaduti'}" id="tabScaduti">
      <StackLayout id="scaduti">
          <Label text="Second Tab" textWrap="true" class="m-15 h2 text-left" color="blue"></Label>
      </StackLayout>
    </StackLayout>
</TabView>
```

in my file.component.ts I have:
```
ngOnInit(){
    console.log(this.page.getViewById("tabViewContainer").getViewById("tabInScadenza"));
  }
```

I don't know what's wrong.

**Comment by NickIliev** [comment]
@gsarme the thing is that you are mixing two concepts - the Angular lifecycle (NgOnInit) and the NativeScript lifecycle. You should either use the Angular way to access your elements (ViewChild, Angular's ID and AfterViewInit/ OnInit events) or the NativeScript way (NativeScript's loaded event or getViewById but after the Angular is rendered)

I would recommend going with the Angular way so that you can utilize the benefits of using Angular.

So instead `id="tabViewContainer"` use Angular ID `#tabViewContainer` and then access the Angular element vie `ViewChild`. With Angular 8 the `ViewChild` directive needs two arguments: the ID and an object that sets the static property. Setting static to false is the default behavior and basically said it will make the element available in `NgAfterViewInit` (not in NgOnInit)

Here is a sample codeshowing the above  - taken from [this full Playground demo](https://play.nativescript.org/?template=play-ng&id=rdDKYE)
```TypeScript
import { Component, OnInit, ViewChild, ElementRef } from "@angular/core";
import { TabView } from "tns-core-modules/ui/tab-view";
import { StackLayout } from "tns-core-modules/ui/layouts/stack-layout";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html",
    styleUrls: ["./home.component.css"]
})
export class HomeComponent implements OnInit {

    @ViewChild("tab", { static: false }) tab: ElementRef;
    @ViewChild("firstStack", { static: false }) firstStack: ElementRef;

    tabNative: TabView;
    firstStackNative: StackLayout;

    constructor() {
    }

    ngOnInit(): void {
    }

    ngAfterViewInit(): void {
        this.tabNative = this.tab.nativeElement;
        this.firstStackNative = this.firstStack.nativeElement;

        console.log(this.tabNative);
        console.log(this.firstStackNative);
    }
}
```

HTML
```HTML
<TabView #tab height="300px">
    <StackLayout #firstStack *tabItem="{title: 'Tab 1'}">
        <Label text="Label in Tab 1" class="h2 text-center"></Label>
    </StackLayout>
    <StackLayout *tabItem="{title: 'Tab 2'}">
        <Label text="Label in Tab 2" class="h2 text-center"></Label>
    </StackLayout>
</TabView>
```

**Comment by gsarme** [comment]
Thank you @NickIliev, I got it. Now I try that with my app!

**Comment by gsarme** [comment]
There's a problem with 
```
  @ViewChild("tab", { static: false }) tab: ElementRef;
```

It gives this error
` error TS2345: Argument of type '{ static: boolean; }' is not assignable to parameter of type '{ read?: any; }'.`

**Comment by NickIliev** [comment]
Yep, Angular ver 7.x.x does not have the additional parameter. It was introduced in version 8.0.0 as a mandatory parameter. If you want to update to version 8 then use[ the upgrade instructions](https://docs.nativescript.org/releases/upgrade-instructions#upgrading-angular-dependencies).
