### ISSUE TITLE
goBack dont work with singleton Page

### ISSUE THREAD

**Issue by webleaf** [NativeScript/NativeScript#7394]
**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.2 version and is up to date.
✔ Component tns-core-modules has 5.4.3 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
✔ Component tns-ios has 5.4.2 version and is up to date.

**Describe the bug**
I use programmatically created Views and store/cache them in variable (not to parse every time) related with https://github.com/NativeScript/NativeScript/issues/6931#issuecomment-465486985
Also looks like related with https://github.com/NativeScript/NativeScript/pull/7327

[![testGoback.gif](https://s3.gifyu.com/images/testGoback.gif)](https://gifyu.com/image/ETHL)

**To Reproduce**
First of all the issue easy reproducible for iOS and with GC() call (without GC() it's exist too, but need more clicks to appear). It also looks like it's only iOS issue.
Also looks like if we try `mainFrame.navigate(() => pageA)` instead `goBack` it don't work too (and crashes with error)
Just copy-paste this code to your `app.ts` or use sample project [testGoback.zip](https://github.com/NativeScript/NativeScript/files/3317835/testGoback.zip)
```typescript
import * as app from "tns-core-modules/application";
import {Page} from "tns-core-modules/ui/page";
import {Frame} from "tns-core-modules/ui/frame";
import {parse} from "tns-core-modules/ui/builder";
import {GC} from "tns-core-modules/utils/utils";

const mainFrame = new Frame();

const pageA = <Page>parse(`<Page navigatingTo="{{ onNavigatingTo }}"><StackLayout><Button text="to PageB" tap="{{ onButtonATap }}"/></StackLayout></Page>`);
pageA.bindingContext = {
    onNavigatingTo: () => {
        console.log("pageA.onNavigatingTo()");
        GC()
    },
    onButtonATap: () => {
        console.log("pageA.onButtonATap()");
        mainFrame.navigate(() => pageB)
    }
};

const pageB = <Page>parse(`<Page><StackLayout><Button text="goBack() to PageA" tap="{{ onButtonBTap }}"/></StackLayout></Page>`);
pageB.bindingContext = {
    onNavigatingTo: () => {
        console.log("pageB.onNavigatingTo()");
        GC()
    },
    onButtonBTap: () => {
        console.log("pageB.onButtonBTap()");
        mainFrame.goBack()
    }
};

app.run({
    create: () => {
        mainFrame.navigate(() => pageA);
        return mainFrame
    }
});
```

**Comment by NickIliev** [comment]
@webleaf the thing is that NativeScript as a framework was not developed with Singleton in mind. Some of the logic related to the layout system, native widgets, etc., is coupled with the initialization and the disposal of those views. To illustrate what I mean I will walk you through the issue you are facing.

Both pages are containing a `Button` and the ios implementation can be found [here](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/button/button.ios.ts). The iOS button was subject to some memory leaks which were fixed by explicitly clearing the `tap` handler when the button is disposed (meaning that you might hit the issue even without calling the `GC`)

Look at [the Button implementation for iOS](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/button/button.ios.ts#L21-L31)

```TypeScript

    public initNativeView(): void {
        super.initNativeView();
        const nativeView = this.nativeViewProtected;
        this._tapHandler = TapHandlerImpl.initWithOwner(new WeakRef(this)); // HERE
        nativeView.addTargetActionForControlEvents(this._tapHandler, "tap", UIControlEvents.TouchUpInside);
    }

    public disposeNativeView(): void {
        this._tapHandler = null; // HERE
        super.disposeNativeView();
    }
```

If you comment the `this._tapHandler = null;` line then your issue will be resolved and the tap handler will never be removed when the `disposeNativeView` is called (the dispose method is [called on tearDownUI in view-base](https://github.com/NativeScript/NativeScript/blob/6f439cb8197568be18e1e53a9f64af7e581ba98f/tns-core-modules/ui/core/view-base/view-base.ts#L813)).

In your implementation, you are initializing the view only once (via `parse` of the Page). So when the button is disposed of, there is [never a new call to `initNativeView`](https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/button/button.ios.ts#L24) which means that the tapHandler is never re-assigned.

So the above said, you could easily workaround your specific issue by using Label instead of Button or by manually changing the code in `tns-core-modules`. The latter is not recommended as the tabHandler was causing a minor memory leak (which is the reason to have an explicit removal of the handler). 

Still, in conclusion, as of this very moment, the framework is not supporting Singelton and entire code-behind logic as there are functionalities and optimizations that are coupled with the initialization of views. It's just that there are a number of widgets (e.g. like the `Button` on iOS) that are extensively using optimization techniques dependent on `initNativeView` and `disposeNaitveView` and a lot of the logic behind `tns-core-modules` is coupled with this strategy.
