### ISSUE TITLE
Modules does not support iOS9

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/NativeScript#740]
Apple has made a change in the API and `NSNotFound` is converted from an enum to a constant.

This breaks the apps in iOS9 and Xcode 7 emulator which uses it by default.

**Comment by fealebenpae** [comment]
The NativeScript for iOS runtime doesn't support compile-time Objective-C constants, but [we're working on adding support for them](https://github.com/NativeScript/ios-runtime/issues/279).

However, it turns out that `NSNotFound` is defined as `NSIntegerMax`, which on 64bit devices is the maximum value of the `int64_t` type. Unfortunately, JavaScript doesn't support integers this large, so `NSNotFound` will end up truncated and not matching the native value. JavaScript code that relies on `NSNotFound` will have to find workarounds.

@Fatme and I came up with such a workaround - instead of comparing the result of `-[NSArray indexOfObject:]` to `NSNotFound`, check whether the returned index is greater than zero and smaller than the count of elements in the array.

**Comment by hshristov** [comment]
@fealebenpae Is it possible to return some other type (e.g. not a primitive JS type) which holds the native value? This way it will be possible to do comparison with it.

**Comment by fealebenpae** [comment]
If we don't return a number primitive we can only return an object, and objects in JavaScript are always compared using identity equality, rather than value equality, so it wouldn't work anyway.

**Comment by tjvantoll** [comment]
Just fyi I hit this in one of my apps as well. Here's the error I get when trying to use a `<TabView>`:

file:///app/tns_modules/ui/tab-view/tab-view.js:168:54: JS ERROR TypeError: tabBarItem.setTitlePositionAdjustment is not a function. (In 'tabBarItem.setTitlePositionAdjustment({ horizontal: 0, vertical: -20 })', 'tabBarItem.setTitlePositionAdjustment' is undefined)

**Comment by ignaciofuentes** [comment]
As a me too fyi, 
I am having the same issue as @tjvantoll. I tried this on both ios 9 and ios 8.4 emulator.

**Comment by fealebenpae** [comment]
@ignaciofuentes, we say that this is an iOS 9 issue, but it's the iOS 9 SDK in Xcode 7 that's the problem, not iOS 9 itself. You can build a NativeScript app with Xcode 6.4 and it will work on iOS 9, but if you build the app with Xcode 7 and run it on iOS 8 you'll get the same problem, so that's why you had the same issue on the iOS 8.4 Simulator.

**Comment by eugeneniemand** [comment]
I also experienced this problem while trying the tab-view example as specified in the docs. Can te docs be updated with a warning or is there an ETA on a fix for this?

**Comment by eugeneniemand** [comment]
@fealebenpae Any idea when nativescript will support xCode 7 to circumvent the above mentioned crash using tab-view?

**Comment by bradmartin** [comment]
+1

**Comment by toddanglin** [comment]
This is a major challenge. Cannot debug a simple Hello World app in the iOS simulator with a TabView on an up-to-date Mac. Is there a work around that can restore TabView support before v1.5?

**Comment by toddanglin** [comment]
Follow-up for those having the problem with TabView described above. Thanks to some quick sleuthing by @jbristowe this work around is available:

You need to patch your local copy of `tab-view.ios.js` (in node_modules > tns-core-modules > ui > tab-view).

Patch these two lines:
Line 79: `tabBarItem.titlePositionAdjustment = { horizontal: 0, vertical: -20 };`
Line 168: `tabBarItem.titlePositionAdjustment = { horizontal: 0, vertical: -20 };`

Changing from a method call to a value assignment fixes the error. Thanks @jbristowe!

**Comment by jbristowe** [comment]
Looks like a fix was made a few days ago: https://github.com/NativeScript/NativeScript/commit/6a176516180326424fa00af5f0d79648977dadb2

**Comment by bradmartin** [comment]
How do you get the master in a project? I have searched all the docs and
ReadMe files and don't see any npm or tns install to pull master. I want
this assuming the fix is in the master of course. Im sure I'm overlooking
it so any help is good to try and resolve this issue.

**Comment by toddanglin** [comment]
@bradmartin If you're just trying to fix this TabView error in a local project, just look for the `tab-view.io.js` file in this folder in your NativeScript project:

(project root) > node_modules > tns-core-modules > ui > tab-view

You should find the JS file there, and you can simply update the two lines referenced above to clear the error. This shouldn't be necessary after the next NativeScript release since the fix has been made to the TNS master branch.

**Comment by NathanaelA** [comment]
@bradmartin - to my knowledge their is no way to pull master from the tns command line.  
 However, I daily compile the masters on http://nativescript.rocks; which you can download any master you need.  One thing to keep in mind is sometimes the common core (this repo) is dependent on the iOS or Android runtimes.

**Comment by bradmartin** [comment]
Thanks @toddanglin and @nathanaela
