### ISSUE TITLE
iOS 9 issues

### ISSUE THREAD

**Issue by atanasovg** [NativeScript/NativeScript#744]
Make sure modules works correctly in iOS9

**Comment by vchimev** [comment]
UnitTestsApp crashes on iOS 9.0:

```
...
file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [LISTVIEW.test_bindingToParentObject] OK
file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [LISTVIEW.test_bindingToParentObjectWithSpacesInIndexer] OK
file:///app/tns_modules/trace/trace.js:145:29: CONSOLE INFO Test: --- [LISTVIEW.test_ConverterIsCalledJustOnce_onAddingItemsToListView] OK
file:///app/TKUnit.js:114:33: JS ERROR Error: ListView leaked!
1   0x100062bb4 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1004f7010 ffi_closure_SYSV_inner
3   0x1004f81b4 .Ldo_closure
4   0x1889e2cf8 <redacted>
```

There are also test failures:
--- [HTTP.test_getJSONP]  FAILED: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
--- [HTTP.test_getString_FromVariousUrls_ShouldWorkProperly]  FAILED: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.
--- [IMAGE SOURCE.testFromUrl]  FAILED: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

**Comment by vchimev** [comment]
Update:

- Memory leaks tests run only on iOS7.0 and iOS8.0 device (no iOS9.0, no simulators),
- To avoid test failures due to [App Transport Security] (https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/), NSAllowsArbitraryLoads key was added to Info.plist of the test applications.
- TabView issue is not present anymore.

**Comment by vchimev** [comment]
The memory leak tests task was moved to: https://github.com/NativeScript/NativeScript/issues/906.
