### ISSUE TITLE
nativescript 6 - ViewBase._applyXmlAttribute Error 

### ISSUE THREAD

**Issue by dudipsh** [NativeScript/NativeScript#7443]
Hi, 
Today I updated to the latest version and now im getting this error

"ViewBase._applyXmlAttribute(...) is deprecated; set attributes as plain properties instead"
I found this code in 
https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/core/view-base/view-base.ts#L883

```typescript
   /**
     * @deprecated
     *
     * This used to be the way to set attribute values in early {N} versions.
     * Now attributes are expected to be set as plain properties on the view instances.
     */
    public _applyXmlAttribute(attribute: string, value: string): boolean {
        console.log("ViewBase._applyXmlAttribute(...) is deprecated; set attributes as plain properties instead");

        if (attribute === "style" || attribute === "rows" || attribute === "columns" || attribute === "fontAttributes") {
            this[attribute] = value;

            return true;
        }

        return false;
    }
```

I am not sure what I need to change in my XML 

angular 8
✔ Component nativescript has 6.0.0-2019-07-02-101519-13543 version and is up to date.
✔ Component tns-core-modules has 6.1.0-next-2019-06-28-190216-06 version and is up to date.
✔ Component tns-android has 6.0.0-rc-2019-06-27-172817-03 version and is up to date.
✔ Component tns-ios has 6.0.0-rc-2019-06-28-105002-01 version and is up to date

**Comment by NickIliev** [comment]
@dudipsh your version is not latest but **`rc`**. That would mean that this is a release candidate for NativeScript 6.0.0 while the official is 5.4.x. So that said there are some breaking changes and deprecated APIs in the upcoming version which would mean that you need to update not only the nativescript related versions but also any plugin that might use a deprecated API (or that needs to address any bre3aking change). We are working with the plugin authors to migrate all plugins.

Meanwhile, your issue is related to a deprecated API being used in `nativescript-angular` which was already resolved - try the `next` version of `nativescript-angular` with the `next` version of `tns-core-modules`
