### ISSUE TITLE
6.0 Webpack Error: Can't resolve './app.ts in JS project

### ISSUE THREAD

**Issue by SephReed** [NativeScript/NativeScript#7572]
Firstly, this update happened without request.  In the future, major releases should probably not be an automatic update.  Especially ones with a very high probability of breaking things.

Anyways, I have a ns-core (js) project, and webpack keeps giving me the error 
> Can't resolve './app.ts' in '..myproject/app'

There's an app.js file right there, and package.json which has this to say:

```
{
  "main": "app.js",
  "android": {
    "v8Flags": "--expose_gc"
  }
}
```

Where should I look for the setting that makes ns think this project is a typescript one?

**Comment by SephReed** [comment]
Eh. Found it.  It's in webpack.config.js.

```
const entryPath = `.${sep}${entryModule}.ts`;
```

**Comment by NathanaelA** [comment]
@SephReed - You might consider doing a `tns create test --js` and copying it's webpack config.   I haven't studied what is different between them, but I do know their is at least three different webpack configs; so you might have more pain if you continue on using a modified TS (or angular) webpack config, rather than switching to the config setup for  JS code...

**Comment by Fatme** [comment]
@SephReed 

I totally agree with @NathanaelA that only modifying `const entryPath = `.${sep}${entryModule}.ts`;` is not a good practice and might lead to unexpected behavior.

It seems that for some reason your project is with `typescript` webpack.config instead of `javascript`. This can happen when the project has `nativescript-dev-typescript` or `typescript` as a dependency. Can you check if this is the case with your project?

**Comment by SephReed** [comment]
It had started off originally as a typescript project.  Will totally try creating a new webpack config.  HMR is breaking on mine currently... but I'm pretty sure that's because I use ns-core, rather than vue or angular.

**Comment by NathanaelA** [comment]
@SephReed - The `tns create test --js` will create you a NS-Core JS app.  So the webpack will be specifically setup for JS on NS-Core.   :)          Just copy the webpack config file out and you should be good to go.     

The other thing is the package.json file for a NS-Core JS app now has very very few dependencies vs the additional flavors; so you might also consider switching your package.json file over; and deleting your node_modules and package-lock.json file, and then add any extra dependencies that you have added.
