### ISSUE TITLE
error typeerror rxjs_observable__webpack_imported_module_1__.observable.of is not a function

### ISSUE THREAD

**Issue by bestazad** [NativeScript/NativeScript#7590]
This is my project https://github.com/bestazad/confusion and when I search `observable` inside my project, I see I have imported it with this line of code `import { Observable } from 'rxjs'; ` in all the files that I needed. 

And it seems there is no error in my project. But when I run the project inside the Android emulator I see this error message in the emulator's screen:

> error typeerror
> rxjs_observable__webpack_imported_module_1__.observable.of is not a
> function

What is the problem and how can I fix it?

**Comment by NickIliev** [comment]
@bestazad it looks like you are using RXJS syntax that is now obsolete. For example instead of `Observable.throw` I think you should use `throwError` as discussed [here](https://github.com/ReactiveX/rxjs/issues/3733#issuecomment-391427430).

Check and update your RXJS code while using the latest supported syntax - closing the issue as unrelated to NativeScript.
