### ISSUE TITLE
Overlapping elements in ListView on IOS

### ISSUE THREAD

**Issue by SebastianCBA** [NativeScript/NativeScript#7634]
Hi! I have a problem with listview on ios using nativescrtipt-vue.

https://play.nativescript.org/?template=play-vue&id=MHVN2k&v=94

Overlapping images:
![image](https://user-images.githubusercontent.com/22308520/62402431-20999480-b55e-11e9-8599-ac8502f031ea.png)

On Android work as expected.

Somebody can help me?

Thanks in advance!

**Comment by NickIliev** [comment]
@SebastianCBA please post the issue in [the Vue repository ](https://github.com/nativescript-vue/nativescript-vue/issues)or ask in the Vue channel in the community slack.

Regarding the issue - I think you need to assign a specific item height when loading dynamically images on iOS - this is due to an iOS-specific where images should have predefined height.

For example, something like [this](https://play.nativescript.org/?template=play-vue&id=MHVN2k&v=121)

**Comment by SebastianCBA** [comment]
@NickIliev thanks for your answer. I don't know the image height, all are distinct.
I created a new isse on vue repository... can you delete this thread?

Thanks in advance

**Comment by SebastianCBA** [comment]
@NickIliev I solved the problem but without autoloadind:
https://play.nativescript.org/?template=play-vue&id=MHVN2k&v=171
regards
