### ISSUE TITLE
[iOS] TextView with multiple paragraphs of text does not resize correctly after keyboard is dismissed

### ISSUE THREAD

**Issue by shiv19** [NativeScript/NativeScript#7734]
**Environment**
Re-creatable in NativeScript Playground

**Describe the bug**
If a TextView has multiple paragraphs, when you tap on it to edit it and then dismiss the keyboard, a portion of the text gets cut out at the bottom of the textview.

**To Reproduce**
https://play.nativescript.org/?template=play-tsc&id=jdFxee&v=2
Open it on a iOS device, just tap anywhere inside the textview and then tap Done on your keyboard.

**Expected behavior**
The text should not get cut out, and everything should be displayed.

**Comment by tsonevn** [comment]
Hi @shiv19,
I tested the sample project and it seems that this issue is caused by the CSS classes provided by the old version of `nativescript-theme-core`. If I update `nativescript-theme-core` plugin to the latest [version `2.0.6`](https://www.npmjs.com/package/nativescript-theme-core) the issue is no longer reproducible. Keep in mind that there are some changes in the import path. You can check the [readme file here](https://www.npmjs.com/package/nativescript-theme-core#usage).

**Comment by shiv19** [comment]
@tsonevn Thanks! I'll try this out tomorrow and report here :)

**Comment by shiv19** [comment]
it does work correctly with theme core 2.0
closing this now.
