### ISSUE TITLE
Get an error: utils.ios.getter() is deprecated with Nativescript

### ISSUE THREAD

**Issue by labo28** [NativeScript/NativeScript#7778]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.3
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.1
 - Plugin(s):

**Describe the bug**
I'm working with Nativescript to create a nice login form with a facebook login option and register option over firebase. I found this nice example which is perfect for my project. (See below) 

But if I simulate it with the command `tns run ios --bundle` everything looks good except for the function to login. If I want to login with my data the console put this out -> 
`CONSOLE LOG file:///node_modules/tns-core-modules/utils/utils.js:48:20 'utils.ios.getter() is deprecated; use the respective native property instead'`

The register method works without problems, but facebook and normal login not. 

Does anyone have a solution to this issue? Thanks in advance.

**Sample project**
Code: https://github.com/drangelod/nsvfbprofile
Tutorial: https://blog.angelengineering.com/nativescript-vue-firebase-profile/

**Comment by tsonevn** [comment]
HI @labo28,
I checked the attached sample project and the problem seems to be connected to some old dependency. Regarding that, make sure that in your project's dependencies are up to date. This issue, also, might be caused by the old `nativescript-plugin-firebase` version, however, this is only an assumption. For further help on this tutorial, I would suggest contacting the author by opening a [new issue here](https://github.com/drangelod/nsvfbprofile/issues) in its demo project or open a new [StackOverflow question here](https://stackoverflow.com/questions/tagged/nativescript).
