### ISSUE TITLE
Usage with DDP?

### ISSUE THREAD

**Issue by Tim-W** [NativeScript/NativeScript#780]
How would I use NativeScript with DDP?

I know there's a library out there called [nativescript-websocket](http://fluentreports.com/blog/?p=95), which I added to my project. After that, I tried installing and requiring `ddp.js`, `node-ddp` and `ddp-client` modules. All of them didn't work; nativescript kept complaining about "cannot find module x" where x is either ddp.js, node-ddp or ddp-client.

I've seen the project [asteroid-nativescript](https://github.com/emmanuelbuah/asteroid-nativescript) on github, but from what I've heard is that it's not ready yet.

**Comment by NathanaelA** [comment]
1. ddp has several requirements including faye-websockets.   Without a lot of changes ddp.js won't work at all.   
2. I don't see a package called node-ddp anywhere, and npm throws a error when I try to install it.
3. ddp-client actually might work; but would still require a little bit of work to the code base since it has several sub modules.   You **might** be able to browserfy it; and then use the browserfied version properly in nativescript.
4. ddp.js that underlies android-nativescript needs work to make it work with NS.  So I would guess Android-nativescript is going to be a while before it is working.

At this point I don't have any ideas for a working "Solution" for you.  It comes down to someone has to write the nativescript version of a DDP library.   Unfortunately at this moment I don't have any more help to offer you since I'm already behind on my paid work.    So I really can't afford at this time to build another wrapper for free to support DDP, especially since I have no use for it in my own projects.

**Comment by NathanaelA** [comment]
Unfortunately their isn't a bounty program yet for NativeScript; as I could probably build a working wrapper in a couple days for it; but I'm not sure a single person would be willing to foot the whole bill...

**Comment by Tim-W** [comment]
I understand completely. I think it's up to the community to build a nativescript wrapper for ddp.

I was referring to the _ddp_ module on npm which is called node-ddp.

**Comment by valentinstoychev** [comment]
Hi @Tim-W - I'm interested to know the application scenario you are after?

**Comment by Tim-W** [comment]
Simply being able to use the ddp-client or astronomy library in my nativescript app.

**Comment by ansarizafar** [comment]
Any update on Meteor ddp client for Nativescript.

**Comment by emmanuelbuah** [comment]
@ansarizafar  Working is ongoing at https://github.com/emmanuelbuah/nativescript.ddp. Join the discussion at https://gitter.im/emmanuelbuah/nativescript.ddp?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by rclai** [comment]
We just posted a bounty, let me know who's interested. Let's try fast-track @emmanuelbuah's discussion. @NathanaelA, care to join?

![Bounty](https://api.bountysource.com/badge/issue?issue_id=26807724)

**Comment by NathanaelA** [comment]
@rclai -- Where do you post a bounty?   :grinning:   Paid work is always appreciated...

**Comment by rclai** [comment]
In bounty source. Click the icon.

**Comment by NathanaelA** [comment]
@rclai ah, RequestPolicy was blocking it -- I didn't even see it or that anything was missing; and it doesn't come through on emails.  Thanks for letting me know I was missing something...

**Comment by emmanuelbuah** [comment]
@NathanaelA Are you interested in working on a solution together. I just haven't dedicate a lot of time to this yet. You know Nativescript in details and I know Meteor. We can collaborate to delivery a meteor ddp client for nativescript. Let me know if you are interest. Ping me at emmanuelbuah@gmail.com if you are interested.

**Comment by emmanuelbuah** [comment]
@rclai Thanks for the support. Hopefully, @NathanaelA and/or I can motivate each other to push this through.

**Comment by rclai** [comment]
I will help out as well since I'm more of a Meteor guy.

**Comment by NathanaelA** [comment]
I'm not sure; I actually have very little availability right this minute. However, if no one tackles in the next little while; I might.

**Comment by rbabayoff** [comment]
Taking into account the actual work needed, I updated the bounty to reflect the economics of creating a bulletproof solution. If goal will be reached, Me and my team will be happy to work on it:

https://www.bountysource.com/issues/26807724-usage-with-ddp

**Comment by rclai** [comment]
We've increased the bounty to $2,500. @NathanaelA @emmanuelbuah what does your availability look like? Otherwise, is anyone able to pitch in for @rbabayoff 's goal?

**Comment by NathanaelA** [comment]
@rclai, Now that actually makes it worth while in my opinion, at least for me to spend the time..  

I am in the process of currently wrapping up a couple projects; so I hopefully will have the time soon.  However, one thing needs to be defined what constitutes a working system?    Which features must be supported.  (I'm haven't messed with Meteor since it was a really early beta).   So I need to know precisely what is expected.   :grinning:

**Comment by rclai** [comment]
@NathanaelA, pretty much everything in the [DDP NPM package](https://www.npmjs.com/package/ddp) as well as [DDP Login](https://www.npmjs.com/package/ddp-login), which was previously together with the former package. What is your preferred method of contact?

**Comment by NathanaelA** [comment]
@rclai -- You can do it here; or via email at nathan@master-technology.com

**Comment by blagoev** [comment]
How hard it can be

https://github.com/blagoev/nativescript-ddp-client
https://github.com/blagoev/nativescript-ddp-client-app

closing this to claim the bounty

**Comment by blagoev** [comment]
updated the application to include required changes

**Comment by triniwiz** [comment]
https://github.com/triniwiz/nativescript-ddp-login for login :smile:
