### ISSUE TITLE
localCompare not working with 'Umlaut'

### ISSUE THREAD

**Issue by Bidou44** [NativeScript/NativeScript#7810]
**Environment**
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 5.4.2 and the latest available version is 6.1.0.
⚠ Update available for component tns-core-modules. Your current version is 5.2.0 and the latest available version is 6.1.1.
⚠ Update available for component tns-android. Your current version is 5.4.0 and the latest available version is 6.1.0.
⚠ Update available for component tns-ios. Your current version is 5.4.2 and the latest available version is 6.1.0.

**Describe the bug**
Using the localeCompare function to sort a list does not work with ¨ (the Umlaut german character). For example, the country **Ö**sterreich appears at the end of my country list (so for example, after Vietnam)

**To Reproduce**
export class Country {
     public name: string;
}

let countries: Array<Country> = ...;
countries = countries.sort((first, second) => {
   return first.name == null ? -1 : first.name.localeCompare(second.name, 'de');
 });

**Expected behavior**
Österreich should be for example between Norway and Poland and not at the end of the country list.

**Sample project**

**Additional context**
For countries without ¨ (Umlaut) it works as expected.

**Comment by tsonevn** [comment]
Hi @Bidou44,
The implementation of the `localeCompare` comes from [V8](https://docs.nativescript.org/angular/core-concepts/android-runtime/overview) for Android and [Apple's JavaScriptCore](https://docs.nativescript.org/angular/core-concepts/ios-runtime/Overview) for iOS. On that matter, this behaviour does not seem to be caused by NativeScript core modules. I found [this thread](https://bugs.chromium.org/p/v8/issues/detail?id=459) in the V8 forum, where a similar case is discussed.

**Comment by Bidou44** [comment]
Ok thank you for that quick response.
Will close this issue since it seems to not be related to nativescript....
