### ISSUE TITLE
bug: application.orientation

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#7815]
**Environment**
 - Cross-platform modules: NS 6.1+

**Describe the bug**
New NS 6 Orientation system has several easily fixed issues:

1. The application.orientation should not have a public setter, as it does nothing other than screw up the orientation value.  The `application.orientation` should be a getter only.

2. The code to "get" orientation is broken.    Right now if I do 
`application.orientation` on startup and it returns `portrait`.  Then rotate the device; it will continue to return `portrait`.    This value should either be internally updated by the orientation changed event or never cached...

**Comment by vchimev** [comment]
Hello @NathanaelA,

Thank you for the constructive feedback.

In regards to:

1. the reason is mentioned [here](https://github.com/NativeScript/NativeScript/pull/7602#discussion_r313012692),

2. it is a lapse that `orientation` property is exposed only to _androidApp_ and _iOSApp_, but not to the _application_ module as well. Here is a pull request for it: https://github.com/NativeScript/NativeScript/pull/7832

**Comment by NathanaelA** [comment]
@vchimev Thanks for showing why the setter was needed.   I can't believe I missed that code; I looked at it several times and just zoned apparently.  :D
