### ISSUE TITLE
auto ios Font Registration (Consistency)

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#786]
Is their some reason we can't attempt to auto register the fonts on iOS.  For example my font definitions are like so:
.icons {
    font-family: MaterialIcons-Regular, Material Icons;
}
If the code did a file-exists("Materialcons-Regular.ttf") on ios, it would see it exists and then it could easily register it.   Or is their something I am missing in why I have to manually register the font on iOS and Android auto-registers the font.

**Comment by nsndeck** [comment]
Sorry for the late replay. 
Indeed there is no need developers to call `registerFont` for iOS. In order to have more consistency between Android and iOS with the new version (1.5 since 1.4 is almost ready) {N} will register automatically all custom fonts placed with `fonts` folder for iOS. This will replicate the default Android behavior. 
`fonts` folder should be located within `app` folder.

**Comment by nsndeck** [comment]
Closed with this [commit](https://github.com/NativeScript/NativeScript/commit/e024589a62c9706d689a14dcf94314308104e701)

**Comment by NathanaelA** [comment]
@nsndeck - Sweet!
