### ISSUE TITLE
Developer workflow broken when linking plain JS app with NativeScript/tns-core-modules

### ISSUE THREAD

**Issue by surdu** [NativeScript/NativeScript#7942]
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules: master (6.2.0)
 - Android Runtime: 6.1.2
 - iOS Runtime: 6.1.0
 - Plugin(s): N/A

**Describe the bug**
 I’m having problems trying to run the Hello World template app using the NativeScript source [as described here](https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-another-app)

When trying to run the app I get the error attached in the screenshot at the end.

**To Reproduce**
1. clone the NativeScript project
2. `tns create test-bkg-pos` in the same folder where you cloned NativeScript
3. `npm install --save ../NativeScript/tns-core-modules` insede the project folder (i.e: `test-bkg-pos`)
4. `tns run android`

**Expected behavior**
The project should work using the source code for core modules.

**Additional context**
Not to flood this issue with a wall of text, I've attached the error as an image. If it turns out the problem is cause by something I did wrong, I'll replace it with the text for others that have the same issue to find this.
![Screen Shot 2019-10-10 at 6 35 05 PM](https://user-images.githubusercontent.com/11520795/66592362-8da05a80-eb9d-11e9-9589-667c47c4e571.png)

**Comment by NickIliev** [comment]
@surdu when executing `tns create test-bkg-pos` are you creating a plain JavaScript project and if so can you please let me know which template you are using?

**Comment by surdu** [comment]
I'm using the plain JS, Hello World template

**Comment by NickIliev** [comment]
@surdu the thing is that the project you are using is plain JavaScript while the NativeScript/tns-core-modules (cloned from the repo) are TypeScript. So you need to transpile the `tns-core-modules` so that your plain JS project will have the transpiled JS files.

in NativeScript repository run
```
tsc
```

and then rebuild the test project you are good to go. The downside is that you will have to transpile the modules after each code change (in `tns-core-modules`). So another option is to grab the tsconfig.json from a TypeScript project and use it in your plain JS project.

**Comment by surdu** [comment]
D'oh! Makes perfect sense! Thank you! I'll update the docs with this info.

**Comment by vakrilov** [comment]
[`development-workflow.md` updated](https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#javascript-applications) in #7911
