### ISSUE TITLE
Animations - add 'bounce'

### ISSUE THREAD

**Issue by jlooper** [NativeScript/NativeScript#799]
I'd like to see 'bounce' added to the very nice Animations library. A little springiness to the rising sun in this animation would make all the difference. I don't know how it's done natively, but in Corona SDK we changed the settings of the physical nature of the object and its surroundings (gravity, density) to determine its bounciness (https://docs.coronalabs.com/api/library/physics/index.html). Something like this would be very nice.

TJ reminds me that I could do a manual 'bounce' with chained commands, but if there were a less manual, cross-platform way to add a natural feel to objects it would be a plus for me.

![rising_sun](https://cloud.githubusercontent.com/assets/1450004/10025052/3768f7ca-6128-11e5-86fc-a421fc2d443a.gif)

**Comment by hamorphis** [comment]
The animation API provides methods for animating view properties with settings such as duration, delay, iterations and curve. It also provides tooling for chaining animations one after another. Having these tools available, one can create any kind of animation such as bounce, slide-in, slide-out. Since the number of possible animations is infinite, we cannot add a pre-defined bounce animation to the public API. If you create a bounce animation, I can include the code snippet [here](http://docs.nativescript.org/animation) so that other users can use it.
