### ISSUE TITLE
Async Tab rendering fails

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#7990]
**Environment**
tns 6.1.2 in Android & iOS

**Describe the bug**
if `Tabs` or `BottomNavigation` gets rendered after page is rendered, only the last `TabContentItem` is visible.
In Android isn't visible the `TabStrip` too.

**To Reproduce**
show  `Tabs` or `BottomNavigation` after a short timeout (in my case after a HTTP Request)

**Sample project**
https://play.nativescript.org/?template=play-vue&id=8TYm1r

**Comment by tsonevn** [comment]
HI @wendt88,
I tested the described scenario by setting the visibility dynamically for the `Tabs` or `BottomNavigation`  in a non-Vue project. However, I was unable to recreate it. You can check my sample project [here](https://play.nativescript.org/?template=play-tsc&id=nKZVwC&v=2). On that matter, this issue seems to be Vue related and you can report [here(nativescript-vue repository)](https://github.com/nativescript-vue/nativescript-vue/issues) by opening a new issue.

**Comment by wendt88** [comment]
Any progress? it does not seems to be a vue specific problem.
[trying the same in angular](https://play.nativescript.org/?template=play-ng&id=mgnZBP), the app crashes. This case isn't recreatable without vue or angular, because `v-if` or `ngIf` are not the same as `visibility`-property.
I noticed , that every change inside `Tabs` or `BottomNavigation` does not gets updated with HMR too. Maby it´s the same problem?
