### ISSUE TITLE
ios State Preservation and Restoration

### ISSUE THREAD

**Issue by dimitriospafos** [NativeScript/NativeScript#8091]
After looking at the Nativescript docs, I was not able to find anything related to ios State Preservation and Restoration for the case that the app get's terminated by the OS. 
Apple docs: https://developer.apple.com/documentation/uikit/view_controllers/preserving_your_app_s_ui_across_launches?language=objc

I would like to be able to restore the state the app when it get's terminated by the OS rather than having the user log in again.

**Comment by NickIliev** [comment]
@dimitriospafos the state restoration is not supported via exposed API but you can access the native API and use the approach given in the linked article.

However, there is another option as mentioned in the article itself that can be easily implemented in a NativeScript app.

> If you prevent restoration from occurring, you can still configure your app’s interface manually in the application:didFinishLaunchingWithOptions: method of your app delegate.

So that said, you can use `application-settings` to save your own custom flags and then reuse those flags in the application delegate (you can overwrite the delegate method as shown in [this documentation article](https://docs.nativescript.org/core-concepts/application-lifecycle#ios-uiapplicationdelegate))

**Comment by dimitriospafos** [comment]
@NickIliev So you are saying in case I want to implement the second approach where I "prevent the restoration from occurring" I should store the "state" (angular component, settings of a page etc into application-settings) and then on application:didFinishLaunchingWithOptions I should retrieve the component and settings from the application-settings and reinitialize them? 

Also when do I save the angular component and/or settings into application-settings since there is no event triggered when the OS terminates the app in the background?

**Comment by NickIliev** [comment]
@dimitriospafos The `application-settings` module is persistent storage so you could retrieve the info stored there whenever needed (not only in 'application:didFinishLaunchingWithOptions' but, for example, you could retrieve the saved settings in some of the Angular lifecycles events like 'ngAfterViewInit').

Regarding **_when do I save_**  you could use t[he suspend event ](https://docs.nativescript.org/core-concepts/application-lifecycle#use-application-events) as it will be triggered when the app is moved to the background. I think the Angular `ngOnDestroy` should also do the job as it should be triggered on suspend.

**Comment by dimitriospafos** [comment]
@NickIliev Thank you for your suggestions. Will try to implement in my app
