### ISSUE TITLE
Native framework not working as expected.

### ISSUE THREAD

**Issue by matty0005** [NativeScript/NativeScript#8186]
- CLI: 6.1.2
 - iOS Runtime: 6.1.1

I am trying to implement the [Brother mobile SDK framework](https://www.brother.co.jp/eng/dev/mobilesdk/download/index.aspx) and they provide [documentation](https://support.brother.com/g/s/es/htmldoc/mobilesdk/guide/print-image.html) for Objective-C and Swift.

Now I understand that this specific framework isn't developed by nativescript, but, the framework itself works when using Brother's example app (which is included with the SDK). 
From the hours of testing and attempting to get this framework to work successfully, I wonder if some of the code is not been executed correctly.

I created a plugin and placed the framework inside that and followed some plugins that I found from online for structure and what not. Here is a sample of the code (js) that I wrote for the plugin to access the framework from inside nativescript: [link](https://www.codepile.net/pile/qeMaVbeR)

From all the testing and playing around with the framework, it seems as though it connects to the printer just fine as if I set an incorrect IP address, it fails to connect. Furthermore, when I pass it the path of a known image, it 'prints' with a '0' error code which identifies that everything went fine and that it had printed, yet nothing prints out. 

I suspect that the settings that I am 'setting' are not been properly set and also potentially some of the background processes in the SDK aren't performing as they should. 
I have posted on [StackOverFlow](https://stackoverflow.com/questions/58868720/brother-printer-sdk-cannot-print-label-error-wrong-label-ios?noredirect=1#comment104041943_58868720) regarding a very similar issue, but have progressed nowhere.  

Am I potentially not referencing the framework correctly, or is something behind the scenes not working as expect, or is something all together different happening?

What would be my best option to get a label to be printed out of the printer using Nativescript?

**Comment by NickIliev** [comment]
@matty0005 as per the example given in the Brother documentation you should use `alloc().initWithPrinterName(name)`

Objective-C example
```Objective-C
BRPtouchPrinter *printer = [[BRPtouchPrinter alloc] initWithPrinterName:@"QL-1110NWB" interface:CONNECTION_TYPE_WLAN];
    [printer setIPAddress:@"your-printer-ip"];
```

that converted to JavaScript (while using[ NativeScript data conversion](https://docs.nativescript.org/core-concepts/ios-runtime/Marshalling-Overview)) should look something like this
```JavaScript
let printer = BRPtouchPrinter.alloc().initWithPrinterNameInterface(printerName, interface);
printer.setIPAddress(ipAdress);
```


Still as the question is related to a 3rd party library I would suggest that you provide a demo project and post it in the community channels (SO or NativeScript community slack).

Closing the issue as unrelated to NativeScript modules.

**Comment by NathanaelA** [comment]
@matty0005 - Hi Matthew, not with the NativeScript team, but as I have developed NativeScript Printer drivers for several different printers (Epson/Brother, Zebra, Star), and I can tell you that frequently the Android/iOS drivers from the companies are very buggy; if you don't get things exactly correct it just won't work or will work very randomly.     

In fact in the last iteration of my drivers, I finally wrote my own Bluetooth and Network interface library to eliminate using any of the manufacturer's drivers because they were basically junk and caused either random full application crashes or printing to work once and then just fail randomly.      If you have any specific questions, feel free to ping me -- I might be able to point you in the correct direction.
