### ISSUE TITLE
getRootView() returns undefined.

### ISSUE THREAD

**Issue by Adam-Booth** [NativeScript/NativeScript#8197]
**Environment**
 - CLI: 6.2.2
 - Cross-platform modules: 6.2.3
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - Plugin(s): N/A

**Describe the bug**
Calling getRootView() returns undefined on both Android and iOS. 

**To Reproduce**
import * as app from "tns-core-modules/application";
...
let rootView = app.getRootView();

**Expected behavior**
Expected a View object to be returned but it is always undefined. I have tried this on multiple machines and different platforms (iOS and Android).

**Comment by lukesUbuntu** [comment]
Do u have code example on git or playground?

**Comment by NickIliev** [comment]
@Adam-Booth where is the method (`let rootView = app.getRootView();`) called ? Indeed, providing a Playground demo would be of great help to investigate your case. 

Closing the issue due to not enough information - please follow the bug report template to provide the information needed.

**Comment by Adam-Booth** [comment]
My bad for not providing enough information.

I've pushed example code to a public repo (https://github.com/Adam-Booth/ns-test).

The login component is shown in the RadSideDrawer and is calling app.getRootView() in the ngAfterViewInit method.

My understanding is that when the login component is shown in the side drawer it is able to call getRootView in order to disable gestures. However, this isn't working.

Thanks

**Comment by NickIliev** [comment]
@Adam-Booth thank you for the provided project. The thing is that the Angular is an abstraction above the NativeScript  (which is an abstraction above the native APIs). So that said, there are some cases where some of the **native** events won't be executed when the top abstraction (Angular) events are triggered. For example, with `ngAfterViewInit` you will be guaranteed that the Angular is rendered but that doesn't always mean that the native elements will be accessible. 

In NativeScript most of those cases are covered but in your particular case (a drawer in the landing page), you might have to do a `dirty` hack and verify that the `getRootView` method is called on the next VM pass.

For example (as done [here](https://github.com/NickIliev/nativescript-ng-cosmos/blob/e4310a16048c520016f0360486faaa1f8f501cb0/app/pages/login/login.component.ts#L50-L53))
```JavaScript

setTimeout(() => {
    this.drawer = <RadSideDrawer>getRootView();
}, 100);
```

I guess that even a 1 ms timeout will do the trick.

**Comment by Adam-Booth** [comment]
Brilliant! Thanks @NickIliev, that got it working.

Cheers!
