### ISSUE TITLE
tns plugin update nativescript-ui-listview ENOENT: no such file or directory

### ISSUE THREAD

**Issue by alexisconsuegra** [NativeScript/NativeScript#8202]
**Environment**
 - NativeScript CLI version: 6.2.2
 - CLI extension nativescript-cloud version: 1.19.3
 - CLI extension nativescript-starter-kits version: 0.3.5
 - Plugin(s): nativescript-ui-listview 

**Describe the bug**
command tns plugin update nativescript-ui-listview fails with error ENOENT: no such file or directory.

**Expected behavior**
update the plugin.

**Additional context**
The reason for the update is that the nativescript-ui-listview plugin is not working. Error: NativeScript caught signal 11. (The core list view works fine. The plugin is not.)

**Comment by DimitarTachev** [comment]
Hi @alexisconsuegra,

Were were not able to reproduce this error by following the steps below:
1) `tns create newJsApp --js && cd newJsApp`
2) `npm i nativescript-ui-listview`
3) `tns plugin update nativescript-ui-listview`

In order to investigate this further, we will need the exact steps to reproduce it. You could also try running the command with `--log trace` in order to get additional details.

**Comment by alexisconsuegra** [comment]
Hi Dimitar,
I installed the plugin by doing "tns plugin add nativescript-ui-listview" not npm i nativescript-ui-listview.
Would that have messed up my app?

**Comment by DimitarTachev** [comment]
Hi @alexisconsuegra,

No, the following steps are also valid and work as expected on our side:
1) `tns create newJsApp --js && cd newJsApp`
2) `tns plugin add nativescript-ui-listview`
3) `tns plugin update nativescript-ui-listview`

We still need your output from the above-mentioned steps in order to investigate it further.

**Comment by alexisconsuegra** [comment]
Hi
I am not able to duplicate the issue on a new app. I guess something went wrong migrating app from NS 5 to 6.
Thanks
