### ISSUE TITLE
Event listeners lost after page.content change

### ISSUE THREAD

**Issue by Gamadril** [NativeScript/NativeScript#8205]
**Environment**
Runtime Version: 6.2.0
Preview App Version: 1.27.0

**Describe the bug**
If the page.content is set dynamically several times, the event listeners of the components inside that content are not called any more after some time.

**To Reproduce**
see playground example

**Expected behavior**
Event listeners are always called

**Sample project**
https://play.nativescript.org/?template=play-js&id=G2vOHb&v=3

- click on "switch layout" to switch to "2"
- click on "switch layout" to switch to "1"
- click on "switch layout" to switch to "2"
- wait for 5-10 seconds
- click on "switch layout" -> click listener is not called

alternatively click "switch layout" until such time as it won't work any more.

**Additional context**
Does not happen on Android.

**Comment by NickIliev** [comment]
In your logic, the content is lazily loaded in your JS file. At the same time, you are using this dynamically created content to change it with another dynamically created content within their own listeners created in the call of `createContent`. The whole scenario is creating some kind of circular dependent logic which is never clearing the listeners and leading to the side effect of the listener not working. I would say that the whole pattern is bad practice - instead of having Singelton contents that are changed dynamically you should probably think of using binding w/ViewModel or other UI approaches (like dynamic hiding/showing of content w/visibility or something of that sort) .

The event listeners will work as expected if you are using a single one - for example, take a look at [this modified demo](https://play.nativescript.org/?template=play-js&id=G2vOHb&v=4) where I am not having content that is lazily loaded

**Comment by Gamadril** [comment]
This issue is not about how to modify current page content. We have very complex application dealing with the dynamic content all the time with switching pages and tracking the navigation stack.
I just stripped everything down to the core of the problem...

**Comment by NickIliev** [comment]
@Gamadril what I meant is that you are creating `content1` and `content2` lazily - meaning outside any application & mobile lifecycles. Those variables won't ever be cleared - and your page content is changed based on this content. It's not that the event listeners are not working - see [the same case ](https://play.nativescript.org/?template=play-js&id=G2vOHb&v=5)without using the content being changed (the listeners never stops working)

**Comment by Gamadril** [comment]
Thanks for the clarification, but I still don't get it... :smile:

> you are creating content1 and content2 lazily

Yes it's intended.

> Those variables won't ever be cleared

One more reason why the JVM must not clear the event binding to the functions

> your page content is changed based on this content

yes, the page content is changed - there is nothing in the Page API preventing it...

> It's not that the event listeners are not working - see the same case without using the content being changed (the listeners never stops working)

As I mentioned in the topic of the issue: The event listeners stop working after modifying page.content. Your example is not doing it.

**Comment by Gamadril** [comment]
How about reopening it since it's a real bug?
