### ISSUE TITLE
showModal crashes (sdk examples version)

### ISSUE THREAD

**Issue by tonyhogben** [NativeScript/NativeScript#8283]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.3.1
 - Cross-platform modules: 6.3.2
 - Android Runtime: N/A
 - iOS Runtime: 6.3.0
 - Plugin(s): None, clean project

**Describe the bug**
I am trying to launch a modal and it just crashes my app. I resorted to running the version as it appears in the SDK examples at https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-category/modal-view/basics and this behaves the same, crashing when you press the button to launch the modal.

**To Reproduce**
Just run https://github.com/NativeScript/nativescript-sdk-examples-js/tree/master/app/ns-ui-category/modal-view/basics and click the button

**Expected behavior**
A modal should launch!

**Comment by NickIliev** [comment]
@tonyhogben I've updated the SDK app versions of tns-core-modules to latest and the modals are working on my side (tested on both iOS and Android) - can you please let me know if you are still experiencing the issue [ via this branch](https://github.com/NativeScript/nativescript-sdk-examples-js/tree/niliev/chore/app/ns-ui-category/modal-view/basics). In case the issue is still appearing please let us know what testing device you are using (iOS version)

**Comment by tonyhogben** [comment]
Thanks @NickIliev. All working!
