### ISSUE TITLE
on emulator and device layout StatusBar is treated differently

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [NativeScript/NativeScript#8328]
**Environment**
I am using latest nativescript vith nativescript-angular 8.20.0

i made simple tab navigation with content inside. (tested even without navigation just with button in app.compnent.tns.html) and on Android emulator button is hidden under StatusBar however on actual device it is not. I am sure i do not have any global styles applied.

![2020_02_11_09_15_26_Android_Emulator_Pixel_2_API_29_5554](https://user-images.githubusercontent.com/3918999/74220683-8191ea00-4cb0-11ea-9da8-e03a9ccefd55.png)

![Screenshot_20200211-091720](https://user-images.githubusercontent.com/3918999/74220697-8a82bb80-4cb0-11ea-9cd2-59fbfb19f303.jpg)

**Comment by NickIliev** [comment]
It is because the above picture is an emulator/device that uses a newer API level (probably Android 9 or 10). You need to add a property in your AndoridManifest.xml to prevent this behavior on the newer API levels. 

See the solution here: https://github.com/NativeScript/nativescript-angular/issues/2110#issuecomment-576570728
