### ISSUE TITLE
Error: View not added to this instance. View: Frame(1348) CurrentParent: undefined ExpectedParent: AppHostView(1)

### ISSUE THREAD

**Issue by kshipra-shelke** [NativeScript/NativeScript#8337]
I just want to know what this bug means. What is "this instance"? Why does it expect a parent?

**Comment by NickIliev** [comment]
@kshipra-shelke 

**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**


**To Reproduce**


**Expected behavior**

**Sample project**


**Additional context**
