### ISSUE TITLE
iOS - CSS Button Border Property are not applied

### ISSUE THREAD

**Issue by kuashe** [NativeScript/NativeScript#8346]
**Environment**

 - iOS Runtime: 6.4
 - iOS Version  : 13

**Describe the bug**

CSS Border property are not applied to Buttons

**To Reproduce**

NativeScript Playground : [CSS Border Buttons Not Working](https://play.nativescript.org/?template=play-tsc&id=qZLIQF)

With a new project 

- Create new project using CLI
- Choose Hello World TypeScript
-  Add iOS Platform
- Edit `app.css` with the following CSS

```
@import '~@nativescript/theme/css/core.css';
@import '~@nativescript/theme/css/default.css';

Button {
    border-color: orange;
    border-width: 10;
    color: red;
}
```
- Run the project

**Expected behavior**

Orange Borders of 10 Units are applied

**Sample project**

[CSS Border Not Working](https://play.nativescript.org/?template=play-tsc&id=qZLIQF&v=2)

**Additional context**

CSS Border Property  **DO** Work with : 

- [Angular Component CSS](https://play.nativescript.org/?template=play-ng&id=9EtHsV)
- [Vue Scoped CSS ](https://play.nativescript.org/?template=play-vue&id=eso6jn)

Other flavors must be tested

**Comment by NickIliev** [comment]
@kuashe the thing is that in your test project (the Playground demo) you are using the `@nativescript/theme` which is creating a default style for the `Button` element selector.

Either remove the theme plugin or overwrite the style via specific class for that element selector.

For example:
```
@import '~@nativescript/theme/css/core.css';
@import '~@nativescript/theme/css/default.css';

/* Button {
    border-color: orange;
    border-width: 10;
    color: red;
} */


Button.my-btn {
    border-color: orange;
    border-width: 10;
    color: red;
}
```

and then
```XML
<Button text="Button" tap="{{ onButtonTap }}" class="my-btn" />
```

**Comment by kuashe** [comment]
Hey @NickIliev thank you for the quick and clear reply.

This behavior seems different compared to regular CSS.

Normally the latest CSS rule is the one applied on the layout. 

Are CSS rules defined in theme uoverridable?

**Comment by NickIliev** [comment]
@kuashe the case with NativeScript CSS is as follows:

- NativeScript will apply the same rules on CSS specificity as you would expect.
- However, [there are two CSS classes used for **light** vs **dark** mode](https://docs.nativescript.org/ui/dark-mode#how-does-it-work) which is actually applied when using the theme. So that said, each of the styles that are coming from the theme is using [these CSS classes](https://docs.nativescript.org/ui/dark-mode#how-does-it-work). This means that when using them all styles will come via a class selector (e.g. applied on type selector `Button`).
