### ISSUE TITLE
Switch styling inconsistencies

### ISSUE THREAD

**Issue by matthew-arosoftware** [NativeScript/NativeScript#8372]
**Environment**

Pixel 4 XL :: Android 10 :: Runtime 6.4.1
iPhone 6S :: iOS 13.2.1 :: Runntime 6.4.0

No Plugins

**Describe the bug**
The playground provided displays three switches.

First is a copy and paste from the documentation about styling a Switch. For Android this views perfectly but in iOS the off background color (red) does not, it shows grey.

Second uses CSS Hex codes instead of color names. In this case both Android and iOS are not showing the correct dark grey background color in the off state.

Third uses a CSS class with the same colors as the second example. iOS work perfectly. Android doesn't work at all and just displays default colors.

**To Reproduce and Sample project**
https://play.nativescript.org/?template=play-ng&id=tmhUSd&v=4

**Expected behavior**

I would expect that the colors in the second and third examples to work exactly the same.

**Comment by NickIliev** [comment]
@matthew-arosoftware the things is that iOS and Android are not following the same rules and they are obviously using different controls to create a switch. While NativeScript is a framework that provides a common way to develop mobile apps for both platforms, it can't always output exactly the same UI or implement exactly the same functionalities because there are some core concepts in the native words (iOS vs Android) that are different.

So simply said, the native controls that are standing behind the NativeScript's `Switch` are having different functions and styling options. That is the reason for the difference.

Note: if you anyone ideas on how to align those - **PRs are welcomed!**
