### ISSUE TITLE
Repeater.itemsLayout bindingContext Issue

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8379]
**Environment**
 - CLI: 6.4
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
If I have a custom component called "my-component" that includes a view-model and has its own bindingContext, calling it inside the Repeater.itemsLayout of another XML view will force it to inherit Repeater.itemsLayout bindingContext inside its own "my-component.xml".

**Expected behavior**
Custom component should keep its own bindingContext inside its own XML file.

**Comment by NickIliev** [comment]
That is to be expected as the binding context for each repeater template should be passed always (otherwise how it would know what to "repeat"). Closing the issue but if you are facing a different problem m from the one I am talking about then please follow the bug report template and provide the requested information (including a sample app demonstrating the issue)
