### ISSUE TITLE
Bottomnavigation programatic navigation bugs.

### ISSUE THREAD

**Issue by aranmohyeddin** [NativeScript/NativeScript#8397]
**Environment**
 - CLI: 6.4.1
 - Cross-platform modules: 6.4.2
 - Android Runtime: 6.4.1

**Describe the bug**
bottomnavigation does not navigate if the component is not visible.

**To Reproduce**
If you click on `1`, then press the button `go to 0` then `show modal`, then `go to 1`, it will take you to page `1`.
If you click on `0`, then `show modal`, then `go to 1`, it will take you to page `0`.

**Sample project**
playground provided in this [Stackoverflow](https://stackoverflow.com/questions/60440418/bottomnavigation-programatic-navigation?noredirect=1#comment106963694_60440418) question

**Comment by NickIliev** [comment]
@aranmohyeddin 

based on
```
I have two pages 0 and 1. there is a button on page 0 that opens a modal that has a button that should close the modal and navigate to page two. 
```

It seems that you are solving the issue by using a small timeout but you don't want to use it because of a bad UX. However, consider that you are kinda creating this UX in the first place - your user is opening page **A** and from that page, they are opening a modal. That modal should direct them to page **B**. However, the actual navigation would happen only after the modal is closed. So that said it is expected that you will actually observe the navigation from A-to-B. The modal is opened from page A in the first place and changing the selected index behind the scenes won't help - we will still need to actually update the UI.

**Comment by aranmohyeddin** [comment]
why is it not possible to direct nativescript to render the correct page behind the scenes and when the modal is closed, immediately show B instead of A? I don't want to see A at all.

A is my home, the modal is where the user does some stuff and earns some money. B is store. The modal is complicated and there is navigation in it also(the task to be performed has multiple steps) at the end when the user makes money. They would like to directly be taken to store to shop with their money. What do you suggest I do?
