### ISSUE TITLE
Switch initializing issues

### ISSUE THREAD

**Issue by csimpi** [NativeScript/NativeScript#8406]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

Newest versions + Android device:
https://play.nativescript.org/?template=play-ng&id=gDKHua&v=3

**Describe the bug**

1. When I use `[cheked]="true"` it throws several errors, it requires an expression, for example `[checked]="1===1"` works well. It should be able to accept a boolean too.

2. When I initialize Switch with `[checked]="EXPRESSION_WHICH_IS_TRUE"` it will fire the `checkedChange` event during initialization. It doesn't fire the event if the initial expression's result is `false`. I think this is clearly a bug, it shouldn't fire the `checkedChange` event during initialization since it's not a change (there wasn't any state before).  Or (this is the less good scenario) it should fire the event even it's `false` too.

**To Reproduce**

Use this sample code. A button exposes the switch and it will fire the event despite that it just appeared nobody changed its state. 
https://play.nativescript.org/?template=play-ng&id=gDKHua&v=3

**Expected behavior**

**Sample project**

https://play.nativescript.org/?template=play-ng&id=gDKHua&v=3

**Additional context**

Slack Thread:
https://app.slack.com/client/T0L97VCSY/C0L9EEURY/thread/C0L9EEURY-1583156576.199300

**Comment by NickIliev** [comment]
@csimpi 

about the **1** point:

The `[cheked]="true"` means that you are using binding to a property called **_true_** (kinda bad practice). Think of it as `[checked]="isTrue"` where in your component you have
```TypeScript
isTrue: boolean;

ngOnInit(): void {
    this.isTrue = true;
}
```

So that said any boolean that is not initialized will return **false**. In your case, the property is not existing which is probably why it is returning a number of errors (not to mention that you are trying to use a preserved word)


About the **second** point:
You are right - indeed the initial value will trigger the **checkedChange**. This is by design as the checked property has a **defaultValue** set to **false** (see [here](https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/ui/switch/switch-common.ts#L25))\

```TypeScript
export const checkedProperty = new Property<SwitchBase, boolean>({ name: "checked", defaultValue: false, valueConverter: booleanConverter, valueChanged: onCheckedPropertyChanged });
checkedProperty.register(SwitchBase);
```

The reason for this is due to the native element (I am not sure if it 3was the iOS or the Android one) wanted to have a default value. This means that if you set an initial value that is **true** it will trigger the checkedChanged event. We had many discussions over the time if this is right or not but so far this is the state of some of the elements on the Core modules. What you could do is to create a logic that checks for the initial load and only then apply your custom logic for checked change event
