### ISSUE TITLE
Icon font rendering bugs

### ISSUE THREAD

**Issue by wendt88** [NativeScript/NativeScript#8409]
**Environment**
√ Getting NativeScript components versions information...
√ Component nativescript has 6.4.1 version and is up to date.
√ Component @nativescript/core has 6.4.2 version and is up to date.
√ Component tns-android has 6.4.1 version and is up to date.

**Describe the bug**
On Android: some icons align the whole label to the right like `float: right`;
On both platforms: some icons are not visible

**Sample project**
https://play.nativescript.org/?template=play-vue&id=MsnonA&v=2

**Additional context**
I use in the sample project the `nativescript-fonticon` plugin, but the bugs exist without fonticon too.
Mainly outline icons are right aligned
I use [`mdi`-icons](https://materialdesignicons.com/) and down#t know if there are some buggy icons in Font awesome too

**Comment by NickIliev** [comment]
Regarding that, some icons are not visible on both platforms. 

It looks like the icons in which hex code is longer than the usual 4 symbols are not rendered (probably due to their hex not being recognized). For example 
```

.mdi-book-information-variant:before {
  content: "\F009A";
}
```

The hex code is F009A which is one symbol longer than most of the icon font codes (like "\F79A")

**Comment by wendt88** [comment]
Thank your for that info.
In my case I use the raw symbol like `` and it also doesn't work, but without the custom font the sign is visible.

**Comment by wendt88** [comment]
found a solution for the missing icons:
[`String.fromCharCode()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode) says "The range is between `0` and `65535` (`0xFFFF`)", so `F009A` is larger than `FFFF` and gets truncated.
the right syntax to get the correct string is:
```js
String.fromCodePoint(parseInt('F009A', 16))
```

it would be maby helpful to explain that inside your docu: https://docs.nativescript.org/ui/components/icon-fonts

**Comment by NathanaelA** [comment]
I have a demo that shows how to use icon fonts properly; but rather than using fromCodePoint/parseInt, it is way simpler to do:
let character = "\uf009a";   // Prefixing the F009A with a "\u" is the key.

However, I detail it all in this blog post: http://fluentreports.com/blog/?p=176 and also show how to use the duotone fonts here:
http://fluentreports.com/blog/?p=1143
