### ISSUE TITLE
Ability to disable BottomNavigation tabStripItems

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8417]
Would be nice if there was the possibility to disable tabStripItems in Bottom Navigation.
For example, it would look like bad app design if user could navigate between tabs while waiting for an HTTP request to finish.
At the moment, setting isEnabled or isUserInteractionEnabled to false makes no difference.

**Comment by NickIliev** [comment]
@DimitrisRK you can use neither `isUserInteractionEnabled` not `isEnabled` for tab strip items (due to how the native element are working)/. But, you could entirely remove the whole TabStrip and make your own (while using layouts that are supporting the above properties). All you need to do is to use the[ **selectedIndexChanged** event](https://docs.nativescript.org/api-reference/classes/_ui_tab_navigation_bottom_navigation_.bottomnavigation#selectedindexchangedevent) to create your own custom tan strip.

**Comment by DimitrisRK** [comment]
This isn't really a question. I'm not asking for help here, but trying to help instead.
Another dirty hack is setting root view (BottomNavigation) items as empty during itemTap event, and put items back when your job is done.

e.g.
`
const storedItems = application.getRootView().items.map(f => f);
application.getRootView().items.splice(0);

// Call this whenever feeling ready to
for (const item of storedItems)
{
	application.getRootView().items.push(item);
}
`
