### ISSUE TITLE
NativeScript Playground never save

### ISSUE THREAD

**Issue by lapodelapis** [NativeScript/NativeScript#8420]
If I import a template from the online examples on the MarketPlace and then edit it, the Playground never saves!! So I lost two hours of work. I click on "save", but, nothing!, the new project never appears in the project list.

**Comment by NickIliev** [comment]
@lapodelapis can you elaborate more - what are the exact steps that you are taking to import the project? What are the exact steps before pressing "Save"?

**Comment by lapodelapis** [comment]
Before saving? Nothing in particular. A few modifications that I can see on the device. But then the project is not saved in the project list. I think I know why; we probably need to fork before we start working on the new project and save it. Doing so worked for me.

**Comment by lapodelapis** [comment]
Thank you, Nick.

**Comment by NickIliev** [comment]
@lapodelapis the Playground provides the option to "lock" your project. So that you could not create a new version of the current one. This was done to minimize the number of projects created from the documentation playgrounds (and for other similar reasons). So going forward with a new fork is the way to go.

**Comment by lapodelapis** [comment]
Thank you, Nick. the information you gave me was very helpful.
