### ISSUE TITLE
How do I manually close the splashscreen?

### ISSUE THREAD

**Issue by aquinn637** [NativeScript/NativeScript#8429]
I'm writing an app with Angular 8+ and NativeScript 6+. I want to use the splashscreen on both iOS and on Android. 

I have called the command **tns resources generate splashes** and I see that the splash image has changed. https://docs.nativescript.org/tooling/docs-cli/project/configuration/resources/resources-generate-splashes#arguments

I want to be able to manually control when the splash screen closes. How can I do this?
I want to be able to close it on different pages depending on what data I load e.g. if the user is already logged in then the home page will hide the splash screen instead of the landing screen.

**Comment by NickIliev** [comment]
@aquinn637 the splash screen is not the place to make navigation decisions and complex code-behind logic. Its purpose is to provide initial interaction for the users while the main application is starting. So that said you shouldn't control when it closes (and as far as I know there is no such option).

If you are creating an Angular base app the best approach would be to create and use AuthGuard which checks if the user is logged in and based on the results navigates to the proper page.

The same is pretty much valid for NativeScript Core where you could use the landing page to navigate deeper if a condition is met.
