### ISSUE TITLE
JavaScript Date functions not fully working

### ISSUE THREAD

**Issue by DimitrisRK** [NativeScript/NativeScript#8472]
**Environment**
 - CLI: 6.4
 - Cross-platform modules:
 - Android Runtime: 6.4.1
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**
JavaScript 'Date' format methods like "toLocaleString" or "toLocaleDateString" don't seem to respect their 'options' parameter formatting properties. This issue occurs on Android.

**Expected behavior**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString

**Comment by NickIliev** [comment]
The Date methods are depending on the Virtual machines that are used by the runtimes 9V8 and JavaScript Core) and also on the version of the Node.js. That said there are a ton of issues reported and related to Date interpretations by the above and all of them 

https://www.google.com/search?q=v8+toLocalDateString&rlz=1C1CHBF_enBG781BG781&oq=v8+toLocalDateString&aqs=chrome..69i57j33.16782j0j4&sourceid=chrome&ie=UTF-8

https://www.google.com/search?rlz=1C1CHBF_enBG781BG781&sxsrf=ALeKk00Ti99fevd-D9nj1flOeZjAfqZ0Fw%3A1585558396057&ei=fLOBXv-SA8iimwX3qIO4BQ&q=javascriptCore+toLocalDateString&oq=javascriptCore+toLocalDateString&gs_lcp=CgZwc3ktYWIQAzIHCCMQsAIQJzoICAAQBxAKEB46CAgAEAgQDRAeOgYIABANEB5Q3d8BWOr0AWDw9wFoAHAAeACAAXiIAfsMkgEENS4xMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwj_wN6n6cHoAhVI0aYKHXfUAFcQ4dUDCAs&uact=5

https://www.google.com/search?rlz=1C1CHBF_enBG781BG781&sxsrf=ALeKk01Y2tKs2dRh2_-kGtxYSJhZw_7JZw%3A1585558604576&ei=TLSBXvXbIoSJk74P7Ia4uAc&q=nodejs+toLocalDateString+not&oq=nodejs+toLocalDateString+not&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAE6BAgAEEc6BggAEBYQHlCFSViTUGDxWWgAcAJ4AIABvAGIAb0EkgEDMC40mAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwj1sZWL6sHoAhWExMQBHWwDDncQ4dUDCAs&uact=5

None of the issues can be fixed in NativeScript so you need to use a workaround (e.g., use a specific date format that works on Android)

**Comment by NickIliev** [comment]
See also [this thread](https://github.com/NativeScript/NativeScript/issues/7583)
