### ISSUE TITLE
ViewModel instantiation

### ISSUE THREAD

**Issue by CatchABus** [NativeScript/NativeScript#8526]
**Is your feature request related to a problem? Please describe.**
Observable's "fromObject" method might be helpful at registering reactive properties but it's quite a bad design to return it as an object inside view model's constructor (thats a method found in NS docs). I know this is a JS feature, but it deprives developers of using things like OOP features (e.g. instanceof comparison since you instantiate an object but another one is returned).

**Describe the solution you'd like**
A way to return an observable object instantiated using my view model class.

**Describe alternatives you've considered**
Extend Observable class. For example: "class WelcomeViewModel extends Observable".
Another method might be using Object.assign.

**Additional context**

```
const observableModule = require("tns-core-modules/data/observable");

// WelcomeViewModel is instantiated but observable is returned
function WelcomeViewModel()
{
    const viewModel = observableModule.fromObject({});
    return viewModel;
}

module.exports = WelcomeViewModel;
```

**Comment by NickIliev** [comment]
@DimitrisRK you could always [use TypeScript](https://github.com/NativeScript/nativescript-app-templates/blob/master/packages/template-drawer-navigation-ts/app/home/home-view-model.ts#L5-L11) ;)

Marking the issue as a feature but note that still this is related to the supported version of JavaScript which in NativeScript is **ES5** (due to some limitations of the VM used by the runtimes) while **_extends_** is supported in **ES6** (EcmaScript2015).
