### ISSUE TITLE
[question] Did Progress stopped supporting Nativescript completely?

### ISSUE THREAD

**Issue by kabaluyot** [NativeScript/NativeScript#8623]
I've read an article about nstudio having the full responsibility now for Nativescript (https://nativescript.org/blog/the-next-chapter-for-nativescript-nstudio/).

However, I was stalking recently with Progress (yes because long ago, they use their backing in nativescript as promotion why switch to nativescript), almost they complete remove nativescript related in their articles, website, etc. Even the progress advocate TJ Vantoll where I assume the tech lead of nativescript went off.

So for the mentioned article, did progress just stopped completely supporting the Nativescript initiative? Because this makes us worry ...

**Comment by dotnetdreamer** [comment]
Unfortunately yes...

**Comment by AnthonyLenglet** [comment]
What kinda sucks to me is that it came out of nowhere, that it got a very small announcement that was really easy to miss, and that we got told about it after it happened.

I do think the new team is a good match, seeing all the things NStudio has already done for the project, but there is a lot of questions that cropped up because of the way this was handled, as well as questions about how some stuff will go (one of the big one being the future of the plugins made by members of the old team, since they make up a *huge* chunk of all the big plugins)

**Comment by jannomeister** [comment]
@triniwiz will you guys also continue the NS Team plugins? ex: nativescript-facebook.

**Comment by triniwiz** [comment]
@jannomeister yes we will

**Comment by AnthonyLenglet** [comment]
@triniwiz it does help, and the fact that you guy will continue the team's plugin will mean that stuff like [nativescript-plugin-firebase](https://github.com/EddyVerbruggen/nativescript-plugin-firebase) will get supported too, and they're pretty important, so it would've sucked to see them fall 😄

**Comment by DimitrisRK** [comment]
The new team is definitely a good match, but this is still worrying. I believe framework should have a big corp to cover its back, apart from development team, and this is more about starters.

Take choosing a new cross-platform framework as an example: Option 1 is made by Facebook, Option 2 is made by Google, Option 3 is hmmm...it abolished a very good cloud build, and changed hands almost twice, no longer having a big name to cover its back.

So, which option would you choose if you were this starter?

I have no intention of being offensive, it's just that this framework abolished a very good cloud build mechanism and changed hands at such a short time and that makes me worried.

**Comment by AnthonyLenglet** [comment]
> Take choosing a new cross-platform framework as an example: Option 1 is made by Facebook, Option 2 is made by Google, Option 3 is hmmm...it abolished a very good cloud build, and changed hands almost twice, no longer having a big name to cover its back.
> 
> So, which option would you choose if you were this starter?

To be fair this is pretty much just the Angular / React / Vue situation, and Vue isn't going bad because of it

**Comment by MrSnoozles** [comment]
Does anyone know if @EddyVerbruggen will continue supporting NativeScript?

> To be fair this is pretty much just the Angular / React / Vue situation, and Vue isn't going bad because of it

That's true, but Vue is financed by patreons and sponsors. nStudio I think still has to make money  (I think?) with client work and by putting functionality behind a paywall with ProPlugins? Maybe Sponsors / Patreon would be an option for future financing too?

**Comment by NathanaelA** [comment]
@DimitrisRK - 

1. The NativeScript framework was created by Telerik which is a 100% owned company of Progress.  So NativeScript never changed hands at all before nStudio.   nStudio is the first transfer of the properties.

2. Have you ever visited https://killedbygoogle.com/  :grin:      Facebook doesn't have quite as bad of a reputation at killing things; but they have killed multiple popular things too...   Big companies doesn't actually mean much unless you can guarantee they don't shift directions.  nStudio was founded because of Nativescript and we have a very singular focus -- Make NativeScript and the community around it strong. ;-)

3. Cloud / SideKick was an unfortunate casualty of the transfer.   They were tied to to many internal Progress proprietary projects; and as such we were unable to take them.    In addition any decisions on those projects are still in Progress's hands, and if you go back to when they posted the original circleci plugin, you can see they were already planning on shutting down the cloud services and moving the community to circleci.   I suspect that the reason it was short notice is that legal had to be involved with that blog post; because of all the paid contracts they had with people and cloud building.   I would NOT be surprised if that blog article was written months ago shortly after the circleci plugin; and had to work its way though all the vetting of making a major change that could affect paying customers and how to deal with any liability of it..  Progress has a lot of overhead and liability in everything they do because of being a public company...

Now with all that said -- If you really still want/need Cloud builds; please ping us at support@ and we will help you as we have already created gihub actions and in the process of working on Azure actions to try and have several ways for you to control your own cloud builds.  :grinning:    And we would be very interested in knowing if you want nStudio cloud building service rather than controlling it yourself.

---

@MrSnoozles - nStudio doesn't own ProPlugins.   It is whole owned by Master Technology.

HOWEVER, nStudio and Master Technology has been in discussions over it, nothing solid to announce yet.  :grinning:       I would recommend you read my blog article on how things https://fluentreports.com/blog/?p=1199 are related as it might clear some things up.

**Comment by AnthonyLenglet** [comment]
> nStudio I think still has to make money (I think?) with client work and by putting functionality behind a paywall with ProPlugins?

reminds me that I wonder how proplugin will go now, will we still have 2 separate marketplace (nativescript marketplace and proplugin) ? is it still going to be a paid plan thing ?
I also wonder how it will go, wasn't one of the reason behind proplugin the fact that every new big nativescript release pretty much required a huge rework of a lot of plugins ? since I'm assuming NStudio had to deal with this if that was the case, will this be improved ?

> > To be fair this is pretty much just the Angular / React / Vue situation, and Vue isn't going bad because of it
> 
> That's true, but Vue is financed by patreons and sponsors. nStudio I think still has to make money (I think?) with client work and by putting functionality behind a paywall with ProPlugins? Maybe Sponsors / Patreon would be an option for future financing too?

Would be cool honestly, I'd be in !

**Comment by DimitrisRK** [comment]
@NathanaelA I believe many of us really needed that speech, it's very encouraging.
Had no idea about Telerik - Progress relationship, and that Google had slaughtered so many of its children. Just checked link and felt nostalgic about good old Orkut. 😄

In our company, we have always been developing web-apps and we started developing mobile apps this year. I was the one to suggest NativeScript because I have been using it for 2 years now for hobby projects after I gave up on hybrid technologies.

We are short on iOs device equipment, so we'll be in need of cloud builds for this platform soon enough. Thank you very much for your team's support and I wish that you keep up the good work!

**Comment by NathanWalker** [comment]
@DimitrisRK Thanks for that - agreed on the cloud building solution - we do have some options we're working on for that starting with an Azure DevOps solution that we hope could be ready for use by next week sometime. From there I think other options could be made available.

**Comment by diegovincent** [comment]
Can we close this question then?

**Comment by NathanWalker** [comment]
Yes thanks for all the discussion and input here everyone - will close as to not distract 👍

**Comment by kabaluyot** [comment]
Thank you nStudio team. Goodluck to NativeScript !
