### ISSUE TITLE
Windows 10 Support 

### ISSUE THREAD

**Issue by steskalja** [NativeScript/NativeScript#8643]
Currently there is no support for compiling to multi-function OS platforms such as Windows and MacOS

Release a version of NativeScript that supports app creation for Windows ("Now") and MacOS ("in the future")

For better context:
Now that Windows 10 has more than 1 Billion devices, approaching closer to 1.5 billion. There is a large opportunity to support the Windows runtime. Maybe you could take a look at the work Microsoft is doing with React Native, since it is open sourced: https://github.com/Microsoft/react-native-windows

**Comment by NathanaelA** [comment]
Are you aware of the nStudio XPlat?   It allows you to target Electron which is Windows/Mac/Linux...

**Comment by NathanWalker** [comment]
I believe the goal would be to allow `native` access to Windows and Mac platform just as NativeScript does today with iOS and Android api's. There's been several discussions around this going back several years and the issue is still open here so we'll keep this one in reference to this in particular:
https://github.com/NativeScript/NativeScript/issues/27

Also see this which is a modern day take by the wonderful @bundyo on desktop support with {N} using QT:
https://github.com/bundyo/nativescript-platform-desktop
