### ISSUE TITLE
Support ModuleMap Link Directives for Third Party iOS Framework Libraries

### ISSUE THREAD

**Issue by mehfuzh** [NativeScript/NativeScript#871]
I am trying to build a Couchbase-Lite pluign based on native __CouchbaseLite.Framework__ which requires SQLLite. One way to make this work is to manually add the following flag in generated app's build settings:

```
OTHER_LDFLAGS = $(inherited) -lsqlite3 –lz –framework CFNetwork –framework Security –framework SystemConfiguration

```

Ideally nativeScript should resolve it from more elegant module.modulemap approach, like when I have the following map file under CouchbaseLite.framework/Modules/ :

```
framework module CouchbaseLite {
  umbrella header "CouchbaseLite.h"

  link "libsqlite3.dylib"
  link "libz.dylib"
  link framework "CFNetwork.framework"
  link framework "Security.framework"
  link framework "SystemConfiguration.framework"

  export *
  module * { export * }
}
```

It should automatically add all the necessary libraries using __link__ directives. 

Repo Link:
https://github.com/mehfuzh/couchbaselite-nativescript

**Comment by fealebenpae** [comment]
Link declarations within module maps are not intended to list the dependencies of a module, but to be a hint to the toolchain what is the actual binary that contains the code of the module (the binary of the framework hosting the module map being an implicit link declaration) in order to facilitate auto-linking on platform/toolchain combos that support it.

The problem you describe with the CouchbaseLite framework is the exact kind of problem we anticipated when we originally came up with a way for NativeScript plugins to augment the Xcode build settings for iOS builds - https://github.com/NativeScript/nativescript-cli/issues/883.

We will not be investing in a solution that relies on a non-standard interpretation of link declarations, as it would not only run counter to the proposal for C/C++ modules as I read it, but it would also be severely limited in what it can achieve, since our research on integrating libraries like the Facebook and Google Maps SDKs has indicated that developers often need to specify build settings like extra compiler flags or header search paths and the module map format is incapable of expressing those.

Please help us flesh out our proposal and implementation for plugin-specified build settings by sharing feedback on the issue I linked to.
