### ISSUE TITLE
unable to run app on catalina ios 

### ISSUE THREAD

**Issue by rellikdb1978** [NativeScript/NativeScript#8788]
Hi I get the following error while "tns run ios" on catalina

Saving metadata generation's stderr stream to: /...../platforms/ios/build/Debug-iphonesimulator/metadata-generation-stderr-x86_64.txt ~/work/qoo/qoo/platforms/ios ld: in /Users/..../platforms/ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector(FIRAnalyticsConnector_8094107d82c527bf23f93e98c9db96d1.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/...../platforms/ios/Pods/FirebaseAnalytics/Frameworks/FIRAnalyticsConnector.framework/FIRAnalyticsConnector' for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation) ** BUILD FAILED **

attaching the trace. 

[out.txt](https://github.com/NativeScript/NativeScript/files/5114435/out.txt)

**Comment by Ross-Olivares** [comment]
Hi @rellikdb1978 
Thank you for reporting this issue.
We are going to try replicate this case on our end and will provide the needed fix. For further info, you could keep track the issue.

**Comment by danielorihuela** [comment]
I have the same problem.

**Comment by danielorihuela** [comment]
I have that very same problem with nativescript angular. Could it be related?

**Comment by danielorihuela** [comment]
I was able to solve my problems doing what is said here: https://developer.apple.com/forums/thread/657913.

_"I've seen quite a bit of weird behavior with frameworks, I think due to changes to the simulators to support Apple silicon. My temporary workaround is, in my app/extension targets, to add "arm64" to the Excluded Architectures build setting when building for the simulator (as your preview appears to be trying to do), and setting "Build Active Architecture Only" to No for all schemes. Might be worth a try."_

**Comment by rellikdb1978** [comment]
Thank you will check if this upgrade works for me.

**Comment by NathanWalker** [comment]
See closing details here: https://github.com/NativeScript/NativeScript/issues/8867#issuecomment-703171842
