### ISSUE TITLE
Builds fail with XCode 7 on El Capitan

### ISSUE THREAD

**Issue by manijak** [NativeScript/NativeScript#879]
Hi, Is there anything specific I need to do to get Nativescript to build my app on El Capitan with xcode 7?
https://groups.google.com/forum/#!topic/nativescript/6dvxXLF93QE

Running latest nightly from http://nativescript.rocks

**Comment by fealebenpae** [comment]
Hi @manijak,

The metadata generation process in the master branch of the iOS runtime was indeed broken for a time while we were [migrating to Clang 3.7](https://github.com/NativeScript/ios-runtime/pull/332) but it should be alright now. That is to say, I believe you must have gotten a bad build, instead of El Capitan breaking anything. Things in master do and will break, unfortunately.

It will help to confirm my assertion that El Capitan is not to blame if you could try to build an app with the official NativeScript release from npm on the same machine.

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#348
