### ISSUE TITLE
some methods could not be called in ios runtime

### ISSUE THREAD

**Issue by cartmanchen** [NativeScript/NativeScript#880]
//view.js
>
var View = UIViewController.extend({
     viewDidLoad: function () {
         console.log('viewDidLoad');
     }
});
exports = View.alloc().init();

In the other file (like app.js):
>
require('./view.js');

the method "viewDidLoaded" has not be called.
Has any error in my code ?

**Comment by fealebenpae** [comment]
`-[UIViewController viewDidLoad]` is called when the controller's view enters the view hierarchy or is otherwise realized. Simply instantiating the view controller will not cause that method to be called. You can force it to be invoked, though, by accessing the controller's `view` property manually.

One more thing - if you wish to overwrite the `exports` object itself in CommonJS, you need to set `module.exports` to the overriding value. Otherwise other modules that require your module will get an empty object.

**Comment by enchev** [comment]
This issue was moved to NativeScript/ios-runtime#347
