### ISSUE TITLE
Nativescript CLI Blank Angular Template Will Not Preview

### ISSUE THREAD

**Issue by Brandonhutah** [NativeScript/NativeScript#8803]
CLI: 7.0.3
OS: Windows 10
NODE: 12.18.3

**Describe the bug**
Attempting to preview a nativescript angular app, generated from the blank template, results in a long list of export bug errors.

**To Reproduce**
Install Nativescript CLI version 7.0.3
Generate a project using `tns create my-blank-ng --template tns-template-blank-ng`
CD into the project and run `tns preview`
Scan barcode with Android Pixel 2XL

Get the attached file as output.
[nativescript-preview-output.txt](https://github.com/NativeScript/NativeScript/files/5160386/nativescript-preview-output.txt)

**Comment by rigor789** [comment]
`tns-template-blank-ng` is the old version of the template, try with `@nativescript/template-blank-ng` which is the updated version!

However, you may still have trouble with it, because the preview app still has the old versions. The update on the apps is a bit slower, as it has to go through the app stores, but we hope it will go live by the end of this week!

**Comment by Brandonhutah** [comment]
Oh good call, just read through the blog on Nativescript 7 being released. My timing is just amazing, lol. Thanks!
