### ISSUE TITLE
Android: BottomNavigation goes blank

### ISSUE THREAD

**Issue by PedroAnibarro1** [NativeScript/NativeScript#9191]
**Environment**

 - CLI: 7.1.2
 - Android Runtime: 6.2.0

Hi @rigor789 ! I just found that changes from commit 12242ed8fd1411c1679e55d4ad640f5b3ddb0518 in version 6.5.25 breaks BottomNavigation on Android. 

Example: When I change from tab 0 to tab 1, seems to work. Then, when I return to the previous tab, it shows a blank screen. 

My scenario: 5 tabs. Every tab opens but I can't go back to them. Only last tab tapped seems to work when tab is tapped again. I'm attaching a video so that it's easier to understand and replicate. If I go back to tns-core-modules 6.5.24 it starts working again.

Thanks for everything you do in the community.

https://user-images.githubusercontent.com/8890152/106833375-cd7c3280-6669-11eb-9986-410319251df4.mov

https://user-images.githubusercontent.com/8890152/106833384-d1a85000-6669-11eb-9577-a22cfb533588.mov

**Comment by rigor789** [comment]
Commented on commit: https://github.com/NativeScript/NativeScript/commit/12242ed8fd1411c1679e55d4ad640f5b3ddb0518#commitcomment-46749217

> @PedroAnibarro1 this was a backport of 4690162
> 
> We have tested the change with multiple apps that use a very similar setup as yours and the changes fixed the crashes.
>
> Without debugging this deeper, I'm not positive what causes the issue in your app. Would it be possible to invite me to your project?

**Comment by PedroAnibarro1** [comment]
@rigor789 here is a small version of my project with my settings that reproduces the problem. Hope it helps.


[Order-404-android-bottomnav-6.5.25.zip](https://github.com/NativeScript/NativeScript/files/5936137/Order-404-android-bottomnav-6.5.25.zip)

**Comment by PedroAnibarro1** [comment]
@rigor789 here is a small version of my project with my settings that reproduces the problem. Hope it helps.

[Order-404-android-bottomnav-6.5.25.zip](https://github.com/NativeScript/NativeScript/files/5936139/Order-404-android-bottomnav-6.5.25.zip)

**Comment by rigor789** [comment]
@PedroAnibarro1 thanks - that's very useful! In the meantime, feel free to stick with `6.5.24`. I did some debugging, and it came back to this few lines: https://github.com/NativeScript/NativeScript/blob/c040cb28fcca4c86f831197190a33f316af27ecd/nativescript-core/ui/bottom-navigation/bottom-navigation.android.ts#L585-L593

`pfm` is being set to `null`. If I change it to `fragmentManager` (set earlier above) - it appears to be working, but looks like causes a memory leak. We need to do some more investigation for a proper fix. I suspect it works fine in other cases, because the view hierarchy is slightly different & `pfm` is present.

**Comment by rigor789** [comment]
Closing because BottomNavigation and Tabs are no longer part of core since NativeScript 8.0:

https://blog.nativescript.org/nativescript-8-announcement/#important-note-about-bottomnavigation-and-tabs
