### ISSUE TITLE
C# backend in NativeScript apps

### ISSUE THREAD

**Issue by fairking** [NativeScript/NativeScript#9229]
I really like the idea of NativeScript by allowing to build an interface using JS/TS and such wonderful UI framework as VueJs in native way.
But I am lack of support of C# as a backend of the NS apps. Having some projects in electron (windows/linux desktop apps) I always used to use ElectronCgi (devices/files/databases/services). I think using nodejs in a backend is a bad idea (at least for me). I know I should probably use Xamarin instead but on the other hand I don't like XAML (the way how it's built) so I would never use such things like Silverlight/WPF/Xamarin/UWP etc.

The possible solution is to use such [ElectronCgi](https://github.com/ruidfigueiredo/electron-cgi) approach as a port between a **local backend** (C# as API services) and frontend (Vuejs as UI). Me and probably other people would really like the ability to write backend in C# or C++ or any other backend language.

What do you think guys?

**Comment by rigor789** [comment]
You are free to use whatever backend you like and then call it via an API (rest, graphql whatever) - node, php, go etc. The NativeScript app just has to communicate with it - but doesn't really care what it's written in.

**Comment by fairking** [comment]
> You are free to use whatever backend you like and then call it via an API (rest, graphql whatever) - node, php, go etc. The NativeScript app just has to communicate with it - but doesn't really care what it's written in.

I mean a local backend, not the server one.

**Comment by rigor789** [comment]
@fairking I don't think I understand what you are looking for then! What do you mean by local, and what does backend refer to in this case?

**Comment by bradmartin** [comment]
hey @fairking - you can create your backend in C# using .NET WebApis, run it locally from within Visual Studio (or VSCode if you are using dotnet core). You would `run` that as the "backend" locally for development and then you HTTP (network) calls inside nativescript would just point to the localhost that starts for the .NET API.

Eventually you would need to host this backend somewhere for it to be accessible to end users if you ever publish the app.

Hope that helps.

**Comment by fairking** [comment]
> @bradmartin  Eventually you would need to host this backend somewhere for it to be accessible to end users if you ever publish the app.
> 
> Hope that helps.

Sorry, there is not cloud, web server or anything centralized. I mean just communication between smartphones (P2P), listen to or response to devices, file system and the sqlite (locally). Also probably NFC.

**Comment by NathanaelA** [comment]
NativeScript uses TypeScript (JavaScript) to write the entire application.    It has built in modules for file system, and plugins for sqlite and I believe NFC.   But pretty much all the code you typically write is in JavaScript or TypeScript.  

NativeScript's real power is that it can access the underlying OS from javascript/typescript.  
So you can  do things like  `console.log("Look I'm a android date:", (new java.util.Date()).toString());` and you would create a Java/Android date value, call its native api "toString()" method which then returns a native Android string, and that is then is behind the scenes  marshaled to a JavaScript string and is printed via the javascript console.log statement.    So you can mix & match native platform api's with JavaScript api's.       

You can write the app in Core/Vanilla style (which is my personal favorite), or actually use what most people consider a web based framework (Angular, Vue, Svelte, etc) and then we replace all web components with native components.   So rather than using say a  <div> you use <StackLayout> and you would get a Native layout on both iOS and Android.

If you want to use C# to build your app; Xamarin is really the only primary option.  I think I saw something recently tweeted about some limited support in the newest .net core (beta?) version...
