### ISSUE TITLE
Angular Component styling ignored

### ISSUE THREAD

**Issue by BrandonWorkman** [NativeScript/NativeScript#9301]
Long story short, I've had to step away from an Angular-NativeScript tutorial about a year ago. After coming back I found nothing was working. I've updated everything and finally got it all working again. The only thing now is component styling will just not work.

That is, whatever styles I place here has no effect:

styleUrls: ['./current-challenge.component.css'],

Interestingly though, styles I place here do:

styles: ['.title {font-size: 26;text-align: center;color: #7c015d;font-weight: bold;}'],

I am noticing I do get the following warnings:

WARNING in ./node_modules/@nativescript/core/profiling/index.js 127:22-47

Module not found: Error: Can't resolve '~/package.json' in 'C:\Users\v63158\Source\Repos\ns-ng-course\node_modules\@nativescript\core\profiling'

WARNING in ./node_modules/@nativescript/core/ui/styling/style-scope.js 27:22-47

Module not found: Error: Can't resolve '~/package.json' in 'C:\Users\v63158\Source\Repos\ns-ng-course\node_modules\@nativescript\core\ui\styling'

The latter definitely stands out to me but as of yet I haven't found a fix for.

I will include my package.json but any help would be much appreciated as I see this technology as something my company could greatly use.

{
  "name": "@nativescript/template-hello-world-ng",
  "main": "src/main.ts",
  "version": "8.0.1",
  "author": "NativeScript Team <oss@nativescript.org>",
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "src",
    "App_Resources",
    "tools",
    "hooks",
    "!tools/assets",
    ".editorconfig",
    "tsconfig.json",
    "references.d.ts"
  ],
  "keywords": [
    "nativescript",
    "mobile",
    "angular",
    "{N}",
    "template"
  ],
  "repository": "<fill-your-repository-here>",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "dependencies": {
    "@angular/animations": "~11.2.7",
    "@angular/common": "~11.2.7",
    "@angular/compiler": "~11.2.7",
    "@angular/core": "~11.2.7",
    "@angular/forms": "~11.2.7",
    "@angular/platform-browser": "~11.2.7",
    "@angular/platform-browser-dynamic": "~11.2.7",
    "@angular/router": "~11.2.7",
    "@nativescript/angular": "~11.8.0",
    "@nativescript/core": "~8.0.0",
    "@nativescript/theme": "~3.0.1",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.6.7",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~11.2.7",
    "@nativescript/android": "8.0.0",
    "@nativescript/types": "~8.0.0",
    "@nativescript/webpack": "^5.0.0-beta.0",
    "@ngtools/webpack": "~11.2.6",
    "typescript": "~4.0.0"
  },
  "private": "true",
  "readme": "NativeScript Application"
}

**Comment by LouieTian0209** [comment]
Same for me. I noticed this after upgrading NativeScript to version 8. Attribute styling on HTML works but styling in CSS files are not being applied.

**Comment by NathanWalker** [comment]
Another webpack patch will be published on Wednesday with this fix. 
cc/ @rigor789

**Comment by rigor789** [comment]
Try `"@nativescript/webpack": "^5.0.0-beta.5",` - `styleUrls` should work with beta.5

**Comment by james-criscuolo** [comment]
It seems like lazy loaded components' styleUrls may not be working? When I hardcode the platform into the component (for testing), it does work, so maybe these are dealt with differently. I wish I could give better info, but if there is something I can do to narrow this down, please let me know.

Here's the hardcoding:
```
@Component({
  selector: "my-login",
  styleUrls: ["./login.component.android.scss"],
```
I say it's related to lazy loading because it appears that all my non-lazy loaded components, webpack is not complaining about, it's only the set I lazy load that is causing issues.

**Comment by BrandonWorkman** [comment]
@rigor789 , @NathanWalker, "@nativescript/webpack": "^5.0.0-beta.5" did it for me, thanks!

**Comment by BrandonWorkman** [comment]
To follow up again on this. Everything was working fine until I started doing lazy loading as @james-criscuolo mentioned. Now component styling is back to not working. @rigor789, @NathanWalker any insight into this? Thanks!

**Comment by timdoege** [comment]
Just to chime in and add info from Slack: As @BrandonWorkman notes, lazy loading seems to cause the issue.
I've added a sample project based on
`ns create ns8-ng-tab --template @nativescript/template-tab-navigation-ng`
here:
https://github.com/timdoege/ns8-ng11-styles-sample

**Comment by rigor789** [comment]
I believe I fixed it in `beta.8` now - @timdoege thanks for the test project, when testing make sure to have both `
browse.component.android.scss ` and `
browse.component.ios.scss`, since we never want to resolve the `.android.scss` file on ios (or the other way around), and `_browse.component.scss` shouldn't be resolved to either, it's specific to scss and how they handle imports...

**Comment by timdoege** [comment]
Thanks, @rigor789 and @NathanWalker for your efforts on this! I just tried `beta.8` and it works both in the test project(I've fixed the typo in the ios stylesheet) and in my project I just migrated from NS7 to NS8 👍

**Comment by robertcbit** [comment]
I'll 2nd that, @rigor789 and @NathanWalker thanks for your efforts on this.  I recently converted my old NS6 app to NS8, turned out to be a very long task full of surprises and head banging on my desk, I should know better by now not to fall to far behind on versions!  :)   This thread addresses my (I hope) last issue with this conversion and absolutely! I was trying everything to get css working.  During that I placed some css in the app.css and right away it worked.  So... completely baffled, I am so happy to of found this thread.  Adding beta.8 fixed the issue, thanks much!  Any one know when It will be out of beta? what thread should I follow for latest releases/fixes? I'm suspecting this repo?
