### ISSUE TITLE
Feature request: Implement Android ActionBar home button API's

### ISSUE THREAD

**Issue by alexrainman** [NativeScript/NativeScript#943]
As Android ActionBar icon is not used anymore and it's like "deprecated" in Material Design", Actionbar home button API's needs to be exposed in AndroidActionBarSettings:

SetDisplayHomeAsUpEnabled (true/false)
SetHomeButtonEnabled (true/false)
OnTapEvent (to be used to toggle a SideDrawer for example)
HomeButtonIcon (to set home button hamburger style icon or app icon)

This, in combination with ActionItem visibility property you are planning to release, will provide the developers with a way to add a hamburger button to both Android and iOS.

Android: using ActionBar Home Button
iOS: using ActionItem with android.visibility="false" ios.position="left"

;)

**Comment by N3ll** [comment]
@alexrainman - this is something that you can already do. For more information you can check this [article](http://localhost:8000/ApiReference/ui/action-bar/HOW-TO.html). In Android the NavigationButton should be used, because that is the only way to position the item on the left, and in iOS it is ok to use an actionItem. 

An example of how you can do it is:
```
 <ActionBar>
      <andoird:NavigationButton icon="res://ic_menu" tap="showSlideout" />
      <ActionBar.actionItems>
        <iOS>
          <ActionItem icon="res://ic_menu" ios.position="left" tap="showSlideout" />
        </iOS>
      </ActionBar.actionItems>
</ActionBar>
```
And in the function showSlideout the side drawer will be toggled.

**Comment by alexrainman** [comment]
Awesome. This is the kind of thing you need to document. I could open the link you provided. For example, where i can find details about this: <android: or this <iOS></iOS> ...?

**Comment by N3ll** [comment]
@alexrainman - Sorry for the misunderstanding! I updated the correct link. We will take notice of improving the documentation.
Thank you for the feedback!
