### ISSUE TITLE
TabView is transparent since iOS 15

### ISSUE THREAD

**Issue by Lucia-Bader** [NativeScript/NativeScript#9614]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.4
 - Cross-platform modules:
 - Android Runtime: ^8.1.4
 - iOS Runtime: ^8.1.0
- nativescript/core: 8.1.4
- nativescript-angular: ^10.0.0
- nativescript/angular": "^11.8.1"
- typescript: ~4.0.0

**Describe the bug**
I'm using Angular with NativeScript and TypeScript. Since iOS 15 the TabView is transparent on first render for all tabs. For tabs without scrolling content the TabView stays transparent during the apps runtime. The defined background color for the TabView only get's initialized correctly for a tab with scrolling content, but to get it initialized correctly you must have switched to another tab at least once before.

**Comment by janoshrubos** [comment]
Since iOS 15, the TabView will have a transparent background when there is a `ScrollView` which is scrolled to the bottom.
See more: [scrollEdgeAppearance](https://developer.apple.com/documentation/uikit/uitabbar/3750912-scrolledgeappearance) 

However if you define a `tabBackgroundColor` I believe it should set the color without scrolling the content in runtime.

I made a PR to fix that behaviour, but I think it could go further for NativeScript to support different colors when a `ScrollView` is scrolled to the bottom with `scrollEdgeAppearance` in iOS 15.

**Comment by davecoffin** [comment]
FYI for anybody that stumbles on this...thanks to @janoshrubos there is a PR in the works so it will be fixed in core soon, but if you want a workaround for now you can use @janoshrubos's code in the PR: https://github.com/NativeScript/NativeScript/pull/9617/files
If you are using default tabview background, its as simple as this:
```
tabViewLoaded(args) {
    this.tabview = args.object;
    let tabviewCtrl: any = this.tabview.ios;
    if (isIOS && Device.osVersion.split('.')[0] == '15') {
      let appearance = UITabBarAppearance.new();
      appearance.configureWithDefaultBackground();
      tabviewCtrl.tabBar.scrollEdgeAppearance = appearance;
      tabviewCtrl.tabBar.standardAppearance = appearance;
    }
}
```

**Comment by Lucia-Bader** [comment]
Thank you for the workaround @davecoffin. I have just one more question. Is it possible to use another background then default background, if yes how does it works?

**Comment by tommag21** [comment]
After creating a new `UITabBarAppearance` apparently `tabTextColor` stops working, has anyone faced this issue?

**Comment by Lucia-Bader** [comment]
@tommag21 yes I'm facing the same issue

**Comment by Lucia-Bader** [comment]
> After creating a new `UITabBarAppearance` apparently `tabTextColor` stops working, has anyone faced this issue?

@tommag21 Could you fix this issue?

**Comment by tommag21** [comment]
> @tommag21 Could you fix this issue?

No, I ended up using up a different component (Material Bottom Navigation plugin) that was more suitable for my case.
