### ISSUE TITLE
Smarter LiveSync

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/NativeScript#977]
### Smarter LiveSync without restarts
 - [x] CLI: Respect deleted files
 - [x] CLI: When sending xml and css files to the device, do not restart the app
 - [x] CLI: When syncing JS, images, fonts, or other resources - restart the entire app
 - [x] CLI: Implement a dedicated tcp socket as communication channel between it and the runtimes
 - [x] CLI: Notify runtimes after the files are on the device that the change had happened
 - [ ] CLI: Research if we can fast sync for other file types (mostly images)
 - [x] CLI: Lower batch time in the cli to 250ms
 - [x] CLI: Implement together batch livesync/restart with fast livesync

***
 - [x] Android runtime: spike tcp socket as communication channel between it and the CLI.
 - [x] Android: notify modules when files are changed and the current page must be reloaded - see bellow

***
 - [x] iOS: notify modules when files are changed and the current page must be reloaded - see bellow

***
 - [x] Modules: implement a global function (tentative name: __nativeScriptLiveSyncCallback). The run times will call it whenever the current page needs to be reloaded

**Comment by NathanaelA** [comment]
@teobugslayer, you don't need to restart the app on font changes.   The minute you load the css, the font will then be loaded if it is missing (using the auto-registration system).  At least that is what I have noticed with my livesync.   I suppose their is a corner case where someone might generate a font named x and replace it with another generation of that font.   But maybe a file size check or date time check.  Restarting the app because I added a new font to the fonts folder would be annoying...

When loading JS files, you really don't have to restart the app unless the JS file is the current page (or maybe a better check, would be to check if it has been ever loaded).   Maybe you should add another global command that checks the require cache to see if the JavaScript file has been loaded; if it has never been loaded; don't restart the app.  Eliminating any Restarts is a GOOD plan...

Third, I would HIGHLY recommend you add a basic JSLINT and a XMLLint (or a built in XML parse) support; your livesync sucks for people that easily do typo's like me.  :grinning:

**Comment by x4080** [comment]
I think Nathanael solution is pretty good in Android.the ios simulator version is already pretty fast, maybe Android is urgently need the update or just use Nathanael solution

**Comment by teobugslayer** [comment]
Thank you for sharing your research about fonts! Did you verify this behavior on both iOS and Android?

Please bear in mind that this issue focuses only on the changes which we are introducing in NativeScript 1.5. We will continue improving LiveSync in the following releases. We need more time to discover and fix all the edge cases on both platforms.

There's a separate [issue](https://github.com/NativeScript/nativescript-cli/issues/452) about linting. We think it is a very good idea and needs to be done at first opportunity.

**Comment by NathanaelA** [comment]
@teobugslayer I didn't verify this on iOS, as my LiveSync is Android only.   However, I believe in v1.5 will have the released the auto font registration system for iOS also; I had put a enhancement request in for it #786 because their was no reason that iOS couldn't do it automatically just like Android did...  So I would "guess" that it should work.   

But yeah, it should be tested to see if it works the assumed way, before you write any code to make it restart.  ;-)

**Comment by x4080** [comment]
And how about a feature to load script from http server? I think about for development and easy update for production purposes. It will be awesome

**Comment by kagha** [comment]
Yes livesync from an HTTP server would be great for Native Script @x4080 @teobugslayer 

This feature is a requirement of many projects I have coming up and is the only reason React Native is still an option for me. They already have the feature but I prefer Native Script for everything else.

The release of this feature I think would greatly improve Native Script's popularity because it enables devs to support customer deployments in a much faster and efficient way.

I am willing to contribute in any way I can to the expedition of the implementation of this this feature.

**Comment by amjd** [comment]
It would be awesome if support for `console.log()` is added in LiveSync mode too. Or any other way to debug apps while in LiveSync mode.

**Comment by vchimev** [comment]
Hi @amjd,

`consoloe.log()` will be supported with LiveSync in {N} version 1.5.0 - https://github.com/NativeScript/nativescript-cli/issues/1130.

**Comment by vchimev** [comment]
Please refer to https://github.com/NativeScript/nativescript-cli/issues for any LiveSync related issues.

**Comment by toddanglin** [comment]
Are there any special requirements to make the new LiveSync work in {N} 1.5.0? I'm using the iOS Simulator and running `tns livesync ios` still causes the app to reload.

FWIW, the terminal shows this error when running `livesync` with the iOS simulator:
**Unable to start service com.apple.mobile.house_arrest. Result code is: 3892314239**

Simulator still loads fine, so not sure the implication of this error. Looked at trace logs, but few obvious errors there. Only error that occurs in logs before one above is this:

```
stderr: 
Transferring project files...
Transferring project files...
Multiple exceptions were thrown:
    at FiberFuture.Future.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:535:15)
...
```

**Comment by GitCharm** [comment]
Issue with Android- calling "tns livesync android" with my connected Android device and am getting the following error:

Project successfully prepared
Transferring project files...
spawn ENAMTOOLONG

Thanks in advance for assistance on this

**Comment by Fatme** [comment]
Hi @toddanglin,

It seems that you have connected device and running simulator. In order to livesync to iOS simulator execute `tns livesync ios --emulator` command. If you change `.xml` or `.css` file the application will not restart but if you change `.js` file the application will restart.

**Comment by Fatme** [comment]
Hi @GitCharm,

Can you execute `tns livesync android --log trace` and send us the produced log output.

**Comment by toddanglin** [comment]
Thanks, @Fatme. I actually don't have any other iOS devices physically connected...but `tns device` does show additional iOS devices. Not sure if that's bad caching of previously connected devices OR if somehow the devices are being detected over WiFi.

Either way, the `tns livesync ios --emulator` command eliminates the error, BUT...

The iOS simulator is still restarting every time I issue the `livesync` command. Here is the last part of the log trace when I run `tns livesync ios --emulator`:

```
Project successfully prepared
AfterHookName for command prepare is after-prepare
Exec ps cax | grep launchd_sim 
 stdout: 79938   ??  S      0:00.88 launchd_sim
 
 stderr: 
Exec killall icn 
 stdout:  
 stderr: 
Exec xcrun simctl launch 4232A8A4-DEE0-43BE-84EE-2A3B8F6161C3 com.htmlui.icn 
 stdout: com.htmlui.icn: 81945
 
 stderr:
```
Seems `livesync` is doing a `killall` every time I run it (regardless of what files do/don't change).

**Comment by ignaciofuentes** [comment]
I am having the same experience as @toddanglin 

I can actually see the visual change right before the app reboots.
I suspect it's related to the typescript compilation step.

**Comment by vchimev** [comment]
@toddanglin,
could you please make sure that you upgraded the **tns-core-modules** package in your app? If you open the *package.json* file of your app, under *dependencies* the record for *tns-core-modules* should point to 1.5.0.

**Comment by ignaciofuentes** [comment]
I just created a brand new hello world app and the smart livesync works just fine... 
after running "tns install typescript" then the smart livesync stops working and every XML/CSS change triggers a restart of the app.

**Comment by toddanglin** [comment]
@vchimev Yes, I can confirm that **tns-core-modules** has been upgraded to 1.5.0. In fact, I deleted the entire tns-core-modules directory and then let npm re-install the latest version to be sure all modules were 100% fresh/upgraded.

@ignaciofuentes That's interesting. To test, I created a brand new project and smart livesync still restarts the app with each update (no TypeScript). I'm testing against iOS simulator on OS X.

**Comment by chrisbarry** [comment]
At the moment, I'm seeing a pretty poor livesync experience with ios. The app fully restarts, and requires a 5-10 second reload time, losing state in the process.

I'm not 100% sure, but due to the existence of this project https://github.com/NathanaelA/nativescript-liveedit and that React Native seems to have a lot swifter reloading, is this something that NativeScript is going to be pushing to achieve (ie hot reloading of as much of the app as possible, without a full rebuild/restart?)

**Comment by toddanglin** [comment]
@chrisbarry Sorry to hear you're having that much trouble. Not normally the livesync experience.

That said, the 2.1 release is aiming to make hot reloading in NativeScript even more robust/faster. Definitely something the core team is continuing to invest a lot of time in improving. You can see it on the high-level roadmap here: https://www.nativescript.org/roadmap

The goal is to support the hot reloading experience you describe: fast, reload all assets, retain state

**Comment by chrisbarry** [comment]
@toddanglin many thanks for the response, NativeScript does seem to be one of the cleanest cross platform tools available today.

2.1 sounds exciting, looking forward to trying that out once it's ready!
