### ISSUE TITLE
Observable addeventlistener called 2 times if we addeventlistener 2 times

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#982]
Or we can only addeventlistener 1 time only ?

Thanks

**Comment by nsndeck** [comment]
Generally if you have added `n` event listeners all of them will be invoked when event is emitted. So it is a good practice to remove event listener before adding a new one (if there is a chance to set one event listeners twice). `removeEventListener` method takes same arguments as `addEventListener` similar to following:
```JavaScript
this.removeEventListener(Observable.propertyChangeEvent, eventHandler, thisArg);
this.addEventListener(Observable.propertyChangeEvent, eventHandler, thisArg);
// or
this.off(Observable.propertyChangeEvent, eventHandler, thisArg);
this.on(Observable.propertyChangeEvent, eventHandler, thisArg);
```

Recently we have a problem with `propertyChange` event - even with a single adding of an event listener we've gotten two notifications. If this is the problem, the issue is already fixed in master.

**Comment by x4080** [comment]
Yes I mean one event is called twice . I tried the latest master and works great.BTW where can we download the js files instead of ts? Thanks we can close the issue then

**Comment by nsndeck** [comment]
Indeed our repo contains only `ts` file, since this is our source code. `JS` files can be produced with just a few steps following these articles:
https://github.com/NativeScript/NativeScript/blob/master/Introduction.md
http://docs.nativescript.org/running-latest

**Comment by x4080** [comment]
Ah alright then

**Comment by NathanaelA** [comment]
@x4080 - I have nightlies of everything including this repo on http://nativescript.rocks -- the nightlies of course are JavaScript since that is what you need.

**Comment by x4080** [comment]
Nathan you are the man :)
