### ISSUE TITLE
gridlayout setrows (programmatically) works in IOS but not in Android

### ISSUE THREAD

**Issue by x4080** [NativeScript/NativeScript#988]
Just a little bug, I discovered it sometime ago (this is for programmatically set different size of the gridlayout, ex : "100,*" changes to "20,*"

**Comment by N3ll** [comment]
@x4080  - in order to change the rows, you can remove them and them again with the new values. For more information, you can check this [How-To](https://docs.nativescript.org/ApiReference/ui/layouts/grid-layout/HOW-TO.html) article. The mothod setRows() is private, thus it is not intended to be used for changing the rows.

**Comment by x4080** [comment]
All right then
